export function getData() {
    const rowData = [
        {
            name: 'Renee Baker',
            jobTitle: 'CTO',
            employmentType: 'Permanent',
            department: 'Executive Management',
            employeeId: 353706,
            location: 'United Kingdom',
            joinDate: '2019-07-31',
            basicMonthlySalary: 8659.59,
            paymentMethod: 'Cash',
            paymentStatus: 'Paid',
            image: '1',
            flag: 'uk'
        },
        {
            name: 'Frank Wilson',
            jobTitle: 'Exec. Vice President',
            employmentType: 'Permanent',
            department: 'Executive Management',
            employeeId: 316904,
            location: 'United Kingdom',
            joinDate: '2010-05-15',
            basicMonthlySalary: 4825.55,
            paymentMethod: 'Check',
            paymentStatus: 'Paid',
            image: '2',
            flag: 'uk'
        },
        {
            name: 'Jonathan Romero',
            jobTitle: 'Head of Department',
            employmentType: 'Permanent',
            department: 'Design',
            employeeId: 936854,
            location: 'United States',
            joinDate: '2019-03-19',
            basicMonthlySalary: 7126.1,
            paymentMethod: 'Bank Transfer',
            paymentStatus: 'Paid',
            image: '3',
            flag: 'us'
        },
        {
            name: 'Heather Mathis',
            jobTitle: 'Employee',
            employmentType: 'Permanent',
            department: 'Design',
            employeeId: 105854,
            location: 'United States',
            joinDate: '2009-05-04',
            basicMonthlySalary: 3364.38,
            paymentMethod: 'Bank Transfer',
            paymentStatus: 'Pending',
            image: '4',
            flag: 'us'

        },
        {
            name: 'Dr. Gregory Mills',
            jobTitle: 'Employee',
            employmentType: 'Permanent',
            department: 'Product',
            employeeId: 196196,
            location: 'Spain',
            joinDate: '2018-11-26',
            basicMonthlySalary: 5088.19,
            paymentMethod: 'Check',
            paymentStatus: 'Pending',
            image: '5',
            flag: 'es'
        },
        {
            name: 'Martin Villanueva',
            jobTitle: 'Employee',
            employmentType: 'Contract',
            department: 'Product',
            employeeId: 900809,
            location: 'Portugal',
            joinDate: '2006-03-02',
            basicMonthlySalary: 7093.81,
            paymentMethod: 'Check',
            paymentStatus: 'Pending',
            image: '6',
            flag: 'po'
        },
        {
            name: 'Mary Stone',
            jobTitle: 'Employee',
            employmentType: 'Permanent',
            department: 'Engineering',
            employeeId: 634325,
            location: 'Netherlands ',
            joinDate: '2019-05-01',
            basicMonthlySalary: 6618.2,
            paymentMethod: 'Cash',
            paymentStatus: 'Paid',
            image: '7',
            flag: 'ne'
        },
        {
            name: 'Dylan Lewis',
            jobTitle: 'CEO',
            employmentType: 'Permanent',
            department: 'Executive Management',
            employeeId: 971769,
            location: 'United Kingdom',
            joinDate: '2005-12-10',
            basicMonthlySalary: 14762.71,
            paymentMethod: 'Bank Transfer',
            paymentStatus: 'Pending',
            image: '8',
            flag: 'uk'
        },
        {
            name: 'Michael Dennis',
            jobTitle: 'Exec. Vice President',
            employmentType: 'Permanent',
            department: 'HR',
            employeeId: 625535,
            location: 'United Kingdom',
            joinDate: '2001-10-21',
            basicMonthlySalary: 4423.64,
            paymentMethod: 'Bank Transfer',
            paymentStatus: 'Paid',
            image: '9',
            flag: 'uk'
        },
        {
            name: 'John Gonzalez',
            jobTitle: 'Head of Department',
            employmentType: 'Permanent',
            department: 'Customer Support',
            employeeId: 703257,
            location: 'Ireland',
            joinDate: '2006-10-09',
            basicMonthlySalary: 3491.98,
            paymentMethod: 'Cash',
            paymentStatus: 'Paid',
            image: '10',
            flag: 'ie'
        },
        {
            name: 'Nicole Bass',
            jobTitle: 'Employee',
            employmentType: 'Permanent',
            department: 'Customer Support',
            employeeId: 859426,
            location: 'Ireland',
            joinDate: '2019-01-04',
            basicMonthlySalary: 2734.11,
            paymentMethod: 'Check',
            paymentStatus: 'Pending',
            image: '11',
            flag: 'ie'
        },
        {
            name: 'Darren Osborn',
            jobTitle: 'Employee',
            employmentType: 'Permanent',
            department: 'Engineering',
            employeeId: 568861,
            location: 'Spain',
            joinDate: '2007-07-15',
            basicMonthlySalary: 7625.11,
            paymentMethod: 'Bank Transfer',
            paymentStatus: 'Pending',
            image: '12',
            flag: 'es'
        },
        {
            name: 'Amanda Arnold',
            jobTitle: 'Employee',
            employmentType: 'Permanent',
            department: 'Engineering',
            employeeId: 605882,
            location: 'Ireland',
            joinDate: '2013-12-06',
            basicMonthlySalary: 2787.82,
            paymentMethod: 'Bank Transfer',
            paymentStatus: 'Paid',
            image: '13',
            flag: 'ie'
        },
        {
            name: 'Richard Willis',
            jobTitle: 'Employee',
            employmentType: 'Contract',
            department: 'Engineering',
            employeeId: 855633,
            location: 'France',
            joinDate: '2007-08-14',
            basicMonthlySalary: 3437.53,
            paymentMethod: 'Check',
            paymentStatus: 'Pending',
            image: '14',
            flag: 'fr'
        },
        {
            name: 'Mary Mckinney',
            jobTitle: 'Employee',
            employmentType: 'Contract',
            department: 'Engineering',
            employeeId: 832328,
            location: 'United Kingdom',
            joinDate: '2014-02-13',
            basicMonthlySalary: 5996.5,
            paymentMethod: 'Check',
            paymentStatus: 'Paid',
            image: '15',
            flag: 'uk'
        },
        {
            name: 'Tammy Love',
            jobTitle: 'Employee',
            employmentType: 'Permanent',
            department: 'Engineering',
            employeeId: 900105,
            location: 'Websterberg',
            joinDate: '2019-03-08',
            basicMonthlySalary: 3153.23,
            paymentMethod: 'Cash',
            paymentStatus: 'Pending',
            image: '16',
            flag: 'fr'
        },
        {
            name: 'Donna Parker',
            jobTitle: 'Employee',
            employmentType: 'Contract',
            department: 'Engineering',
            employeeId: 352690,
            location: 'North Robertchester',
            joinDate: '2008-11-30',
            basicMonthlySalary: 2011.26,
            paymentMethod: 'Check',
            paymentStatus: 'Pending',
            image: '17',
            flag: 'es'
        },
        {
            name: 'Trevor Williams',
            jobTitle: 'Employee',
            employmentType: 'Contract',
            department: 'Engineering',
            employeeId: 568297,
            location: 'Mossfurt',
            joinDate: '2022-01-09',
            basicMonthlySalary: 5893.18,
            paymentMethod: 'Cash',
            paymentStatus: 'Paid',
            image: '18',
            flag: 'fr'
        },
        {
            name: 'Daniel Rodgers',
            jobTitle: 'Employee',
            employmentType: 'Permanent',
            department: 'Engineering',
            employeeId: 209501,
            location: 'Lake Patrick',
            joinDate: '2004-12-25',
            basicMonthlySalary: 6555.64,
            paymentMethod: 'Bank Transfer',
            paymentStatus: 'Paid',
            image: '19',
            flag: 'uk'
        },
        {
            name: 'Shawn Phillips',
            jobTitle: 'Head of Department',
            employmentType: 'Permanent',
            department: 'Product',
            employeeId: 597662,
            location: 'Kathrynbury',
            joinDate: '2022-10-30',
            basicMonthlySalary: 3402.91,
            paymentMethod: 'Bank Transfer',
            paymentStatus: 'Pending',
            image: '20',
            flag: 'us'
        },
        {
            name: 'Jill Hobbs',
            jobTitle: 'Employee',
            employmentType: 'Contract',
            department: 'Product',
            employeeId: 297310,
            location: 'Meyersmouth',
            joinDate: '2001-11-29',
            basicMonthlySalary: 5478.9,
            paymentMethod: 'Cash',
            paymentStatus: 'Pending',
            image: '17',
            flag: 'ne'
        },
        {
            name: 'John Hall',
            jobTitle: 'Employee',
            employmentType: 'Contract',
            department: 'Legal',
            employeeId: 284758,
            location: 'Mclaughlinbury',
            joinDate: '2011-06-05',
            basicMonthlySalary: 5388.43,
            paymentMethod: 'Cash',
            paymentStatus: 'Pending',
            image: '12',
            flag: 'fr'
        },
        {
            name: 'Alexandria Novak',
            jobTitle: 'Employee',
            employmentType: 'Contract',
            department: 'Legal',
            employeeId: 322302,
            location: 'United Kingdom',
            joinDate: '2014-06-29',
            basicMonthlySalary: 2676.37,
            paymentMethod: 'Check',
            paymentStatus: 'Pending',
            image: '1',
            flag: 'uk'
        },
        {
            name: 'Donald Brennan',
            jobTitle: 'Employee',
            employmentType: 'Permanent',
            department: 'Sales',
            employeeId: 71358,
            location: 'Ireland',
            joinDate: '2002-06-14',
            basicMonthlySalary: 7272.37,
            paymentMethod: 'Check',
            paymentStatus: 'Paid',
            image: '2',
            flag: 'ie'
        },
        {
            name: 'Andrea Kim',
            jobTitle: 'Employee',
            employmentType: 'Permanent',
            department: 'Sales',
            employeeId: 688798,
            location: 'United Kingdom',
            joinDate: '2011-05-05',
            basicMonthlySalary: 2823.27,
            paymentMethod: 'Check',
            paymentStatus: 'Paid',
            image: '3',
            flag: 'uk'
        },
        {
            name: 'Rachel Mckenzie',
            jobTitle: 'Employee',
            employmentType: 'Contract',
            department: 'Customer Support',
            employeeId: 984668,
            location: 'United States',
            joinDate: '2001-07-15',
            basicMonthlySalary: 2672.37,
            paymentMethod: 'Cash',
            paymentStatus: 'Pending',
            image: '7',
            flag: 'us'
        },
    ];
    return rowData;
}