import type { EnterpriseModuleName } from '../interfaces/iModule';

const modules: Record<EnterpriseModuleName, 0> = {
    AdvancedFilterApiModule: 0,
    AdvancedFilterCoreModule: 0,
    AdvancedFilterModule: 0,
    AggregationModule: 0,
    ClientSideRowModelExpansionModule: 0,
    ClipboardApiModule: 0,
    ClipboardCoreModule: 0,
    ClipboardModule: 0,
    ColumnChooserModule: 0,
    ColumnMenuModule: 0,
    ColumnsToolPanelCoreModule: 0,
    ColumnsToolPanelModule: 0,
    ColumnsToolPanelRowGroupingModule: 0,
    ContextMenuModule: 0,
    EnterpriseCoreModule: 0,
    ExcelExportApiModule: 0,
    ExcelExportCoreModule: 0,
    ExcelExportModule: 0,
    FiltersToolPanelModule: 0,
    GridChartsApiModule: 0,
    GridChartsCoreModule: 0,
    GridChartsEnterpriseFeaturesModule: 0,
    GridChartsModule: 0,
    GroupFilterModule: 0,
    GroupFloatingFilterModule: 0,
    LoadingCellRendererModule: 0,
    MasterDetailApiModule: 0,
    MasterDetailCoreModule: 0,
    MasterDetailModule: 0,
    MenuApiModule: 0,
    MenuCoreModule: 0,
    MenuModule: 0,
    MultiFilterCoreModule: 0,
    MultiFilterModule: 0,
    MultiFloatingFilterModule: 0,
    PivotModule: 0,
    RangeSelectionApiModule: 0,
    RangeSelectionCoreModule: 0,
    RangeSelectionFillHandleModule: 0,
    RangeSelectionModule: 0,
    RangeSelectionRangeHandleModule: 0,
    RichSelectModule: 0,
    RowGroupingApiModule: 0,
    RowGroupingCoreModule: 0,
    RowGroupingModule: 0,
    ServerSideRowModelApiModule: 0,
    ServerSideRowModelCoreModule: 0,
    ServerSideRowModelModule: 0,
    ServerSideRowModelRowGroupingModule: 0,
    ServerSideRowModelRowSelectionModule: 0,
    ServerSideRowModelSortModule: 0,
    SetFilterCoreModule: 0,
    SetFilterModule: 0,
    SetFloatingFilterModule: 0,
    SideBarApiModule: 0,
    SideBarCoreModule: 0,
    SideBarModule: 0,
    SkeletonCellRendererModule: 0,
    SparklinesModule: 0,
    StatusBarApiModule: 0,
    StatusBarCoreModule: 0,
    StatusBarModule: 0,
    StatusBarSelectionModule: 0,
    ViewportRowModelCoreModule: 0,
    ViewportRowModelModule: 0,
};

export const ENTERPRISE_MODULE_NAMES: Set<EnterpriseModuleName> = new Set(
    Object.keys(modules) as EnterpriseModuleName[]
);
