version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/ag-grid-angular"
    schedule:
      interval: "monthly"
    ignore:
      # For all deps
      - dependency-name: "*"
        # ignore all major updates
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/packages/ag-grid-community"
    schedule:
      interval: "monthly"
    ignore:
      # For all deps
      - dependency-name: "*"
        # ignore all major updates
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/packages/ag-grid-enterprise"
    schedule:
      interval: "monthly"
    ignore:
      # For all deps
      - dependency-name: "*"
        # ignore all major updates
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/packages/ag-grid-react"
    schedule:
      interval: "monthly"
    ignore:
      # For all deps
      - dependency-name: "*"
        # ignore all major updates
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/packages/ag-grid-vue3"
    schedule:
      interval: "monthly"
    ignore:
      # For all deps
      - dependency-name: "*"
        # ignore all major updates
        update-types: ["version-update:semver-major"]
