export function getData() {
    return [
        {
            product: 'Macbook Pro 14',
            sku: 'MNTR-XYZ-749',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 12,
            committed: 0,
            unavailable: 29,
            incoming: 45,
            image: 'macbook',
            price: 2499,
            soldLastMonth: 15,
            priceIncrease: 5, // in percentage
        },
        {
            product: 'Aesop Karst',
            sku: 'MNTR-XYZ-533',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 5,
            committed: 0,
            unavailable: 0,
            incoming: 0,
            image: 'aesop',
            price: 95,
            soldLastMonth: 40,
            priceIncrease: 3,
        },
        {
            product: 'ACG Mountain Fly 2 Low',
            sku: 'MNTR-XYZ-789',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 4,
            committed: 0,
            unavailable: 24,
            incoming: 15,
            image: 'shoe',
            price: 180,
            soldLastMonth: 25,
            priceIncrease: 2,
        },
        {
            product: 'MUUTO Linear Table Lamp',
            sku: 'MNTR-XYZ-256',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 12,
            committed: 10,
            unavailable: 0,
            incoming: 0,
            image: 'lamp',
            price: 350,
            soldLastMonth: 5,
            priceIncrease: 1.5,
        },
        {
            product: 'Sonos Ace Headphones',
            sku: 'MNTR-XYZ-125',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 21,
            committed: 10,
            unavailable: 0,
            incoming: 0,
            image: 'headphones',
            price: 299,
            soldLastMonth: 12,
            priceIncrease: 4,
        },
        {
            product: 'Harbour Dining Chair',
            sku: 'MNTR-XYZ-942',
            status: 'Paused',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 11,
            incoming: 5,
            image: 'chair',
            price: 499,
            soldLastMonth: 8,
            priceIncrease: 2.5,
        },
        {
            product: 'Ceramic and Brass Oil Diffuser',
            sku: 'MNTR-XYZ-458',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 3,
            committed: 1,
            unavailable: 0,
            incoming: 0,
            image: 'candle',
            price: 75,
            soldLastMonth: 18,
            priceIncrease: 3.5,
        },
        {
            product: 'Artifox Desk',
            sku: 'MNTR-XYZ-799',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
            image: 'desk',
            price: 1200,
            soldLastMonth: 3,
            priceIncrease: 5,
        },
        {
            product: 'Fellow EKG Pro Electric Kettle',
            sku: 'MNTR-XYZ-299',
            status: 'Paused',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
            image: 'kettle',
            price: 159,
            soldLastMonth: 22,
            priceIncrease: 1.8,
        },
        {
            product: 'Nordic Kitchen Timer',
            sku: 'MNTR-XYZ-839',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 18,
            incoming: 14,
            image: 'timer',
            price: 30,
            soldLastMonth: 45,
            priceIncrease: 2.2,
        },
        {
            product: 'VIEWSONIC 774 Screen',
            sku: 'MNTR-XYZ-969',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 8,
            incoming: 30,
            image: 'aesop',
            price: 499,
            soldLastMonth: 7,
            priceIncrease: 4.5,
        },
        {
            product: 'PHILIPS 916 Display',
            sku: 'MNTR-XYZ-139',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 43,
            incoming: 11,
            image: 'timer',
            price: 599,
            soldLastMonth: 4,
            priceIncrease: 1.7,
        },
        {
            product: 'MSI 318 Display',
            sku: 'MNTR-XYZ-999',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
            image: 'kettle',
            price: 399,
            soldLastMonth: 6,
            priceIncrease: 3,
        },
        {
            product: 'DELL 565 Screen',
            sku: 'MNTR-XYZ-960',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 21,
            incoming: 39,
            image: 'lamp',
            price: 699,
            soldLastMonth: 8,
            priceIncrease: 2.5,
        },
        {
            product: 'DELL 197 Screen',
            sku: 'MNTR-XYZ-473',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 47,
            incoming: 7,
            image: 'headphones',
            price: 749,
            soldLastMonth: 3,
            priceIncrease: 2.8,
        },
        {
            product: 'ACER 522 Screen',
            sku: 'MNTR-XYZ-981',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 9,
            incoming: 45,
            image: 'kettle',
            price: 459,
            soldLastMonth: 10,
            priceIncrease: 3.2,
        },
        {
            product: 'LG 961 Screen',
            sku: 'MNTR-XYZ-124',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
            image: 'lamp',
            price: 529,
            soldLastMonth: 12,
            priceIncrease: 1.5,
        },
        {
            product: 'DELL 373 Screen',
            sku: 'MNTR-XYZ-297',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 17,
            committed: 10,
            unavailable: 0,
            incoming: 0,
            image: 'headphones',
            price: 899,
            soldLastMonth: 9,
            priceIncrease: 4.3,
        },
        {
            product: 'PHILIPS 393 Display',
            sku: 'MNTR-XYZ-358',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 20,
            committed: 11,
            unavailable: 0,
            incoming: 0,
            image: 'kettle',
            price: 649,
            soldLastMonth: 11,
            priceIncrease: 3.1,
        },
        {
            product: 'AOC 138 Screen',
            sku: 'MNTR-XYZ-857',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 1,
            committed: 1,
            unavailable: 0,
            incoming: 0,
            image: 'aesop',
            price: 429,
            soldLastMonth: 14,
            priceIncrease: 2,
        },
        {
            product: 'MSI 219 Display',
            sku: 'MNTR-XYZ-469',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 26,
            incoming: 25,
            image: 'headphones',
            price: 399,
            soldLastMonth: 13,
            priceIncrease: 2.7,
        },
        {
            product: 'SAMSUNG 101 Screen',
            sku: 'MNTR-XYZ-692',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 35,
            incoming: 29,
            image: 'candle',
            price: 449,
            soldLastMonth: 9,
            priceIncrease: 1.9,
        },
        {
            product: 'HP 306 Display',
            sku: 'MNTR-XYZ-376',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 29,
            incoming: 45,
            image: 'macbook',
            price: 1999,
            soldLastMonth: 20,
            priceIncrease: 4.8,
        },
    ];
}
