export function getData() {
    const data = [
        {
            product: 'Macbook Pro 14',
            sku: 'MNTR-XYZ-749',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 12,
            committed: 0,
            unavailable: 29,
            incoming: 45,
            image: 'macbook',
            price: 2499,
            soldLastMonth: 15,
            priceIncrease: 5, // in percentage
            category: 'Electronics',
            variants: 2,
            variant: [{ name: 'abc' }],
        },
        {
            product: 'Aesop Karst',
            sku: 'MNTR-XYZ-533',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 5,
            committed: 0,
            unavailable: 0,
            incoming: 0,
            image: 'aesop',
            price: 95,
            soldLastMonth: 40,
            priceIncrease: 3,
            category: 'Beauty',
            variantName: 'Aesop',
        },
        {
            product: 'ACG Mountain Fly 2 Low',
            sku: 'MNTR-XYZ-789',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 4,
            committed: 0,
            unavailable: 24,
            incoming: 15,
            image: 'shoe',
            price: 180,
            soldLastMonth: 25,
            priceIncrease: 2,
            category: 'Footwear',
            variantName: 'ACG',
        },
        {
            product: 'MUUTO Linear Table Lamp',
            sku: 'MNTR-XYZ-256',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 12,
            committed: 10,
            unavailable: 0,
            incoming: 0,
            image: 'lamp',
            price: 350,
            soldLastMonth: 5,
            priceIncrease: 1.5,
            category: 'Home & Furniture',
            variantName: 'MUUTO',
        },
        {
            product: 'Sonos Ace Headphones',
            sku: 'MNTR-XYZ-125',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 21,
            committed: 10,
            unavailable: 0,
            incoming: 0,
            image: 'headphones',
            price: 299,
            soldLastMonth: 12,
            priceIncrease: 4,
            category: 'Electronics',
            variantName: 'Sonos',
        },
        {
            product: 'Harbour Dining Chair',
            sku: 'MNTR-XYZ-942',
            status: 'Paused',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 11,
            incoming: 5,
            image: 'chair',
            price: 499,
            soldLastMonth: 8,
            priceIncrease: 2.5,
            category: 'Home & Furniture',
            variantName: 'Harbour',
        },
        {
            product: 'Ceramic and Brass Oil Diffuser',
            sku: 'MNTR-XYZ-458',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 3,
            committed: 1,
            unavailable: 0,
            incoming: 0,
            image: 'candle',
            price: 75,
            soldLastMonth: 18,
            priceIncrease: 3.5,
            category: 'Home & Furniture',
            variantName: 'Ceramic',
        },
        {
            product: 'Artifox Desk',
            sku: 'MNTR-XYZ-799',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
            image: 'desk',
            price: 1200,
            soldLastMonth: 3,
            priceIncrease: 5,
            category: 'Home & Furniture',
            variantName: 'Artifox',
        },
        {
            product: 'Fellow EKG Pro Electric Kettle',
            sku: 'MNTR-XYZ-299',
            status: 'Paused',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
            image: 'kettle',
            price: 159,
            soldLastMonth: 22,
            priceIncrease: 1.8,
            category: 'Home & Furniture',
            variantName: 'Fellow',
        },
        {
            product: 'Nordic Kitchen Timer',
            sku: 'MNTR-XYZ-839',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 18,
            incoming: 14,
            image: 'timer',
            price: 30,
            soldLastMonth: 45,
            priceIncrease: 2.2,
            category: 'Home & Furniture',
            variantName: 'Nordic',
        },
        {
            product: 'VIEWSONIC 774 Screen',
            sku: 'MNTR-XYZ-969',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 8,
            incoming: 30,
            image: 'aesop',
            price: 499,
            soldLastMonth: 7,
            priceIncrease: 4.5,
            category: 'Electronics',
            variantName: 'VIEWSONIC',
        },
        {
            product: 'PHILIPS 916 Display',
            sku: 'MNTR-XYZ-139',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 43,
            incoming: 11,
            image: 'timer',
            price: 599,
            soldLastMonth: 4,
            priceIncrease: 1.7,
            category: 'Electronics',
            variantName: 'PHILIPS',
        },
        {
            product: 'MSI 318 Display',
            sku: 'MNTR-XYZ-999',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
            image: 'kettle',
            price: 399,
            soldLastMonth: 6,
            priceIncrease: 3,
            category: 'Electronics',
            variantName: 'MSI',
        },
        {
            product: 'DELL 565 Screen',
            sku: 'MNTR-XYZ-960',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 21,
            incoming: 39,
            image: 'lamp',
            price: 699,
            soldLastMonth: 8,
            priceIncrease: 2.5,
            category: 'Electronics',
            variantName: 'DELL',
        },
        {
            product: 'DELL 197 Screen',
            sku: 'MNTR-XYZ-473',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 47,
            incoming: 7,
            image: 'headphones',
            price: 749,
            soldLastMonth: 3,
            priceIncrease: 2.8,
            category: 'Electronics',
            variantName: 'DELL',
        },
        {
            product: 'ACER 522 Screen',
            sku: 'MNTR-XYZ-981',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 9,
            incoming: 45,
            image: 'kettle',
            price: 459,
            soldLastMonth: 10,
            priceIncrease: 3.2,
            category: 'Electronics',
            variantName: 'ACER',
        },
        {
            product: 'LG 961 Screen',
            sku: 'MNTR-XYZ-124',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
            image: 'lamp',
            price: 529,
            soldLastMonth: 12,
            priceIncrease: 1.5,
            category: 'Electronics',
            variantName: 'LG',
        },
    ];

    // Map products to the new structure with variant counts
    return data.map((product) => ({
        ...product,
    }));
}
