# we ignore all octokit packages because we dont have any incoming/user driven requests to it and only
# use to create and upload releases
[[PackageOverrides]]
name = "octokit"
ignore = true

[[PackageOverrides]]
name = "@octokit/endpoint"
ignore = true

[[PackageOverrides]]
name = "@octokit/app"
ignore = true

[[PackageOverrides]]
name = "@octokit/core"
ignore = true

[[PackageOverrides]]
name = "@octokit/oauth-app"
ignore = true

[[PackageOverrides]]
name = "@octokit/plugin-paginate-graphql"
ignore = true

[[PackageOverrides]]
name = "@octokit/plugin-paginate-rest"
ignore = true

[[PackageOverrides]]
name = "@octokit/plugin-rest-endpoint-methods"
ignore = true

[[PackageOverrides]]
name = "@octokit/plugin-retry"
ignore = true

[[PackageOverrides]]
name = "@octokit/plugin-throttling"
ignore = true

[[PackageOverrides]]
name = "@octokit/request-error"
ignore = true

[[PackageOverrides]]
name = "@octokit/request"
ignore = true

[[PackageOverrides]]
name = "@octokit/types"
ignore = true

# We don't use vite to serve files outside of development
[[PackageOverrides]]
name = "vite"
ignore = true

# node-forge is only used for angular dev server
[[PackageOverrides]]
name = "node-forge"
ignore = true

[[IgnoredVulns]]
id = "GHSA-jr5f-v2jv-69x6"
reason = "We only use axios in examples"

[[IgnoredVulns]]
id = "GHSA-3xgq-45jj-v275"
reason = "cross-spawn is used in development/testing - it's not used in the final production build"

[[IgnoredVulns]]
id = "GHSA-4www-5p9h-95mh"
reason = "middleware is used in development/testing - it's not used in the final production build"

[[IgnoredVulns]]
id = "GHSA-9gqv-wp59-fq42"
reason = "middleware is used in development/testing - it's not used in the final production build"

[[IgnoredVulns]]
id = "GHSA-593f-38f6-jp5m"
reason = "middleware is used in development/testing - it's not used in the final production build"

[[IgnoredVulns]]
id = "GHSA-x2rg-q646-7m2v"
reason = "middleware is used in development/testing - it's not used in the final production build"

[[IgnoredVulns]]
id = "GHSA-p8p7-x288-28g6"
reason = "Request calls are only used in our examples - not in the production code"

[[IgnoredVulns]]
id = "GHSA-9crc-q9x8-hgqq"
reason = "We don't use vitest to visit non ag-grid/charts sites, only for testing/dev purposes"

[[IgnoredVulns]]
id = "GHSA-4v9v-hfq4-rm2v"
reason = "We only use the dev server for development/testing - it's not used in the final production build"

[[IgnoredVulns]]
id = "GHSA-9jgg-88mc-972h"
reason = "We only use the dev server for development/testing - it's not used in the final production build"

[[IgnoredVulns]]
id = "GHSA-xvf7-4v9q-58w6"
reason = "We do not use form-data directly and where it is used is only for testing or examples"

[[IgnoredVulns]]
id = "GHSA-xffm-g5w8-qvg7"
reason = "eslint is only used in development/testing - it's not used in the final production build"

[[IgnoredVulns]]
id = "GHSA-4r6h-8v6p-xvw6"
reason = "sheetjs is only used in development/testing - it's not used in the final production build"

[[IgnoredVulns]]
id = "GHSA-5pgg-2g8v-p4x9"
reason = "sheetjs is only used in development/testing - it's not used in the final production build"

[[IgnoredVulns]]
id = "GHSA-grv7-fg5c-xmjg"
reason = "braces is only used in development/testing - it's not used in the final production build"

[[IgnoredVulns]]
id = "GHSA-fjxv-7rqg-78g4"
reason = "We do not use form-data directly and where it is used is only for testing or examples"

[[IgnoredVulns]]
id = "GHSA-76c9-3jph-rj3q"
reason = "We do not use on-headers directly and where it is used is only for testing or examples"

[[IgnoredVulns]]
id = "GHSA-4vvj-4cpr-p986"
reason = "Vulnerable versions are only used in webpack-dev-server which is not used in production code"

[[IgnoredVulns]]
id = "GHSA-mvw6-62qv-vmqf"
reason = "We do not use koa directly and where it is used is only for testing or dev use"

[[IgnoredVulns]]
id = "GHSA-jgmv-j7ww-jx2x"
reason = "We do not use koa directly and where it is used is only for testing or dev use"

[[IgnoredVulns]]
id = "GHSA-v6h2-p8h4-qcjw"
reason = "Low risk and determined to not be exploitable in our use case"

[[IgnoredVulns]]
id = "GHSA-52f5-9888-hmc6"
reason = "Low risk and determined to not be exploitable in our use case"

[[IgnoredVulns]]
id = "GHSA-67mh-4wv8-2f99"
reason = "esbuild dev server is only used for development/testing - it's not used in the final production build"

[[IgnoredVulns]]
id = "GHSA-5ff5-9fcw-vg88"
reason = "astro is only used for generating a static site, so server vulnerabilities do not apply"

[[IgnoredVulns]]
id = "GHSA-fvmw-cj7j-j39q"
reason = "astro is only used for generating a static site, so server vulnerabilities do not apply. We also do not use the cloudflare plugin"

[[IgnoredVulns]]
id = "GHSA-ggxq-hp9w-j794"
reason = "astro is only used for generating a static site, so server middleware vulnerabilities do not apply"

[[IgnoredVulns]]
id = "GHSA-hr2q-hp5q-x767"
reason = "astro is only used for generating a static site, so server middleware vulnerabilities do not apply"

[[IgnoredVulns]]
id = "GHSA-w2vj-39qv-7vh7"
reason = "astro is only used for generating a static site, and this only applies to the development server"

[[IgnoredVulns]]
id = "GHSA-x3h8-62x9-952g"
reason = "astro is only used for generating a static site, and this only applies to the development server"

[[IgnoredVulns]]
id = "GHSA-wrwg-2hg8-v723"
reason = "This vulnerability affects server-side code, but astro is only used for generating a static site"

[[IgnoredVulns]]
id = "GHSA-4hjh-wcwx-xvwj"
reason = "We only use axios for build and testing"

[[IgnoredVulns]]
id = "GHSA-5j98-mcp5-4vw2"
reason = "glob not accessible to end user/external users"

