export function getData() {
    return [
        {
            product: 'Macbook Pro 14',
            imageURL: 'https://m.media-amazon.com/images/I/417f6xk78FL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-749',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 29,
            incoming: 45,
            image: 'macbook',
        },
        {
            product: 'Aesop Karst',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-533',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
            image: 'aesop',
        },
        {
            product: 'ACG Mountain Fly 2 Low',
            imageURL: 'https://m.media-amazon.com/images/I/41xEuOTeNtL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-789',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 24,
            incoming: 15,
            image: 'shoe',
        },
        {
            product: 'MUUTO Linear Table Lamp',
            imageURL: 'https://m.media-amazon.com/images/I/417f6xk78FL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-256',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 12,
            committed: 10,
            unavailable: 0,
            incoming: 0,
            image: 'lamp',
        },
        {
            product: 'Sonos Ace Headphones',
            imageURL: 'https://m.media-amazon.com/images/I/51exKYtDPjL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-125',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 21,
            committed: 10,
            unavailable: 0,
            incoming: 0,
            image: 'headphones',
        },
        {
            product: 'Harbour Dining Chair',
            imageURL: 'https://m.media-amazon.com/images/I/51exKYtDPjL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-942',
            status: 'Paused',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 11,
            incoming: 5,
            image: 'chair',
        },
        {
            product: 'Ceramic and Brass Oil Diffuser',
            imageURL: 'https://m.media-amazon.com/images/I/51exKYtDPjL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-458',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 3,
            committed: 1,
            unavailable: 0,
            incoming: 0,
            image: 'candle',
        },
        {
            product: 'Artifox Desk',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-799',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
            image: 'desk',
        },
        {
            product: 'Fellow EKG Pro Electric Kettle',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-299',
            status: 'Paused',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
            image: 'kettle',
        },
        {
            product: 'Nordic Kitchen Timer',
            imageURL: 'https://m.media-amazon.com/images/I/41xEuOTeNtL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-839',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 18,
            incoming: 14,
            image: 'timer',
        },
        {
            product: 'VIEWSONIC 774 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/417f6xk78FL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-969',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 8,
            incoming: 30,
            image: 'aesop',
        },
        {
            product: 'PHILIPS 916 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41xEuOTeNtL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-139',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 43,
            incoming: 11,
            image: 'timer',
        },
        {
            product: 'MSI 318 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41LY5DafDIL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-999',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
            image: 'kettle',
        },
        {
            product: 'DELL 565 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/417f6xk78FL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-960',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 21,
            incoming: 39,
            image: 'lamp',
        },
        {
            product: 'DELL 197 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-473',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 47,
            incoming: 7,
            image: 'headphones',
        },
        {
            product: 'ACER 522 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/51exKYtDPjL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-981',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 9,
            incoming: 45,
            image: 'kettle',
        },
        {
            product: 'LG 961 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-124',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
            image: 'lamp',
        },
        {
            product: 'DELL 373 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41LY5DafDIL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-297',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 17,
            committed: 10,
            unavailable: 0,
            incoming: 0,
            image: 'headphones',
        },
        {
            product: 'PHILIPS 393 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41qcLf3LCuL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-358',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 20,
            committed: 11,
            unavailable: 0,
            incoming: 0,
            image: 'kettle',
        },
        {
            product: 'AOC 138 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-857',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 1,
            committed: 1,
            unavailable: 0,
            incoming: 0,
            image: 'aesop',
        },
        {
            product: 'MSI 219 Display',
            imageURL: 'https://m.media-amazon.com/images/I/417f6xk78FL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-469',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 26,
            incoming: 25,
            image: 'headphones',
        },
        {
            product: 'SAMSUNG 101 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41qcLf3LCuL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-692',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 33,
            incoming: 43,
            image: 'kettle',
        },
        {
            product: 'DELL 464 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41DnbGHFhDL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-652',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 7,
            committed: 3,
            unavailable: 0,
            incoming: 0,
            image: 'aesop',
        },
    ];
}
