export function getData() {
    return [
        {
            product: 'Macbook Pro 14',
            imageURL: 'https://m.media-amazon.com/images/I/417f6xk78FL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-749',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 29,
            incoming: 45,
            image: 'macbook',
        },
        {
            product: 'Aesop Karst',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-533',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
            image: 'aesop',
        },
        {
            product: 'ACG Mountain Fly 2 Low',
            imageURL: 'https://m.media-amazon.com/images/I/41xEuOTeNtL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-789',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 24,
            incoming: 15,
            image: 'shoe',
        },
        {
            product: 'MUUTO Linear Table Lamp',
            imageURL: 'https://m.media-amazon.com/images/I/417f6xk78FL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-256',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 12,
            committed: 10,
            unavailable: 0,
            incoming: 0,
            image: 'lamp',
        },
        {
            product: 'Sonos Ace Headphones',
            imageURL: 'https://m.media-amazon.com/images/I/51exKYtDPjL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-125',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 21,
            committed: 10,
            unavailable: 0,
            incoming: 0,
            image: 'headphones',
        },
        {
            product: 'Harbour Dining Chair',
            imageURL: 'https://m.media-amazon.com/images/I/51exKYtDPjL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-942',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 11,
            incoming: 5,
            image: 'chair',
        },
        {
            product: 'Ceramic and Brass Oil Diffuser',
            imageURL: 'https://m.media-amazon.com/images/I/51exKYtDPjL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-458',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 3,
            committed: 1,
            unavailable: 0,
            incoming: 0,
            image: 'candle',
        },
        {
            product: 'Artifox Desk',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-799',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
            image: 'desk',
        },
        {
            product: 'Fellow EKG Pro Electric Kettle',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-299',
            status: 'Paused',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
            image: 'kettle',
        },
        {
            product: 'Nordic Kitchen Timer',
            imageURL: 'https://m.media-amazon.com/images/I/41xEuOTeNtL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-839',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 18,
            incoming: 14,
            image: 'timer',
        },
        {
            product: 'VIEWSONIC 774 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/417f6xk78FL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-969',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 8,
            incoming: 30,
        },
        {
            product: 'PHILIPS 916 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41xEuOTeNtL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-139',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 43,
            incoming: 11,
        },
        {
            product: 'MSI 318 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41LY5DafDIL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-999',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'DELL 565 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/417f6xk78FL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-960',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 21,
            incoming: 39,
        },
        {
            product: 'DELL 197 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-473',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 47,
            incoming: 7,
        },
        {
            product: 'ACER 522 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/51exKYtDPjL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-981',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 9,
            incoming: 45,
        },
        {
            product: 'LG 961 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-124',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'DELL 373 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41LY5DafDIL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-297',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 17,
            committed: 10,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'PHILIPS 393 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41qcLf3LCuL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-358',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 20,
            committed: 11,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'AOC 138 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-857',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 1,
            committed: 1,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'MSI 219 Display',
            imageURL: 'https://m.media-amazon.com/images/I/417f6xk78FL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-469',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 26,
            incoming: 25,
        },
        {
            product: 'SAMSUNG 101 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41qcLf3LCuL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-692',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 33,
            incoming: 43,
        },
        {
            product: 'DELL 464 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41DnbGHFhDL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-652',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 7,
            committed: 3,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'DELL 479 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/417f6xk78FL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-602',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 23,
            committed: 9,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'SAMSUNG 302 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/417f6xk78FL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-675',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 18,
            incoming: 32,
        },
        {
            product: 'ACER 840 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-572',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 9,
            incoming: 20,
        },
        {
            product: 'DELL 472 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/41DnbGHFhDL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-607',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 49,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'PHILIPS 494 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41LY5DafDIL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-843',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 18,
            incoming: 15,
        },
        {
            product: 'SAMSUNG 518 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/51exKYtDPjL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-700',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 26,
            committed: 1,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'AOC 253 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41xEuOTeNtL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-770',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'SAMSUNG 788 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41DnbGHFhDL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-553',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 14,
            committed: 1,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'MSI 166 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/51exKYtDPjL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-507',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 32,
            incoming: 10,
        },
        {
            product: 'ACER 727 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/51exKYtDPjL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-885',
            status: 'Paused',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'MSI 777 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41LY5DafDIL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-625',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 48,
            committed: 8,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'SAMSUNG 847 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41qcLf3LCuL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-341',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 7,
            committed: 7,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'ASUS 412 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/51exKYtDPjL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-650',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'BENQ 535 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41LY5DafDIL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-439',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 32,
            committed: 31,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'LG 915 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-654',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'ASUS 707 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/417f6xk78FL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-579',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 49,
            incoming: 12,
        },
        {
            product: 'AOC 256 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/41xEuOTeNtL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-894',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 4,
            incoming: 32,
        },
        {
            product: 'AOC 372 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-265',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'BENQ 610 Display',
            imageURL: 'https://m.media-amazon.com/images/I/51exKYtDPjL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-964',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 2,
            committed: 2,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'ACER 490 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/41DnbGHFhDL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-847',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 50,
            incoming: 14,
        },
        {
            product: 'HP 599 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/41xEuOTeNtL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-465',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 13,
            incoming: 15,
        },
        {
            product: 'BENQ 146 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/51exKYtDPjL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-722',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 1,
            incoming: 12,
        },
        {
            product: 'HP 690 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-453',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 41,
            incoming: 14,
        },
        {
            product: 'ASUS 804 Display',
            imageURL: 'https://m.media-amazon.com/images/I/417f6xk78FL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-959',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 40,
            incoming: 38,
        },
        {
            product: 'PHILIPS 338 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41xEuOTeNtL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-133',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 26,
            incoming: 14,
        },
        {
            product: 'LG 446 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-375',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 43,
            committed: 4,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'LENOVO 957 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41DnbGHFhDL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-178',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'LG 456 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-124',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 12,
            committed: 6,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'AOC 901 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41xEuOTeNtL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-390',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 25,
            committed: 18,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'ACER 115 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/417f6xk78FL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-790',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 27,
            committed: 4,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'LG 921 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-664',
            status: 'Paused',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'DELL 788 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41xEuOTeNtL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-669',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 43,
            committed: 33,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'BENQ 443 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41DnbGHFhDL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-688',
            status: 'Paused',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'LG 461 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/41xEuOTeNtL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-232',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'DELL 623 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41qcLf3LCuL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-215',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 23,
            committed: 8,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'MSI 457 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-491',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 12,
            incoming: 25,
        },
        {
            product: 'DELL 496 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41qcLf3LCuL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-495',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 19,
            committed: 8,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'PHILIPS 668 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41qcLf3LCuL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-836',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'VIEWSONIC 345 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41DnbGHFhDL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-985',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 43,
            committed: 43,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'HP 809 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41qcLf3LCuL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-303',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 8,
            committed: 4,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'DELL 760 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-216',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 12,
            committed: 10,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'LENOVO 140 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41xEuOTeNtL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-936',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 38,
            committed: 19,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'SAMSUNG 395 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/51exKYtDPjL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-564',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 5,
            committed: 1,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'HP 103 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-433',
            status: 'Paused',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'LG 847 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41xEuOTeNtL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-951',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'MSI 743 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-112',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 29,
            committed: 20,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'MSI 317 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/51exKYtDPjL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-795',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 25,
            incoming: 31,
        },
        {
            product: 'LENOVO 783 Display',
            imageURL: 'https://m.media-amazon.com/images/I/417f6xk78FL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-495',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 8,
            incoming: 32,
        },
        {
            product: 'VIEWSONIC 187 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-380',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 1,
            incoming: 29,
        },
        {
            product: 'ASUS 325 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/41DnbGHFhDL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-396',
            status: 'Paused',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'BENQ 412 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41LY5DafDIL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-752',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 20,
            incoming: 9,
        },
        {
            product: 'DELL 231 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41DnbGHFhDL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-776',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'MSI 669 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41LY5DafDIL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-307',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'HP 568 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/417f6xk78FL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-685',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 43,
            incoming: 26,
        },
        {
            product: 'PHILIPS 573 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/51exKYtDPjL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-201',
            status: 'Paused',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'ACER 915 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41DnbGHFhDL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-465',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 13,
            incoming: 5,
        },
        {
            product: 'DELL 421 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/417f6xk78FL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-791',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 3,
            committed: 1,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'PHILIPS 438 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-278',
            status: 'Paused',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'HP 138 Display',
            imageURL: 'https://m.media-amazon.com/images/I/51exKYtDPjL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-295',
            status: 'Paused',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'ASUS 282 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41qcLf3LCuL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-262',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 26,
            committed: 2,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'MSI 866 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41LY5DafDIL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-292',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 15,
            committed: 1,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'SAMSUNG 650 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/41LY5DafDIL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-158',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 13,
            committed: 10,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'AOC 276 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41CKarkc4EL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-104',
            status: 'Active',
            whenSoldOut: 'Discontinue',
            available: 26,
            committed: 10,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'AOC 365 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41qcLf3LCuL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-942',
            status: 'Paused',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'AOC 398 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/41DnbGHFhDL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-177',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 7,
            incoming: 1,
        },
        {
            product: 'LG 921 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41DnbGHFhDL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-218',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 8,
            committed: 2,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'DELL 260 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/417f6xk78FL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-671',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 13,
            incoming: 27,
        },
        {
            product: 'SAMSUNG 962 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41xEuOTeNtL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-201',
            status: 'Out of Stock',
            whenSoldOut: 'Back order',
            available: 0,
            committed: 0,
            unavailable: 38,
            incoming: 30,
        },
        {
            product: 'BENQ 804 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41DnbGHFhDL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-629',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 36,
            committed: 2,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'DELL 428 Display',
            imageURL: 'https://m.media-amazon.com/images/I/41xEuOTeNtL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-380',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 17,
            committed: 5,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'LG 497 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41qcLf3LCuL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-899',
            status: 'Paused',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'SAMSUNG 527 Display',
            imageURL: 'https://m.media-amazon.com/images/I/51exKYtDPjL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-542',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 5,
            incoming: 27,
        },
        {
            product: 'DELL 827 Screen',
            imageURL: 'https://m.media-amazon.com/images/I/41LY5DafDIL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-660',
            status: 'Active',
            whenSoldOut: 'Back order',
            available: 14,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'LG 354 Display',
            imageURL: 'https://m.media-amazon.com/images/I/51exKYtDPjL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-835',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 31,
            incoming: 13,
        },
        {
            product: 'VIEWSONIC 709 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/41LY5DafDIL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-949',
            status: 'Paused',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
        {
            product: 'SAMSUNG 133 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/41qcLf3LCuL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-742',
            status: 'Out of Stock',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 35,
            incoming: 34,
        },
        {
            product: 'LG 719 Monitor',
            imageURL: 'https://m.media-amazon.com/images/I/41DnbGHFhDL._AC_UF480,480_SR480,480_.jpg',
            sku: 'MNTR-XYZ-615',
            status: 'Paused',
            whenSoldOut: 'Discontinue',
            available: 0,
            committed: 0,
            unavailable: 0,
            incoming: 0,
        },
    ];
}
