../node_modules/.bin/webpack --config webpack.config.js --entry ./ClientSideRowModelModule.ts -o ../bundles/ClientSideRowModelModule.bundle.js
../node_modules/.bin/webpack --config webpack.config.js --entry ./CsvExportModule.ts -o ../bundles/CsvExportModule.bundle.js
../node_modules/.bin/webpack --config webpack.config.js --entry ./InfiniteRowModelModule.ts -o ../bundles/InfiniteRowModelModule.bundle.js
../node_modules/.bin/webpack --config webpack.config.js --entry ./GridChartsModule.ts -o ../bundles/GridChartsModule.bundle.js
../node_modules/.bin/webpack --config webpack.config.js --entry ./ClipboardModule.ts -o ../bundles/ClipboardModule.bundle.js
../node_modules/.bin/webpack --config webpack.config.js --entry ./ColumnsToolPanelModule.ts -o ../bundles/ColumnsToolPanelModule.bundle.js
../node_modules/.bin/webpack --config webpack.config.js --entry ./ExcelExportModule.ts -o ../bundles/ExcelExportModule.bundle.js
../node_modules/.bin/webpack --config webpack.config.js --entry ./FiltersToolPanelModule.ts -o ../bundles/FiltersToolPanelModule.bundle.js
../node_modules/.bin/webpack --config webpack.config.js --entry ./MasterDetailModule.ts -o ../bundles/MasterDetailModule.bundle.js
../node_modules/.bin/webpack --config webpack.config.js --entry ./MenuModule.ts -o ../bundles/MenuModule.bundle.js
../node_modules/.bin/webpack --config webpack.config.js --entry ./RangeSelectionModule.ts -o ../bundles/RangeSelectionModule.bundle.js
../node_modules/.bin/webpack --config webpack.config.js --entry ./RichSelectModule.ts -o ../bundles/RichSelectModule.bundle.js
../node_modules/.bin/webpack --config webpack.config.js --entry ./RowGroupingModule.ts -o ../bundles/RowGroupingModule.bundle.js
../node_modules/.bin/webpack --config webpack.config.js --entry ./ServerSideRowModelModule.ts -o ../bundles/ServerSideRowModelModule.bundle.js
../node_modules/.bin/webpack --config webpack.config.js --entry ./SetFilterModule.ts -o ../bundles/SetFilterModule.bundle.js
../node_modules/.bin/webpack --config webpack.config.js --entry ./SideBarModule.ts -o ../bundles/SideBarModule.bundle.js
../node_modules/.bin/webpack --config webpack.config.js --entry ./StatusBarModule.ts -o ../bundles/StatusBarModule.bundle.js
../node_modules/.bin/webpack --config webpack.config.js --entry ./ViewportRowModelModule.ts -o ../bundles/ViewportRowModelModule.bundle.js