#!/usr/bin/env bash

git checkout HEAD -- .gitignore
git reset community-modules/angular/dist
git reset community-modules/client-side-row-model/dist
git reset community-modules/core/dist
git reset community-modules/csv-export/dist
git reset community-modules/infinite-row-model/dist
git reset community-modules/react/dist
git reset community-modules/styles/*.css
git reset community-modules/styles/_css-content.scss
git reset community-modules/vue3/dist
git reset enterprise-modules/advanced-filter/dist
git reset enterprise-modules/charts/dist
git reset enterprise-modules/charts-enterprise/dist
git reset enterprise-modules/clipboard/dist
git reset enterprise-modules/column-tool-panel/dist
git reset enterprise-modules/core/dist
git reset enterprise-modules/excel-export/dist
git reset enterprise-modules/filter-tool-panel/dist
git reset enterprise-modules/master-detail/dist
git reset enterprise-modules/menu/dist
git reset enterprise-modules/multi-filter/dist
git reset enterprise-modules/range-selection/dist
git reset enterprise-modules/rich-select/dist
git reset enterprise-modules/row-grouping/dist
git reset enterprise-modules/server-side-row-model/dist
git reset enterprise-modules/set-filter/dist
git reset enterprise-modules/side-bar/dist
git reset enterprise-modules/sparklines/dist
git reset enterprise-modules/status-bar/dist
git reset enterprise-modules/viewport-row-model/dist
git reset packages/ag-grid-angular/dist
git reset packages/ag-grid-charts-enterprise/dist
git reset packages/ag-grid-charts-enterprise/styles
git reset packages/ag-grid-community/dist
git reset packages/ag-grid-community/styles
git reset packages/ag-grid-enterprise/dist
git reset packages/ag-grid-enterprise/styles
git reset packages/ag-grid-react/dist
git reset packages/ag-grid-vue3/dist
git reset plugins/ag-grid-generate-code-reference-files/dist
git reset plugins/ag-grid-task-autogen/dist
git reset plugins/ag-grid-generate-code-reference-files/src/executors/generate/_copiedFromCore
