#!/usr/bin/env bash

git checkout HEAD -- .gitignore
git reset common-modules/license/dist
git reset grid-packages/ag-grid-vue/lib/main.d.ts
git reset grid-packages/ag-grid-vue/lib/main.js
git reset grid-packages/ag-grid-vue/main.d.ts
git reset grid-packages/ag-grid-vue/main.js
git reset grid-packages/ag-grid-vue/lib/
git reset grid-packages/ag-grid-vue3/lib/main.d.ts
git reset grid-packages/ag-grid-vue3/lib/main.js
git reset grid-packages/ag-grid-vue3/main.d.ts
git reset grid-packages/ag-grid-vue3/main.js
git reset grid-packages/ag-grid-vue3/lib/
git reset grid-packages/ag-grid-solid/dist
git reset grid-packages/ag-grid-react/lib
git reset grid-packages/ag-grid-react/bundles/
git reset grid-packages/ag-grid-enterprise/main.d.ts
git reset grid-packages/ag-grid-enterprise/dist
git reset grid-packages/ag-grid-community/src/styles
git reset grid-packages/ag-grid-vue3/dist
git reset grid-packages/ag-grid-community/dist
git reset grid-packages/ag-grid-community/main.d.ts
git reset grid-packages/ag-grid-angular/dist
git reset grid-enterprise-modules/all-modules/dist
git reset grid-enterprise-modules/all-modules/ts-lint-rules/dist
git reset grid-enterprise-modules/charts/dist
git reset grid-enterprise-modules/charts/typings
git reset grid-enterprise-modules/clipboard/dist
git reset grid-enterprise-modules/column-tool-panel/dist
git reset grid-enterprise-modules/core/dist
git reset grid-enterprise-modules/core/typings
git reset grid-enterprise-modules/excel-export/dist
git reset grid-enterprise-modules/filter-tool-panel/dist
git reset grid-enterprise-modules/master-detail/dist
git reset grid-enterprise-modules/menu/dist
git reset grid-enterprise-modules/range-selection/dist
git reset grid-enterprise-modules/rich-select/dist
git reset grid-enterprise-modules/row-grouping/dist
git reset grid-enterprise-modules/server-side-row-model/dist
git reset grid-enterprise-modules/multi-filter/dist
git reset grid-enterprise-modules/set-filter/dist
git reset grid-enterprise-modules/set-filter/typings
git reset grid-enterprise-modules/sparklines/dist
git reset grid-enterprise-modules/side-bar/dist
git reset grid-enterprise-modules/status-bar/dist
git reset grid-enterprise-modules/viewport-row-model/dist
git reset grid-community-modules/all-modules/dist
git reset grid-community-modules/angular/dist
git reset grid-community-modules/client-side-row-model/dist
git reset grid-community-modules/core/dist
git reset grid-community-modules/core/typings
git reset grid-enterprise-modules/excel-export/typings
git reset grid-community-modules/csv-export/dist
git reset grid-community-modules/csv-export/typings
git reset grid-community-modules/infinite-row-model/dist
git reset grid-community-modules/solid/dist
git reset grid-community-modules/react/lib
git reset grid-community-modules/react/bundles
git reset grid-community-modules/vue/dist
git reset grid-packages/ag-grid-vue/dist
git reset grid-community-modules/vue3/dist
git reset grid-community-modules/vue3/lib
git reset charts-community-modules/ag-charts-angular/dist
git reset charts-community-modules/ag-charts-community/dist
git reset charts-community-modules/ag-charts-community/typings
git reset charts-community-modules/ag-charts-react/lib
git reset charts-community-modules/ag-charts-react/umd
git reset charts-community-modules/ag-charts-vue/lib
git reset charts-community-modules/ag-charts-vue/dist
git reset charts-community-modules/ag-charts-vue3/lib
git reset charts-community-modules/ag-charts-vue3/dist
git reset charts-enterprise-modules/ag-charts-enterprise/dist
git reset grid-community-modules/vue/lib

git reset grid-community-modules/all-modules/styles
git reset grid-enterprise-modules/all-modules/styles
git reset grid-community-modules/angular-legacy/dist
git reset grid-community-modules/styles/*.css
git reset grid-community-modules/styles/_css-content.scss

git reset grid-packages/ag-grid-angular-legacy/dist
git reset grid-packages/ag-grid-community/styles
git reset grid-packages/ag-grid-enterprise/styles
git reset charts-community-modules/ag-charts-angular-legacy/dist
git reset grid-packages/ag-grid-docs/documentation/cypress.config.AUTO.json
