export interface IProduct {
    productName: string;
    salesRevenue: number;
    profitMargin: number;
    status: 'Delivered' | 'Pending' | 'Cancelled';
}

export function getData(): IProduct[] {
    return [
        { productName: 'Wireless Headphones', salesRevenue: 15420, profitMargin: 0.28, status: 'Delivered' },
        { productName: 'USB-C Hub', salesRevenue: 8750, profitMargin: 0.22, status: 'Delivered' },
        { productName: 'Mechanical Keyboard', salesRevenue: 22100, profitMargin: 0.31, status: 'Pending' },
        { productName: 'Monitor Stand', salesRevenue: 3200, profitMargin: 0.18, status: 'Delivered' },
        { productName: 'Webcam HD', salesRevenue: 12800, profitMargin: 0.25, status: 'Delivered' },
        { productName: 'Laptop Sleeve', salesRevenue: 890, profitMargin: 0.35, status: 'Cancelled' },
        { productName: 'Mouse Pad XL', salesRevenue: 450, profitMargin: 0.42, status: 'Delivered' },
        { productName: 'Bluetooth Speaker', salesRevenue: 18900, profitMargin: 0.24, status: 'Pending' },
        { productName: 'Phone Stand', salesRevenue: 1250, profitMargin: 0.38, status: 'Delivered' },
        { productName: 'Cable Organiser', salesRevenue: 680, profitMargin: 0.45, status: 'Delivered' },
        { productName: 'Desk Lamp LED', salesRevenue: 7400, profitMargin: 0.21, status: 'Delivered' },
        { productName: 'Ergonomic Mouse', salesRevenue: 11200, profitMargin: 0.27, status: 'Pending' },
        { productName: 'Portable SSD', salesRevenue: 28500, profitMargin: 0.19, status: 'Delivered' },
        { productName: 'Screen Protector', salesRevenue: 320, profitMargin: 0.52, status: 'Delivered' },
        { productName: 'HDMI Cable', salesRevenue: 1800, profitMargin: 0.33, status: 'Delivered' },
        { productName: 'Wireless Charger', salesRevenue: 9600, profitMargin: 0.26, status: 'Cancelled' },
        { productName: 'USB Flash Drive', salesRevenue: 2100, profitMargin: 0.29, status: 'Delivered' },
        { productName: 'Laptop Stand', salesRevenue: 14300, profitMargin: 0.23, status: 'Delivered' },
        { productName: 'Power Bank', salesRevenue: 16700, profitMargin: 0.21, status: 'Pending' },
        { productName: 'Smart Watch Band', salesRevenue: 4500, profitMargin: 0.34, status: 'Delivered' },
        { productName: 'Noise Cancelling Earbuds', salesRevenue: 35200, profitMargin: 0.32, status: 'Delivered' },
        { productName: 'Tablet Case', salesRevenue: 2800, profitMargin: 0.41, status: 'Delivered' },
        { productName: 'Mini Projector', salesRevenue: 42000, profitMargin: 0.18, status: 'Pending' },
        { productName: 'Ring Light', salesRevenue: 5600, profitMargin: 0.27, status: 'Delivered' },
        { productName: 'Microphone USB', salesRevenue: 13400, profitMargin: 0.24, status: 'Delivered' },
        { productName: 'Drawing Tablet', salesRevenue: 19800, profitMargin: 0.22, status: 'Cancelled' },
        { productName: 'Network Switch', salesRevenue: 7800, profitMargin: 0.16, status: 'Delivered' },
        { productName: 'Ethernet Cable', salesRevenue: 520, profitMargin: 0.38, status: 'Delivered' },
        { productName: 'Router WiFi 6', salesRevenue: 24600, profitMargin: 0.2, status: 'Pending' },
        { productName: 'Surge Protector', salesRevenue: 3100, profitMargin: 0.31, status: 'Delivered' },
        { productName: 'Desk Organiser', salesRevenue: 1650, profitMargin: 0.44, status: 'Delivered' },
        { productName: 'Monitor Arm', salesRevenue: 8900, profitMargin: 0.25, status: 'Delivered' },
        { productName: 'Keyboard Wrist Rest', salesRevenue: 780, profitMargin: 0.48, status: 'Pending' },
        { productName: 'Document Scanner', salesRevenue: 17500, profitMargin: 0.17, status: 'Delivered' },
        { productName: 'Label Printer', salesRevenue: 6200, profitMargin: 0.23, status: 'Delivered' },
        { productName: 'Paper Shredder', salesRevenue: 9400, profitMargin: 0.19, status: 'Cancelled' },
        { productName: 'Air Purifier', salesRevenue: 31000, profitMargin: 0.21, status: 'Delivered' },
        { productName: 'Desk Fan', salesRevenue: 2400, profitMargin: 0.36, status: 'Delivered' },
        { productName: 'Foot Rest', salesRevenue: 1900, profitMargin: 0.42, status: 'Pending' },
        { productName: 'Cable Management Kit', salesRevenue: 850, profitMargin: 0.51, status: 'Delivered' },
        { productName: 'Privacy Screen', salesRevenue: 4800, profitMargin: 0.28, status: 'Delivered' },
        { productName: 'Cleaning Kit', salesRevenue: 380, profitMargin: 0.55, status: 'Delivered' },
        { productName: 'VR Headset', salesRevenue: 38500, profitMargin: 0.15, status: 'Pending' },
        { productName: 'Game Controller', salesRevenue: 7200, profitMargin: 0.26, status: 'Delivered' },
        { productName: 'Capture Card', salesRevenue: 12600, profitMargin: 0.22, status: 'Delivered' },
        { productName: 'Stream Deck', salesRevenue: 14900, profitMargin: 0.24, status: 'Cancelled' },
        { productName: 'Green Screen', salesRevenue: 5100, profitMargin: 0.33, status: 'Delivered' },
        { productName: 'Tripod', salesRevenue: 3800, profitMargin: 0.29, status: 'Delivered' },
        { productName: 'Camera Lens', salesRevenue: 28900, profitMargin: 0.18, status: 'Pending' },
        { productName: 'Memory Card', salesRevenue: 1400, profitMargin: 0.37, status: 'Delivered' },
        { productName: 'Card Reader', salesRevenue: 620, profitMargin: 0.43, status: 'Delivered' },
        { productName: 'External GPU', salesRevenue: 45000, profitMargin: 0.14, status: 'Delivered' },
        { productName: 'RAM Module', salesRevenue: 8600, profitMargin: 0.21, status: 'Pending' },
        { productName: 'CPU Cooler', salesRevenue: 6800, profitMargin: 0.25, status: 'Delivered' },
        { productName: 'Thermal Paste', salesRevenue: 180, profitMargin: 0.58, status: 'Delivered' },
        { productName: 'PC Case', salesRevenue: 11500, profitMargin: 0.2, status: 'Cancelled' },
        { productName: 'Case Fan', salesRevenue: 950, profitMargin: 0.39, status: 'Delivered' },
        { productName: 'RGB Light Strip', salesRevenue: 2200, profitMargin: 0.35, status: 'Delivered' },
        { productName: 'Smart Plug', salesRevenue: 1100, profitMargin: 0.41, status: 'Pending' },
        { productName: 'Smart Bulb', salesRevenue: 1350, profitMargin: 0.38, status: 'Delivered' },
        { productName: 'Door Sensor', salesRevenue: 580, profitMargin: 0.46, status: 'Delivered' },
        { productName: 'Motion Detector', salesRevenue: 920, profitMargin: 0.44, status: 'Delivered' },
        { productName: 'Smart Thermostat', salesRevenue: 15800, profitMargin: 0.19, status: 'Pending' },
        { productName: 'Security Camera', salesRevenue: 21400, profitMargin: 0.23, status: 'Delivered' },
        { productName: 'Video Doorbell', salesRevenue: 18200, profitMargin: 0.21, status: 'Delivered' },
        { productName: 'Smart Lock', salesRevenue: 24100, profitMargin: 0.2, status: 'Cancelled' },
        { productName: 'Voice Assistant', salesRevenue: 9800, profitMargin: 0.17, status: 'Delivered' },
        { productName: 'Smart Display', salesRevenue: 16400, profitMargin: 0.18, status: 'Delivered' },
        { productName: 'Fitness Tracker', salesRevenue: 7900, profitMargin: 0.28, status: 'Pending' },
        { productName: 'Heart Rate Monitor', salesRevenue: 4200, profitMargin: 0.32, status: 'Delivered' },
        { productName: 'Yoga Mat', salesRevenue: 650, profitMargin: 0.47, status: 'Delivered' },
        { productName: 'Resistance Bands', salesRevenue: 420, profitMargin: 0.53, status: 'Delivered' },
        { productName: 'Foam Roller', salesRevenue: 780, profitMargin: 0.45, status: 'Pending' },
        { productName: 'Water Bottle Smart', salesRevenue: 1800, profitMargin: 0.36, status: 'Delivered' },
        { productName: 'Posture Corrector', salesRevenue: 2600, profitMargin: 0.4, status: 'Delivered' },
        { productName: 'Blue Light Glasses', salesRevenue: 3400, profitMargin: 0.43, status: 'Cancelled' },
        { productName: 'Desk Bike', salesRevenue: 27500, profitMargin: 0.16, status: 'Delivered' },
        { productName: 'Standing Mat', salesRevenue: 1950, profitMargin: 0.38, status: 'Delivered' },
    ];
}
