import type { GridApi, GridOptions } from 'ag-grid-community';
import {
    ClientSideRowModelModule,
    ModuleRegistry,
    NumberFilterModule,
    TextFilterModule,
    ValidationModule,
    createGrid,
} from 'ag-grid-community';
import { AutoGenerateColumnsModule } from 'ag-grid-enterprise';

import { FileDropOverlay } from './fileDropOverlay_typescript';

ModuleRegistry.registerModules([
    ClientSideRowModelModule,
    TextFilterModule,
    NumberFilterModule,
    AutoGenerateColumnsModule,
    ...(process.env.NODE_ENV !== 'production' ? [ValidationModule] : []),
]);

const sampleCsv = `Name,Age,Country,Sport,Gold,Silver,Bronze
Michael Phelps,23,United States,Swimming,8,0,0
Usain Bolt,21,Jamaica,Athletics,3,0,0
Natalie Coughlin,25,United States,Swimming,1,2,3
Stephanie Rice,20,Australia,Swimming,3,0,0
Chris Hoy,32,Great Britain,Cycling,3,0,0
Rebecca Adlington,19,Great Britain,Swimming,2,0,0
Kobe Bryant,29,United States,Basketball,1,0,0
Elena Isinbaeva,26,Russia,Athletics,1,0,0
Shelly-Ann Fraser,21,Jamaica,Athletics,1,0,0
Alain Bernard,25,France,Swimming,1,1,0`;

let gridApi: GridApi;

const gridOptions: GridOptions = {
    autoGenerateColumnDefs: true,
    activeOverlay: FileDropOverlay,
    processAutoGeneratedColumnDefs: (params) => {
        return params.colDefs.map((colDef) => {
            const sampleValue = params.rowData[0]?.[colDef.field!];
            if (!isNaN(Number(sampleValue))) {
                return { ...colDef, filter: 'agNumberColumnFilter' };
            }
            return { ...colDef, filter: 'agTextColumnFilter' };
        });
    },
};

function unquote(value: string): string {
    const trimmed = value.trim();
    if (trimmed.length >= 2 && trimmed[0] === '"' && trimmed[trimmed.length - 1] === '"') {
        return trimmed.slice(1, -1).replace(/""/g, '"');
    }
    return trimmed;
}

function parseCsv(csvText: string): Record<string, string | number>[] {
    const lines = csvText.trim().split('\n');
    const headers = lines[0].split(',').map(unquote);
    const rows: Record<string, string | number>[] = [];
    for (let i = 1, len = lines.length; i < len; ++i) {
        const values = lines[i].split(',').map(unquote);
        const row: Record<string, string | number> = {};
        for (let j = 0, hLen = headers.length; j < hLen; ++j) {
            const val = values[j];
            row[headers[j]] = isNaN(Number(val)) ? val : Number(val);
        }
        rows.push(row);
    }
    return rows;
}

function loadData(csvText: string) {
    const rowData = parseCsv(csvText);
    gridApi.setGridOption('rowData', rowData);
    gridApi.setGridOption('activeOverlay', undefined);
}

function onLoadSampleData() {
    loadData(sampleCsv);
}

function onClearData() {
    gridApi.setGridOption('rowData', null);
    gridApi.setGridOption('columnDefs', []);
    gridApi.setGridOption('activeOverlay', FileDropOverlay);
}

document.addEventListener('DOMContentLoaded', () => {
    const gridDiv = document.querySelector<HTMLElement>('#myGrid')!;
    gridApi = createGrid(gridDiv, gridOptions);

    gridDiv.addEventListener('dragover', (event) => {
        event.preventDefault();
    });

    gridDiv.addEventListener('drop', (event) => {
        event.preventDefault();
        const file = event.dataTransfer?.files[0];
        if (!file) {
            return;
        }
        const reader = new FileReader();
        reader.onload = (e) => {
            const text = e.target?.result as string;
            loadData(text);
        };
        reader.readAsText(file);
    });
});
