/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../src/aggrid.module';
class AgGridModuleInjector extends import0.ɵNgModuleInjector<import1.AgGridModule> {
  _AgGridModule_0:import1.AgGridModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.AgGridModule {
    this._AgGridModule_0 = new import1.AgGridModule();
    return this._AgGridModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.AgGridModule)) { return this._AgGridModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AgGridModuleNgFactory:import0.NgModuleFactory<import1.AgGridModule> = new import0.NgModuleFactory<any>(AgGridModuleInjector,import1.AgGridModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FsYmVydG8vR29vZ2xlIERyaXZlL2FnLWdyaWQvcmVsZWFzZXMvOS4wLjMvYWctZ3JpZC1hbmd1bGFyL3NyYy9hZ2dyaWQubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2FsYmVydG8vR29vZ2xlIERyaXZlL2FnLWdyaWQvcmVsZWFzZXMvOS4wLjMvYWctZ3JpZC1hbmd1bGFyL3NyYy9hZ2dyaWQubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
