/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../src/agGridNg2';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_container';
import * as import7 from '../../src/ng2FrameworkFactory';
import * as import8 from '../../src/ng2FrameworkComponentWrapper';
import * as import9 from '@angular/core/src/linker/query_list';
import * as import10 from '@angular/core/src/linker/view_type';
import * as import11 from '@angular/core/src/change_detection/constants';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '../../src/baseComponentFactory';
import * as import14 from '@angular/core/src/zone/ng_zone';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from '@angular/core/src/linker/component_factory_resolver';
export class Wrapper_AgGridNg2 {
  /*private*/ _eventHandler:Function;
  context:import0.AgGridNg2;
  /*private*/ _changed:boolean;
  /*private*/ _changes:{[key: string]:any};
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  /*private*/ _expr_50:any;
  /*private*/ _expr_51:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_53:any;
  /*private*/ _expr_54:any;
  /*private*/ _expr_55:any;
  /*private*/ _expr_56:any;
  /*private*/ _expr_57:any;
  /*private*/ _expr_58:any;
  /*private*/ _expr_59:any;
  /*private*/ _expr_60:any;
  /*private*/ _expr_61:any;
  /*private*/ _expr_62:any;
  /*private*/ _expr_63:any;
  /*private*/ _expr_64:any;
  /*private*/ _expr_65:any;
  /*private*/ _expr_66:any;
  /*private*/ _expr_67:any;
  /*private*/ _expr_68:any;
  /*private*/ _expr_69:any;
  /*private*/ _expr_70:any;
  /*private*/ _expr_71:any;
  /*private*/ _expr_72:any;
  /*private*/ _expr_73:any;
  /*private*/ _expr_74:any;
  /*private*/ _expr_75:any;
  /*private*/ _expr_76:any;
  /*private*/ _expr_77:any;
  /*private*/ _expr_78:any;
  /*private*/ _expr_79:any;
  /*private*/ _expr_80:any;
  /*private*/ _expr_81:any;
  /*private*/ _expr_82:any;
  /*private*/ _expr_83:any;
  /*private*/ _expr_84:any;
  /*private*/ _expr_85:any;
  /*private*/ _expr_86:any;
  /*private*/ _expr_87:any;
  /*private*/ _expr_88:any;
  /*private*/ _expr_89:any;
  /*private*/ _expr_90:any;
  /*private*/ _expr_91:any;
  /*private*/ _expr_92:any;
  /*private*/ _expr_93:any;
  /*private*/ _expr_94:any;
  /*private*/ _expr_95:any;
  /*private*/ _expr_96:any;
  /*private*/ _expr_97:any;
  /*private*/ _expr_98:any;
  /*private*/ _expr_99:any;
  /*private*/ _expr_100:any;
  /*private*/ _expr_101:any;
  /*private*/ _expr_102:any;
  /*private*/ _expr_103:any;
  /*private*/ _expr_104:any;
  /*private*/ _expr_105:any;
  /*private*/ _expr_106:any;
  /*private*/ _expr_107:any;
  /*private*/ _expr_108:any;
  /*private*/ _expr_109:any;
  /*private*/ _expr_110:any;
  /*private*/ _expr_111:any;
  /*private*/ _expr_112:any;
  /*private*/ _expr_113:any;
  /*private*/ _expr_114:any;
  /*private*/ _expr_115:any;
  /*private*/ _expr_116:any;
  /*private*/ _expr_117:any;
  /*private*/ _expr_118:any;
  /*private*/ _expr_119:any;
  /*private*/ _expr_120:any;
  /*private*/ _expr_121:any;
  /*private*/ _expr_122:any;
  /*private*/ _expr_123:any;
  /*private*/ _expr_124:any;
  /*private*/ _expr_125:any;
  /*private*/ _expr_126:any;
  /*private*/ _expr_127:any;
  /*private*/ _expr_128:any;
  /*private*/ _expr_129:any;
  /*private*/ _expr_130:any;
  /*private*/ _expr_131:any;
  /*private*/ _expr_132:any;
  /*private*/ _expr_133:any;
  /*private*/ _expr_134:any;
  /*private*/ _expr_135:any;
  /*private*/ _expr_136:any;
  /*private*/ _expr_137:any;
  /*private*/ _expr_138:any;
  /*private*/ _expr_139:any;
  /*private*/ _expr_140:any;
  /*private*/ _expr_141:any;
  /*private*/ _expr_142:any;
  /*private*/ _expr_143:any;
  /*private*/ _expr_144:any;
  /*private*/ _expr_145:any;
  /*private*/ _expr_146:any;
  /*private*/ _expr_147:any;
  /*private*/ _expr_148:any;
  /*private*/ _expr_149:any;
  /*private*/ _expr_150:any;
  /*private*/ _expr_151:any;
  /*private*/ _expr_152:any;
  subscription0:any;
  subscription1:any;
  subscription2:any;
  subscription3:any;
  subscription4:any;
  subscription5:any;
  subscription6:any;
  subscription7:any;
  subscription8:any;
  subscription9:any;
  subscription10:any;
  subscription11:any;
  subscription12:any;
  subscription13:any;
  subscription14:any;
  subscription15:any;
  subscription16:any;
  subscription17:any;
  subscription18:any;
  subscription19:any;
  subscription20:any;
  subscription21:any;
  subscription22:any;
  subscription23:any;
  subscription24:any;
  subscription25:any;
  subscription26:any;
  subscription27:any;
  subscription28:any;
  subscription29:any;
  subscription30:any;
  subscription31:any;
  subscription32:any;
  subscription33:any;
  subscription34:any;
  subscription35:any;
  subscription36:any;
  subscription37:any;
  subscription38:any;
  subscription39:any;
  subscription40:any;
  subscription41:any;
  subscription42:any;
  subscription43:any;
  subscription44:any;
  subscription45:any;
  subscription46:any;
  subscription47:any;
  subscription48:any;
  subscription49:any;
  subscription50:any;
  subscription51:any;
  subscription52:any;
  subscription53:any;
  subscription54:any;
  subscription55:any;
  subscription56:any;
  subscription57:any;
  subscription58:any;
  subscription59:any;
  subscription60:any;
  subscription61:any;
  subscription62:any;
  subscription63:any;
  subscription64:any;
  subscription65:any;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this._changed = false;
    this._changes = {};
    this.context = new import0.AgGridNg2(p0,p1,p2,p3,p4);
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
    this._expr_2 = import1.UNINITIALIZED;
    this._expr_3 = import1.UNINITIALIZED;
    this._expr_4 = import1.UNINITIALIZED;
    this._expr_5 = import1.UNINITIALIZED;
    this._expr_6 = import1.UNINITIALIZED;
    this._expr_7 = import1.UNINITIALIZED;
    this._expr_8 = import1.UNINITIALIZED;
    this._expr_9 = import1.UNINITIALIZED;
    this._expr_10 = import1.UNINITIALIZED;
    this._expr_11 = import1.UNINITIALIZED;
    this._expr_12 = import1.UNINITIALIZED;
    this._expr_13 = import1.UNINITIALIZED;
    this._expr_14 = import1.UNINITIALIZED;
    this._expr_15 = import1.UNINITIALIZED;
    this._expr_16 = import1.UNINITIALIZED;
    this._expr_17 = import1.UNINITIALIZED;
    this._expr_18 = import1.UNINITIALIZED;
    this._expr_19 = import1.UNINITIALIZED;
    this._expr_20 = import1.UNINITIALIZED;
    this._expr_21 = import1.UNINITIALIZED;
    this._expr_22 = import1.UNINITIALIZED;
    this._expr_23 = import1.UNINITIALIZED;
    this._expr_24 = import1.UNINITIALIZED;
    this._expr_25 = import1.UNINITIALIZED;
    this._expr_26 = import1.UNINITIALIZED;
    this._expr_27 = import1.UNINITIALIZED;
    this._expr_28 = import1.UNINITIALIZED;
    this._expr_29 = import1.UNINITIALIZED;
    this._expr_30 = import1.UNINITIALIZED;
    this._expr_31 = import1.UNINITIALIZED;
    this._expr_32 = import1.UNINITIALIZED;
    this._expr_33 = import1.UNINITIALIZED;
    this._expr_34 = import1.UNINITIALIZED;
    this._expr_35 = import1.UNINITIALIZED;
    this._expr_36 = import1.UNINITIALIZED;
    this._expr_37 = import1.UNINITIALIZED;
    this._expr_38 = import1.UNINITIALIZED;
    this._expr_39 = import1.UNINITIALIZED;
    this._expr_40 = import1.UNINITIALIZED;
    this._expr_41 = import1.UNINITIALIZED;
    this._expr_42 = import1.UNINITIALIZED;
    this._expr_43 = import1.UNINITIALIZED;
    this._expr_44 = import1.UNINITIALIZED;
    this._expr_45 = import1.UNINITIALIZED;
    this._expr_46 = import1.UNINITIALIZED;
    this._expr_47 = import1.UNINITIALIZED;
    this._expr_48 = import1.UNINITIALIZED;
    this._expr_49 = import1.UNINITIALIZED;
    this._expr_50 = import1.UNINITIALIZED;
    this._expr_51 = import1.UNINITIALIZED;
    this._expr_52 = import1.UNINITIALIZED;
    this._expr_53 = import1.UNINITIALIZED;
    this._expr_54 = import1.UNINITIALIZED;
    this._expr_55 = import1.UNINITIALIZED;
    this._expr_56 = import1.UNINITIALIZED;
    this._expr_57 = import1.UNINITIALIZED;
    this._expr_58 = import1.UNINITIALIZED;
    this._expr_59 = import1.UNINITIALIZED;
    this._expr_60 = import1.UNINITIALIZED;
    this._expr_61 = import1.UNINITIALIZED;
    this._expr_62 = import1.UNINITIALIZED;
    this._expr_63 = import1.UNINITIALIZED;
    this._expr_64 = import1.UNINITIALIZED;
    this._expr_65 = import1.UNINITIALIZED;
    this._expr_66 = import1.UNINITIALIZED;
    this._expr_67 = import1.UNINITIALIZED;
    this._expr_68 = import1.UNINITIALIZED;
    this._expr_69 = import1.UNINITIALIZED;
    this._expr_70 = import1.UNINITIALIZED;
    this._expr_71 = import1.UNINITIALIZED;
    this._expr_72 = import1.UNINITIALIZED;
    this._expr_73 = import1.UNINITIALIZED;
    this._expr_74 = import1.UNINITIALIZED;
    this._expr_75 = import1.UNINITIALIZED;
    this._expr_76 = import1.UNINITIALIZED;
    this._expr_77 = import1.UNINITIALIZED;
    this._expr_78 = import1.UNINITIALIZED;
    this._expr_79 = import1.UNINITIALIZED;
    this._expr_80 = import1.UNINITIALIZED;
    this._expr_81 = import1.UNINITIALIZED;
    this._expr_82 = import1.UNINITIALIZED;
    this._expr_83 = import1.UNINITIALIZED;
    this._expr_84 = import1.UNINITIALIZED;
    this._expr_85 = import1.UNINITIALIZED;
    this._expr_86 = import1.UNINITIALIZED;
    this._expr_87 = import1.UNINITIALIZED;
    this._expr_88 = import1.UNINITIALIZED;
    this._expr_89 = import1.UNINITIALIZED;
    this._expr_90 = import1.UNINITIALIZED;
    this._expr_91 = import1.UNINITIALIZED;
    this._expr_92 = import1.UNINITIALIZED;
    this._expr_93 = import1.UNINITIALIZED;
    this._expr_94 = import1.UNINITIALIZED;
    this._expr_95 = import1.UNINITIALIZED;
    this._expr_96 = import1.UNINITIALIZED;
    this._expr_97 = import1.UNINITIALIZED;
    this._expr_98 = import1.UNINITIALIZED;
    this._expr_99 = import1.UNINITIALIZED;
    this._expr_100 = import1.UNINITIALIZED;
    this._expr_101 = import1.UNINITIALIZED;
    this._expr_102 = import1.UNINITIALIZED;
    this._expr_103 = import1.UNINITIALIZED;
    this._expr_104 = import1.UNINITIALIZED;
    this._expr_105 = import1.UNINITIALIZED;
    this._expr_106 = import1.UNINITIALIZED;
    this._expr_107 = import1.UNINITIALIZED;
    this._expr_108 = import1.UNINITIALIZED;
    this._expr_109 = import1.UNINITIALIZED;
    this._expr_110 = import1.UNINITIALIZED;
    this._expr_111 = import1.UNINITIALIZED;
    this._expr_112 = import1.UNINITIALIZED;
    this._expr_113 = import1.UNINITIALIZED;
    this._expr_114 = import1.UNINITIALIZED;
    this._expr_115 = import1.UNINITIALIZED;
    this._expr_116 = import1.UNINITIALIZED;
    this._expr_117 = import1.UNINITIALIZED;
    this._expr_118 = import1.UNINITIALIZED;
    this._expr_119 = import1.UNINITIALIZED;
    this._expr_120 = import1.UNINITIALIZED;
    this._expr_121 = import1.UNINITIALIZED;
    this._expr_122 = import1.UNINITIALIZED;
    this._expr_123 = import1.UNINITIALIZED;
    this._expr_124 = import1.UNINITIALIZED;
    this._expr_125 = import1.UNINITIALIZED;
    this._expr_126 = import1.UNINITIALIZED;
    this._expr_127 = import1.UNINITIALIZED;
    this._expr_128 = import1.UNINITIALIZED;
    this._expr_129 = import1.UNINITIALIZED;
    this._expr_130 = import1.UNINITIALIZED;
    this._expr_131 = import1.UNINITIALIZED;
    this._expr_132 = import1.UNINITIALIZED;
    this._expr_133 = import1.UNINITIALIZED;
    this._expr_134 = import1.UNINITIALIZED;
    this._expr_135 = import1.UNINITIALIZED;
    this._expr_136 = import1.UNINITIALIZED;
    this._expr_137 = import1.UNINITIALIZED;
    this._expr_138 = import1.UNINITIALIZED;
    this._expr_139 = import1.UNINITIALIZED;
    this._expr_140 = import1.UNINITIALIZED;
    this._expr_141 = import1.UNINITIALIZED;
    this._expr_142 = import1.UNINITIALIZED;
    this._expr_143 = import1.UNINITIALIZED;
    this._expr_144 = import1.UNINITIALIZED;
    this._expr_145 = import1.UNINITIALIZED;
    this._expr_146 = import1.UNINITIALIZED;
    this._expr_147 = import1.UNINITIALIZED;
    this._expr_148 = import1.UNINITIALIZED;
    this._expr_149 = import1.UNINITIALIZED;
    this._expr_150 = import1.UNINITIALIZED;
    this._expr_151 = import1.UNINITIALIZED;
    this._expr_152 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    this.context.ngOnDestroy();
    (this.subscription0 && this.subscription0.unsubscribe());
    (this.subscription1 && this.subscription1.unsubscribe());
    (this.subscription2 && this.subscription2.unsubscribe());
    (this.subscription3 && this.subscription3.unsubscribe());
    (this.subscription4 && this.subscription4.unsubscribe());
    (this.subscription5 && this.subscription5.unsubscribe());
    (this.subscription6 && this.subscription6.unsubscribe());
    (this.subscription7 && this.subscription7.unsubscribe());
    (this.subscription8 && this.subscription8.unsubscribe());
    (this.subscription9 && this.subscription9.unsubscribe());
    (this.subscription10 && this.subscription10.unsubscribe());
    (this.subscription11 && this.subscription11.unsubscribe());
    (this.subscription12 && this.subscription12.unsubscribe());
    (this.subscription13 && this.subscription13.unsubscribe());
    (this.subscription14 && this.subscription14.unsubscribe());
    (this.subscription15 && this.subscription15.unsubscribe());
    (this.subscription16 && this.subscription16.unsubscribe());
    (this.subscription17 && this.subscription17.unsubscribe());
    (this.subscription18 && this.subscription18.unsubscribe());
    (this.subscription19 && this.subscription19.unsubscribe());
    (this.subscription20 && this.subscription20.unsubscribe());
    (this.subscription21 && this.subscription21.unsubscribe());
    (this.subscription22 && this.subscription22.unsubscribe());
    (this.subscription23 && this.subscription23.unsubscribe());
    (this.subscription24 && this.subscription24.unsubscribe());
    (this.subscription25 && this.subscription25.unsubscribe());
    (this.subscription26 && this.subscription26.unsubscribe());
    (this.subscription27 && this.subscription27.unsubscribe());
    (this.subscription28 && this.subscription28.unsubscribe());
    (this.subscription29 && this.subscription29.unsubscribe());
    (this.subscription30 && this.subscription30.unsubscribe());
    (this.subscription31 && this.subscription31.unsubscribe());
    (this.subscription32 && this.subscription32.unsubscribe());
    (this.subscription33 && this.subscription33.unsubscribe());
    (this.subscription34 && this.subscription34.unsubscribe());
    (this.subscription35 && this.subscription35.unsubscribe());
    (this.subscription36 && this.subscription36.unsubscribe());
    (this.subscription37 && this.subscription37.unsubscribe());
    (this.subscription38 && this.subscription38.unsubscribe());
    (this.subscription39 && this.subscription39.unsubscribe());
    (this.subscription40 && this.subscription40.unsubscribe());
    (this.subscription41 && this.subscription41.unsubscribe());
    (this.subscription42 && this.subscription42.unsubscribe());
    (this.subscription43 && this.subscription43.unsubscribe());
    (this.subscription44 && this.subscription44.unsubscribe());
    (this.subscription45 && this.subscription45.unsubscribe());
    (this.subscription46 && this.subscription46.unsubscribe());
    (this.subscription47 && this.subscription47.unsubscribe());
    (this.subscription48 && this.subscription48.unsubscribe());
    (this.subscription49 && this.subscription49.unsubscribe());
    (this.subscription50 && this.subscription50.unsubscribe());
    (this.subscription51 && this.subscription51.unsubscribe());
    (this.subscription52 && this.subscription52.unsubscribe());
    (this.subscription53 && this.subscription53.unsubscribe());
    (this.subscription54 && this.subscription54.unsubscribe());
    (this.subscription55 && this.subscription55.unsubscribe());
    (this.subscription56 && this.subscription56.unsubscribe());
    (this.subscription57 && this.subscription57.unsubscribe());
    (this.subscription58 && this.subscription58.unsubscribe());
    (this.subscription59 && this.subscription59.unsubscribe());
    (this.subscription60 && this.subscription60.unsubscribe());
    (this.subscription61 && this.subscription61.unsubscribe());
    (this.subscription62 && this.subscription62.unsubscribe());
    (this.subscription63 && this.subscription63.unsubscribe());
    (this.subscription64 && this.subscription64.unsubscribe());
    (this.subscription65 && this.subscription65.unsubscribe());
  }
  check_gridOptions(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.gridOptions = currValue;
      this._changes['gridOptions'] = new import1.SimpleChange(this._expr_0,currValue);
      this._expr_0 = currValue;
    }
  }
  check_slaveGrids(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.slaveGrids = currValue;
      this._changes['slaveGrids'] = new import1.SimpleChange(this._expr_1,currValue);
      this._expr_1 = currValue;
    }
  }
  check_rowData(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_2,currValue))) {
      this._changed = true;
      this.context.rowData = currValue;
      this._changes['rowData'] = new import1.SimpleChange(this._expr_2,currValue);
      this._expr_2 = currValue;
    }
  }
  check_floatingTopRowData(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_3,currValue))) {
      this._changed = true;
      this.context.floatingTopRowData = currValue;
      this._changes['floatingTopRowData'] = new import1.SimpleChange(this._expr_3,currValue);
      this._expr_3 = currValue;
    }
  }
  check_floatingBottomRowData(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_4,currValue))) {
      this._changed = true;
      this.context.floatingBottomRowData = currValue;
      this._changes['floatingBottomRowData'] = new import1.SimpleChange(this._expr_4,currValue);
      this._expr_4 = currValue;
    }
  }
  check_columnDefs(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_5,currValue))) {
      this._changed = true;
      this.context.columnDefs = currValue;
      this._changes['columnDefs'] = new import1.SimpleChange(this._expr_5,currValue);
      this._expr_5 = currValue;
    }
  }
  check_defaultColDef(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_6,currValue))) {
      this._changed = true;
      this.context.defaultColDef = currValue;
      this._changes['defaultColDef'] = new import1.SimpleChange(this._expr_6,currValue);
      this._expr_6 = currValue;
    }
  }
  check_rowStyle(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_7,currValue))) {
      this._changed = true;
      this.context.rowStyle = currValue;
      this._changes['rowStyle'] = new import1.SimpleChange(this._expr_7,currValue);
      this._expr_7 = currValue;
    }
  }
  check_context(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_8,currValue))) {
      this._changed = true;
      this.context.context = currValue;
      this._changes['context'] = new import1.SimpleChange(this._expr_8,currValue);
      this._expr_8 = currValue;
    }
  }
  check_groupColumnDef(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_9,currValue))) {
      this._changed = true;
      this.context.groupColumnDef = currValue;
      this._changes['groupColumnDef'] = new import1.SimpleChange(this._expr_9,currValue);
      this._expr_9 = currValue;
    }
  }
  check_localeText(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_10,currValue))) {
      this._changed = true;
      this.context.localeText = currValue;
      this._changes['localeText'] = new import1.SimpleChange(this._expr_10,currValue);
      this._expr_10 = currValue;
    }
  }
  check_icons(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_11,currValue))) {
      this._changed = true;
      this.context.icons = currValue;
      this._changes['icons'] = new import1.SimpleChange(this._expr_11,currValue);
      this._expr_11 = currValue;
    }
  }
  check_datasource(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_12,currValue))) {
      this._changed = true;
      this.context.datasource = currValue;
      this._changes['datasource'] = new import1.SimpleChange(this._expr_12,currValue);
      this._expr_12 = currValue;
    }
  }
  check_viewportDatasource(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_13,currValue))) {
      this._changed = true;
      this.context.viewportDatasource = currValue;
      this._changes['viewportDatasource'] = new import1.SimpleChange(this._expr_13,currValue);
      this._expr_13 = currValue;
    }
  }
  check_groupRowRendererParams(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_14,currValue))) {
      this._changed = true;
      this.context.groupRowRendererParams = currValue;
      this._changes['groupRowRendererParams'] = new import1.SimpleChange(this._expr_14,currValue);
      this._expr_14 = currValue;
    }
  }
  check_aggFuncs(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_15,currValue))) {
      this._changed = true;
      this.context.aggFuncs = currValue;
      this._changes['aggFuncs'] = new import1.SimpleChange(this._expr_15,currValue);
      this._expr_15 = currValue;
    }
  }
  check_fullWidthCellRendererParams(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_16,currValue))) {
      this._changed = true;
      this.context.fullWidthCellRendererParams = currValue;
      this._changes['fullWidthCellRendererParams'] = new import1.SimpleChange(this._expr_16,currValue);
      this._expr_16 = currValue;
    }
  }
  check_sortingOrder(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_17,currValue))) {
      this._changed = true;
      this.context.sortingOrder = currValue;
      this._changes['sortingOrder'] = new import1.SimpleChange(this._expr_17,currValue);
      this._expr_17 = currValue;
    }
  }
  check_rowClass(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_18,currValue))) {
      this._changed = true;
      this.context.rowClass = currValue;
      this._changes['rowClass'] = new import1.SimpleChange(this._expr_18,currValue);
      this._expr_18 = currValue;
    }
  }
  check_rowSelection(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_19,currValue))) {
      this._changed = true;
      this.context.rowSelection = currValue;
      this._changes['rowSelection'] = new import1.SimpleChange(this._expr_19,currValue);
      this._expr_19 = currValue;
    }
  }
  check_overlayLoadingTemplate(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_20,currValue))) {
      this._changed = true;
      this.context.overlayLoadingTemplate = currValue;
      this._changes['overlayLoadingTemplate'] = new import1.SimpleChange(this._expr_20,currValue);
      this._expr_20 = currValue;
    }
  }
  check_overlayNoRowsTemplate(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_21,currValue))) {
      this._changed = true;
      this.context.overlayNoRowsTemplate = currValue;
      this._changes['overlayNoRowsTemplate'] = new import1.SimpleChange(this._expr_21,currValue);
      this._expr_21 = currValue;
    }
  }
  check_headerCellTemplate(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_22,currValue))) {
      this._changed = true;
      this.context.headerCellTemplate = currValue;
      this._changes['headerCellTemplate'] = new import1.SimpleChange(this._expr_22,currValue);
      this._expr_22 = currValue;
    }
  }
  check_quickFilterText(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_23,currValue))) {
      this._changed = true;
      this.context.quickFilterText = currValue;
      this._changes['quickFilterText'] = new import1.SimpleChange(this._expr_23,currValue);
      this._expr_23 = currValue;
    }
  }
  check_rowModelType(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_24,currValue))) {
      this._changed = true;
      this.context.rowModelType = currValue;
      this._changes['rowModelType'] = new import1.SimpleChange(this._expr_24,currValue);
      this._expr_24 = currValue;
    }
  }
  check_rowHeight(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_25,currValue))) {
      this._changed = true;
      this.context.rowHeight = currValue;
      this._changes['rowHeight'] = new import1.SimpleChange(this._expr_25,currValue);
      this._expr_25 = currValue;
    }
  }
  check_rowBuffer(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_26,currValue))) {
      this._changed = true;
      this.context.rowBuffer = currValue;
      this._changes['rowBuffer'] = new import1.SimpleChange(this._expr_26,currValue);
      this._expr_26 = currValue;
    }
  }
  check_colWidth(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_27,currValue))) {
      this._changed = true;
      this.context.colWidth = currValue;
      this._changes['colWidth'] = new import1.SimpleChange(this._expr_27,currValue);
      this._expr_27 = currValue;
    }
  }
  check_headerHeight(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_28,currValue))) {
      this._changed = true;
      this.context.headerHeight = currValue;
      this._changes['headerHeight'] = new import1.SimpleChange(this._expr_28,currValue);
      this._expr_28 = currValue;
    }
  }
  check_groupDefaultExpanded(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_29,currValue))) {
      this._changed = true;
      this.context.groupDefaultExpanded = currValue;
      this._changes['groupDefaultExpanded'] = new import1.SimpleChange(this._expr_29,currValue);
      this._expr_29 = currValue;
    }
  }
  check_minColWidth(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_30,currValue))) {
      this._changed = true;
      this.context.minColWidth = currValue;
      this._changes['minColWidth'] = new import1.SimpleChange(this._expr_30,currValue);
      this._expr_30 = currValue;
    }
  }
  check_maxColWidth(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_31,currValue))) {
      this._changed = true;
      this.context.maxColWidth = currValue;
      this._changes['maxColWidth'] = new import1.SimpleChange(this._expr_31,currValue);
      this._expr_31 = currValue;
    }
  }
  check_viewportRowModelPageSize(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_32,currValue))) {
      this._changed = true;
      this.context.viewportRowModelPageSize = currValue;
      this._changes['viewportRowModelPageSize'] = new import1.SimpleChange(this._expr_32,currValue);
      this._expr_32 = currValue;
    }
  }
  check_viewportRowModelBufferSize(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_33,currValue))) {
      this._changed = true;
      this.context.viewportRowModelBufferSize = currValue;
      this._changes['viewportRowModelBufferSize'] = new import1.SimpleChange(this._expr_33,currValue);
      this._expr_33 = currValue;
    }
  }
  check_layoutInterval(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_34,currValue))) {
      this._changed = true;
      this.context.layoutInterval = currValue;
      this._changes['layoutInterval'] = new import1.SimpleChange(this._expr_34,currValue);
      this._expr_34 = currValue;
    }
  }
  check_autoSizePadding(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_35,currValue))) {
      this._changed = true;
      this.context.autoSizePadding = currValue;
      this._changes['autoSizePadding'] = new import1.SimpleChange(this._expr_35,currValue);
      this._expr_35 = currValue;
    }
  }
  check_maxPagesInCache(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_36,currValue))) {
      this._changed = true;
      this.context.maxPagesInCache = currValue;
      this._changes['maxPagesInCache'] = new import1.SimpleChange(this._expr_36,currValue);
      this._expr_36 = currValue;
    }
  }
  check_maxConcurrentDatasourceRequests(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_37,currValue))) {
      this._changed = true;
      this.context.maxConcurrentDatasourceRequests = currValue;
      this._changes['maxConcurrentDatasourceRequests'] = new import1.SimpleChange(this._expr_37,currValue);
      this._expr_37 = currValue;
    }
  }
  check_paginationOverflowSize(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_38,currValue))) {
      this._changed = true;
      this.context.paginationOverflowSize = currValue;
      this._changes['paginationOverflowSize'] = new import1.SimpleChange(this._expr_38,currValue);
      this._expr_38 = currValue;
    }
  }
  check_paginationPageSize(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_39,currValue))) {
      this._changed = true;
      this.context.paginationPageSize = currValue;
      this._changes['paginationPageSize'] = new import1.SimpleChange(this._expr_39,currValue);
      this._expr_39 = currValue;
    }
  }
  check_paginationInitialRowCount(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_40,currValue))) {
      this._changed = true;
      this.context.paginationInitialRowCount = currValue;
      this._changes['paginationInitialRowCount'] = new import1.SimpleChange(this._expr_40,currValue);
      this._expr_40 = currValue;
    }
  }
  check_headerCellRenderer(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_41,currValue))) {
      this._changed = true;
      this.context.headerCellRenderer = currValue;
      this._changes['headerCellRenderer'] = new import1.SimpleChange(this._expr_41,currValue);
      this._expr_41 = currValue;
    }
  }
  check_localeTextFunc(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_42,currValue))) {
      this._changed = true;
      this.context.localeTextFunc = currValue;
      this._changes['localeTextFunc'] = new import1.SimpleChange(this._expr_42,currValue);
      this._expr_42 = currValue;
    }
  }
  check_groupRowInnerRenderer(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_43,currValue))) {
      this._changed = true;
      this.context.groupRowInnerRenderer = currValue;
      this._changes['groupRowInnerRenderer'] = new import1.SimpleChange(this._expr_43,currValue);
      this._expr_43 = currValue;
    }
  }
  check_groupRowRenderer(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_44,currValue))) {
      this._changed = true;
      this.context.groupRowRenderer = currValue;
      this._changes['groupRowRenderer'] = new import1.SimpleChange(this._expr_44,currValue);
      this._expr_44 = currValue;
    }
  }
  check_isScrollLag(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_45,currValue))) {
      this._changed = true;
      this.context.isScrollLag = currValue;
      this._changes['isScrollLag'] = new import1.SimpleChange(this._expr_45,currValue);
      this._expr_45 = currValue;
    }
  }
  check_isExternalFilterPresent(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_46,currValue))) {
      this._changed = true;
      this.context.isExternalFilterPresent = currValue;
      this._changes['isExternalFilterPresent'] = new import1.SimpleChange(this._expr_46,currValue);
      this._expr_46 = currValue;
    }
  }
  check_getRowHeight(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_47,currValue))) {
      this._changed = true;
      this.context.getRowHeight = currValue;
      this._changes['getRowHeight'] = new import1.SimpleChange(this._expr_47,currValue);
      this._expr_47 = currValue;
    }
  }
  check_doesExternalFilterPass(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_48,currValue))) {
      this._changed = true;
      this.context.doesExternalFilterPass = currValue;
      this._changes['doesExternalFilterPass'] = new import1.SimpleChange(this._expr_48,currValue);
      this._expr_48 = currValue;
    }
  }
  check_getRowClass(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_49,currValue))) {
      this._changed = true;
      this.context.getRowClass = currValue;
      this._changes['getRowClass'] = new import1.SimpleChange(this._expr_49,currValue);
      this._expr_49 = currValue;
    }
  }
  check_getRowStyle(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_50,currValue))) {
      this._changed = true;
      this.context.getRowStyle = currValue;
      this._changes['getRowStyle'] = new import1.SimpleChange(this._expr_50,currValue);
      this._expr_50 = currValue;
    }
  }
  check_getHeaderCellTemplate(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_51,currValue))) {
      this._changed = true;
      this.context.getHeaderCellTemplate = currValue;
      this._changes['getHeaderCellTemplate'] = new import1.SimpleChange(this._expr_51,currValue);
      this._expr_51 = currValue;
    }
  }
  check_traverseNode(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_52,currValue))) {
      this._changed = true;
      this.context.traverseNode = currValue;
      this._changes['traverseNode'] = new import1.SimpleChange(this._expr_52,currValue);
      this._expr_52 = currValue;
    }
  }
  check_getContextMenuItems(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_53,currValue))) {
      this._changed = true;
      this.context.getContextMenuItems = currValue;
      this._changes['getContextMenuItems'] = new import1.SimpleChange(this._expr_53,currValue);
      this._expr_53 = currValue;
    }
  }
  check_getMainMenuItems(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_54,currValue))) {
      this._changed = true;
      this.context.getMainMenuItems = currValue;
      this._changes['getMainMenuItems'] = new import1.SimpleChange(this._expr_54,currValue);
      this._expr_54 = currValue;
    }
  }
  check_processRowPostCreate(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_55,currValue))) {
      this._changed = true;
      this.context.processRowPostCreate = currValue;
      this._changes['processRowPostCreate'] = new import1.SimpleChange(this._expr_55,currValue);
      this._expr_55 = currValue;
    }
  }
  check_processCellForClipboard(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_56,currValue))) {
      this._changed = true;
      this.context.processCellForClipboard = currValue;
      this._changes['processCellForClipboard'] = new import1.SimpleChange(this._expr_56,currValue);
      this._expr_56 = currValue;
    }
  }
  check_getNodeChildDetails(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_57,currValue))) {
      this._changed = true;
      this.context.getNodeChildDetails = currValue;
      this._changes['getNodeChildDetails'] = new import1.SimpleChange(this._expr_57,currValue);
      this._expr_57 = currValue;
    }
  }
  check_groupRowAggNodes(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_58,currValue))) {
      this._changed = true;
      this.context.groupRowAggNodes = currValue;
      this._changes['groupRowAggNodes'] = new import1.SimpleChange(this._expr_58,currValue);
      this._expr_58 = currValue;
    }
  }
  check_getRowNodeId(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_59,currValue))) {
      this._changed = true;
      this.context.getRowNodeId = currValue;
      this._changes['getRowNodeId'] = new import1.SimpleChange(this._expr_59,currValue);
      this._expr_59 = currValue;
    }
  }
  check_isFullWidthCell(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_60,currValue))) {
      this._changed = true;
      this.context.isFullWidthCell = currValue;
      this._changes['isFullWidthCell'] = new import1.SimpleChange(this._expr_60,currValue);
      this._expr_60 = currValue;
    }
  }
  check_fullWidthCellRenderer(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_61,currValue))) {
      this._changed = true;
      this.context.fullWidthCellRenderer = currValue;
      this._changes['fullWidthCellRenderer'] = new import1.SimpleChange(this._expr_61,currValue);
      this._expr_61 = currValue;
    }
  }
  check_doesDataFlower(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_62,currValue))) {
      this._changed = true;
      this.context.doesDataFlower = currValue;
      this._changes['doesDataFlower'] = new import1.SimpleChange(this._expr_62,currValue);
      this._expr_62 = currValue;
    }
  }
  check_toolPanelSuppressRowGroups(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_63,currValue))) {
      this._changed = true;
      this.context.toolPanelSuppressRowGroups = currValue;
      this._changes['toolPanelSuppressRowGroups'] = new import1.SimpleChange(this._expr_63,currValue);
      this._expr_63 = currValue;
    }
  }
  check_toolPanelSuppressValues(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_64,currValue))) {
      this._changed = true;
      this.context.toolPanelSuppressValues = currValue;
      this._changes['toolPanelSuppressValues'] = new import1.SimpleChange(this._expr_64,currValue);
      this._expr_64 = currValue;
    }
  }
  check_toolPanelSuppressPivots(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_65,currValue))) {
      this._changed = true;
      this.context.toolPanelSuppressPivots = currValue;
      this._changes['toolPanelSuppressPivots'] = new import1.SimpleChange(this._expr_65,currValue);
      this._expr_65 = currValue;
    }
  }
  check_toolPanelSuppressPivotMode(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_66,currValue))) {
      this._changed = true;
      this.context.toolPanelSuppressPivotMode = currValue;
      this._changes['toolPanelSuppressPivotMode'] = new import1.SimpleChange(this._expr_66,currValue);
      this._expr_66 = currValue;
    }
  }
  check_suppressRowClickSelection(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_67,currValue))) {
      this._changed = true;
      this.context.suppressRowClickSelection = currValue;
      this._changes['suppressRowClickSelection'] = new import1.SimpleChange(this._expr_67,currValue);
      this._expr_67 = currValue;
    }
  }
  check_suppressCellSelection(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_68,currValue))) {
      this._changed = true;
      this.context.suppressCellSelection = currValue;
      this._changes['suppressCellSelection'] = new import1.SimpleChange(this._expr_68,currValue);
      this._expr_68 = currValue;
    }
  }
  check_suppressHorizontalScroll(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_69,currValue))) {
      this._changed = true;
      this.context.suppressHorizontalScroll = currValue;
      this._changes['suppressHorizontalScroll'] = new import1.SimpleChange(this._expr_69,currValue);
      this._expr_69 = currValue;
    }
  }
  check_debug(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_70,currValue))) {
      this._changed = true;
      this.context.debug = currValue;
      this._changes['debug'] = new import1.SimpleChange(this._expr_70,currValue);
      this._expr_70 = currValue;
    }
  }
  check_enableColResize(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_71,currValue))) {
      this._changed = true;
      this.context.enableColResize = currValue;
      this._changes['enableColResize'] = new import1.SimpleChange(this._expr_71,currValue);
      this._expr_71 = currValue;
    }
  }
  check_enableCellExpressions(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_72,currValue))) {
      this._changed = true;
      this.context.enableCellExpressions = currValue;
      this._changes['enableCellExpressions'] = new import1.SimpleChange(this._expr_72,currValue);
      this._expr_72 = currValue;
    }
  }
  check_enableSorting(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_73,currValue))) {
      this._changed = true;
      this.context.enableSorting = currValue;
      this._changes['enableSorting'] = new import1.SimpleChange(this._expr_73,currValue);
      this._expr_73 = currValue;
    }
  }
  check_enableServerSideSorting(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_74,currValue))) {
      this._changed = true;
      this.context.enableServerSideSorting = currValue;
      this._changes['enableServerSideSorting'] = new import1.SimpleChange(this._expr_74,currValue);
      this._expr_74 = currValue;
    }
  }
  check_enableFilter(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_75,currValue))) {
      this._changed = true;
      this.context.enableFilter = currValue;
      this._changes['enableFilter'] = new import1.SimpleChange(this._expr_75,currValue);
      this._expr_75 = currValue;
    }
  }
  check_enableServerSideFilter(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_76,currValue))) {
      this._changed = true;
      this.context.enableServerSideFilter = currValue;
      this._changes['enableServerSideFilter'] = new import1.SimpleChange(this._expr_76,currValue);
      this._expr_76 = currValue;
    }
  }
  check_angularCompileRows(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_77,currValue))) {
      this._changed = true;
      this.context.angularCompileRows = currValue;
      this._changes['angularCompileRows'] = new import1.SimpleChange(this._expr_77,currValue);
      this._expr_77 = currValue;
    }
  }
  check_angularCompileFilters(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_78,currValue))) {
      this._changed = true;
      this.context.angularCompileFilters = currValue;
      this._changes['angularCompileFilters'] = new import1.SimpleChange(this._expr_78,currValue);
      this._expr_78 = currValue;
    }
  }
  check_angularCompileHeaders(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_79,currValue))) {
      this._changed = true;
      this.context.angularCompileHeaders = currValue;
      this._changes['angularCompileHeaders'] = new import1.SimpleChange(this._expr_79,currValue);
      this._expr_79 = currValue;
    }
  }
  check_groupSuppressAutoColumn(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_80,currValue))) {
      this._changed = true;
      this.context.groupSuppressAutoColumn = currValue;
      this._changes['groupSuppressAutoColumn'] = new import1.SimpleChange(this._expr_80,currValue);
      this._expr_80 = currValue;
    }
  }
  check_groupSelectsChildren(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_81,currValue))) {
      this._changed = true;
      this.context.groupSelectsChildren = currValue;
      this._changes['groupSelectsChildren'] = new import1.SimpleChange(this._expr_81,currValue);
      this._expr_81 = currValue;
    }
  }
  check_groupIncludeFooter(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_82,currValue))) {
      this._changed = true;
      this.context.groupIncludeFooter = currValue;
      this._changes['groupIncludeFooter'] = new import1.SimpleChange(this._expr_82,currValue);
      this._expr_82 = currValue;
    }
  }
  check_groupUseEntireRow(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_83,currValue))) {
      this._changed = true;
      this.context.groupUseEntireRow = currValue;
      this._changes['groupUseEntireRow'] = new import1.SimpleChange(this._expr_83,currValue);
      this._expr_83 = currValue;
    }
  }
  check_groupSuppressRow(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_84,currValue))) {
      this._changed = true;
      this.context.groupSuppressRow = currValue;
      this._changes['groupSuppressRow'] = new import1.SimpleChange(this._expr_84,currValue);
      this._expr_84 = currValue;
    }
  }
  check_groupSuppressBlankHeader(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_85,currValue))) {
      this._changed = true;
      this.context.groupSuppressBlankHeader = currValue;
      this._changes['groupSuppressBlankHeader'] = new import1.SimpleChange(this._expr_85,currValue);
      this._expr_85 = currValue;
    }
  }
  check_forPrint(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_86,currValue))) {
      this._changed = true;
      this.context.forPrint = currValue;
      this._changes['forPrint'] = new import1.SimpleChange(this._expr_86,currValue);
      this._expr_86 = currValue;
    }
  }
  check_suppressMenuHide(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_87,currValue))) {
      this._changed = true;
      this.context.suppressMenuHide = currValue;
      this._changes['suppressMenuHide'] = new import1.SimpleChange(this._expr_87,currValue);
      this._expr_87 = currValue;
    }
  }
  check_rowDeselection(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_88,currValue))) {
      this._changed = true;
      this.context.rowDeselection = currValue;
      this._changes['rowDeselection'] = new import1.SimpleChange(this._expr_88,currValue);
      this._expr_88 = currValue;
    }
  }
  check_unSortIcon(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_89,currValue))) {
      this._changed = true;
      this.context.unSortIcon = currValue;
      this._changes['unSortIcon'] = new import1.SimpleChange(this._expr_89,currValue);
      this._expr_89 = currValue;
    }
  }
  check_suppressMultiSort(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_90,currValue))) {
      this._changed = true;
      this.context.suppressMultiSort = currValue;
      this._changes['suppressMultiSort'] = new import1.SimpleChange(this._expr_90,currValue);
      this._expr_90 = currValue;
    }
  }
  check_suppressScrollLag(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_91,currValue))) {
      this._changed = true;
      this.context.suppressScrollLag = currValue;
      this._changes['suppressScrollLag'] = new import1.SimpleChange(this._expr_91,currValue);
      this._expr_91 = currValue;
    }
  }
  check_singleClickEdit(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_92,currValue))) {
      this._changed = true;
      this.context.singleClickEdit = currValue;
      this._changes['singleClickEdit'] = new import1.SimpleChange(this._expr_92,currValue);
      this._expr_92 = currValue;
    }
  }
  check_suppressLoadingOverlay(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_93,currValue))) {
      this._changed = true;
      this.context.suppressLoadingOverlay = currValue;
      this._changes['suppressLoadingOverlay'] = new import1.SimpleChange(this._expr_93,currValue);
      this._expr_93 = currValue;
    }
  }
  check_suppressNoRowsOverlay(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_94,currValue))) {
      this._changed = true;
      this.context.suppressNoRowsOverlay = currValue;
      this._changes['suppressNoRowsOverlay'] = new import1.SimpleChange(this._expr_94,currValue);
      this._expr_94 = currValue;
    }
  }
  check_suppressAutoSize(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_95,currValue))) {
      this._changed = true;
      this.context.suppressAutoSize = currValue;
      this._changes['suppressAutoSize'] = new import1.SimpleChange(this._expr_95,currValue);
      this._expr_95 = currValue;
    }
  }
  check_suppressParentsInRowNodes(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_96,currValue))) {
      this._changed = true;
      this.context.suppressParentsInRowNodes = currValue;
      this._changes['suppressParentsInRowNodes'] = new import1.SimpleChange(this._expr_96,currValue);
      this._expr_96 = currValue;
    }
  }
  check_showToolPanel(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_97,currValue))) {
      this._changed = true;
      this.context.showToolPanel = currValue;
      this._changes['showToolPanel'] = new import1.SimpleChange(this._expr_97,currValue);
      this._expr_97 = currValue;
    }
  }
  check_suppressColumnMoveAnimation(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_98,currValue))) {
      this._changed = true;
      this.context.suppressColumnMoveAnimation = currValue;
      this._changes['suppressColumnMoveAnimation'] = new import1.SimpleChange(this._expr_98,currValue);
      this._expr_98 = currValue;
    }
  }
  check_suppressMovableColumns(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_99,currValue))) {
      this._changed = true;
      this.context.suppressMovableColumns = currValue;
      this._changes['suppressMovableColumns'] = new import1.SimpleChange(this._expr_99,currValue);
      this._expr_99 = currValue;
    }
  }
  check_suppressFieldDotNotation(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_100,currValue))) {
      this._changed = true;
      this.context.suppressFieldDotNotation = currValue;
      this._changes['suppressFieldDotNotation'] = new import1.SimpleChange(this._expr_100,currValue);
      this._expr_100 = currValue;
    }
  }
  check_enableRangeSelection(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_101,currValue))) {
      this._changed = true;
      this.context.enableRangeSelection = currValue;
      this._changes['enableRangeSelection'] = new import1.SimpleChange(this._expr_101,currValue);
      this._expr_101 = currValue;
    }
  }
  check_suppressEnterprise(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_102,currValue))) {
      this._changed = true;
      this.context.suppressEnterprise = currValue;
      this._changes['suppressEnterprise'] = new import1.SimpleChange(this._expr_102,currValue);
      this._expr_102 = currValue;
    }
  }
  check_rowGroupPanelShow(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_103,currValue))) {
      this._changed = true;
      this.context.rowGroupPanelShow = currValue;
      this._changes['rowGroupPanelShow'] = new import1.SimpleChange(this._expr_103,currValue);
      this._expr_103 = currValue;
    }
  }
  check_pivotPanelShow(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_104,currValue))) {
      this._changed = true;
      this.context.pivotPanelShow = currValue;
      this._changes['pivotPanelShow'] = new import1.SimpleChange(this._expr_104,currValue);
      this._expr_104 = currValue;
    }
  }
  check_suppressContextMenu(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_105,currValue))) {
      this._changed = true;
      this.context.suppressContextMenu = currValue;
      this._changes['suppressContextMenu'] = new import1.SimpleChange(this._expr_105,currValue);
      this._expr_105 = currValue;
    }
  }
  check_suppressMenuFilterPanel(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_106,currValue))) {
      this._changed = true;
      this.context.suppressMenuFilterPanel = currValue;
      this._changes['suppressMenuFilterPanel'] = new import1.SimpleChange(this._expr_106,currValue);
      this._expr_106 = currValue;
    }
  }
  check_suppressMenuMainPanel(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_107,currValue))) {
      this._changed = true;
      this.context.suppressMenuMainPanel = currValue;
      this._changes['suppressMenuMainPanel'] = new import1.SimpleChange(this._expr_107,currValue);
      this._expr_107 = currValue;
    }
  }
  check_suppressMenuColumnPanel(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_108,currValue))) {
      this._changed = true;
      this.context.suppressMenuColumnPanel = currValue;
      this._changes['suppressMenuColumnPanel'] = new import1.SimpleChange(this._expr_108,currValue);
      this._expr_108 = currValue;
    }
  }
  check_enableStatusBar(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_109,currValue))) {
      this._changed = true;
      this.context.enableStatusBar = currValue;
      this._changes['enableStatusBar'] = new import1.SimpleChange(this._expr_109,currValue);
      this._expr_109 = currValue;
    }
  }
  check_rememberGroupStateWhenNewData(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_110,currValue))) {
      this._changed = true;
      this.context.rememberGroupStateWhenNewData = currValue;
      this._changes['rememberGroupStateWhenNewData'] = new import1.SimpleChange(this._expr_110,currValue);
      this._expr_110 = currValue;
    }
  }
  check_enableCellChangeFlash(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_111,currValue))) {
      this._changed = true;
      this.context.enableCellChangeFlash = currValue;
      this._changes['enableCellChangeFlash'] = new import1.SimpleChange(this._expr_111,currValue);
      this._expr_111 = currValue;
    }
  }
  check_suppressDragLeaveHidesColumns(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_112,currValue))) {
      this._changed = true;
      this.context.suppressDragLeaveHidesColumns = currValue;
      this._changes['suppressDragLeaveHidesColumns'] = new import1.SimpleChange(this._expr_112,currValue);
      this._expr_112 = currValue;
    }
  }
  check_suppressMiddleClickScrolls(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_113,currValue))) {
      this._changed = true;
      this.context.suppressMiddleClickScrolls = currValue;
      this._changes['suppressMiddleClickScrolls'] = new import1.SimpleChange(this._expr_113,currValue);
      this._expr_113 = currValue;
    }
  }
  check_suppressPreventDefaultOnMouseWheel(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_114,currValue))) {
      this._changed = true;
      this.context.suppressPreventDefaultOnMouseWheel = currValue;
      this._changes['suppressPreventDefaultOnMouseWheel'] = new import1.SimpleChange(this._expr_114,currValue);
      this._expr_114 = currValue;
    }
  }
  check_suppressUseColIdForGroups(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_115,currValue))) {
      this._changed = true;
      this.context.suppressUseColIdForGroups = currValue;
      this._changes['suppressUseColIdForGroups'] = new import1.SimpleChange(this._expr_115,currValue);
      this._expr_115 = currValue;
    }
  }
  check_suppressCopyRowsToClipboard(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_116,currValue))) {
      this._changed = true;
      this.context.suppressCopyRowsToClipboard = currValue;
      this._changes['suppressCopyRowsToClipboard'] = new import1.SimpleChange(this._expr_116,currValue);
      this._expr_116 = currValue;
    }
  }
  check_pivotMode(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_117,currValue))) {
      this._changed = true;
      this.context.pivotMode = currValue;
      this._changes['pivotMode'] = new import1.SimpleChange(this._expr_117,currValue);
      this._expr_117 = currValue;
    }
  }
  check_suppressAggFuncInHeader(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_118,currValue))) {
      this._changed = true;
      this.context.suppressAggFuncInHeader = currValue;
      this._changes['suppressAggFuncInHeader'] = new import1.SimpleChange(this._expr_118,currValue);
      this._expr_118 = currValue;
    }
  }
  check_suppressColumnVirtualisation(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_119,currValue))) {
      this._changed = true;
      this.context.suppressColumnVirtualisation = currValue;
      this._changes['suppressColumnVirtualisation'] = new import1.SimpleChange(this._expr_119,currValue);
      this._expr_119 = currValue;
    }
  }
  check_suppressFocusAfterRefresh(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_120,currValue))) {
      this._changed = true;
      this.context.suppressFocusAfterRefresh = currValue;
      this._changes['suppressFocusAfterRefresh'] = new import1.SimpleChange(this._expr_120,currValue);
      this._expr_120 = currValue;
    }
  }
  check_functionsPassive(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_121,currValue))) {
      this._changed = true;
      this.context.functionsPassive = currValue;
      this._changes['functionsPassive'] = new import1.SimpleChange(this._expr_121,currValue);
      this._expr_121 = currValue;
    }
  }
  check_functionsReadOnly(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_122,currValue))) {
      this._changed = true;
      this.context.functionsReadOnly = currValue;
      this._changes['functionsReadOnly'] = new import1.SimpleChange(this._expr_122,currValue);
      this._expr_122 = currValue;
    }
  }
  check_defaultColGroupDef(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_123,currValue))) {
      this._changed = true;
      this.context.defaultColGroupDef = currValue;
      this._changes['defaultColGroupDef'] = new import1.SimpleChange(this._expr_123,currValue);
      this._expr_123 = currValue;
    }
  }
  check_editType(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_124,currValue))) {
      this._changed = true;
      this.context.editType = currValue;
      this._changes['editType'] = new import1.SimpleChange(this._expr_124,currValue);
      this._expr_124 = currValue;
    }
  }
  check_scrollbarWidth(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_125,currValue))) {
      this._changed = true;
      this.context.scrollbarWidth = currValue;
      this._changes['scrollbarWidth'] = new import1.SimpleChange(this._expr_125,currValue);
      this._expr_125 = currValue;
    }
  }
  check_groupRowInnerRendererFramework(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_126,currValue))) {
      this._changed = true;
      this.context.groupRowInnerRendererFramework = currValue;
      this._changes['groupRowInnerRendererFramework'] = new import1.SimpleChange(this._expr_126,currValue);
      this._expr_126 = currValue;
    }
  }
  check_groupRowRendererFramework(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_127,currValue))) {
      this._changed = true;
      this.context.groupRowRendererFramework = currValue;
      this._changes['groupRowRendererFramework'] = new import1.SimpleChange(this._expr_127,currValue);
      this._expr_127 = currValue;
    }
  }
  check_fullWidthCellRendererFramework(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_128,currValue))) {
      this._changed = true;
      this.context.fullWidthCellRendererFramework = currValue;
      this._changes['fullWidthCellRendererFramework'] = new import1.SimpleChange(this._expr_128,currValue);
      this._expr_128 = currValue;
    }
  }
  check_processSecondaryColDef(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_129,currValue))) {
      this._changed = true;
      this.context.processSecondaryColDef = currValue;
      this._changes['processSecondaryColDef'] = new import1.SimpleChange(this._expr_129,currValue);
      this._expr_129 = currValue;
    }
  }
  check_processSecondaryColGroupDef(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_130,currValue))) {
      this._changed = true;
      this.context.processSecondaryColGroupDef = currValue;
      this._changes['processSecondaryColGroupDef'] = new import1.SimpleChange(this._expr_130,currValue);
      this._expr_130 = currValue;
    }
  }
  check_suppressRowHoverClass(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_131,currValue))) {
      this._changed = true;
      this.context.suppressRowHoverClass = currValue;
      this._changes['suppressRowHoverClass'] = new import1.SimpleChange(this._expr_131,currValue);
      this._expr_131 = currValue;
    }
  }
  check_suppressTouch(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_132,currValue))) {
      this._changed = true;
      this.context.suppressTouch = currValue;
      this._changes['suppressTouch'] = new import1.SimpleChange(this._expr_132,currValue);
      this._expr_132 = currValue;
    }
  }
  check_animateRows(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_133,currValue))) {
      this._changed = true;
      this.context.animateRows = currValue;
      this._changes['animateRows'] = new import1.SimpleChange(this._expr_133,currValue);
      this._expr_133 = currValue;
    }
  }
  check_groupSelectsFiltered(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_134,currValue))) {
      this._changed = true;
      this.context.groupSelectsFiltered = currValue;
      this._changes['groupSelectsFiltered'] = new import1.SimpleChange(this._expr_134,currValue);
      this._expr_134 = currValue;
    }
  }
  check_groupRemoveSingleChildren(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_135,currValue))) {
      this._changed = true;
      this.context.groupRemoveSingleChildren = currValue;
      this._changes['groupRemoveSingleChildren'] = new import1.SimpleChange(this._expr_135,currValue);
      this._expr_135 = currValue;
    }
  }
  check_getBusinessKeyForNode(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_136,currValue))) {
      this._changed = true;
      this.context.getBusinessKeyForNode = currValue;
      this._changes['getBusinessKeyForNode'] = new import1.SimpleChange(this._expr_136,currValue);
      this._expr_136 = currValue;
    }
  }
  check_checkboxSelection(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_137,currValue))) {
      this._changed = true;
      this.context.checkboxSelection = currValue;
      this._changes['checkboxSelection'] = new import1.SimpleChange(this._expr_137,currValue);
      this._expr_137 = currValue;
    }
  }
  check_enableRtl(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_138,currValue))) {
      this._changed = true;
      this.context.enableRtl = currValue;
      this._changes['enableRtl'] = new import1.SimpleChange(this._expr_138,currValue);
      this._expr_138 = currValue;
    }
  }
  check_suppressClickEdit(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_139,currValue))) {
      this._changed = true;
      this.context.suppressClickEdit = currValue;
      this._changes['suppressClickEdit'] = new import1.SimpleChange(this._expr_139,currValue);
      this._expr_139 = currValue;
    }
  }
  check_enableRtlSupport(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_140,currValue))) {
      this._changed = true;
      this.context.enableRtlSupport = currValue;
      this._changes['enableRtlSupport'] = new import1.SimpleChange(this._expr_140,currValue);
      this._expr_140 = currValue;
    }
  }
  check_excelStyles(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_141,currValue))) {
      this._changed = true;
      this.context.excelStyles = currValue;
      this._changes['excelStyles'] = new import1.SimpleChange(this._expr_141,currValue);
      this._expr_141 = currValue;
    }
  }
  check_dateComponent(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_142,currValue))) {
      this._changed = true;
      this.context.dateComponent = currValue;
      this._changes['dateComponent'] = new import1.SimpleChange(this._expr_142,currValue);
      this._expr_142 = currValue;
    }
  }
  check_dateComponentFramework(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_143,currValue))) {
      this._changed = true;
      this.context.dateComponentFramework = currValue;
      this._changes['dateComponentFramework'] = new import1.SimpleChange(this._expr_143,currValue);
      this._expr_143 = currValue;
    }
  }
  check_dateComponentParams(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_144,currValue))) {
      this._changed = true;
      this.context.dateComponentParams = currValue;
      this._changes['dateComponentParams'] = new import1.SimpleChange(this._expr_144,currValue);
      this._expr_144 = currValue;
    }
  }
  check_sendToClipboard(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_145,currValue))) {
      this._changed = true;
      this.context.sendToClipboard = currValue;
      this._changes['sendToClipboard'] = new import1.SimpleChange(this._expr_145,currValue);
      this._expr_145 = currValue;
    }
  }
  check_navigateToNextCell(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_146,currValue))) {
      this._changed = true;
      this.context.navigateToNextCell = currValue;
      this._changes['navigateToNextCell'] = new import1.SimpleChange(this._expr_146,currValue);
      this._expr_146 = currValue;
    }
  }
  check_tabToNextCell(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_147,currValue))) {
      this._changed = true;
      this.context.tabToNextCell = currValue;
      this._changes['tabToNextCell'] = new import1.SimpleChange(this._expr_147,currValue);
      this._expr_147 = currValue;
    }
  }
  check_processCellFromClipboard(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_148,currValue))) {
      this._changed = true;
      this.context.processCellFromClipboard = currValue;
      this._changes['processCellFromClipboard'] = new import1.SimpleChange(this._expr_148,currValue);
      this._expr_148 = currValue;
    }
  }
  check_getDocument(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_149,currValue))) {
      this._changed = true;
      this.context.getDocument = currValue;
      this._changes['getDocument'] = new import1.SimpleChange(this._expr_149,currValue);
      this._expr_149 = currValue;
    }
  }
  check_enableGroupEdit(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_150,currValue))) {
      this._changed = true;
      this.context.enableGroupEdit = currValue;
      this._changes['enableGroupEdit'] = new import1.SimpleChange(this._expr_150,currValue);
      this._expr_150 = currValue;
    }
  }
  check_embedFullWidthRows(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_151,currValue))) {
      this._changed = true;
      this.context.embedFullWidthRows = currValue;
      this._changes['embedFullWidthRows'] = new import1.SimpleChange(this._expr_151,currValue);
      this._expr_151 = currValue;
    }
  }
  check_suppressTabbing(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_152,currValue))) {
      this._changed = true;
      this.context.suppressTabbing = currValue;
      this._changes['suppressTabbing'] = new import1.SimpleChange(this._expr_152,currValue);
      this._expr_152 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if (changed) {
      this.context.ngOnChanges(this._changes);
      this._changes = {};
    } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean,emit1:boolean,emit2:boolean,emit3:boolean,emit4:boolean,emit5:boolean,emit6:boolean,emit7:boolean,emit8:boolean,emit9:boolean,emit10:boolean,emit11:boolean,emit12:boolean,emit13:boolean,emit14:boolean,emit15:boolean,emit16:boolean,emit17:boolean,emit18:boolean,emit19:boolean,emit20:boolean,emit21:boolean,emit22:boolean,emit23:boolean,emit24:boolean,emit25:boolean,emit26:boolean,emit27:boolean,emit28:boolean,emit29:boolean,emit30:boolean,emit31:boolean,emit32:boolean,emit33:boolean,emit34:boolean,emit35:boolean,emit36:boolean,emit37:boolean,emit38:boolean,emit39:boolean,emit40:boolean,emit41:boolean,emit42:boolean,emit43:boolean,emit44:boolean,emit45:boolean,emit46:boolean,emit47:boolean,emit48:boolean,emit49:boolean,emit50:boolean,emit51:boolean,emit52:boolean,emit53:boolean,emit54:boolean,emit55:boolean,emit56:boolean,emit57:boolean,emit58:boolean,emit59:boolean,emit60:boolean,emit61:boolean,emit62:boolean,emit63:boolean,emit64:boolean,emit65:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.gridReady.subscribe(_eventHandler.bind(view,'gridReady'))); }
    if (emit1) { (this.subscription1 = this.context.columnEverythingChanged.subscribe(_eventHandler.bind(view,'columnEverythingChanged'))); }
    if (emit2) { (this.subscription2 = this.context.newColumnsLoaded.subscribe(_eventHandler.bind(view,'newColumnsLoaded'))); }
    if (emit3) { (this.subscription3 = this.context.columnPivotModeChanged.subscribe(_eventHandler.bind(view,'columnPivotModeChanged'))); }
    if (emit4) { (this.subscription4 = this.context.columnRowGroupChanged.subscribe(_eventHandler.bind(view,'columnRowGroupChanged'))); }
    if (emit5) { (this.subscription5 = this.context.columnPivotChanged.subscribe(_eventHandler.bind(view,'columnPivotChanged'))); }
    if (emit6) { (this.subscription6 = this.context.gridColumnsChanged.subscribe(_eventHandler.bind(view,'gridColumnsChanged'))); }
    if (emit7) { (this.subscription7 = this.context.columnValueChanged.subscribe(_eventHandler.bind(view,'columnValueChanged'))); }
    if (emit8) { (this.subscription8 = this.context.columnMoved.subscribe(_eventHandler.bind(view,'columnMoved'))); }
    if (emit9) { (this.subscription9 = this.context.columnVisible.subscribe(_eventHandler.bind(view,'columnVisible'))); }
    if (emit10) { (this.subscription10 = this.context.columnPinned.subscribe(_eventHandler.bind(view,'columnPinned'))); }
    if (emit11) { (this.subscription11 = this.context.columnGroupOpened.subscribe(_eventHandler.bind(view,'columnGroupOpened'))); }
    if (emit12) { (this.subscription12 = this.context.columnResized.subscribe(_eventHandler.bind(view,'columnResized'))); }
    if (emit13) { (this.subscription13 = this.context.displayedColumnsChanged.subscribe(_eventHandler.bind(view,'displayedColumnsChanged'))); }
    if (emit14) { (this.subscription14 = this.context.virtualColumnsChanged.subscribe(_eventHandler.bind(view,'virtualColumnsChanged'))); }
    if (emit15) { (this.subscription15 = this.context.rowGroupOpened.subscribe(_eventHandler.bind(view,'rowGroupOpened'))); }
    if (emit16) { (this.subscription16 = this.context.rowDataChanged.subscribe(_eventHandler.bind(view,'rowDataChanged'))); }
    if (emit17) { (this.subscription17 = this.context.floatingRowDataChanged.subscribe(_eventHandler.bind(view,'floatingRowDataChanged'))); }
    if (emit18) { (this.subscription18 = this.context.rangeSelectionChanged.subscribe(_eventHandler.bind(view,'rangeSelectionChanged'))); }
    if (emit19) { (this.subscription19 = this.context.columnRowGroupAddRequest.subscribe(_eventHandler.bind(view,'columnRowGroupAddRequest'))); }
    if (emit20) { (this.subscription20 = this.context.columnRowGroupRemoveRequest.subscribe(_eventHandler.bind(view,'columnRowGroupRemoveRequest'))); }
    if (emit21) { (this.subscription21 = this.context.columnPivotAddRequest.subscribe(_eventHandler.bind(view,'columnPivotAddRequest'))); }
    if (emit22) { (this.subscription22 = this.context.columnPivotRemoveRequest.subscribe(_eventHandler.bind(view,'columnPivotRemoveRequest'))); }
    if (emit23) { (this.subscription23 = this.context.columnValueAddRequest.subscribe(_eventHandler.bind(view,'columnValueAddRequest'))); }
    if (emit24) { (this.subscription24 = this.context.columnValueRemoveRequest.subscribe(_eventHandler.bind(view,'columnValueRemoveRequest'))); }
    if (emit25) { (this.subscription25 = this.context.columnAggFuncChangeRequest.subscribe(_eventHandler.bind(view,'columnAggFuncChangeRequest'))); }
    if (emit26) { (this.subscription26 = this.context.clipboardPaste.subscribe(_eventHandler.bind(view,'clipboardPaste'))); }
    if (emit27) { (this.subscription27 = this.context.modelUpdated.subscribe(_eventHandler.bind(view,'modelUpdated'))); }
    if (emit28) { (this.subscription28 = this.context.cellClicked.subscribe(_eventHandler.bind(view,'cellClicked'))); }
    if (emit29) { (this.subscription29 = this.context.cellDoubleClicked.subscribe(_eventHandler.bind(view,'cellDoubleClicked'))); }
    if (emit30) { (this.subscription30 = this.context.cellContextMenu.subscribe(_eventHandler.bind(view,'cellContextMenu'))); }
    if (emit31) { (this.subscription31 = this.context.cellValueChanged.subscribe(_eventHandler.bind(view,'cellValueChanged'))); }
    if (emit32) { (this.subscription32 = this.context.cellFocused.subscribe(_eventHandler.bind(view,'cellFocused'))); }
    if (emit33) { (this.subscription33 = this.context.rowSelected.subscribe(_eventHandler.bind(view,'rowSelected'))); }
    if (emit34) { (this.subscription34 = this.context.selectionChanged.subscribe(_eventHandler.bind(view,'selectionChanged'))); }
    if (emit35) { (this.subscription35 = this.context.beforeFilterChanged.subscribe(_eventHandler.bind(view,'beforeFilterChanged'))); }
    if (emit36) { (this.subscription36 = this.context.filterChanged.subscribe(_eventHandler.bind(view,'filterChanged'))); }
    if (emit37) { (this.subscription37 = this.context.afterFilterChanged.subscribe(_eventHandler.bind(view,'afterFilterChanged'))); }
    if (emit38) { (this.subscription38 = this.context.filterModified.subscribe(_eventHandler.bind(view,'filterModified'))); }
    if (emit39) { (this.subscription39 = this.context.beforeSortChanged.subscribe(_eventHandler.bind(view,'beforeSortChanged'))); }
    if (emit40) { (this.subscription40 = this.context.sortChanged.subscribe(_eventHandler.bind(view,'sortChanged'))); }
    if (emit41) { (this.subscription41 = this.context.afterSortChanged.subscribe(_eventHandler.bind(view,'afterSortChanged'))); }
    if (emit42) { (this.subscription42 = this.context.virtualRowRemoved.subscribe(_eventHandler.bind(view,'virtualRowRemoved'))); }
    if (emit43) { (this.subscription43 = this.context.rowClicked.subscribe(_eventHandler.bind(view,'rowClicked'))); }
    if (emit44) { (this.subscription44 = this.context.rowDoubleClicked.subscribe(_eventHandler.bind(view,'rowDoubleClicked'))); }
    if (emit45) { (this.subscription45 = this.context.gridSizeChanged.subscribe(_eventHandler.bind(view,'gridSizeChanged'))); }
    if (emit46) { (this.subscription46 = this.context.viewportChanged.subscribe(_eventHandler.bind(view,'viewportChanged'))); }
    if (emit47) { (this.subscription47 = this.context.dragStarted.subscribe(_eventHandler.bind(view,'dragStarted'))); }
    if (emit48) { (this.subscription48 = this.context.dragStopped.subscribe(_eventHandler.bind(view,'dragStopped'))); }
    if (emit49) { (this.subscription49 = this.context.itemsAdded.subscribe(_eventHandler.bind(view,'itemsAdded'))); }
    if (emit50) { (this.subscription50 = this.context.itemsRemoved.subscribe(_eventHandler.bind(view,'itemsRemoved'))); }
    if (emit51) { (this.subscription51 = this.context.columnRowGroupChangeRequest.subscribe(_eventHandler.bind(view,'columnRowGroupChangeRequest'))); }
    if (emit52) { (this.subscription52 = this.context.columnPivotChangeRequest.subscribe(_eventHandler.bind(view,'columnPivotChangeRequest'))); }
    if (emit53) { (this.subscription53 = this.context.columnValueChangeRequest.subscribe(_eventHandler.bind(view,'columnValueChangeRequest'))); }
    if (emit54) { (this.subscription54 = this.context.rowValueChanged.subscribe(_eventHandler.bind(view,'rowValueChanged'))); }
    if (emit55) { (this.subscription55 = this.context.bodyScroll.subscribe(_eventHandler.bind(view,'bodyScroll'))); }
    if (emit56) { (this.subscription56 = this.context.rowEditingStarted.subscribe(_eventHandler.bind(view,'rowEditingStarted'))); }
    if (emit57) { (this.subscription57 = this.context.rowEditingStopped.subscribe(_eventHandler.bind(view,'rowEditingStopped'))); }
    if (emit58) { (this.subscription58 = this.context.cellEditingStarted.subscribe(_eventHandler.bind(view,'cellEditingStarted'))); }
    if (emit59) { (this.subscription59 = this.context.cellEditingStopped.subscribe(_eventHandler.bind(view,'cellEditingStopped'))); }
    if (emit60) { (this.subscription60 = this.context.displayedColumnsWidthChanged.subscribe(_eventHandler.bind(view,'displayedColumnsWidthChanged'))); }
    if (emit61) { (this.subscription61 = this.context.scrollVisibilityChanged.subscribe(_eventHandler.bind(view,'scrollVisibilityChanged'))); }
    if (emit62) { (this.subscription62 = this.context.flashCells.subscribe(_eventHandler.bind(view,'flashCells'))); }
    if (emit63) { (this.subscription63 = this.context.cellMouseOver.subscribe(_eventHandler.bind(view,'cellMouseOver'))); }
    if (emit64) { (this.subscription64 = this.context.cellMouseOut.subscribe(_eventHandler.bind(view,'cellMouseOut'))); }
    if (emit65) { (this.subscription65 = this.context.columnHoverChanged.subscribe(_eventHandler.bind(view,'columnHoverChanged'))); }
  }
}
var renderType_AgGridNg2_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_AgGridNg2_Host0 extends import2.AppView<any> {
  _el_0:any;
  /*private*/ _vc_0:import6.ViewContainer;
  compView_0:import2.AppView<import0.AgGridNg2>;
  _Ng2FrameworkFactory_0_5:import7.Ng2FrameworkFactory;
  _Ng2FrameworkComponentWrapper_0_6:import8.Ng2FrameworkComponentWrapper;
  _AgGridNg2_0_7:Wrapper_AgGridNg2;
  _query_AgGridColumn_0_0:import9.QueryList<any>;
  _el_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AgGridNg2_Host0,renderType_AgGridNg2_Host,import10.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import11.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import12.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ag-grid-ng2',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._vc_0 = new import6.ViewContainer(0,(null as any),this,this._el_0);
    this.compView_0 = new View_AgGridNg20(this.viewUtils,this,0,this._el_0);
    this._Ng2FrameworkFactory_0_5 = new import7.Ng2FrameworkFactory(this.injectorGet(import13.BaseComponentFactory,this.parentIndex),this.injectorGet(import14.NgZone,this.parentIndex));
    this._Ng2FrameworkComponentWrapper_0_6 = new import8.Ng2FrameworkComponentWrapper();
    this._AgGridNg2_0_7 = new Wrapper_AgGridNg2(new import15.ElementRef(this._el_0),this._vc_0.vcRef,this._Ng2FrameworkFactory_0_5,this._Ng2FrameworkComponentWrapper_0_6,this.injectorGet(import16.ComponentFactoryResolver,this.parentIndex));
    this._query_AgGridColumn_0_0 = new import9.QueryList<any>();
    this.compView_0.create(this._AgGridNg2_0_7.context);
    this._el_1 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this.init(this._el_1,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import12.ComponentRef_<any>(0,this,this._el_0,this._AgGridNg2_0_7.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import7.Ng2FrameworkFactory) && (0 === requestNodeIndex))) { return this._Ng2FrameworkFactory_0_5; }
    if (((token === import8.Ng2FrameworkComponentWrapper) && (0 === requestNodeIndex))) { return this._Ng2FrameworkComponentWrapper_0_6; }
    if (((token === import0.AgGridNg2) && (0 === requestNodeIndex))) { return this._AgGridNg2_0_7.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AgGridNg2_0_7.ngDoCheck(this,this._el_0,throwOnChange);
    this._vc_0.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) { if (this._query_AgGridColumn_0_0.dirty) {
      this._query_AgGridColumn_0_0.reset(([] as any[]));
      this._AgGridNg2_0_7.context.columns = this._query_AgGridColumn_0_0;
      this._query_AgGridColumn_0_0.notifyOnChanges();
    } }
    this.compView_0.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._AgGridNg2_0_7.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
    this.compView_0.destroy();
    this._AgGridNg2_0_7.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._vc_0.nativeElement,ctx);
    this._vc_0.visitNestedViewRootNodes(cb,ctx);
    cb(this._el_1,ctx);
  }
}
export const AgGridNg2NgFactory:import12.ComponentFactory<import0.AgGridNg2> = new import12.ComponentFactory<import0.AgGridNg2>('ag-grid-ng2',View_AgGridNg2_Host0,import0.AgGridNg2);
const styles_AgGridNg2:any[] = ([] as any[]);
var renderType_AgGridNg2:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_AgGridNg2,{});
export class View_AgGridNg20 extends import2.AppView<import0.AgGridNg2> {
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AgGridNg20,renderType_AgGridNg2,import10.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import11.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import12.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): ([] as any[])),(null as any));
    return (null as any);
  }
}