/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../src/agGridColumn';
const styles_AgGridColumn:any[] = ([] as any[]);
export const RenderType_AgGridColumn:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AgGridColumn,
    data:{}});
export function View_AgGridColumn_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,([] as any[]),(null as any),(null as any));
}
export function View_AgGridColumn_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),2,'ag-grid-column',
      ([] as any[]),(null as any),(null as any),(null as any),View_AgGridColumn_0,
      RenderType_AgGridColumn)),i0.ɵdid(1,49152,[[1,4]],1,i1.AgGridColumn,([] as any[]),
      (null as any),(null as any)),i0.ɵqud(603979776,1,{childColumns:1})],(null as any),
      (null as any));
}
export const AgGridColumnNgFactory:i0.ComponentFactory<i1.AgGridColumn> = i0.ɵccf('ag-grid-column',
    i1.AgGridColumn,View_AgGridColumn_Host_0,{headerName:'headerName',columnGroupShow:'columnGroupShow',
        headerClass:'headerClass',toolPanelClass:'toolPanelClass',headerValueGetter:'headerValueGetter',
        suppressToolPanel:'suppressToolPanel',children:'children',groupId:'groupId',
        openByDefault:'openByDefault',marryChildren:'marryChildren',headerGroupComponent:'headerGroupComponent',
        headerGroupComponentFramework:'headerGroupComponentFramework',headerGroupComponentParams:'headerGroupComponentParams',
        colId:'colId',sort:'sort',sortedAt:'sortedAt',sortingOrder:'sortingOrder',
        field:'field',type:'type',hide:'hide',pinned:'pinned',tooltipField:'tooltipField',
        headerTooltip:'headerTooltip',valueGetter:'valueGetter',valueSetter:'valueSetter',
        keyCreator:'keyCreator',headerCellRenderer:'headerCellRenderer',headerCellTemplate:'headerCellTemplate',
        width:'width',minWidth:'minWidth',maxWidth:'maxWidth',cellClass:'cellClass',
        cellStyle:'cellStyle',cellRenderer:'cellRenderer',cellRendererFramework:'cellRendererFramework',
        cellRendererParams:'cellRendererParams',cellEditor:'cellEditor',cellEditorFramework:'cellEditorFramework',
        cellEditorParams:'cellEditorParams',pinnedRowCellRenderer:'pinnedRowCellRenderer',
        pinnedRowCellRendererFramework:'pinnedRowCellRendererFramework',pinnedRowCellRendererParams:'pinnedRowCellRendererParams',
        valueFormatter:'valueFormatter',pinnedRowValueFormatter:'pinnedRowValueFormatter',
        valueParser:'valueParser',aggFunc:'aggFunc',allowedAggFuncs:'allowedAggFuncs',
        rowGroupIndex:'rowGroupIndex',rowGroup:'rowGroup',showRowGroup:'showRowGroup',
        pivotIndex:'pivotIndex',pivot:'pivot',comparator:'comparator',equals:'equals',
        pivotComparator:'pivotComparator',checkboxSelection:'checkboxSelection',headerCheckboxSelection:'headerCheckboxSelection',
        headerCheckboxSelectionFilteredOnly:'headerCheckboxSelectionFilteredOnly',
        suppressMenu:'suppressMenu',menuTabs:'menuTabs',suppressSorting:'suppressSorting',
        suppressMovable:'suppressMovable',suppressFilter:'suppressFilter',unSortIcon:'unSortIcon',
        suppressSizeToFit:'suppressSizeToFit',suppressResize:'suppressResize',suppressAutoSize:'suppressAutoSize',
        suppressKeyboardEvent:'suppressKeyboardEvent',enableRowGroup:'enableRowGroup',
        enablePivot:'enablePivot',enableValue:'enableValue',editable:'editable',colSpan:'colSpan',
        suppressPaste:'suppressPaste',suppressNavigable:'suppressNavigable',getQuickFilterText:'getQuickFilterText',
        newValueHandler:'newValueHandler',volatile:'volatile',template:'template',
        filter:'filter',filterFramework:'filterFramework',filterParams:'filterParams',
        cellClassRules:'cellClassRules',onCellValueChanged:'onCellValueChanged',onCellClicked:'onCellClicked',
        onCellDoubleClicked:'onCellDoubleClicked',onCellContextMenu:'onCellContextMenu',
        icons:'icons',enableCellChangeFlash:'enableCellChangeFlash',headerComponent:'headerComponent',
        headerComponentFramework:'headerComponentFramework',headerComponentParams:'headerComponentParams',
        floatingFilterComponent:'floatingFilterComponent',floatingFilterComponentParams:'floatingFilterComponentParams',
        floatingFilterComponentFramework:'floatingFilterComponentFramework',refData:'refData'},
    {},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FsYmVydG8vdm9sYXRpbGUvcmVsZWFzZXMvMTQuMC4wL2FnLWdyaWQtYW5ndWxhci9zcmMvYWdHcmlkQ29sdW1uLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2FsYmVydG8vdm9sYXRpbGUvcmVsZWFzZXMvMTQuMC4wL2FnLWdyaWQtYW5ndWxhci9zcmMvYWdHcmlkQ29sdW1uLnRzIiwibmc6Ly8vVXNlcnMvYWxiZXJ0by92b2xhdGlsZS9yZWxlYXNlcy8xNC4wLjAvYWctZ3JpZC1hbmd1bGFyL3NyYy9hZ0dyaWRDb2x1bW4udHMuQWdHcmlkQ29sdW1uX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGFnLWdyaWQtY29sdW1uPjwvYWctZ3JpZC1jb2x1bW4+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTs2QkFBQSxVQUFBO01BQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
