export function getData(): any[] {
    return [
        {
            athlete: 'Michael Phelps',
            age: 27,
            country: 'United States',
            year: 2012,
            date: '12/08/2012',
            sport: 'Swimming',
            gold: 4,
            silver: 2,
            bronze: 0,
            total: 6,
        },
        {
            athlete: 'Natalie Coughlin',
            age: 25,
            country: 'United States',
            year: 2008,
            date: '24/08/2008',
            sport: 'Swimming',
            gold: 1,
            silver: 2,
            bronze: 3,
            total: 6,
        },
        {
            athlete: 'Aleksey Nemov',
            age: 24,
            country: 'Russia',
            year: 2000,
            date: '01/10/2000',
            sport: 'Gymnastics',
            gold: 2,
            silver: 1,
            bronze: 3,
            total: 6,
        },
        {
            athlete: 'Alicia Coutts',
            age: 24,
            country: 'Australia',
            year: 2012,
            date: '12/08/2012',
            sport: 'Swimming',
            gold: 1,
            silver: 3,
            bronze: 1,
            total: 5,
        },
        {
            athlete: 'Missy Franklin',
            age: 17,
            country: 'United States',
            year: 2012,
            date: '12/08/2012',
            sport: 'Swimming',
            gold: 4,
            silver: 0,
            bronze: 1,
            total: 5,
        },
    ];
}
