import type { ModuleName } from '../../interfaces/iModule';
import type { IconName, IconValue } from '../../utils/icon';

export const ICON_VALUES: Record<IconValue, 1> = {
    expanded: 1,
    contracted: 1,
    'tree-closed': 1,
    'tree-open': 1,
    'tree-indeterminate': 1,
    pin: 1,
    'eye-slash': 1,
    arrows: 1,
    left: 1,
    right: 1,
    group: 1,
    aggregation: 1,
    pivot: 1,
    'not-allowed': 1,
    chart: 1,
    cross: 1,
    cancel: 1,
    tick: 1,
    first: 1,
    previous: 1,
    next: 1,
    last: 1,
    linked: 1,
    unlinked: 1,
    'color-picker': 1,
    loading: 1,
    menu: 1,
    'menu-alt': 1,
    filter: 1,
    columns: 1,
    maximize: 1,
    minimize: 1,
    copy: 1,
    cut: 1,
    paste: 1,
    grip: 1,
    save: 1,
    csv: 1,
    excel: 1,
    'small-down': 1,
    'small-left': 1,
    'small-right': 1,
    'small-up': 1,
    asc: 1,
    desc: 1,
    none: 1,
    up: 1,
    down: 1,
    plus: 1,
    minus: 1,
    settings: 1,
    'checkbox-checked': 1,
    'checkbox-indeterminate': 1,
    'checkbox-unchecked': 1,
    'radio-button-on': 1,
    'radio-button-off': 1,
    eye: 1,
};

export const ICON_MODULES: Record<IconName, ModuleName | ModuleName[]> = {
    chart: 'MenuCoreModule',
    cancel: 'EnterpriseCoreModule',
    first: 'PaginationCoreModule',
    previous: 'PaginationCoreModule',
    next: 'PaginationCoreModule',
    last: 'PaginationCoreModule',
    linked: 'GridChartsCoreModule',
    unlinked: 'GridChartsCoreModule',
    menu: 'ColumnHeaderCompModule',
    legacyMenu: 'ColumnMenuModule',
    filter: 'ColumnFilterModule',
    filterActive: 'ColumnFilterModule',
    filterTab: 'ColumnMenuModule',
    filtersToolPanel: 'FiltersToolPanelModule',
    columns: ['MenuCoreModule'],
    columnsToolPanel: ['ColumnsToolPanelCoreModule'],
    maximize: 'EnterpriseCoreModule',
    minimize: 'EnterpriseCoreModule',
    save: 'MenuCoreModule',
    columnGroupOpened: 'ColumnGroupHeaderCompModule',
    columnGroupClosed: 'ColumnGroupHeaderCompModule',
    accordionOpen: 'EnterpriseCoreModule',
    accordionClosed: 'EnterpriseCoreModule',
    accordionIndeterminate: 'EnterpriseCoreModule',
    columnSelectClosed: ['ColumnsToolPanelCoreModule', 'ColumnMenuModule', 'ColumnChooserModule'],
    columnSelectOpen: ['ColumnsToolPanelCoreModule', 'ColumnMenuModule', 'ColumnChooserModule'],
    columnSelectIndeterminate: ['ColumnsToolPanelCoreModule', 'ColumnMenuModule', 'ColumnChooserModule'],
    columnMovePin: 'DragAndDropModule',
    columnMoveHide: 'DragAndDropModule',
    columnMoveMove: 'DragAndDropModule',
    columnMoveLeft: 'DragAndDropModule',
    columnMoveRight: 'DragAndDropModule',
    columnMoveGroup: 'DragAndDropModule',
    columnMoveValue: 'DragAndDropModule',
    columnMovePivot: 'DragAndDropModule',
    dropNotAllowed: 'DragAndDropModule',
    groupContracted: 'GroupCellRendererModule',
    groupExpanded: 'GroupCellRendererModule',
    setFilterGroupClosed: 'SetFilterCoreModule',
    setFilterGroupOpen: 'SetFilterCoreModule',
    setFilterGroupIndeterminate: 'SetFilterCoreModule',
    close: 'EnterpriseCoreModule',
    check: 'MenuItemModule',
    colorPicker: 'CommunityCoreModule',
    groupLoading: 'LoadingCellRendererModule',
    menuAlt: 'ColumnHeaderCompModule',
    menuPin: 'MenuCoreModule',
    menuValue: 'MenuCoreModule',
    menuAddRowGroup: ['MenuCoreModule', 'ColumnsToolPanelCoreModule'],
    menuRemoveRowGroup: ['MenuCoreModule', 'ColumnsToolPanelCoreModule'],
    clipboardCopy: 'MenuCoreModule',
    clipboardCut: 'MenuCoreModule',
    clipboardPaste: 'MenuCoreModule',
    pivotPanel: ['ColumnsToolPanelCoreModule', 'RowGroupingPanelModule'],
    rowGroupPanel: ['ColumnsToolPanelCoreModule', 'RowGroupingPanelModule'],
    valuePanel: 'ColumnsToolPanelCoreModule',
    columnDrag: 'EnterpriseCoreModule',
    rowDrag: ['RowDragCoreModule', 'NativeDragModule'],
    csvExport: 'MenuCoreModule',
    excelExport: 'MenuCoreModule',
    smallDown: 'CommunityCoreModule',
    selectOpen: 'CommunityCoreModule',
    richSelectOpen: 'RichSelectModule',
    richSelectRemove: 'RichSelectModule',
    smallLeft: 'CommunityCoreModule',
    smallRight: 'CommunityCoreModule',
    subMenuOpen: 'MenuItemModule',
    subMenuOpenRtl: 'MenuItemModule',
    panelDelimiter: 'RowGroupingPanelModule',
    panelDelimiterRtl: 'RowGroupingPanelModule',
    smallUp: 'CommunityCoreModule',
    sortAscending: ['MenuCoreModule', 'SortIndicatorCompModule'],
    sortDescending: ['MenuCoreModule', 'SortIndicatorCompModule'],
    sortUnSort: ['MenuCoreModule', 'SortIndicatorCompModule'],
    advancedFilterBuilder: 'AdvancedFilterCoreModule',
    advancedFilterBuilderDrag: 'AdvancedFilterCoreModule',
    advancedFilterBuilderInvalid: 'AdvancedFilterCoreModule',
    advancedFilterBuilderMoveUp: 'AdvancedFilterCoreModule',
    advancedFilterBuilderMoveDown: 'AdvancedFilterCoreModule',
    advancedFilterBuilderAdd: 'AdvancedFilterCoreModule',
    advancedFilterBuilderRemove: 'AdvancedFilterCoreModule',
    advancedFilterBuilderSelectOpen: 'AdvancedFilterCoreModule',
    chartsMenu: 'GridChartsCoreModule',
    chartsMenuEdit: 'GridChartsCoreModule',
    chartsMenuAdvancedSettings: 'GridChartsCoreModule',
    chartsMenuAdd: 'GridChartsCoreModule',
    chartsColorPicker: 'GridChartsCoreModule',
    chartsThemePrevious: 'GridChartsCoreModule',
    chartsThemeNext: 'GridChartsCoreModule',
    chartsDownload: 'GridChartsCoreModule',
    checkboxChecked: 'CommunityCoreModule',
    checkboxIndeterminate: 'CommunityCoreModule',
    checkboxUnchecked: 'CommunityCoreModule',
    radioButtonOn: 'CommunityCoreModule',
    radioButtonOff: 'CommunityCoreModule',
};

export const DEPRECATED_ICONS_V33: Set<IconName> = new Set([
    'colorPicker',
    'smallUp',
    'checkboxChecked',
    'checkboxIndeterminate',
    'checkboxUnchecked',
    'radioButtonOn',
    'radioButtonOff',
    'smallDown',
    'smallLeft',
    'smallRight',
]);
