import type { UserComponentName } from '../../context/context';
import type { ModuleName } from '../../interfaces/iModule';

export const USER_COMP_MODULES: Record<UserComponentName, ModuleName> = {
    agSetColumnFilter: 'SetFilterCoreModule',
    agSetColumnFloatingFilter: 'SetFloatingFilterModule',
    agMultiColumnFilter: 'MultiFilterCoreModule',
    agMultiColumnFloatingFilter: 'MultiFloatingFilterModule',
    agGroupColumnFilter: 'GroupFilterModule',
    agGroupColumnFloatingFilter: 'GroupFloatingFilterModule',
    agGroupCellRenderer: 'GroupCellRendererModule',
    agGroupRowRenderer: 'GroupCellRendererModule',
    agRichSelect: 'RichSelectModule',
    agRichSelectCellEditor: 'RichSelectModule',
    agDetailCellRenderer: 'MasterDetailCoreModule',
    agSparklineCellRenderer: 'SparklinesModule',
    agDragAndDropImage: 'DragAndDropModule',
    agColumnHeader: 'ColumnHeaderCompModule',
    agColumnGroupHeader: 'ColumnGroupHeaderCompModule',
    agSortIndicator: 'SortIndicatorCompModule',
    agAnimateShowChangeCellRenderer: 'AnimateShowChangeCellRendererModule',
    agAnimateSlideCellRenderer: 'AnimateSlideCellRendererModule',
    agLoadingCellRenderer: 'LoadingCellRendererModule',
    agSkeletonCellRenderer: 'SkeletonCellRendererModule',
    agCheckboxCellRenderer: 'CheckboxCellRendererModule',
    agLoadingOverlay: 'LoadingOverlayModule',
    agNoRowsOverlay: 'NoRowsOverlayModule',
    agTooltipComponent: 'TooltipCompModule',
    agReadOnlyFloatingFilter: 'ReadOnlyFloatingFilterModule',
    agTextColumnFilter: 'SimpleFilterModule',
    agNumberColumnFilter: 'SimpleFilterModule',
    agDateColumnFilter: 'SimpleFilterModule',
    agDateInput: 'SimpleFilterModule',
    agTextColumnFloatingFilter: 'SimpleFloatingFilterModule',
    agNumberColumnFloatingFilter: 'SimpleFloatingFilterModule',
    agDateColumnFloatingFilter: 'SimpleFloatingFilterModule',
    agCellEditor: 'DefaultEditorModule',
    agSelectCellEditor: 'SelectEditorModule',
    agTextCellEditor: 'DataTypeEditorsModule',
    agNumberCellEditor: 'DataTypeEditorsModule',
    agDateCellEditor: 'DataTypeEditorsModule',
    agDateStringCellEditor: 'DataTypeEditorsModule',
    agCheckboxCellEditor: 'DataTypeEditorsModule',
    agLargeTextCellEditor: 'LargeTextEditorModule',
    agMenuItem: 'MenuItemModule',
    agColumnsToolPanel: 'ColumnsToolPanelCoreModule',
    agFiltersToolPanel: 'FiltersToolPanelModule',
    agAggregationComponent: 'StatusBarCoreModule',
    agSelectedRowCountComponent: 'StatusBarCoreModule',
    agTotalRowCountComponent: 'StatusBarCoreModule',
    agFilteredRowCountComponent: 'StatusBarCoreModule',
    agTotalAndFilteredRowCountComponent: 'StatusBarCoreModule',
};
