export function getData() {
    const rowData = [
        {
            orgHierarchy: ['Dylan Lewis'],
            jobTitle: 'CEO',
            employmentType: 'Permanent',
            department: 'Executive Management',
            employeeId: 971769,
            location: 'United Kingdom',
            joinDate: '2005-12-10',
            basicMonthlySalary: 14762.71,
            currency: 'GBP',
            paymentMethod: 'Bank Transfer',
            paymentStatus: 'Pending',
            image: '8',
            flag: 'uk',
        },
        {
            orgHierarchy: ['Dylan Lewis', 'Renee Baker'],
            jobTitle: 'CTO',
            employmentType: 'Permanent',
            department: 'Executive Management',
            employeeId: 353706,
            location: 'United Kingdom',
            joinDate: '2019-07-31',
            basicMonthlySalary: 8659.59,
            currency: 'GBP',
            paymentMethod: 'Cash',
            paymentStatus: 'Paid',
            image: '1',
            flag: 'uk',
        },
        {
            orgHierarchy: ['Dylan Lewis', 'Frank Wilson'],
            jobTitle: 'Exec. Vice President',
            employmentType: 'Permanent',
            department: 'Executive Management',
            employeeId: 316904,
            location: 'United Kingdom',
            joinDate: '2010-05-15',
            basicMonthlySalary: 4825.55,
            currency: 'GBP',
            paymentMethod: 'Check',
            paymentStatus: 'Paid',
            image: '2',
            flag: 'uk',
        },
        {
            orgHierarchy: ['Dylan Lewis', 'Michael Dennis'],
            jobTitle: 'Exec. Vice President',
            employmentType: 'Permanent',
            department: 'Executive Management',
            employeeId: 625535,
            location: 'United Kingdom',
            joinDate: '2001-10-21',
            basicMonthlySalary: 4423.64,
            currency: 'GBP',
            paymentMethod: 'Bank Transfer',
            paymentStatus: 'Paid',
            image: '9',
            flag: 'uk',
        },
        {
            orgHierarchy: ['John Gonzalez'],
            jobTitle: 'Head of Department',
            employmentType: 'Permanent',
            department: 'Customer Support',
            employeeId: 703257,
            location: 'Ireland',
            joinDate: '2006-10-09',
            basicMonthlySalary: 3491.98,
            currency: 'EUR',
            paymentMethod: 'Cash',
            paymentStatus: 'Paid',
            image: '10',
            flag: 'ie',
        },
        {
            orgHierarchy: ['John Gonzalez', 'Nicole Bass'],
            jobTitle: 'Employee',
            employmentType: 'Permanent',
            department: 'Customer Support',
            employeeId: 859426,
            location: 'Ireland',
            joinDate: '2019-01-04',
            basicMonthlySalary: 2734.11,
            currency: 'EUR',
            paymentMethod: 'Check',
            paymentStatus: 'Pending',
            image: '11',
            flag: 'ie',
        },
        {
            orgHierarchy: ['John Gonzalez', 'Rachel Mckenzie'],
            jobTitle: 'Employee',
            employmentType: 'Contract',
            department: 'Customer Support',
            employeeId: 984668,
            location: 'United States',
            joinDate: '2001-07-15',
            basicMonthlySalary: 2672.37,
            currency: 'USD',
            paymentMethod: 'Cash',
            paymentStatus: 'Pending',
            image: '7',
            flag: 'us',
        },
        {
            orgHierarchy: ['Jonathan Romero'],
            jobTitle: 'Head of Department',
            employmentType: 'Permanent',
            department: 'Design',
            employeeId: 936854,
            location: 'United States',
            joinDate: '2019-03-19',
            basicMonthlySalary: 7126.1,
            currency: 'USD',
            paymentMethod: 'Bank Transfer',
            paymentStatus: 'Paid',
            image: '3',
            flag: 'us',
        },
        {
            orgHierarchy: ['Jonathan Romero', 'Heather Mathis'],
            jobTitle: 'Employee',
            employmentType: 'Permanent',
            department: 'Design',
            employeeId: 105854,
            location: 'United States',
            joinDate: '2009-05-04',
            basicMonthlySalary: 3364.38,
            currency: 'USD',
            paymentMethod: 'Bank Transfer',
            paymentStatus: 'Pending',
            image: '4',
            flag: 'us',
        },
        {
            orgHierarchy: ['Jonathan Romero', 'Dr. Gregory Mills'],
            jobTitle: 'Employee',
            employmentType: 'Permanent',
            department: 'Design',
            employeeId: 196196,
            location: 'Spain',
            joinDate: '2018-11-26',
            basicMonthlySalary: 5088.19,
            currency: 'EUR',
            paymentMethod: 'Check',
            paymentStatus: 'Pending',
            image: '5',
            flag: 'es',
        },
        {
            orgHierarchy: ['Shawn Phillips'],
            jobTitle: 'Head of Department',
            employmentType: 'Permanent',
            department: 'Product',
            employeeId: 597662,
            location: 'Kathrynbury',
            joinDate: '2022-10-30',
            basicMonthlySalary: 3402.91,
            currency: 'USD',
            paymentMethod: 'Bank Transfer',
            paymentStatus: 'Pending',
            image: '9',
            flag: 'us',
        },
        {
            orgHierarchy: ['Shawn Phillips', 'Jill Hobbs'],
            jobTitle: 'Employee',
            employmentType: 'Contract',
            department: 'Product',
            employeeId: 297310,
            location: 'Meyersmouth',
            joinDate: '2001-11-29',
            basicMonthlySalary: 5478.9,
            currency: 'EUR',
            paymentMethod: 'Cash',
            paymentStatus: 'Pending',
            image: '17',
            flag: 'ne',
        },
        {
            orgHierarchy: ['Shawn Phillips', 'Martin Villanueva'],
            jobTitle: 'Employee',
            employmentType: 'Contract',
            department: 'Product',
            employeeId: 900809,
            location: 'Portugal',
            joinDate: '2006-03-02',
            basicMonthlySalary: 7093.81,
            currency: 'EUR',
            paymentMethod: 'Check',
            paymentStatus: 'Pending',
            image: '6',
            flag: 'po',
        },
        {
            orgHierarchy: ['Shawn Phillips', 'Mary Stone'],
            jobTitle: 'Head of Department',
            employmentType: 'Permanent',
            department: 'Engineering',
            employeeId: 634325,
            location: 'Netherlands ',
            joinDate: '2019-05-01',
            basicMonthlySalary: 6618.2,
            currency: 'EUR',
            paymentMethod: 'Cash',
            paymentStatus: 'Paid',
            image: '7',
            flag: 'ne',
        },
        {
            orgHierarchy: ['Shawn Phillips',  'Darren Osborn'],
            jobTitle: 'Employee',
            employmentType: 'Permanent',
            department: 'Engineering',
            employeeId: 568861,
            location: 'Spain',
            joinDate: '2007-07-15',
            basicMonthlySalary: 7625.11,
            currency: 'EUR',
            paymentMethod: 'Bank Transfer',
            paymentStatus: 'Pending',
            image: '12',
            flag: 'es',
        },
        {
            orgHierarchy: ['Shawn Phillips',  'Amanda Arnold'],
            jobTitle: 'Employee',
            employmentType: 'Permanent',
            department: 'Engineering',
            employeeId: 605882,
            location: 'Ireland',
            joinDate: '2013-12-06',
            basicMonthlySalary: 2787.82,
            currency: 'EUR',
            paymentMethod: 'Bank Transfer',
            paymentStatus: 'Paid',
            image: '13',
            flag: 'ie',
        },
        {
            orgHierarchy: ['Shawn Phillips',  'Richard Willis'],
            jobTitle: 'Employee',
            employmentType: 'Contract',
            department: 'Engineering',
            employeeId: 855633,
            location: 'France',
            joinDate: '2007-08-14',
            basicMonthlySalary: 3437.53,
            currency: 'EUR',
            paymentMethod: 'Check',
            paymentStatus: 'Pending',
            image: '14',
            flag: 'fr',
        },
        {
            orgHierarchy: ['Shawn Phillips',  'Mary Mckinney'],
            jobTitle: 'Employee',
            employmentType: 'Contract',
            department: 'Engineering',
            employeeId: 832328,
            location: 'United Kingdom',
            joinDate: '2014-02-13',
            basicMonthlySalary: 5996.5,
            currency: 'GBP',
            paymentMethod: 'Check',
            paymentStatus: 'Paid',
            image: '15',
            flag: 'uk',
        },
        {
            orgHierarchy: ['Shawn Phillips',  'Tammy Love'],
            jobTitle: 'Employee',
            employmentType: 'Permanent',
            department: 'Engineering',
            employeeId: 900105,
            location: 'Websterberg',
            joinDate: '2019-03-08',
            basicMonthlySalary: 3153.23,
            currency: 'EUR',
            paymentMethod: 'Cash',
            paymentStatus: 'Pending',
            image: '16',
            flag: 'fr',
        },
        {
            orgHierarchy: ['Shawn Phillips',  'Donna Parker'],
            jobTitle: 'Employee',
            employmentType: 'Contract',
            department: 'Engineering',
            employeeId: 352690,
            location: 'North Robertchester',
            joinDate: '2008-11-30',
            basicMonthlySalary: 2011.26,
            currency: 'GBP',
            paymentMethod: 'Check',
            paymentStatus: 'Pending',
            image: '17',
            flag: 'es',
        },
        {
            orgHierarchy: ['Shawn Phillips',  'Trevor Williams'],
            jobTitle: 'Employee',
            employmentType: 'Contract',
            department: 'Engineering',
            employeeId: 568297,
            location: 'Mossfurt',
            joinDate: '2022-01-09',
            basicMonthlySalary: 5893.18,
            currency: 'EUR',
            paymentMethod: 'Cash',
            paymentStatus: 'Paid',
            image: '18',
            flag: 'fr',
        },
        {
            orgHierarchy: ['Shawn Phillips',  'Daniel Rodgers'],
            jobTitle: 'Employee',
            employmentType: 'Permanent',
            department: 'Engineering',
            employeeId: 209501,
            location: 'Lake Patrick',
            joinDate: '2004-12-25',
            basicMonthlySalary: 6555.64,
            currency: 'GBP',
            paymentMethod: 'Bank Transfer',
            paymentStatus: 'Paid',
            image: '19',
            flag: 'uk',
        },
        {
            orgHierarchy: ['John Hall'],
            jobTitle: 'Head of Department',
            employmentType: 'Contract',
            department: 'Legal',
            employeeId: 284758,
            location: 'Mclaughlinbury',
            joinDate: '2011-06-05',
            basicMonthlySalary: 5388.43,
            currency: 'EUR',
            paymentMethod: 'Cash',
            paymentStatus: 'Pending',
            image: '12',
            flag: 'fr',
        },
        {
            orgHierarchy: ['John Hall',  'Alexandria Novak'],
            jobTitle: 'Employee',
            employmentType: 'Contract',
            department: 'Legal',
            employeeId: 322302,
            location: 'United Kingdom',
            joinDate: '2014-06-29',
            basicMonthlySalary: 2676.37,
            currency: 'GBP',
            paymentMethod: 'Check',
            paymentStatus: 'Pending',
            image: '1',
            flag: 'uk',
        },
        {
            orgHierarchy: ['John Hall',  'Donald Brennan'],
            jobTitle: 'Employee',
            employmentType: 'Permanent',
            department: 'Legal',
            employeeId: 71358,
            location: 'Ireland',
            joinDate: '2002-06-14',
            basicMonthlySalary: 7272.37,
            currency: 'EUR',
            paymentMethod: 'Check',
            paymentStatus: 'Paid',
            image: '2',
            flag: 'ie',
        },
        {
            orgHierarchy: ['John Hall',  'Andrea Kim'],
            jobTitle: 'Employee',
            employmentType: 'Permanent',
            department: 'Legal',
            employeeId: 688798,
            location: 'United Kingdom',
            joinDate: '2011-05-05',
            basicMonthlySalary: 2823.27,
            currency: 'GBP',
            paymentMethod: 'Check',
            paymentStatus: 'Paid',
            image: '3',
            flag: 'uk',
        },
    ];
    return rowData;
}
