import React, { StrictMode, useCallback, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';

import type { ColDef, GridApi } from 'ag-grid-community';
import {
    AutoGenerateColumnsModule,
    ClientSideRowModelModule,
    NumberFilterModule,
    TextFilterModule,
    ValidationModule,
} from 'ag-grid-community';
import { AgGridProvider, AgGridReact } from 'ag-grid-react';

import FileDropOverlay from './fileDropOverlay';
import './styles.css';

const modules = [
    ClientSideRowModelModule,
    TextFilterModule,
    NumberFilterModule,
    AutoGenerateColumnsModule,
    ...(process.env.NODE_ENV !== 'production' ? [ValidationModule] : []),
];

const sampleCsv = `Name,Age,Country,Sport,Gold,Silver,Bronze
Michael Phelps,23,United States,Swimming,8,0,0
Usain Bolt,21,Jamaica,Athletics,3,0,0
Natalie Coughlin,25,United States,Swimming,1,2,3
Stephanie Rice,20,Australia,Swimming,3,0,0
Chris Hoy,32,Great Britain,Cycling,3,0,0
Rebecca Adlington,19,Great Britain,Swimming,2,0,0
Kobe Bryant,29,United States,Basketball,1,0,0
Elena Isinbaeva,26,Russia,Athletics,1,0,0
Shelly-Ann Fraser,21,Jamaica,Athletics,1,0,0
Alain Bernard,25,France,Swimming,1,1,0`;

function unquote(value: string): string {
    const trimmed = value.trim();
    if (trimmed.length >= 2 && trimmed[0] === '"' && trimmed[trimmed.length - 1] === '"') {
        return trimmed.slice(1, -1).replace(/""/g, '"');
    }
    return trimmed;
}

function parseCsv(csvText: string): Record<string, string | number>[] {
    const lines = csvText.trim().split('\n');
    const headers = lines[0].split(',').map(unquote);
    return lines.slice(1).map((line) => {
        const values = line.split(',').map(unquote);
        const row: Record<string, string | number> = {};
        headers.forEach((header, j) => {
            const val = values[j];
            row[header] = isNaN(Number(val)) ? val : Number(val);
        });
        return row;
    });
}

const GridExample = () => {
    const gridRef = useRef<GridApi>(null);
    const [rowData, setRowData] = useState<Record<string, string | number>[] | null>(null);
    const [columnDefs, setColumnDefs] = useState<ColDef[]>([]);
    const [activeOverlay, setActiveOverlay] = useState<any>(FileDropOverlay);

    const processAutoGeneratedColumnDefs = useCallback((params: { colDefs: ColDef[]; rowData: any[] }) => {
        return params.colDefs.map((colDef) => {
            const sampleValue = params.rowData[0]?.[colDef.field!];
            if (!isNaN(Number(sampleValue))) {
                return { ...colDef, filter: 'agNumberColumnFilter' };
            }
            return { ...colDef, filter: 'agTextColumnFilter' };
        });
    }, []);

    const loadData = useCallback((csvText: string) => {
        const data = parseCsv(csvText);
        setRowData(data);
        setActiveOverlay(undefined);
    }, []);

    const onLoadSampleData = useCallback(() => {
        loadData(sampleCsv);
    }, [loadData]);

    const onClearData = useCallback(() => {
        setRowData(null);
        setColumnDefs([]);
        setActiveOverlay(FileDropOverlay);
    }, []);

    const onDrop = useCallback(
        (event: React.DragEvent) => {
            event.preventDefault();
            const file = event.dataTransfer?.files[0];
            if (!file) return;
            const reader = new FileReader();
            reader.onload = (e) => {
                const text = e.target?.result as string;
                loadData(text);
            };
            reader.readAsText(file);
        },
        [loadData]
    );

    const onDragOver = useCallback((event: React.DragEvent) => {
        event.preventDefault();
    }, []);

    return (
        <AgGridProvider modules={modules}>
            <div className="example-wrapper">
                <div className="button-row">
                    <button onClick={onLoadSampleData}>Load Sample CSV</button>
                    <button onClick={onClearData}>Clear Data</button>
                </div>
                <div className="grid-wrapper" onDrop={onDrop} onDragOver={onDragOver}>
                    <AgGridReact
                        ref={gridRef}
                        autoGenerateColumnDefs={true}
                        rowData={rowData}
                        columnDefs={columnDefs}
                        activeOverlay={activeOverlay}
                        processAutoGeneratedColumnDefs={processAutoGeneratedColumnDefs}
                    />
                </div>
            </div>
        </AgGridProvider>
    );
};

const root = createRoot(document.getElementById('root')!);
root.render(
    <StrictMode>
        <GridExample />
    </StrictMode>
);
