name: 'Run Framework Example Tests'
description: 'Run Framework Example Tests'
inputs:
  framework:
    description: 'Framework to use'
    required: true
    default: 'invalid-framework'
  browsers:
    description: 'Broswers to run tests on: all / chromium'
    required: true
    default: 'chromium'
  test-pattern:
    description: 'Test pattern to run'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup
      id: setup
      uses: ./.github/actions/setup-nx
      with:
        cache_mode: ro

    - name: Run ${{ inputs.framework }} Examples
      env:
        FRAMEWORK: ${{ inputs.framework }}
        BASE_URL: https://grid-staging.ag-grid.com/
      shell: bash
      run: yarn nx run ag-grid-docs:test:interactive:${{ inputs.browsers }} ${{inputs.test-pattern}} --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
    
    - name: Upload Test Report
      id: upload-recipes-report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-${{ inputs.framework }}-examples-${{ matrix.shardIndex }}-of-${{ matrix.shardTotal }}
        path: reports/
        retention-days: ${{env.DEFAULT_RETENTION_DAYS}}