import type { GridApi, GridOptions } from 'ag-grid-community';
import {
    ClientSideRowModelModule,
    ColumnAutoSizeModule,
    CsvExportModule,
    ModuleRegistry,
    QuickFilterModule,
    TextFilterModule,
    ValidationModule,
    createGrid,
} from 'ag-grid-community';
import {
    ColumnMenuModule,
    ColumnsToolPanelModule,
    ExcelExportModule,
    FiltersToolPanelModule,
    FindModule,
    RowGroupingModule,
    RowGroupingPanelModule,
    SideBarModule,
    ToolbarModule,
} from 'ag-grid-enterprise';

ModuleRegistry.registerModules([
    TextFilterModule,
    ClientSideRowModelModule,
    ColumnAutoSizeModule,
    CsvExportModule,
    QuickFilterModule,
    ColumnMenuModule,
    ColumnsToolPanelModule,
    ExcelExportModule,
    FiltersToolPanelModule,
    FindModule,
    RowGroupingModule,
    RowGroupingPanelModule,
    SideBarModule,
    ToolbarModule,
    ...(process.env.NODE_ENV !== 'production' ? [ValidationModule] : []),
]);

let gridApi: GridApi;

const gridOptions: GridOptions = {
    columnDefs: [
        { field: 'athlete', minWidth: 200 },
        { field: 'country', minWidth: 200 },
        { field: 'sport', minWidth: 200 },
        { field: 'year' },
        { field: 'gold', enableValue: true },
        { field: 'silver', enableValue: true },
        { field: 'bronze', enableValue: true },
        { field: 'total' },
    ],
    defaultColDef: {
        flex: 1,
        minWidth: 100,
        filter: true,
        enableRowGroup: true,
        enablePivot: true,
    },
    enableFilterHandlers: true,
    sideBar: {
        toolPanels: ['columns', 'filters-new'],
        defaultToolPanel: '',
    },
    toolbar: {
        items: [
            'rowGroupPanel',
            'pivotPanel',
            { component: 'quickFilter', alignment: 'right' },
            { component: 'find', alignment: 'right' },
            'separator',
            { component: 'columnsPanel', alignment: 'right' },
            { component: 'filtersPanel', alignment: 'right' },
            { component: 'autoSizeAll', alignment: 'right' },
            'separator',
            { component: 'export', alignment: 'right' },
            'separator',
            { component: 'resetColumns', alignment: 'right', display: 'iconAndLabel' },
        ],
    },
    rowData: [
        {
            athlete: 'Michael Phelps',
            country: 'United States',
            sport: 'Swimming',
            year: 2008,
            gold: 8,
            silver: 0,
            bronze: 0,
            total: 8,
        },
        {
            athlete: 'Natalie Coughlin',
            country: 'United States',
            sport: 'Swimming',
            year: 2008,
            gold: 1,
            silver: 2,
            bronze: 3,
            total: 6,
        },
        {
            athlete: 'Usain Bolt',
            country: 'Jamaica',
            sport: 'Athletics',
            year: 2008,
            gold: 3,
            silver: 0,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Shelly-Ann Fraser',
            country: 'Jamaica',
            sport: 'Athletics',
            year: 2008,
            gold: 1,
            silver: 0,
            bronze: 0,
            total: 1,
        },
        {
            athlete: 'Ian Thorpe',
            country: 'Australia',
            sport: 'Swimming',
            year: 2000,
            gold: 3,
            silver: 2,
            bronze: 0,
            total: 5,
        },
        {
            athlete: 'Cathy Freeman',
            country: 'Australia',
            sport: 'Athletics',
            year: 2000,
            gold: 1,
            silver: 0,
            bronze: 0,
            total: 1,
        },
        {
            athlete: 'Mo Farah',
            country: 'Great Britain',
            sport: 'Athletics',
            year: 2012,
            gold: 2,
            silver: 0,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Jessica Ennis',
            country: 'Great Britain',
            sport: 'Athletics',
            year: 2012,
            gold: 1,
            silver: 0,
            bronze: 0,
            total: 1,
        },
        {
            athlete: 'Eliud Kipchoge',
            country: 'Kenya',
            sport: 'Athletics',
            year: 2016,
            gold: 1,
            silver: 0,
            bronze: 0,
            total: 1,
        },
        {
            athlete: 'Sun Yang',
            country: 'China',
            sport: 'Swimming',
            year: 2012,
            gold: 2,
            silver: 1,
            bronze: 0,
            total: 3,
        },
    ],
};

document.addEventListener('DOMContentLoaded', () => {
    const gridDiv = document.querySelector<HTMLElement>('#myGrid')!;
    gridApi = createGrid(gridDiv, gridOptions);
});
