name: jira-integration
author: sdwvit
description: Creates a Jira ticket based on the test results.
inputs:
  JIRA_API_AUTH:
    description: 'Jira API authentication header'
    required: true
  JIRA_SUMMARY:
    description: 'Jira ticket title, should be more descriptive than the workflow name'
    required: true
  CTRF_REPORT_FILE:
    description: 'Path to the CTRF report file'
    required: false
  CURRENT_COMMIT_SHA:
    description: 'Current/Variant commit SHA being tested'
    required: false
  PREV_COMMIT_SHA:
    description: 'Base/Control commit SHA to compare against'
    required: false
  IS_SUCCESS:
    description: 'Indicates if the workflow run was successful'
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Get last failed step
      id: last-failed-step
      if: ${{ failure() && !inputs.IS_SUCCESS }}
      continue-on-error: true
      uses: ./external/ag-shared/github/actions/get-last-failed-step
      with:
        JOB_ID: ${{ github.run_id }}
        REPO_NAME: ${{ github.repository }}

    - name: Generate JIRA files
      shell: bash
      env:
        JIRA_DESCRIPTION_FILE: './jira-description.txt'
        JIRA_FINGERPRINT_FILE: './jira-fingerprint.txt'
        CTRF_REPORT_FILE: ${{ inputs.CTRF_REPORT_FILE }}
        WORKFLOW_NAME: ${{ github.workflow }}
        JOB_ID: ${{ github.run_id }}
        CURRENT_COMMIT_SHA: ${{ inputs.CURRENT_COMMIT_SHA }}
        PREV_COMMIT_SHA: ${{ inputs.PREV_COMMIT_SHA }}
        REPO_URL: ${{ github.server_url }}/${{ github.repository }}
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        IS_SUCCESS: ${{ inputs.IS_SUCCESS == 'true' && !steps.last-failed-step.outputs.failed_step }}
        LAST_FAILED_STEP: ${{ steps.last-failed-step.outputs.failed_step }}
      run: |
        node ./scripts/ci/gen-jira-files.mjs        
        {
          echo 'JIRA_FINGERPRINT<<EOF'
          cat $JIRA_FINGERPRINT_FILE
          echo 'EOF'
        } >> $GITHUB_ENV
        {
          echo 'JIRA_DESCRIPTION<<EOF'
          cat $JIRA_DESCRIPTION_FILE
          echo 'EOF'
        } >> $GITHUB_ENV

    - name: Create Jira Ticket
      env:
        JIRA_FINGERPRINT: ${{ env.JIRA_FINGERPRINT }}
        JIRA_DESCRIPTION: ${{ env.JIRA_DESCRIPTION }}
        JIRA_API_AUTH: ${{ inputs.JIRA_API_AUTH }}
        WORKFLOW_NAME: ${{ github.workflow }}
        JIRA_SUMMARY: ${{ inputs.JIRA_SUMMARY }}
        IS_SUCCESS: ${{ inputs.IS_SUCCESS == 'true' && !steps.last-failed-step.outputs.failed_step }}
      shell: bash
      run: |
        node ./scripts/ci/create-jira-ticket.mjs
