export function getData(): IOlympicData[] {
    return [
        {
            athlete: 'Ryan Lochte',
            age: 27,
            country: 'United States',
            year: 2012,
            date: '12/08/2012',
            sport: 'Swimming',
            gold: 2,
            silver: 2,
            bronze: 1,
            total: 5,
        },
        {
            athlete: 'Yekaterina Lobaznyuk',
            age: 17,
            country: 'Russia',
            year: 2000,
            date: '01/10/2000',
            sport: 'Gymnastics',
            gold: 0,
            silver: 2,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Ryan Lochte',
            age: 20,
            country: 'United States',
            year: 2004,
            date: '29/08/2004',
            sport: 'Swimming',
            gold: 1,
            silver: 1,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Ericka Lorenz',
            age: 23,
            country: 'United States',
            year: 2004,
            date: '29/08/2004',
            sport: 'Waterpolo',
            gold: 0,
            silver: 0,
            bronze: 1,
            total: 1,
        },
        {
            athlete: 'Ericka Lorenz',
            age: 19,
            country: 'United States',
            year: 2000,
            date: '01/10/2000',
            sport: 'Waterpolo',
            gold: 0,
            silver: 1,
            bronze: 0,
            total: 1,
        },
        {
            athlete: 'Nikita Lobintsev',
            age: 23,
            country: 'Russia',
            year: 2012,
            date: '12/08/2012',
            sport: 'Swimming',
            gold: 0,
            silver: 0,
            bronze: 1,
            total: 1,
        },
        {
            athlete: 'Tatyana Logunova',
            age: 24,
            country: 'Russia',
            year: 2004,
            date: '29/08/2004',
            sport: 'Fencing',
            gold: 1,
            silver: 0,
            bronze: 0,
            total: 1,
        },
        {
            athlete: 'Tatyana Logunova',
            age: 20,
            country: 'Russia',
            year: 2000,
            date: '01/10/2000',
            sport: 'Fencing',
            gold: 1,
            silver: 0,
            bronze: 0,
            total: 1,
        },
        {
            athlete: 'Nelson Loyola',
            age: 32,
            country: 'Cuba',
            year: 2000,
            date: '01/10/2000',
            sport: 'Fencing',
            gold: 0,
            silver: 0,
            bronze: 1,
            total: 1,
        },
    ];
}
