var LINUX_DISTROS = [
    'Manjaro',
    'MX Linux',
    'Mint',
    'elementary',
    'Ubuntu',
    'Debian',
    'Fedora',
    'Solus',
    'openSUSE',
    'Zorin',
    'ReactOS',
    'CentOS',
    'Arch',
    'KDE neon',
    'deepin',
    'antiX',
    'Antergos',
    'Kali',
    'Parrot',
    'Lite',
    'ArcoLinux',
    'FreeBSD',
    'Ubuntu Kylin',
    'Lubuntu',
    'SparkyLinux',
    'Peppermint',
    'SmartOS',
    'PCLinuxOS',
    'Mageia',
    'Endless',
]

var CITIES = [
    'Tokyo',
    'Jakarta',
    'Delhi',
    'Manila',
    'Seoul',
    'Shanghai',
    'Mumbai',
    'New York',
    'Beijing',
    'Sao Paulo',
    'Mexico City',
    'Guangzhou',
    'Dhaka',
    'Osaka-Kobe-Kyoto',
    'Moscow',
    'Cairo',
    'Bangkok',
    'Los Angeles',
    'Buenos Aires',
]

var LAPTOPS = [
    'Hewlett Packard',
    'Lenovo',
    'Dell',
    'Asus',
    'Apple',
    'Acer',
    'Microsoft',
    'Razer',
]
