// Locate a system Apache, write a minimal httpd.conf for the harness docroot, and start/stop it.
//
// Portable across macOS (built-in httpd, modules in /usr/libexec/apache2) and Debian/RHEL. When
// Apache or a required module is missing the caller SKIPs (exit 0) unless HTTPD_REQUIRED=1 - that
// is the ONLY condition under which the harness may skip.
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const REQUIRED_MODS = [
    'mpm_prefork',
    'unixd',
    'authz_core',
    'log_config',
    'mime',
    'dir',
    'alias',
    'rewrite',
    'headers',
];

const which = (cmd) => {
    try {
        return execFileSync('sh', ['-c', `command -v ${cmd}`], { encoding: 'utf8' }).trim() || null;
    } catch {
        return null;
    }
};

/** Returns { httpd, loadModules } or { skip: reason }. */
export function detectApache() {
    let httpd = process.env.HTTPD || null;
    if (!httpd) {
        for (const c of ['httpd', 'apache2', '/usr/sbin/httpd', '/usr/sbin/apache2']) {
            const found = c.startsWith('/') ? (existsSync(c) ? c : null) : which(c);
            if (found) {
                httpd = found;
                break;
            }
        }
    }
    if (!httpd) {
        return { skip: 'no httpd/apache2 binary found' };
    }
    let mods = process.env.HTTPD_MODULES || null;
    if (!mods) {
        mods = [
            '/usr/libexec/apache2',
            '/usr/lib/apache2/modules',
            '/usr/lib64/httpd/modules',
            '/etc/httpd/modules',
            '/usr/lib/httpd/modules',
        ].find((d) => existsSync(join(d, 'mod_rewrite.so')));
    }
    if (!mods) {
        return { skip: 'Apache modules directory not found' };
    }
    // Debian compiles some modules (unixd, log_config) into the binary: those appear in `httpd -l`,
    // have no .so on disk, and must not be LoadModule'd ("module is built-in").
    let builtin = '';
    try {
        builtin = execFileSync(httpd, ['-l'], { encoding: 'utf8' });
    } catch {
        // an httpd that cannot list its modules still gets every module loaded from disk
    }
    const loadModules = [];
    for (const m of REQUIRED_MODS) {
        if (new RegExp(`mod_${m}\\.c$`, 'm').test(builtin)) {
            continue;
        }
        const so = join(mods, `mod_${m}.so`);
        if (!existsSync(so)) {
            return { skip: `required Apache module mod_${m}.so not found in ${mods}` };
        }
        loadModules.push(`LoadModule ${m}_module ${so}`);
    }
    return { httpd, modsDir: mods, loadModules };
}

/**
 * The real MIME map, so `%{CONTENT_TYPE}` expressions in the generated rules fire exactly as in
 * production. Never /dev/null: that silently disables every content-type-scoped header.
 */
export function findMimeTypes() {
    const candidates = [
        process.env.MIME_TYPES,
        '/private/etc/apache2/mime.types',
        '/etc/apache2/mime.types',
        '/etc/mime.types',
    ];
    const found = candidates.find((p) => p && existsSync(p) && readFileSync(p, 'utf8').includes('text/html'));
    if (!found) {
        throw new Error(
            'no mime.types found (tried /private/etc/apache2/mime.types, /etc/mime.types); set MIME_TYPES=/path/to/mime.types'
        );
    }
    return found;
}

export function writeHttpdConf({ work, htdocs, port, loadModules, mimeTypes }) {
    const conf = `# GENERATED by the htaccess harness. Mirrors the parts of the production vhost the generated
# .htaccess files depend on: a real MIME map, DirectoryIndex, AllowOverride All on the docroot.
ServerRoot "${work}"
DefaultRuntimeDir "${work}"
Mutex file:${work} default
TypesConfig "${mimeTypes}"
Listen 127.0.0.1:${port}
${loadModules.join('\n')}
# Pin the canonical name+port so %{SERVER_PORT} is the real listen port, not the port implied by a
# port-less Host header. Otherwise "Host: www.ag-grid.com" would look like port 80 and fire the
# https-upgrade rule (gated on port 80) for every row, masking the behaviour under test. A
# same-server Location therefore comes back as http://localhost:${port}/... and the harness
# normalises it to a host-relative path.
ServerName localhost:${port}
UseCanonicalName On
PidFile "${work}/httpd.pid"
ErrorLog "${work}/logs/error.log"
LogLevel ${process.env.REWRITE_TRACE ? 'warn rewrite:trace3' : 'warn'}
LogFormat "%h \\"%r\\" %>s host=%{Host}i accept=\\"%{Accept}i\\"" harness
CustomLog "${work}/logs/access.log" harness
DocumentRoot "${htdocs}"
DirectoryIndex index.html
<Directory />
    AllowOverride None
    Require all denied
</Directory>
<Directory "${htdocs}">
    Options FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
`;
    const path = join(work, 'httpd.conf');
    writeFileSync(path, conf);
    return path;
}

export function startHttpd(httpd, confPath) {
    // -t first: a malformed generated .htaccess is not caught here (it is read per request), but a
    // broken httpd.conf is, with a clear message.
    execFileSync(httpd, ['-f', confPath, '-t'], { stdio: 'pipe' });
    execFileSync(httpd, ['-f', confPath, '-k', 'start'], { stdio: 'inherit' });
}

export function stopHttpd(httpd, confPath) {
    try {
        execFileSync(httpd, ['-f', confPath, '-k', 'stop'], { stdio: 'ignore' });
    } catch {
        // already stopped
    }
}
