import { AgChart, AgChartOptions } from "ag-charts-community"
import { getData } from "./data"

const options: AgChartOptions = {
  container: document.getElementById("myChart"),
  title: {
    text: "Apple's revenue by product category",
  },
  subtitle: {
    text: "in billion U.S. dollars",
  },
  data: getData(),
  series: [
    {
      type: "column",
      xKey: "year",
      yKey: "NAQ1",
      yName: "Q1",
      legendItemName: "Q1",
      stackGroup: "na",
      fill: "#f3622d",
    },
    {
      type: "column",
      xKey: "year",
      yKey: "NAQ2",
      yName: "Q2",
      legendItemName: "Q2",
      stackGroup: "na",
      fill: "#fba71b",
    },
    {
      type: "column",
      xKey: "year",
      yKey: "NAQ3",
      yName: "Q3",
      legendItemName: "Q3",
      stackGroup: "na",
      fill: "#57b757",
    },
    {
      type: "column",
      xKey: "year",
      yKey: "NAQ4",
      yName: "Q4",
      legendItemName: "Q4",
      stackGroup: "na",
      fill: "#41a9c9",
    },
    {
      type: "column",
      xKey: "year",
      yKey: "EURQ1",
      legendItemName: "Q1",
      stackGroup: "eur",
      showInLegend: false,
    },
    {
      type: "column",
      xKey: "year",
      yKey: "EURQ2",
      legendItemName: "Q2",
      stackGroup: "eur",
      showInLegend: false,
    },
    {
      type: "column",
      xKey: "year",
      yKey: "EURQ3",
      legendItemName: "Q3",
      stackGroup: "eur",
      showInLegend: false,
    },
    {
      type: "column",
      xKey: "year",
      yKey: "EURQ4",
      legendItemName: "Q4",
      stackGroup: "eur",
      showInLegend: false,
    },
    {
      type: "column",
      xKey: "year",
      yKey: "ASIAQ1",
      legendItemName: "Q1",
      stackGroup: "asia",
      showInLegend: false,
    },
    {
      type: "column",
      xKey: "year",
      yKey: "ASIAQ2",
      legendItemName: "Q2",
      stackGroup: "asia",
      showInLegend: false,
    },
    {
      type: "column",
      xKey: "year",
      yKey: "ASIAQ3",
      legendItemName: "Q3",
      stackGroup: "asia",
      showInLegend: false,
    },
    {
      type: "column",
      xKey: "year",
      yKey: "ASIAQ4",
      legendItemName: "Q4",
      stackGroup: "asia",
      showInLegend: false,
    },
  ],
}

AgChart.create(options)
