// Source: https://www.gov.uk/government/statistical-data-sets/banana-prices
export function getData(): any[] {
    return [
        {
            week: 1,
            belize: null,
            cameroon: null,
            columbia: null,
            costaRica: null,
            dominicanRepublic: null,
            ecuador: null,
            ghana: null,
            honduras: null,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: null,
            windwardIsles: null,
            guatemala: null,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 2,
            belize: null,
            cameroon: null,
            columbia: 0.66,
            costaRica: 0.78,
            dominicanRepublic: 0.58,
            ecuador: 0.64,
            ghana: null,
            honduras: null,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.64,
            windwardIsles: null,
            guatemala: null,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 3,
            belize: 0.58,
            cameroon: null,
            columbia: 0.68,
            costaRica: 0.7,
            dominicanRepublic: 0.69,
            ecuador: 0.82,
            ghana: null,
            honduras: null,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.64,
            windwardIsles: null,
            guatemala: null,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 4,
            belize: null,
            cameroon: null,
            columbia: 0.71,
            costaRica: 0.7,
            dominicanRepublic: null,
            ecuador: 0.82,
            ghana: null,
            honduras: 0.78,
            ivoryCoast: null,
            jamaica: null,
            mexico: 0.63,
            panama: 0.71,
            windwardIsles: null,
            guatemala: null,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 5,
            belize: null,
            cameroon: null,
            columbia: null,
            costaRica: 0.73,
            dominicanRepublic: 0.79,
            ecuador: null,
            ghana: null,
            honduras: null,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.74,
            windwardIsles: null,
            guatemala: null,
            nicaragua: 0.74,
            brazil: null,
        },
        {
            week: 6,
            belize: null,
            cameroon: null,
            columbia: 0.79,
            costaRica: 0.78,
            dominicanRepublic: null,
            ecuador: 0.71,
            ghana: null,
            honduras: 0.75,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.79,
            windwardIsles: null,
            guatemala: 0.74,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 7,
            belize: null,
            cameroon: null,
            columbia: null,
            costaRica: 0.78,
            dominicanRepublic: 0.65,
            ecuador: 0.76,
            ghana: null,
            honduras: 0.76,
            ivoryCoast: null,
            jamaica: null,
            mexico: 0.79,
            panama: 0.81,
            windwardIsles: null,
            guatemala: 0.74,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 8,
            belize: null,
            cameroon: null,
            columbia: 0.79,
            costaRica: 0.83,
            dominicanRepublic: 0.36,
            ecuador: 0.85,
            ghana: null,
            honduras: null,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: null,
            windwardIsles: 0.44,
            guatemala: 0.75,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 9,
            belize: null,
            cameroon: null,
            columbia: null,
            costaRica: 0.84,
            dominicanRepublic: null,
            ecuador: null,
            ghana: null,
            honduras: null,
            ivoryCoast: 0.4,
            jamaica: null,
            mexico: null,
            panama: 0.79,
            windwardIsles: 0.33,
            guatemala: 0.71,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 10,
            belize: 0.79,
            cameroon: null,
            columbia: null,
            costaRica: 0.8,
            dominicanRepublic: null,
            ecuador: 0.74,
            ghana: null,
            honduras: 0.73,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.85,
            windwardIsles: null,
            guatemala: 0.77,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 11,
            belize: 0.85,
            cameroon: null,
            columbia: null,
            costaRica: 0.84,
            dominicanRepublic: null,
            ecuador: 0.74,
            ghana: null,
            honduras: 0.8,
            ivoryCoast: 0.85,
            jamaica: null,
            mexico: null,
            panama: 0.86,
            windwardIsles: null,
            guatemala: 0.85,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 12,
            belize: 0.88,
            cameroon: null,
            columbia: null,
            costaRica: 0.9,
            dominicanRepublic: null,
            ecuador: 0.9,
            ghana: null,
            honduras: 0.93,
            ivoryCoast: 0.81,
            jamaica: null,
            mexico: null,
            panama: 0.97,
            windwardIsles: null,
            guatemala: 0.88,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 13,
            belize: 0.8,
            cameroon: null,
            columbia: null,
            costaRica: 0.83,
            dominicanRepublic: null,
            ecuador: 0.83,
            ghana: null,
            honduras: 0.82,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.9,
            windwardIsles: null,
            guatemala: 0.76,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 14,
            belize: 0.83,
            cameroon: null,
            columbia: 0.61,
            costaRica: 0.83,
            dominicanRepublic: null,
            ecuador: null,
            ghana: null,
            honduras: null,
            ivoryCoast: 0.55,
            jamaica: null,
            mexico: null,
            panama: null,
            windwardIsles: 0.29,
            guatemala: 0.82,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 15,
            belize: 0.74,
            cameroon: null,
            columbia: 0.78,
            costaRica: 0.8,
            dominicanRepublic: 0.77,
            ecuador: 0.74,
            ghana: null,
            honduras: null,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: null,
            windwardIsles: 0.35,
            guatemala: 0.75,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 16,
            belize: 0.79,
            cameroon: null,
            columbia: 0.75,
            costaRica: 0.71,
            dominicanRepublic: null,
            ecuador: 0.8,
            ghana: null,
            honduras: 0.71,
            ivoryCoast: null,
            jamaica: 0.66,
            mexico: null,
            panama: 0.85,
            windwardIsles: null,
            guatemala: 0.79,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 17,
            belize: 0.83,
            cameroon: null,
            columbia: 0.71,
            costaRica: 0.84,
            dominicanRepublic: null,
            ecuador: 0.8,
            ghana: null,
            honduras: 0.75,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.84,
            windwardIsles: null,
            guatemala: 0.79,
            nicaragua: null,
            brazil: 0.79,
        },
        {
            week: 18,
            belize: 0.83,
            cameroon: null,
            columbia: null,
            costaRica: 0.92,
            dominicanRepublic: null,
            ecuador: 0.8,
            ghana: null,
            honduras: 0.8,
            ivoryCoast: 0.72,
            jamaica: null,
            mexico: null,
            panama: 0.78,
            windwardIsles: null,
            guatemala: 0.83,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 19,
            belize: 0.77,
            cameroon: null,
            columbia: null,
            costaRica: 0.82,
            dominicanRepublic: null,
            ecuador: 0.78,
            ghana: null,
            honduras: 0.86,
            ivoryCoast: 0.77,
            jamaica: null,
            mexico: null,
            panama: 0.86,
            windwardIsles: null,
            guatemala: 0.77,
            nicaragua: null,
            brazil: 0.74,
        },
        {
            week: 20,
            belize: 0.74,
            cameroon: null,
            columbia: 0.76,
            costaRica: 0.82,
            dominicanRepublic: null,
            ecuador: 0.79,
            ghana: null,
            honduras: 0.8,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.84,
            windwardIsles: null,
            guatemala: null,
            nicaragua: null,
            brazil: 0.74,
        },
        {
            week: 21,
            belize: 0.74,
            cameroon: null,
            columbia: null,
            costaRica: 0.82,
            dominicanRepublic: null,
            ecuador: 0.78,
            ghana: null,
            honduras: null,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.82,
            windwardIsles: 0.31,
            guatemala: 0.74,
            nicaragua: null,
            brazil: 0.74,
        },
        {
            week: 22,
            belize: 0.74,
            cameroon: null,
            columbia: 0.62,
            costaRica: 0.85,
            dominicanRepublic: null,
            ecuador: 0.77,
            ghana: null,
            honduras: null,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.82,
            windwardIsles: 0.29,
            guatemala: 0.71,
            nicaragua: null,
            brazil: 0.68,
        },
        {
            week: 23,
            belize: 0.68,
            cameroon: null,
            columbia: 0.78,
            costaRica: 0.78,
            dominicanRepublic: null,
            ecuador: 0.78,
            ghana: null,
            honduras: 0.8,
            ivoryCoast: 0.64,
            jamaica: null,
            mexico: null,
            panama: 0.85,
            windwardIsles: null,
            guatemala: 0.71,
            nicaragua: null,
            brazil: 0.68,
        },
        {
            week: 24,
            belize: null,
            cameroon: null,
            columbia: 0.45,
            costaRica: 0.81,
            dominicanRepublic: null,
            ecuador: 0.77,
            ghana: null,
            honduras: 0.68,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: null,
            windwardIsles: null,
            guatemala: 0.74,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 25,
            belize: null,
            cameroon: null,
            columbia: 0.68,
            costaRica: 0.8,
            dominicanRepublic: null,
            ecuador: 0.55,
            ghana: null,
            honduras: 0.68,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: null,
            windwardIsles: 0.29,
            guatemala: 0.7,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 26,
            belize: null,
            cameroon: null,
            columbia: 0.71,
            costaRica: 0.81,
            dominicanRepublic: null,
            ecuador: null,
            ghana: null,
            honduras: 0.72,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.89,
            windwardIsles: null,
            guatemala: 0.61,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 27,
            belize: null,
            cameroon: null,
            columbia: 0.71,
            costaRica: 0.74,
            dominicanRepublic: null,
            ecuador: null,
            ghana: 0.53,
            honduras: 0.69,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.81,
            windwardIsles: null,
            guatemala: 0.61,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 28,
            belize: null,
            cameroon: null,
            columbia: 0.68,
            costaRica: 0.81,
            dominicanRepublic: 0.62,
            ecuador: 0.29,
            ghana: null,
            honduras: 0.63,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: null,
            windwardIsles: 0.29,
            guatemala: 0.72,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 29,
            belize: null,
            cameroon: null,
            columbia: 0.66,
            costaRica: 0.71,
            dominicanRepublic: null,
            ecuador: null,
            ghana: null,
            honduras: 0.63,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.73,
            windwardIsles: null,
            guatemala: null,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 30,
            belize: null,
            cameroon: null,
            columbia: 0.64,
            costaRica: 0.76,
            dominicanRepublic: null,
            ecuador: 0.55,
            ghana: null,
            honduras: 0.66,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.61,
            windwardIsles: null,
            guatemala: null,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 31,
            belize: null,
            cameroon: 0.68,
            columbia: 0.74,
            costaRica: 0.78,
            dominicanRepublic: 0.73,
            ecuador: null,
            ghana: null,
            honduras: 0.68,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: null,
            windwardIsles: 0.25,
            guatemala: 0.77,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 32,
            belize: null,
            cameroon: null,
            columbia: 0.76,
            costaRica: 0.75,
            dominicanRepublic: 0.51,
            ecuador: 0.86,
            ghana: null,
            honduras: 0.66,
            ivoryCoast: 0.57,
            jamaica: null,
            mexico: null,
            panama: 0.68,
            windwardIsles: null,
            guatemala: 0.79,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 33,
            belize: null,
            cameroon: null,
            columbia: 0.68,
            costaRica: 0.7,
            dominicanRepublic: null,
            ecuador: 0.75,
            ghana: null,
            honduras: 0.66,
            ivoryCoast: 0.66,
            jamaica: null,
            mexico: null,
            panama: 0.73,
            windwardIsles: null,
            guatemala: null,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 34,
            belize: null,
            cameroon: null,
            columbia: 0.86,
            costaRica: 0.78,
            dominicanRepublic: 0.55,
            ecuador: 0.74,
            ghana: null,
            honduras: null,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: null,
            windwardIsles: null,
            guatemala: 0.77,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 35,
            belize: null,
            cameroon: null,
            columbia: 0.68,
            costaRica: 0.78,
            dominicanRepublic: null,
            ecuador: 0.63,
            ghana: null,
            honduras: null,
            ivoryCoast: 0.4,
            jamaica: null,
            mexico: null,
            panama: 0.68,
            windwardIsles: null,
            guatemala: null,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 36,
            belize: null,
            cameroon: null,
            columbia: null,
            costaRica: 0.75,
            dominicanRepublic: null,
            ecuador: 0.76,
            ghana: null,
            honduras: null,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.76,
            windwardIsles: null,
            guatemala: 0.75,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 37,
            belize: null,
            cameroon: 0.56,
            columbia: 0.69,
            costaRica: 0.74,
            dominicanRepublic: 0.46,
            ecuador: 0.86,
            ghana: null,
            honduras: 0.54,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.63,
            windwardIsles: null,
            guatemala: 0.77,
            nicaragua: 0.44,
            brazil: null,
        },
        {
            week: 38,
            belize: null,
            cameroon: null,
            columbia: 0.7,
            costaRica: 0.83,
            dominicanRepublic: null,
            ecuador: null,
            ghana: null,
            honduras: 0.41,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.78,
            windwardIsles: null,
            guatemala: 0.73,
            nicaragua: 0.31,
            brazil: null,
        },
        {
            week: 39,
            belize: null,
            cameroon: null,
            columbia: 0.66,
            costaRica: 0.79,
            dominicanRepublic: null,
            ecuador: 0.5,
            ghana: null,
            honduras: 0.64,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.84,
            windwardIsles: null,
            guatemala: null,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 40,
            belize: null,
            cameroon: null,
            columbia: 0.66,
            costaRica: 0.79,
            dominicanRepublic: null,
            ecuador: 0.88,
            ghana: null,
            honduras: 0.64,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.67,
            windwardIsles: null,
            guatemala: null,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 41,
            belize: null,
            cameroon: null,
            columbia: 0.78,
            costaRica: 0.78,
            dominicanRepublic: null,
            ecuador: null,
            ghana: null,
            honduras: 0.64,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.87,
            windwardIsles: null,
            guatemala: null,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 42,
            belize: null,
            cameroon: null,
            columbia: 0.74,
            costaRica: 0.75,
            dominicanRepublic: null,
            ecuador: 0.69,
            ghana: null,
            honduras: 0.66,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.86,
            windwardIsles: null,
            guatemala: null,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 43,
            belize: null,
            cameroon: null,
            columbia: 0.74,
            costaRica: 0.75,
            dominicanRepublic: null,
            ecuador: 0.69,
            ghana: null,
            honduras: 0.68,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.58,
            windwardIsles: 0.39,
            guatemala: null,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 44,
            belize: 0.85,
            cameroon: null,
            columbia: 0.74,
            costaRica: 0.81,
            dominicanRepublic: 0.68,
            ecuador: null,
            ghana: null,
            honduras: 0.66,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.68,
            windwardIsles: 0.36,
            guatemala: null,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 45,
            belize: null,
            cameroon: null,
            columbia: 0.74,
            costaRica: 0.85,
            dominicanRepublic: 0.68,
            ecuador: 0.79,
            ghana: null,
            honduras: 0.67,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.68,
            windwardIsles: 0.39,
            guatemala: 0.79,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 46,
            belize: 0.88,
            cameroon: null,
            columbia: 0.74,
            costaRica: 0.85,
            dominicanRepublic: 0.68,
            ecuador: 0.79,
            ghana: null,
            honduras: 0.62,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.58,
            windwardIsles: 0.29,
            guatemala: null,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 47,
            belize: 0.86,
            cameroon: null,
            columbia: 0.74,
            costaRica: 0.82,
            dominicanRepublic: 0.31,
            ecuador: 0.44,
            ghana: null,
            honduras: 0.7,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.74,
            windwardIsles: null,
            guatemala: null,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 48,
            belize: null,
            cameroon: 0.54,
            columbia: 0.74,
            costaRica: 0.71,
            dominicanRepublic: null,
            ecuador: 0.64,
            ghana: null,
            honduras: 0.66,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.68,
            windwardIsles: null,
            guatemala: null,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 49,
            belize: null,
            cameroon: null,
            columbia: 0.74,
            costaRica: 0.75,
            dominicanRepublic: null,
            ecuador: 0.68,
            ghana: null,
            honduras: 0.66,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.72,
            windwardIsles: null,
            guatemala: null,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 50,
            belize: null,
            cameroon: null,
            columbia: 0.68,
            costaRica: 0.54,
            dominicanRepublic: 0.58,
            ecuador: 0.65,
            ghana: null,
            honduras: 0.66,
            ivoryCoast: null,
            jamaica: null,
            mexico: 0.46,
            panama: 0.69,
            windwardIsles: null,
            guatemala: null,
            nicaragua: null,
            brazil: null,
        },
        {
            week: 51,
            belize: null,
            cameroon: null,
            columbia: 0.61,
            costaRica: 0.71,
            dominicanRepublic: null,
            ecuador: 0.51,
            ghana: null,
            honduras: 0.64,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: 0.71,
            windwardIsles: 0.25,
            guatemala: 0.73,
            nicaragua: null,
            brazil: 0.85,
        },
        {
            week: 52,
            belize: null,
            cameroon: null,
            columbia: null,
            costaRica: null,
            dominicanRepublic: null,
            ecuador: null,
            ghana: null,
            honduras: null,
            ivoryCoast: null,
            jamaica: null,
            mexico: null,
            panama: null,
            windwardIsles: null,
            guatemala: null,
            nicaragua: null,
            brazil: null,
        },
    ];
}