import type { GridOptions } from './entities/gridOptions';
import type { AgGridCommon } from './interfaces/iCommon';

type GridOptionKey = keyof GridOptions;

type GetKeys<T, U> = {
    [K in keyof T]: U extends T[K] ? K : T[K] extends U | null | undefined ? K : never; //Reverse match for string literal types
}[keyof T];

/**
 *  Get the GridProperties that are of type `any`.
 *  Works by finding the properties that can extend a non existing string.
 *  This will only be the properties of type `any`.
 */
export type AnyGridOptions = {
    [K in keyof GridOptions]: GridOptions[K] extends 'NO_MATCH' ? K : never;
}[keyof GridOptions];

/**
 * Get all the GridOptions properties of the provided type.
 * Will also include `any` properties.
 */
type KeysLike<U> = Exclude<GetKeys<GridOptions, U>, undefined>;
/**
 * Get all the GridOption properties that strictly contain the provided type.
 * Does not include `any` properties.
 */
type KeysOfType<U> = Exclude<GetKeys<GridOptions, U>, AnyGridOptions>;
type CallbackKeys = KeysOfType<(any: AgGridCommon<any, any>) => any>;
/** All function properties excluding those explicity match the common callback interface. */
// eslint-disable-next-line @typescript-eslint/ban-types
type FunctionKeys = Exclude<KeysLike<Function>, CallbackKeys>;

export const INITIAL_GRID_OPTION_KEYS = {
    enableBrowserTooltips: true,
    tooltipTrigger: true,
    tooltipMouseTrack: true,
    tooltipShowMode: true,
    tooltipInteraction: true,
    defaultColGroupDef: true,
    suppressAutoSize: true,
    skipHeaderOnAutoSize: true,
    autoSizeStrategy: true,
    components: true,
    stopEditingWhenCellsLoseFocus: true,
    undoRedoCellEditing: true,
    undoRedoCellEditingLimit: true,
    excelStyles: true,
    cacheQuickFilter: true,
    customChartThemes: true,
    chartThemeOverrides: true,
    chartToolPanelsDef: true,
    loadingCellRendererSelector: true,
    localeText: true,
    keepDetailRows: true,
    keepDetailRowsCount: true,
    detailRowHeight: true,
    detailRowAutoHeight: true,
    tabIndex: true,
    valueCache: true,
    valueCacheNeverExpires: true,
    enableCellExpressions: true,
    suppressTouch: true,
    suppressBrowserResizeObserver: true,
    suppressPropertyNamesCheck: true,
    debug: true,
    dragAndDropImageComponent: true,
    loadingOverlayComponent: true,
    suppressLoadingOverlay: true,
    noRowsOverlayComponent: true,
    paginationPageSizeSelector: true,
    paginateChildRows: true,
    pivotPanelShow: true,
    pivotSuppressAutoColumn: true,
    suppressExpandablePivotGroups: true,
    aggFuncs: true,
    allowShowChangeAfterFilter: true,
    ensureDomOrder: true,
    enableRtl: true,
    suppressColumnVirtualisation: true,
    suppressMaxRenderedRowRestriction: true,
    suppressRowVirtualisation: true,
    rowDragText: true,
    groupLockGroupColumns: true,
    suppressGroupRowsSticky: true,
    rowModelType: true,
    cacheOverflowSize: true,
    infiniteInitialRowCount: true,
    serverSideInitialRowCount: true,
    maxBlocksInCache: true,
    maxConcurrentDatasourceRequests: true,
    blockLoadDebounceMillis: true,
    serverSideOnlyRefreshFilteredGroups: true,
    serverSidePivotResultFieldSeparator: true,
    viewportRowModelPageSize: true,
    viewportRowModelBufferSize: true,
    debounceVerticalScrollbar: true,
    suppressAnimationFrame: true,
    suppressPreventDefaultOnMouseWheel: true,
    scrollbarWidth: true,
    icons: true,
    suppressRowTransform: true,
    gridId: true,
    enableGroupEdit: true,
    initialState: true,
    processUnpinnedColumns: true,
    createChartContainer: true,
    getLocaleText: true,
    getRowId: true,
    reactiveCustomComponents: true,
    columnMenu: true,
    suppressSetFilterByDefault: true,
};

type InitialGridOptionKey = keyof typeof INITIAL_GRID_OPTION_KEYS;

export type ManagedGridOptionKey = Exclude<GridOptionKey, InitialGridOptionKey>;

export type ManagedGridOptions<TData = any> = {
    [K in ManagedGridOptionKey]?: GridOptions<TData>[K];
};

/**
 * These keys are used for validating properties supplied on a gridOptions object, and for code generation.
 * If you change the properties on the gridOptions interface, you *must* update this file as well to be consistent.
 */
export class PropertyKeys {
    public static STRING_PROPERTIES: KeysOfType<string>[] = [
        'overlayLoadingTemplate',
        'overlayNoRowsTemplate',
        'gridId',
        'quickFilterText',
        'rowModelType',
        'editType',
        'domLayout',
        'clipboardDelimiter',
        'rowGroupPanelShow',
        'multiSortKey',
        'pivotColumnGroupTotals',
        'pivotRowTotals',
        'pivotPanelShow',
        'fillHandleDirection',
        'groupDisplayType',
        'treeDataDisplayType',
        'colResizeDefault',
        'tooltipTrigger',
        'serverSidePivotResultFieldSeparator',
        'columnMenu',
        'tooltipShowMode',
        'grandTotalRow',
        'treeDataChildrenField',
    ];

    public static OBJECT_PROPERTIES: KeysLike<object | HTMLElement>[] = [
        'components',
        'rowStyle',
        'context',
        'autoGroupColumnDef',
        'localeText',
        'icons',
        'datasource',
        'dragAndDropImageComponentParams',
        'serverSideDatasource',
        'viewportDatasource',
        'groupRowRendererParams',
        'aggFuncs',
        'fullWidthCellRendererParams',
        'defaultColGroupDef',
        'defaultColDef',
        'defaultCsvExportParams',
        'defaultExcelExportParams',
        'columnTypes',
        'rowClassRules',
        'detailCellRendererParams',
        'loadingCellRendererParams',
        'loadingOverlayComponentParams',
        'noRowsOverlayComponentParams',
        'popupParent',
        'statusBar',
        'sideBar',
        'theme',
        'chartThemeOverrides',
        'customChartThemes',
        'chartToolPanelsDef',
        'dataTypeDefinitions',
        'advancedFilterParent',
        'advancedFilterBuilderParams',
        'initialState',
        'autoSizeStrategy',
        'cellSelection',
        'selectionColumnDef',
    ];

    public static ARRAY_PROPERTIES: KeysOfType<any[]>[] = [
        'sortingOrder',
        'alignedGrids',
        'rowData',
        'columnDefs',
        'excelStyles',
        'pinnedTopRowData',
        'pinnedBottomRowData',
        'chartThemes',
        'rowClass',
        'paginationPageSizeSelector',
    ];

    // These properties are coerced at runtime, do not do union types
    public static NUMBER_PROPERTIES: KeysOfType<number>[] = [
        'rowHeight',
        'detailRowHeight',
        'rowBuffer',
        'headerHeight',
        'groupHeaderHeight',
        'groupLockGroupColumns',
        'floatingFiltersHeight',
        'pivotHeaderHeight',
        'pivotGroupHeaderHeight',
        'groupDefaultExpanded',
        'pivotDefaultExpanded',
        'viewportRowModelPageSize',
        'viewportRowModelBufferSize',
        'autoSizePadding',
        'maxBlocksInCache',
        'maxConcurrentDatasourceRequests',
        'tooltipShowDelay',
        'tooltipHideDelay',
        'cacheOverflowSize',
        'paginationPageSize',
        'cacheBlockSize',
        'infiniteInitialRowCount',
        'serverSideInitialRowCount',
        'scrollbarWidth',
        'asyncTransactionWaitMillis',
        'blockLoadDebounceMillis',
        'keepDetailRowsCount',
        'undoRedoCellEditingLimit',
        'cellFlashDuration',
        'cellFadeDuration',
        'tabIndex',
        'pivotMaxGeneratedColumns',
    ];

    // These properties are coerced at runtime, do not do union types
    public static BOOLEAN_PROPERTIES: KeysOfType<boolean>[] = [
        'suppressMakeColumnVisibleAfterUnGroup',
        'suppressRowClickSelection',
        'suppressCellFocus',
        'suppressHeaderFocus',
        'suppressHorizontalScroll',
        'groupSelectsChildren',
        'alwaysShowHorizontalScroll',
        'alwaysShowVerticalScroll',
        'debug',
        'enableBrowserTooltips',
        'enableCellExpressions',
        'groupSuppressBlankHeader',
        'suppressMenuHide',
        'suppressRowDeselection',
        'unSortIcon',
        'suppressMultiSort',
        'alwaysMultiSort',
        'singleClickEdit',
        'suppressLoadingOverlay',
        'suppressNoRowsOverlay',
        'suppressAutoSize',
        'skipHeaderOnAutoSize',
        'suppressColumnMoveAnimation',
        'suppressMoveWhenColumnDragging',
        'suppressMovableColumns',
        'suppressFieldDotNotation',
        'enableRangeSelection',
        'enableRangeHandle',
        'enableFillHandle',
        'suppressClearOnFillReduction',
        'deltaSort',
        'suppressTouch',
        'allowContextMenuWithControlKey',
        'suppressContextMenu',
        'suppressDragLeaveHidesColumns',
        'suppressRowGroupHidesColumns',
        'suppressMiddleClickScrolls',
        'suppressPreventDefaultOnMouseWheel',
        'suppressCopyRowsToClipboard',
        'copyHeadersToClipboard',
        'copyGroupHeadersToClipboard',
        'pivotMode',
        'suppressAggFuncInHeader',
        'suppressColumnVirtualisation',
        'alwaysAggregateAtRootLevel',
        'suppressFocusAfterRefresh',
        'functionsReadOnly',
        'animateRows',
        'groupSelectsFiltered',
        'groupRemoveSingleChildren',
        'groupRemoveLowestSingleChildren',
        'enableRtl',
        'suppressClickEdit',
        'rowDragEntireRow',
        'rowDragManaged',
        'suppressRowDrag',
        'suppressMoveWhenRowDragging',
        'rowDragMultiRow',
        'enableGroupEdit',
        'embedFullWidthRows',
        'suppressPaginationPanel',
        'groupHideOpenParents',
        'groupAllowUnbalanced',
        'pagination',
        'paginationAutoPageSize',
        'suppressScrollOnNewData',
        'suppressScrollWhenPopupsAreOpen',
        'purgeClosedRowNodes',
        'cacheQuickFilter',
        'includeHiddenColumnsInQuickFilter',
        'ensureDomOrder',
        'accentedSort',
        'suppressChangeDetection',
        'valueCache',
        'valueCacheNeverExpires',
        'aggregateOnlyChangedColumns',
        'suppressAnimationFrame',
        'suppressExcelExport',
        'suppressCsvExport',
        'includeHiddenColumnsInAdvancedFilter',
        'suppressMultiRangeSelection',
        'enterNavigatesVerticallyAfterEdit',
        'enterNavigatesVertically',
        'suppressPropertyNamesCheck',
        'rowMultiSelectWithClick',
        'suppressRowHoverHighlight',
        'suppressRowTransform',
        'suppressClipboardPaste',
        'suppressLastEmptyLineOnPaste',
        'enableCharts',
        'suppressMaintainUnsortedOrder',
        'enableCellTextSelection',
        'suppressBrowserResizeObserver',
        'suppressMaxRenderedRowRestriction',
        'excludeChildrenWhenTreeDataFiltering',
        'tooltipMouseTrack',
        'tooltipInteraction',
        'keepDetailRows',
        'paginateChildRows',
        'preventDefaultOnContextMenu',
        'undoRedoCellEditing',
        'allowDragFromColumnsToolPanel',
        'pivotSuppressAutoColumn',
        'suppressExpandablePivotGroups',
        'debounceVerticalScrollbar',
        'detailRowAutoHeight',
        'serverSideSortAllLevels',
        'serverSideEnableClientSideSort',
        'serverSideOnlyRefreshFilteredGroups',
        'suppressAggFilteredOnly',
        'showOpenedGroup',
        'suppressClipboardApi',
        'suppressModelUpdateAfterUpdateTransaction',
        'stopEditingWhenCellsLoseFocus',
        'groupMaintainOrder',
        'columnHoverHighlight',
        'readOnlyEdit',
        'suppressRowVirtualisation',
        'enableCellEditingOnBackspace',
        'resetRowDataOnUpdate',
        'removePivotHeaderRowWhenSingleValueColumn',
        'suppressCopySingleCellRanges',
        'suppressGroupRowsSticky',
        'suppressCutToClipboard',
        'rowGroupPanelSuppressSort',
        'allowShowChangeAfterFilter',
        'enableAdvancedFilter',
        'masterDetail',
        'treeData',
        'reactiveCustomComponents',
        'applyQuickFilterBeforePivotOrAgg',
        'suppressServerSideFullWidthLoadingRow',
        'suppressAdvancedFilterEval',
        'loading',
        'maintainColumnOrder',
        'enableStrictPivotColumnOrder',
        'suppressSetFilterByDefault',
    ];

    // If property does not fit above, i.e union that should not be coerced.
    public static OTHER_PROPERTIES: GridOptionKey[] = [
        'suppressStickyTotalRow',
        // needs avoid coercion to boolean so that we can warn if it's unset
        'loadThemeGoogleFonts',
        'rowSelection',
        'groupHideParentOfSingleChild',
        'suppressGroupChangesColumnVisibility',
    ];

    public static FUNCTION_PROPERTIES: (CallbackKeys | FunctionKeys)[] = [
        'doesExternalFilterPass',
        'processPivotResultColDef',
        'processPivotResultColGroupDef',
        'getBusinessKeyForNode',
        'isRowSelectable',
        'rowDragText',
        'groupRowRenderer',
        'dragAndDropImageComponent',
        'fullWidthCellRenderer',
        'loadingCellRenderer',
        'loadingOverlayComponent',
        'noRowsOverlayComponent',
        'detailCellRenderer',
        'quickFilterParser',
        'quickFilterMatcher',
        'getLocaleText',
        'isExternalFilterPresent',
        'getRowHeight',
        'getRowClass',
        'getRowStyle',
        'getContextMenuItems',
        'getMainMenuItems',
        'processRowPostCreate',
        'processCellForClipboard',
        'getGroupRowAgg',
        'isFullWidthRow',
        'sendToClipboard',
        'focusGridInnerElement',
        'navigateToNextHeader',
        'tabToNextHeader',
        'navigateToNextCell',
        'tabToNextCell',
        'processCellFromClipboard',
        'getDocument',
        'postProcessPopup',
        'getChildCount',
        'getDataPath',
        'isRowMaster',
        'postSortRows',
        'processHeaderForClipboard',
        'processUnpinnedColumns',
        'processGroupHeaderForClipboard',
        'paginationNumberFormatter',
        'processDataFromClipboard',
        'getServerSideGroupKey',
        'isServerSideGroup',
        'createChartContainer',
        'getChartToolbarItems',
        'fillOperation',
        'isApplyServerSideTransaction',
        'getServerSideGroupLevelParams',
        'isServerSideGroupOpenByDefault',
        'isGroupOpenByDefault',
        'initialGroupOrderComparator',
        'loadingCellRendererSelector',
        'getRowId',
        'groupAggFiltering',
        'chartMenuItems',
        'groupTotalRow',
    ];

    public static ALL_PROPERTIES: GridOptionKey[] = [
        ...PropertyKeys.ARRAY_PROPERTIES,
        ...PropertyKeys.OBJECT_PROPERTIES,
        ...PropertyKeys.STRING_PROPERTIES,
        ...PropertyKeys.NUMBER_PROPERTIES,
        ...PropertyKeys.FUNCTION_PROPERTIES,
        ...PropertyKeys.BOOLEAN_PROPERTIES,
        ...PropertyKeys.OTHER_PROPERTIES,
    ];
}
