export function getData(): any[] {
    return [
        {
            athlete: 'Matt Grevers',
            age: 23,
            country: 'United States',
            year: 2008,
            date: '24/08/2008',
            sport: 'Swimming',
            gold: 2,
            silver: 1,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Margaret Hoelzer',
            age: 25,
            country: 'United States',
            year: 2008,
            date: '24/08/2008',
            sport: 'Swimming',
            gold: 0,
            silver: 2,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Katie Hoff',
            age: 19,
            country: 'United States',
            year: 2008,
            date: '24/08/2008',
            sport: 'Swimming',
            gold: 0,
            silver: 1,
            bronze: 2,
            total: 3,
        },
        {
            athlete: 'Leisel Jones',
            age: 22,
            country: 'Australia',
            year: 2008,
            date: '24/08/2008',
            sport: 'Swimming',
            gold: 2,
            silver: 1,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Andrew Lauterstein',
            age: 21,
            country: 'Australia',
            year: 2008,
            date: '24/08/2008',
            sport: 'Swimming',
            gold: 0,
            silver: 1,
            bronze: 2,
            total: 3,
        },
        {
            athlete: 'Jason Lezak',
            age: 32,
            country: 'United States',
            year: 2008,
            date: '24/08/2008',
            sport: 'Swimming',
            gold: 2,
            silver: 0,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Pang Jiaying',
            age: 23,
            country: 'China',
            year: 2008,
            date: '24/08/2008',
            sport: 'Swimming',
            gold: 0,
            silver: 1,
            bronze: 2,
            total: 3,
        },
        {
            athlete: 'Aaron Peirsol',
            age: 25,
            country: 'United States',
            year: 2008,
            date: '24/08/2008',
            sport: 'Swimming',
            gold: 2,
            silver: 1,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Steph Rice',
            age: 20,
            country: 'Australia',
            year: 2008,
            date: '24/08/2008',
            sport: 'Swimming',
            gold: 3,
            silver: 0,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Jess Schipper',
            age: 21,
            country: 'Australia',
            year: 2008,
            date: '24/08/2008',
            sport: 'Swimming',
            gold: 1,
            silver: 0,
            bronze: 2,
            total: 3,
        },
        {
            athlete: 'Rebecca Soni',
            age: 21,
            country: 'United States',
            year: 2008,
            date: '24/08/2008',
            sport: 'Swimming',
            gold: 1,
            silver: 2,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Eamon Sullivan',
            age: 22,
            country: 'Australia',
            year: 2008,
            date: '24/08/2008',
            sport: 'Swimming',
            gold: 0,
            silver: 2,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Dara Torres',
            age: 41,
            country: 'United States',
            year: 2008,
            date: '24/08/2008',
            sport: 'Swimming',
            gold: 0,
            silver: 3,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Amanda Beard',
            age: 22,
            country: 'United States',
            year: 2004,
            date: '29/08/2004',
            sport: 'Swimming',
            gold: 1,
            silver: 2,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Antje Buschschulte',
            age: 25,
            country: 'Germany',
            year: 2004,
            date: '29/08/2004',
            sport: 'Swimming',
            gold: 0,
            silver: 0,
            bronze: 3,
            total: 3,
        },
        {
            athlete: 'Ian Crocker',
            age: 21,
            country: 'United States',
            year: 2004,
            date: '29/08/2004',
            sport: 'Swimming',
            gold: 1,
            silver: 1,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Grant Hackett',
            age: 24,
            country: 'Australia',
            year: 2004,
            date: '29/08/2004',
            sport: 'Swimming',
            gold: 1,
            silver: 2,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Brendan Hansen',
            age: 22,
            country: 'United States',
            year: 2004,
            date: '29/08/2004',
            sport: 'Swimming',
            gold: 1,
            silver: 1,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Jodie Henry',
            age: 20,
            country: 'Australia',
            year: 2004,
            date: '29/08/2004',
            sport: 'Swimming',
            gold: 3,
            silver: 0,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Leisel Jones',
            age: 18,
            country: 'Australia',
            year: 2004,
            date: '29/08/2004',
            sport: 'Swimming',
            gold: 1,
            silver: 1,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Laure Manaudou',
            age: 17,
            country: 'France',
            year: 2004,
            date: '29/08/2004',
            sport: 'Swimming',
            gold: 1,
            silver: 1,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Aaron Peirsol',
            age: 21,
            country: 'United States',
            year: 2004,
            date: '29/08/2004',
            sport: 'Swimming',
            gold: 3,
            silver: 0,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Kaitlin Sandeno',
            age: 21,
            country: 'United States',
            year: 2004,
            date: '29/08/2004',
            sport: 'Swimming',
            gold: 1,
            silver: 1,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Lenny Krayzelburg',
            age: 24,
            country: 'United States',
            year: 2000,
            date: '01/10/2000',
            sport: 'Swimming',
            gold: 3,
            silver: 0,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Petria Thomas',
            age: 25,
            country: 'Australia',
            year: 2000,
            date: '01/10/2000',
            sport: 'Swimming',
            gold: 0,
            silver: 2,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Matt Welsh',
            age: 23,
            country: 'Australia',
            year: 2000,
            date: '01/10/2000',
            sport: 'Swimming',
            gold: 0,
            silver: 2,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Lee Jeong-Su',
            age: 20,
            country: 'South Korea',
            year: 2010,
            date: '28/02/2010',
            sport: 'Short-Track Speed Skating',
            gold: 2,
            silver: 1,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Apolo Anton Ohno',
            age: 27,
            country: 'United States',
            year: 2010,
            date: '28/02/2010',
            sport: 'Short-Track Speed Skating',
            gold: 0,
            silver: 1,
            bronze: 2,
            total: 3,
        },
        {
            athlete: 'Wang Meng',
            age: 24,
            country: 'China',
            year: 2010,
            date: '28/02/2010',
            sport: 'Short-Track Speed Skating',
            gold: 3,
            silver: 0,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Jin Seon-Yu',
            age: 17,
            country: 'South Korea',
            year: 2006,
            date: '26/02/2006',
            sport: 'Short-Track Speed Skating',
            gold: 3,
            silver: 0,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Lee Ho-Seok',
            age: 19,
            country: 'South Korea',
            year: 2006,
            date: '26/02/2006',
            sport: 'Short-Track Speed Skating',
            gold: 1,
            silver: 2,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Apolo Anton Ohno',
            age: 23,
            country: 'United States',
            year: 2006,
            date: '26/02/2006',
            sport: 'Short-Track Speed Skating',
            gold: 1,
            silver: 0,
            bronze: 2,
            total: 3,
        },
        {
            athlete: 'Wang Meng',
            age: 20,
            country: 'China',
            year: 2006,
            date: '26/02/2006',
            sport: 'Short-Track Speed Skating',
            gold: 1,
            silver: 1,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Marc Gagnon',
            age: 26,
            country: 'Canada',
            year: 2002,
            date: '24/02/2002',
            sport: 'Short-Track Speed Skating',
            gold: 2,
            silver: 0,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Yang Yang (A)',
            age: 25,
            country: 'China',
            year: 2002,
            date: '24/02/2002',
            sport: 'Short-Track Speed Skating',
            gold: 2,
            silver: 1,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Stephanie Beckert',
            age: 21,
            country: 'Germany',
            year: 2010,
            date: '28/02/2010',
            sport: 'Speed Skating',
            gold: 1,
            silver: 2,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Chad Hedrick',
            age: 28,
            country: 'United States',
            year: 2006,
            date: '26/02/2006',
            sport: 'Speed Skating',
            gold: 1,
            silver: 1,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Sabine Völker',
            age: 28,
            country: 'Germany',
            year: 2002,
            date: '24/02/2002',
            sport: 'Speed Skating',
            gold: 0,
            silver: 2,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Johnny Spillane',
            age: 29,
            country: 'United States',
            year: 2010,
            date: '28/02/2010',
            sport: 'Nordic Combined',
            gold: 0,
            silver: 3,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Georg Hettich',
            age: 27,
            country: 'Germany',
            year: 2006,
            date: '26/02/2006',
            sport: 'Nordic Combined',
            gold: 1,
            silver: 1,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Aly Raisman',
            age: 18,
            country: 'United States',
            year: 2012,
            date: '12/08/2012',
            sport: 'Gymnastics',
            gold: 2,
            silver: 0,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Zou Kai',
            age: 24,
            country: 'China',
            year: 2012,
            date: '12/08/2012',
            sport: 'Gymnastics',
            gold: 2,
            silver: 0,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Cheng Fei',
            age: 20,
            country: 'China',
            year: 2008,
            date: '24/08/2008',
            sport: 'Gymnastics',
            gold: 1,
            silver: 0,
            bronze: 2,
            total: 3,
        },
        {
            athlete: 'Yang Wei',
            age: 28,
            country: 'China',
            year: 2008,
            date: '24/08/2008',
            sport: 'Gymnastics',
            gold: 2,
            silver: 1,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Yang Yilin',
            age: 15,
            country: 'China',
            year: 2008,
            date: '24/08/2008',
            sport: 'Gymnastics',
            gold: 1,
            silver: 0,
            bronze: 2,
            total: 3,
        },
        {
            athlete: 'Zou Kai',
            age: 20,
            country: 'China',
            year: 2008,
            date: '24/08/2008',
            sport: 'Gymnastics',
            gold: 3,
            silver: 0,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Paul Hamm',
            age: 21,
            country: 'United States',
            year: 2004,
            date: '29/08/2004',
            sport: 'Gymnastics',
            gold: 1,
            silver: 2,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Carly Patterson',
            age: 16,
            country: 'United States',
            year: 2004,
            date: '29/08/2004',
            sport: 'Gymnastics',
            gold: 1,
            silver: 2,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Svetlana Khorkina',
            age: 21,
            country: 'Russia',
            year: 2000,
            date: '01/10/2000',
            sport: 'Gymnastics',
            gold: 1,
            silver: 2,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Yekaterina Lobaznyuk',
            age: 17,
            country: 'Russia',
            year: 2000,
            date: '01/10/2000',
            sport: 'Gymnastics',
            gold: 0,
            silver: 2,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Yelena Zamolodchikova',
            age: 17,
            country: 'Russia',
            year: 2000,
            date: '01/10/2000',
            sport: 'Gymnastics',
            gold: 2,
            silver: 1,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Guo Shuang',
            age: 26,
            country: 'China',
            year: 2012,
            date: '12/08/2012',
            sport: 'Cycling',
            gold: 0,
            silver: 2,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Chris Hoy',
            age: 32,
            country: 'Great Britain',
            year: 2008,
            date: '24/08/2008',
            sport: 'Cycling',
            gold: 3,
            silver: 0,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Bradley Wiggins',
            age: 24,
            country: 'Great Britain',
            year: 2004,
            date: '29/08/2004',
            sport: 'Cycling',
            gold: 1,
            silver: 1,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Florian Rousseau',
            age: 26,
            country: 'France',
            year: 2000,
            date: '01/10/2000',
            sport: 'Cycling',
            gold: 2,
            silver: 1,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Yuliya Chepalova',
            age: 25,
            country: 'Russia',
            year: 2002,
            date: '24/02/2002',
            sport: 'Cross Country Skiing',
            gold: 1,
            silver: 1,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Magdalena Neuner',
            age: 23,
            country: 'Germany',
            year: 2010,
            date: '28/02/2010',
            sport: 'Biathlon',
            gold: 2,
            silver: 1,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Albina Akhatova',
            age: 29,
            country: 'Russia',
            year: 2006,
            date: '26/02/2006',
            sport: 'Biathlon',
            gold: 1,
            silver: 0,
            bronze: 2,
            total: 3,
        },
        {
            athlete: 'Sven Fischer',
            age: 34,
            country: 'Germany',
            year: 2006,
            date: '26/02/2006',
            sport: 'Biathlon',
            gold: 2,
            silver: 0,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Martina Glagow-Beck',
            age: 26,
            country: 'Germany',
            year: 2006,
            date: '26/02/2006',
            sport: 'Biathlon',
            gold: 0,
            silver: 3,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Michael Greis',
            age: 29,
            country: 'Germany',
            year: 2006,
            date: '26/02/2006',
            sport: 'Biathlon',
            gold: 3,
            silver: 0,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Kati Wilhelm',
            age: 29,
            country: 'Germany',
            year: 2006,
            date: '26/02/2006',
            sport: 'Biathlon',
            gold: 1,
            silver: 2,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Kati Wilhelm',
            age: 25,
            country: 'Germany',
            year: 2002,
            date: '24/02/2002',
            sport: 'Biathlon',
            gold: 2,
            silver: 1,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Allyson Felix',
            age: 26,
            country: 'United States',
            year: 2012,
            date: '12/08/2012',
            sport: 'Athletics',
            gold: 3,
            silver: 0,
            bronze: 0,
            total: 3,
        },
        {
            athlete: 'Carmelita Jeter',
            age: 32,
            country: 'United States',
            year: 2012,
            date: '12/08/2012',
            sport: 'Athletics',
            gold: 1,
            silver: 1,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Justin Gatlin',
            age: 22,
            country: 'United States',
            year: 2004,
            date: '29/08/2004',
            sport: 'Athletics',
            gold: 1,
            silver: 1,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Bode Miller',
            age: 32,
            country: 'United States',
            year: 2010,
            date: '28/02/2010',
            sport: 'Alpine Skiing',
            gold: 1,
            silver: 1,
            bronze: 1,
            total: 3,
        },
        {
            athlete: 'Ding Ning',
            age: 22,
            country: 'China',
            year: 2012,
            date: '12/08/2012',
            sport: 'Table Tennis',
            gold: 1,
            silver: 1,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Li Xiaoxia',
            age: 24,
            country: 'China',
            year: 2012,
            date: '12/08/2012',
            sport: 'Table Tennis',
            gold: 2,
            silver: 0,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Dmitrij Ovtcharov',
            age: 23,
            country: 'Germany',
            year: 2012,
            date: '12/08/2012',
            sport: 'Table Tennis',
            gold: 0,
            silver: 0,
            bronze: 2,
            total: 2,
        },
        {
            athlete: 'Wang Hao',
            age: 28,
            country: 'China',
            year: 2012,
            date: '12/08/2012',
            sport: 'Table Tennis',
            gold: 1,
            silver: 1,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Zhang Jike',
            age: 24,
            country: 'China',
            year: 2012,
            date: '12/08/2012',
            sport: 'Table Tennis',
            gold: 2,
            silver: 0,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Guo Yue',
            age: 20,
            country: 'China',
            year: 2008,
            date: '24/08/2008',
            sport: 'Table Tennis',
            gold: 1,
            silver: 0,
            bronze: 1,
            total: 2,
        },
        {
            athlete: 'Ma Lin',
            age: 28,
            country: 'China',
            year: 2008,
            date: '24/08/2008',
            sport: 'Table Tennis',
            gold: 2,
            silver: 0,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Wang Hao',
            age: 24,
            country: 'China',
            year: 2008,
            date: '24/08/2008',
            sport: 'Table Tennis',
            gold: 1,
            silver: 1,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Wang Liqin',
            age: 30,
            country: 'China',
            year: 2008,
            date: '24/08/2008',
            sport: 'Table Tennis',
            gold: 1,
            silver: 0,
            bronze: 1,
            total: 2,
        },
        {
            athlete: 'Wang Nan',
            age: 29,
            country: 'China',
            year: 2008,
            date: '24/08/2008',
            sport: 'Table Tennis',
            gold: 1,
            silver: 1,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Zhang Yining',
            age: 26,
            country: 'China',
            year: 2008,
            date: '24/08/2008',
            sport: 'Table Tennis',
            gold: 2,
            silver: 0,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Zhang Yining',
            age: 22,
            country: 'China',
            year: 2004,
            date: '29/08/2004',
            sport: 'Table Tennis',
            gold: 2,
            silver: 0,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Kong Linghui',
            age: 24,
            country: 'China',
            year: 2000,
            date: '01/10/2000',
            sport: 'Table Tennis',
            gold: 1,
            silver: 1,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Li Ju',
            age: 24,
            country: 'China',
            year: 2000,
            date: '01/10/2000',
            sport: 'Table Tennis',
            gold: 1,
            silver: 1,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Liu Guoliang',
            age: 24,
            country: 'China',
            year: 2000,
            date: '01/10/2000',
            sport: 'Table Tennis',
            gold: 0,
            silver: 1,
            bronze: 1,
            total: 2,
        },
        {
            athlete: 'Wang Nan',
            age: 21,
            country: 'China',
            year: 2000,
            date: '01/10/2000',
            sport: 'Table Tennis',
            gold: 2,
            silver: 0,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Mike Bryan',
            age: 34,
            country: 'United States',
            year: 2012,
            date: '12/08/2012',
            sport: 'Tennis',
            gold: 1,
            silver: 0,
            bronze: 1,
            total: 2,
        },
        {
            athlete: 'Andy Murray',
            age: 25,
            country: 'Great Britain',
            year: 2012,
            date: '12/08/2012',
            sport: 'Tennis',
            gold: 1,
            silver: 1,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Serena Williams',
            age: 30,
            country: 'United States',
            year: 2012,
            date: '12/08/2012',
            sport: 'Tennis',
            gold: 2,
            silver: 0,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Venus Williams',
            age: 20,
            country: 'United States',
            year: 2000,
            date: '01/10/2000',
            sport: 'Tennis',
            gold: 2,
            silver: 0,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Huang Xuechen',
            age: 22,
            country: 'China',
            year: 2012,
            date: '12/08/2012',
            sport: 'Synchronized Swimming',
            gold: 0,
            silver: 1,
            bronze: 1,
            total: 2,
        },
        {
            athlete: 'Nataliya Ishchenko',
            age: 26,
            country: 'Russia',
            year: 2012,
            date: '12/08/2012',
            sport: 'Synchronized Swimming',
            gold: 2,
            silver: 0,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Liu Ou',
            age: 25,
            country: 'China',
            year: 2012,
            date: '12/08/2012',
            sport: 'Synchronized Swimming',
            gold: 0,
            silver: 1,
            bronze: 1,
            total: 2,
        },
        {
            athlete: 'Svetlana Romashina',
            age: 22,
            country: 'Russia',
            year: 2012,
            date: '12/08/2012',
            sport: 'Synchronized Swimming',
            gold: 2,
            silver: 0,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Anastasiya Davydova',
            age: 25,
            country: 'Russia',
            year: 2008,
            date: '24/08/2008',
            sport: 'Synchronized Swimming',
            gold: 2,
            silver: 0,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Anastasiya Yermakova',
            age: 25,
            country: 'Russia',
            year: 2008,
            date: '24/08/2008',
            sport: 'Synchronized Swimming',
            gold: 2,
            silver: 0,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Alison Bartosik',
            age: 21,
            country: 'United States',
            year: 2004,
            date: '29/08/2004',
            sport: 'Synchronized Swimming',
            gold: 0,
            silver: 0,
            bronze: 2,
            total: 2,
        },
        {
            athlete: 'Anastasiya Davydova',
            age: 21,
            country: 'Russia',
            year: 2004,
            date: '29/08/2004',
            sport: 'Synchronized Swimming',
            gold: 2,
            silver: 0,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Anna Kozlova',
            age: 31,
            country: 'United States',
            year: 2004,
            date: '29/08/2004',
            sport: 'Synchronized Swimming',
            gold: 0,
            silver: 0,
            bronze: 2,
            total: 2,
        },
        {
            athlete: 'Anastasiya Yermakova',
            age: 21,
            country: 'Russia',
            year: 2004,
            date: '29/08/2004',
            sport: 'Synchronized Swimming',
            gold: 2,
            silver: 0,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Olga Brusnikina',
            age: 21,
            country: 'Russia',
            year: 2000,
            date: '01/10/2000',
            sport: 'Synchronized Swimming',
            gold: 2,
            silver: 0,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Mariya Kiselyova',
            age: 25,
            country: 'Russia',
            year: 2000,
            date: '01/10/2000',
            sport: 'Synchronized Swimming',
            gold: 2,
            silver: 0,
            bronze: 0,
            total: 2,
        },
        {
            athlete: 'Becky Adlington',
            age: 23,
            country: 'Great Britain',
            year: 2012,
            date: '12/08/2012',
            sport: 'Swimming',
            gold: 0,
            silver: 0,
            bronze: 2,
            total: 2,
        },
        {
            athlete: 'Bronte Barratt',
            age: 23,
            country: 'Australia',
            year: 2012,
            date: '12/08/2012',
            sport: 'Swimming',
            gold: 0,
            silver: 1,
            bronze: 1,
            total: 2,
        },
    ];
}
