// ag-grid-ng2 v6.1.4
import { QueryList } from '@angular/core';
import { ColDef } from "ag-grid/main";
export declare class AgGridColumn {
    childColumns: QueryList<AgGridColumn>;
    field: string;
    headerName: string;
    columnGroupShow: any;
    headerClass: any;
    colId: any;
    headerCellTemplate: any;
    hide: any;
    pinned: boolean;
    filter: any;
    filterParams: any;
    headerTooltip: any;
    tooltipField: any;
    valueGetter: any;
    keyCreator: any;
    headerValueGetter: any;
    width: number;
    minWidth: any;
    maxWidth: any;
    cellClass: any;
    cellStyle: any;
    cellRenderer: any;
    cellFormatter: any;
    floatingCellRenderer: any;
    floatingCellFormatter: any;
    onCellClicked: any;
    onCellDoubleClicked: any;
    onCellContextMenu: any;
    aggFunc: any;
    rowGroupIndex: any;
    comparator: any;
    checkboxSelection: any;
    suppressMenu: any;
    suppressSorting: any;
    unSortIcon: any;
    sort: any;
    sortedAt: any;
    suppressSizeToFit: any;
    suppressMovable: any;
    suppressFilter: any;
    suppressResize: any;
    editable: any;
    suppressNavigable: any;
    cellEditor: any;
    newValueHandler: any;
    onCellValueChanged: any;
    volatile: any;
    enableRowGroup: any;
    enablePivot: any;
    enableValue: any;
    enableCellChangeFlash: any;
    hasChildColumns(): boolean;
    toColDef(): ColDef;
    private copyProperties(from, to);
}
