import { AG_GRID_LOCALE_EG, AG_GRID_LOCALE_IL } from '@ag-grid-community/locale';

export interface LanguageConfig {
    localeText: Record<string, string> | undefined;
    enableRtl: boolean;
    headers: {
        group: string;
        participant: string;
        name: string;
        language: string;
        languageTooltip: string;
        country: string;
        gameOfChoice: string;
        gameName: string;
        bought: string;
        bankBalance: string;
        extraInfo1: string;
        extraInfo2: string;
        rating: string;
        totalWinnings: string;
        monthlyBreakdown: string;
    };
    months: string[];
    contextMenu: {
        customMenuItem: string;
    };
    cellContent: {
        abra: string;
        cadabra: string;
        noStars: string;
        empty: string;
    };
    colNames: string[];
    countries: { country: string; continent: string; language: string }[];
    games: string[];
    firstNames: string[];
    lastNames: string[];
    editorLanguages: string[];
    editorCountries: string[];
}

const ENGLISH: LanguageConfig = {
    localeText: undefined,
    enableRtl: false,
    headers: {
        group: 'Group',
        participant: 'Participant',
        name: 'Name',
        language: 'Language',
        languageTooltip: 'Example tooltip for Language',
        country: 'Country',
        gameOfChoice: 'Game of Choice',
        gameName: 'Game Name',
        bought: 'Bought',
        bankBalance: 'Bank Balance',
        extraInfo1: 'Extra Info 1',
        extraInfo2: 'Extra Info 2',
        rating: 'Rating',
        totalWinnings: 'Total Winnings',
        monthlyBreakdown: 'Monthly Breakdown',
    },
    months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    contextMenu: {
        customMenuItem: 'Custom Menu Item',
    },
    cellContent: {
        abra: 'Abra...',
        cadabra: '...cadabra!',
        noStars: '(No stars)',
        empty: '(empty)',
    },
    colNames: [
        'Station',
        'Railway',
        'Street',
        'Address',
        'Toy',
        'Soft Box',
        'Make and Model',
        'Longest Day',
        'Shortest Night',
    ],
    countries: [
        { country: 'Ireland', continent: 'Europe', language: 'English' },
        { country: 'Spain', continent: 'Europe', language: 'Spanish' },
        { country: 'United Kingdom', continent: 'Europe', language: 'English' },
        { country: 'France', continent: 'Europe', language: 'French' },
        { country: 'Germany', continent: 'Europe', language: 'German' },
        { country: 'Luxembourg', continent: 'Europe', language: 'French' },
        { country: 'Sweden', continent: 'Europe', language: 'Swedish' },
        { country: 'Norway', continent: 'Europe', language: 'Norwegian' },
        { country: 'Italy', continent: 'Europe', language: 'Italian' },
        { country: 'Greece', continent: 'Europe', language: 'Greek' },
        { country: 'Iceland', continent: 'Europe', language: 'Icelandic' },
        { country: 'Portugal', continent: 'Europe', language: 'Portuguese' },
        { country: 'Malta', continent: 'Europe', language: 'Maltese' },
        { country: 'Brazil', continent: 'South America', language: 'Portuguese' },
        { country: 'Argentina', continent: 'South America', language: 'Spanish' },
        { country: 'Colombia', continent: 'South America', language: 'Spanish' },
        { country: 'Peru', continent: 'South America', language: 'Spanish' },
        { country: 'Venezuela', continent: 'South America', language: 'Spanish' },
        { country: 'Uruguay', continent: 'South America', language: 'Spanish' },
        { country: 'Belgium', continent: 'Europe', language: 'French' },
    ],
    games: [
        'Chess',
        'Cross and Circle',
        'Daldøs',
        'Downfall',
        'DVONN',
        'Fanorona',
        'Game of the Generals',
        'Ghosts',
        'Abalone',
        'Agon',
        'Backgammon',
        'Battleship',
        'Blockade',
        'Blood Bowl',
        'Bul',
        'Camelot',
        'Checkers',
        'Go',
        'Gipf',
        'Guess Who?',
        'Hare and Hounds',
        'Hex',
        'Hijara',
        'Isola',
        'Janggi (Korean Chess)',
        'Le Jeu de la Guerre',
        'Patolli',
        'Plateau',
        'PÜNCT',
        'Rithmomachy',
        'Sáhkku',
        'Senet',
        'Shogi',
        'Space Hulk',
        'Stratego',
        'Sugoroku',
        'Tâb',
        'Tablut',
        'Tantrix',
        'Wari',
        'Xiangqi (Chinese chess)',
        'YINSH',
        'ZÈRTZ',
        'Kalah',
        'Kamisado',
        'Liu po',
        'Lost Cities',
        'Mad Gab',
        'Master Mind',
        "Nine Men's Morris",
        'Obsession',
        'Othello',
    ],
    firstNames: [
        'Sophie',
        'Isabelle',
        'Emily',
        'Olivia',
        'Lily',
        'Chloe',
        'Isabella',
        'Amelia',
        'Jessica',
        'Sophia',
        'Ava',
        'Charlotte',
        'Mia',
        'Lucy',
        'Grace',
        'Ruby',
        'Ella',
        'Evie',
        'Freya',
        'Isla',
        'Poppy',
        'Daisy',
        'Layla',
    ],
    lastNames: [
        'Beckham',
        'Black',
        'Braxton',
        'Brennan',
        'Brock',
        'Bryson',
        'Cadwell',
        'Cage',
        'Carson',
        'Chandler',
        'Cohen',
        'Cole',
        'Corbin',
        'Dallas',
        'Dalton',
        'Dane',
        'Donovan',
        'Easton',
        'Fisher',
        'Fletcher',
        'Grady',
        'Greyson',
        'Griffin',
        'Gunner',
        'Hayden',
        'Hudson',
        'Hunter',
        'Jacoby',
        'Jagger',
        'Jaxon',
        'Jett',
        'Kade',
        'Kane',
        'Keating',
        'Keegan',
        'Kingston',
        'Kobe',
    ],
    editorLanguages: [
        'English',
        'Spanish',
        'French',
        'Portuguese',
        'German',
        'Swedish',
        'Norwegian',
        'Italian',
        'Greek',
        'Icelandic',
        'Portuguese',
        'Maltese',
    ],
    editorCountries: [
        'Argentina',
        'Brazil',
        'Colombia',
        'France',
        'Germany',
        'Greece',
        'Iceland',
        'Ireland',
        'Italy',
        'Malta',
        'Portugal',
        'Norway',
        'Peru',
        'Spain',
        'Sweden',
        'United Kingdom',
        'Uruguay',
        'Venezuela',
        'Belgium',
        'Luxembourg',
    ],
};

const ARABIC: LanguageConfig = {
    localeText: AG_GRID_LOCALE_EG,
    enableRtl: true,
    headers: {
        group: 'مجموعة',
        participant: 'المشارك',
        name: 'الاسم',
        language: 'اللغة',
        languageTooltip: 'تلميح مثال للغة',
        country: 'البلد',
        gameOfChoice: 'اللعبة المفضلة',
        gameName: 'اسم اللعبة',
        bought: 'تم الشراء',
        bankBalance: 'الرصيد البنكي',
        extraInfo1: 'معلومات إضافية 1',
        extraInfo2: 'معلومات إضافية 2',
        rating: 'التقييم',
        totalWinnings: 'إجمالي الأرباح',
        monthlyBreakdown: 'التفصيل الشهري',
    },
    months: [
        'يناير',
        'فبراير',
        'مارس',
        'أبريل',
        'مايو',
        'يونيو',
        'يوليو',
        'أغسطس',
        'سبتمبر',
        'أكتوبر',
        'نوفمبر',
        'ديسمبر',
    ],
    contextMenu: {
        customMenuItem: 'عنصر قائمة مخصص',
    },
    cellContent: {
        abra: 'أبرا...',
        cadabra: '...كادابرا!',
        noStars: '(بدون نجوم)',
        empty: '(فارغ)',
    },
    colNames: ['محطة', 'سكة حديد', 'شارع', 'عنوان', 'لعبة', 'صندوق', 'الشركة والطراز', 'أطول يوم', 'أقصر ليلة'],
    countries: [
        { country: 'أيرلندا', continent: 'أوروبا', language: 'الإنجليزية' },
        { country: 'إسبانيا', continent: 'أوروبا', language: 'الإسبانية' },
        { country: 'المملكة المتحدة', continent: 'أوروبا', language: 'الإنجليزية' },
        { country: 'فرنسا', continent: 'أوروبا', language: 'الفرنسية' },
        { country: 'ألمانيا', continent: 'أوروبا', language: 'الألمانية' },
        { country: 'لوكسمبورغ', continent: 'أوروبا', language: 'الفرنسية' },
        { country: 'السويد', continent: 'أوروبا', language: 'السويدية' },
        { country: 'النرويج', continent: 'أوروبا', language: 'النرويجية' },
        { country: 'إيطاليا', continent: 'أوروبا', language: 'الإيطالية' },
        { country: 'اليونان', continent: 'أوروبا', language: 'اليونانية' },
        { country: 'أيسلندا', continent: 'أوروبا', language: 'الأيسلندية' },
        { country: 'البرتغال', continent: 'أوروبا', language: 'البرتغالية' },
        { country: 'مالطا', continent: 'أوروبا', language: 'المالطية' },
        { country: 'البرازيل', continent: 'أمريكا الجنوبية', language: 'البرتغالية' },
        { country: 'الأرجنتين', continent: 'أمريكا الجنوبية', language: 'الإسبانية' },
        { country: 'كولومبيا', continent: 'أمريكا الجنوبية', language: 'الإسبانية' },
        { country: 'بيرو', continent: 'أمريكا الجنوبية', language: 'الإسبانية' },
        { country: 'فنزويلا', continent: 'أمريكا الجنوبية', language: 'الإسبانية' },
        { country: 'أوروغواي', continent: 'أمريكا الجنوبية', language: 'الإسبانية' },
        { country: 'بلجيكا', continent: 'أوروبا', language: 'الفرنسية' },
    ],
    games: [
        'شطرنج',
        'الدائرة والصليب',
        'دالدوس',
        'السقوط',
        'دفون',
        'فانورونا',
        'لعبة الجنرالات',
        'الأشباح',
        'أبالون',
        'آغون',
        'طاولة الزهر',
        'سفينة حربية',
        'حصار',
        'بلود بول',
        'بول',
        'كاميلوت',
        'داما',
        'غو',
        'غيبف',
        'احزر من؟',
        'الأرنب والكلاب',
        'هيكس',
        'هيجارا',
        'إيزولا',
        'جانغي (شطرنج كوري)',
        'لعبة الحرب',
        'باتولي',
        'بلاتو',
        'بونكت',
        'ريثموماكي',
        'ساهكو',
        'سينيت',
        'شوغي',
        'سبيس هالك',
        'ستراتيغو',
        'سوغوروكو',
        'طاب',
        'تابلوت',
        'تانتريكس',
        'واري',
        'شيانغتشي (شطرنج صيني)',
        'يينش',
        'زيرتز',
        'كالاه',
        'كاميسادو',
        'ليو بو',
        'المدن المفقودة',
        'ماد غاب',
        'ماستر مايند',
        'مطحنة الرجال التسعة',
        'هوس',
        'أوثيلو',
    ],
    firstNames: [
        'فاطمة',
        'عائشة',
        'مريم',
        'خديجة',
        'زينب',
        'نور',
        'سارة',
        'ليلى',
        'هدى',
        'أمينة',
        'رنا',
        'دانا',
        'ياسمين',
        'لمى',
        'سلمى',
        'ريم',
        'هالة',
        'منى',
        'سميرة',
        'نادية',
        'رشا',
        'سحر',
        'جنى',
    ],
    lastNames: [
        'أحمد',
        'محمد',
        'علي',
        'حسن',
        'حسين',
        'إبراهيم',
        'خالد',
        'عمر',
        'يوسف',
        'سعيد',
        'مصطفى',
        'عبد الله',
        'الشريف',
        'المنصور',
        'الحكيم',
        'النجار',
        'الخطيب',
        'البكري',
        'الزهراني',
        'القحطاني',
        'العتيبي',
        'الغامدي',
        'الدوسري',
        'الشمري',
        'المطيري',
        'الحربي',
        'السبيعي',
        'العنزي',
        'الرشيدي',
        'البلوي',
        'الجهني',
        'المالكي',
        'الثبيتي',
        'الزهراء',
        'الفهد',
        'السلمي',
        'الحازمي',
    ],
    editorLanguages: [
        'الإنجليزية',
        'الإسبانية',
        'الفرنسية',
        'البرتغالية',
        'الألمانية',
        'السويدية',
        'النرويجية',
        'الإيطالية',
        'اليونانية',
        'الأيسلندية',
        'البرتغالية',
        'المالطية',
    ],
    editorCountries: [
        'الأرجنتين',
        'البرازيل',
        'كولومبيا',
        'فرنسا',
        'ألمانيا',
        'اليونان',
        'أيسلندا',
        'أيرلندا',
        'إيطاليا',
        'مالطا',
        'البرتغال',
        'النرويج',
        'بيرو',
        'إسبانيا',
        'السويد',
        'المملكة المتحدة',
        'أوروغواي',
        'فنزويلا',
        'بلجيكا',
        'لوكسمبورغ',
    ],
};

const HEBREW: LanguageConfig = {
    localeText: AG_GRID_LOCALE_IL,
    enableRtl: true,
    headers: {
        group: 'קבוצה',
        participant: 'משתתף',
        name: 'שם',
        language: 'שפה',
        languageTooltip: 'תיאור לדוגמה עבור שפה',
        country: 'מדינה',
        gameOfChoice: 'משחק מועדף',
        gameName: 'שם המשחק',
        bought: 'נרכש',
        bankBalance: 'יתרת בנק',
        extraInfo1: 'מידע נוסף 1',
        extraInfo2: 'מידע נוסף 2',
        rating: 'דירוג',
        totalWinnings: 'סה״כ זכיות',
        monthlyBreakdown: 'פירוט חודשי',
    },
    months: [
        'ינואר',
        'פברואר',
        'מרץ',
        'אפריל',
        'מאי',
        'יוני',
        'יולי',
        'אוגוסט',
        'ספטמבר',
        'אוקטובר',
        'נובמבר',
        'דצמבר',
    ],
    contextMenu: {
        customMenuItem: 'פריט תפריט מותאם',
    },
    cellContent: {
        abra: '...אברא',
        cadabra: '!כדברא...',
        noStars: '(ללא כוכבים)',
        empty: '(ריק)',
    },
    colNames: ['תחנה', 'רכבת', 'רחוב', 'כתובת', 'צעצוע', 'קופסה', 'יצרן ודגם', 'היום הארוך', 'הלילה הקצר'],
    countries: [
        { country: 'אירלנד', continent: 'אירופה', language: 'אנגלית' },
        { country: 'ספרד', continent: 'אירופה', language: 'ספרדית' },
        { country: 'בריטניה', continent: 'אירופה', language: 'אנגלית' },
        { country: 'צרפת', continent: 'אירופה', language: 'צרפתית' },
        { country: 'גרמניה', continent: 'אירופה', language: 'גרמנית' },
        { country: 'לוקסמבורג', continent: 'אירופה', language: 'צרפתית' },
        { country: 'שוודיה', continent: 'אירופה', language: 'שוודית' },
        { country: 'נורווגיה', continent: 'אירופה', language: 'נורווגית' },
        { country: 'איטליה', continent: 'אירופה', language: 'איטלקית' },
        { country: 'יוון', continent: 'אירופה', language: 'יוונית' },
        { country: 'איסלנד', continent: 'אירופה', language: 'איסלנדית' },
        { country: 'פורטוגל', continent: 'אירופה', language: 'פורטוגזית' },
        { country: 'מלטה', continent: 'אירופה', language: 'מלטזית' },
        { country: 'ברזיל', continent: 'דרום אמריקה', language: 'פורטוגזית' },
        { country: 'ארגנטינה', continent: 'דרום אמריקה', language: 'ספרדית' },
        { country: 'קולומביה', continent: 'דרום אמריקה', language: 'ספרדית' },
        { country: 'פרו', continent: 'דרום אמריקה', language: 'ספרדית' },
        { country: 'ונצואלה', continent: 'דרום אמריקה', language: 'ספרדית' },
        { country: 'אורוגוואי', continent: 'דרום אמריקה', language: 'ספרדית' },
        { country: 'בלגיה', continent: 'אירופה', language: 'צרפתית' },
    ],
    games: [
        'שחמט',
        'עיגול וצלב',
        'דלדוס',
        'מפולת',
        'דבון',
        'פנורונה',
        'משחק הגנרלים',
        'רוחות',
        'אבלון',
        'אגון',
        'שש-בש',
        'ספינות קרב',
        'מצור',
        'בלאד באול',
        'בול',
        'קמלוט',
        'דמקה',
        'גו',
        'גיפף',
        'נחש מי?',
        'ארנב וכלבים',
        'הקס',
        'היג׳ארה',
        'איזולה',
        'ג׳אנגי (שחמט קוריאני)',
        'משחק המלחמה',
        'פטולי',
        'פלאטו',
        'פונקט',
        'ריתמומכיה',
        'סאהקו',
        'סנט',
        'שוגי',
        'ספייס האלק',
        'סטרטגו',
        'סוגורוקו',
        'טאב',
        'טבלוט',
        'טנטריקס',
        'וארי',
        'שיאנגצ׳י (שחמט סיני)',
        'יינש',
        'זרטץ',
        'קלח',
        'קמיסדו',
        'ליו פו',
        'ערים אבודות',
        'מד גאב',
        'מאסטר מיינד',
        'טחנת תשעה',
        'אובססיה',
        'אותלו',
    ],
    firstNames: [
        'נועה',
        'תמר',
        'שירה',
        'יעל',
        'מיכל',
        'רחל',
        'דנה',
        'אורי',
        'הילה',
        'ליאת',
        'מאיה',
        'רונית',
        'עדי',
        'שרה',
        'אביגיל',
        'מרים',
        'רבקה',
        'לאה',
        'חנה',
        'אסתר',
        'גלית',
        'ענת',
        'טלי',
    ],
    lastNames: [
        'כהן',
        'לוי',
        'מזרחי',
        'פרץ',
        'ביטון',
        'דהן',
        'אברהם',
        'פרידמן',
        'שפירא',
        'גולדברג',
        'רוזנברג',
        'ברקוביץ',
        'אלון',
        'שלום',
        'יוסף',
        'דוד',
        'חיים',
        'גבאי',
        'אזולאי',
        'מלכה',
        'אוחיון',
        'שמעון',
        'בנימין',
        'אליהו',
        'מרדכי',
        'גרינברג',
        'הרשקוביץ',
        'שטרנברג',
        'ויינשטיין',
        'זילברמן',
        'קפלן',
        'ברנשטיין',
        'רוזנטל',
        'גולדשטיין',
        'הלפרין',
        'ליבוביץ',
        'פינקלשטיין',
    ],
    editorLanguages: [
        'אנגלית',
        'ספרדית',
        'צרפתית',
        'פורטוגזית',
        'גרמנית',
        'שוודית',
        'נורווגית',
        'איטלקית',
        'יוונית',
        'איסלנדית',
        'פורטוגזית',
        'מלטזית',
    ],
    editorCountries: [
        'ארגנטינה',
        'ברזיל',
        'קולומביה',
        'צרפת',
        'גרמניה',
        'יוון',
        'איסלנד',
        'אירלנד',
        'איטליה',
        'מלטה',
        'פורטוגל',
        'נורווגיה',
        'פרו',
        'ספרד',
        'שוודיה',
        'בריטניה',
        'אורוגוואי',
        'ונצואלה',
        'בלגיה',
        'לוקסמבורג',
    ],
};

export const LANGUAGES: Record<string, LanguageConfig> = {
    english: ENGLISH,
    arabic: ARABIC,
    hebrew: HEBREW,
};
