export const getData = () => [
    { id: 'fr-paris', region: 'Europe', segment: 'Corporate', country: 'France', amount: 30 },
    { id: 'fr-lyon', region: 'Europe', segment: 'Corporate', country: 'France', amount: 30 },
    { id: 'de-berlin', region: 'Europe', segment: 'Corporate', country: 'Germany', amount: 35 },
    { id: 'de-hamburg', region: 'Europe', segment: 'Corporate', country: 'Germany', amount: 25 },
    { id: 'es-madrid', region: 'Europe', segment: 'Corporate', country: 'Spain', amount: 28 },
    { id: 'es-barcelona', region: 'Europe', segment: 'Corporate', country: 'Spain', amount: 32 },
    { id: 'it-rome', region: 'Europe', segment: 'Enterprise', country: 'Italy', amount: 40 },
    { id: 'it-milan', region: 'Europe', segment: 'Enterprise', country: 'Italy', amount: 20 },
    { id: 'pl-warsaw', region: 'Europe', segment: 'Enterprise', country: 'Poland', amount: 26 },
    { id: 'pl-krakow', region: 'Europe', segment: 'Enterprise', country: 'Poland', amount: 24 },
    { id: 'us-nyc', region: 'Americas', segment: 'Corporate', country: 'USA', amount: 70 },
    { id: 'us-la', region: 'Americas', segment: 'Corporate', country: 'USA', amount: 30 },
    { id: 'us-austin', region: 'Americas', segment: 'Corporate', country: 'USA', amount: 25 },
    { id: 'ca-toronto', region: 'Americas', segment: 'Enterprise', country: 'Canada', amount: 35 },
    { id: 'ca-vancouver', region: 'Americas', segment: 'Enterprise', country: 'Canada', amount: 25 },
    { id: 'br-sao-paulo', region: 'Americas', segment: 'Enterprise', country: 'Brazil', amount: 30 },
    { id: 'br-rio', region: 'Americas', segment: 'Enterprise', country: 'Brazil', amount: 22 },
    { id: 'mx-tijuana', region: 'Americas', segment: 'Enterprise', country: 'Mexico', amount: 28 },
    { id: 'mx-guadalajara', region: 'Americas', segment: 'Enterprise', country: 'Mexico', amount: 18 },
];
