// Source: https://www.gov.uk/government/statistics/total-energy-section-1-energy-trends
export const DATA_ENERGY_TRENDS_BY_QUARTER = [
    { quarter: 'Q1', coal: -666, manufacturedFuels: -14, primaryOil: -261, petroleum: -124, naturalGas: -1197 },
    { quarter: 'Q2', coal: 208, manufacturedFuels: 71, primaryOil: 950, petroleum: -318, naturalGas: 906 },
    { quarter: 'Q3', coal: 426, manufacturedFuels: 19, primaryOil: -845, petroleum: 166, naturalGas: 276 },
    { quarter: 'Q4', coal: 158, manufacturedFuels: -29, primaryOil: -156, petroleum: -19, naturalGas: 672 },
];

// Source: https://www.gov.uk/government/statistics/total-energy-section-1-energy-trends
export const DATA_ENERGY_TRENDS = [
    {
        month: 'Jan',
        coal: 0.8,
        petroleum: 5.6,
        naturalGas: 9.4,
        bioenergyWaste: 1.6,
        nuclear: 1.2,
        windSolarHydro: 0.7,
        imported: 0.2,
    },
    {
        month: 'Feb',
        coal: 1.1,
        petroleum: 5.6,
        naturalGas: 8.8,
        bioenergyWaste: 1.6,
        nuclear: 1.2,
        windSolarHydro: 0.5,
        imported: 0.1,
    },
    {
        month: 'Mar',
        coal: 1.4,
        petroleum: 5.4,
        naturalGas: 9.0,
        bioenergyWaste: 1.6,
        nuclear: 1.2,
        windSolarHydro: 0.6,
        imported: 0.1,
    },
    {
        month: 'Apr',
        coal: 0.6,
        petroleum: 5.9,
        naturalGas: 6.3,
        bioenergyWaste: 1.3,
        nuclear: 1.2,
        windSolarHydro: 0.5,
        imported: 0.1,
    },
    {
        month: 'May',
        coal: 0.5,
        petroleum: 5.6,
        naturalGas: 4.5,
        bioenergyWaste: 1.3,
        nuclear: 1.2,
        windSolarHydro: 0.5,
        imported: 0.2,
    },
    {
        month: 'Jun',
        coal: 0.5,
        petroleum: 5.8,
        naturalGas: 3.8,
        bioenergyWaste: 1.3,
        nuclear: 1.2,
        windSolarHydro: 0.4,
        imported: 0.1,
    },
    {
        month: 'Jul',
        coal: 0.4,
        petroleum: 5.6,
        naturalGas: 3.9,
        bioenergyWaste: 1.3,
        nuclear: 1.2,
        windSolarHydro: 0.4,
        imported: 0.2,
    },
    {
        month: 'Aug',
        coal: 0.4,
        petroleum: 5.9,
        naturalGas: 3.7,
        bioenergyWaste: 1.3,
        nuclear: 1.3,
        windSolarHydro: 0.4,
        imported: 0.1,
    },
    {
        month: 'Sep',
        coal: 0.7,
        petroleum: 5.8,
        naturalGas: 4.1,
        bioenergyWaste: 1.3,
        nuclear: 1.2,
        windSolarHydro: 0.6,
        imported: 0.1,
    },
    {
        month: 'Oct',
        coal: 0.6,
        petroleum: 5.5,
        naturalGas: 5.9,
        bioenergyWaste: 1.6,
        nuclear: 1.0,
        windSolarHydro: 0.6,
        imported: 0.1,
    },
    {
        month: 'Nov',
        coal: 0.9,
        petroleum: 5.9,
        naturalGas: 7.3,
        bioenergyWaste: 1.6,
        nuclear: 1.0,
        windSolarHydro: 0.7,
        imported: 0.1,
    },
    {
        month: 'Dec',
        coal: 0.7,
        petroleum: 5.8,
        naturalGas: 8.2,
        bioenergyWaste: 1.6,
        nuclear: 1.1,
        windSolarHydro: 0.6,
        imported: 0.1,
    },
];
