export function getData(): any[] {
    return [
        {
            symbol: 'A',
            name: 'Agilent Technologies Inc. Common Stock',
            change: [90],
            volume: '$971,760',
        },
        {
            symbol: 'AAL',
            name: 'American Airlines Group Inc. Common Stock',
            change: [20],
            volume: '$20,309,670',
        },
        {
            symbol: 'AAP',
            name: 'Advance Auto Parts Inc Advance Auto Parts Inc W/I',
            change: [40],
            volume: '$699,427',
        },
        {
            symbol: 'AAPL',
            name: 'Apple Inc. Common Stock',
            change: [50],
            volume: '$57,807,909',
        },
        {
            symbol: 'ABB',
            name: 'ABB Ltd Common Stock',
            change: [80],
            volume: '$901,811',
        },
        {
            symbol: 'ABBV',
            name: 'AbbVie Inc. Common Stock',
            change: [20],
            volume: '$5,364,090',
        },
        {
            symbol: 'ABC',
            name: 'AmerisourceBergen Corporation Common Stock',
            change: [40],
            volume: '$549,618',
        },
        {
            symbol: 'ABMD',
            name: 'ABIOMED Inc. Common Stock',
            change: [20],
            volume: '$137,763',
        },
        {
            symbol: 'ABNB',
            name: 'Airbnb Inc. Class A Common Stock',
            change: [90],
            volume: '$4,456,806',
        },
        {
            symbol: 'ABT',
            name: 'Abbott Laboratories Common Stock',
            change: [20],
            volume: '$2,463,348',
        },
        {
            symbol: 'ACGL',
            name: 'Arch Capital Group Ltd. Common Stock',
            change: [100],
            volume: '$1,975,171',
        },
        {
            symbol: 'ACH',
            name: 'Aluminum Corporation of China Limited American Depositary Shares',
            change: [100],
            volume: '$146,834',
        },
        {
            symbol: 'ACI',
            name: 'Albertsons Companies Inc. Class A Common Stock',
            change: [80],
            volume: '$1,690,708',
        },
        {
            symbol: 'ACN',
            name: 'Accenture plc Class A Ordinary Shares (Ireland)',
            change: [90],
            volume: '$1,566,073',
        },
        {
            symbol: 'ADBE',
            name: 'Adobe Inc. Common Stock',
            change: [15],
            volume: '$1,640,336',
        },
        {
            symbol: 'ADI',
            name: 'Analog Devices Inc. Common Stock',
            change: [20],
            volume: '$2,385,593',
        },
        {
            symbol: 'ADM',
            name: 'Archer-Daniels-Midland Company Common Stock',
            change: [90],
            volume: '$1,160,569',
        },
        {
            symbol: 'ADP',
            name: 'Automatic Data Processing Inc. Common Stock',
            change: [20],
            volume: '$1,115,876',
        },
        {
            symbol: 'ADSK',
            name: 'Autodesk Inc. Common Stock',
            change: [90],
            volume: '$1,818,966',
        },
        {
            symbol: 'AEE',
            name: 'Ameren Corporation Common Stock',
            change: [70],
            volume: '$787,992',
        },
        {
            symbol: 'AEM',
            name: 'Agnico Eagle Mines Limited Common Stock',
            change: [90],
            volume: '$1,217,286',
        },
        {
            symbol: 'AEP',
            name: 'American Electric Power Company Inc. Common Stock',
            change: [15],
            volume: '$1,407,521',
        },
        {
            symbol: 'AES',
            name: 'The AES Corporation Common Stock',
            change: [60],
            volume: '$7,178,641',
        },
        {
            symbol: 'AFG',
            name: 'American Financial Group Inc. Common Stock',
            change: [90],
            volume: '$200,011',
        },
        {
            symbol: 'AFL',
            name: 'AFLAC Incorporated Common Stock',
            change: [90],
            volume: '$1,832,452',
        },
        {
            symbol: 'AFRM',
            name: 'Affirm Holdings Inc. Class A Common Stock',
            change: [30],
            volume: '$6,096,379',
        },
        {
            symbol: 'AGCO',
            name: 'AGCO Corporation Common Stock',
            change: [15],
            volume: '$314,102',
        },
        {
            symbol: 'AGL',
            name: 'agilon health inc. Common Stock',
            change: [100],
            volume: '$218,535',
        },
        {
            symbol: 'AGR',
            name: 'Avangrid Inc. Common Stock',
            change: [90],
            volume: '$402,039',
        },
        {
            symbol: 'AIG',
            name: 'American International Group Inc. New Common Stock',
            change: [40],
            volume: '$4,556,709',
        },
        {
            symbol: 'AIZ',
            name: 'Assurant Inc. Common Stock',
            change: [30],
            volume: '$269,804',
        },
        {
            symbol: 'AJG',
            name: 'Arthur J. Gallagher & Co. Common Stock',
            change: [80],
            volume: '$1,114,620',
        },
        {
            symbol: 'AKAM',
            name: 'Akamai Technologies Inc. Common Stock',
            change: [90],
            volume: '$910,724',
        },
        {
            symbol: 'ALB',
            name: 'Albemarle Corporation Common Stock',
            change: [60],
            volume: '$860,457',
        },
        {
            symbol: 'ALC',
            name: 'Alcon Inc. Ordinary Shares',
            change: [40],
            volume: '$441,966',
        },
        {
            symbol: 'ALGN',
            name: 'Align Technology Inc. Common Stock',
            change: [15],
            volume: '$356,643',
        },
        {
            symbol: 'ALL',
            name: 'Allstate Corporation (The) Common Stock',
            change: [20],
            volume: '$1,405,300',
        },
        {
            symbol: 'ALLE',
            name: 'Allegion plc Ordinary Shares',
            change: [15],
            volume: '$1,141,503',
        },
        {
            symbol: 'ALLY',
            name: 'Ally Financial Inc. Common Stock',
            change: [80],
            volume: '$3,693,001',
        },
        {
            symbol: 'ALNY',
            name: 'Alnylam Pharmaceuticals Inc. Common Stock',
            change: [50],
            volume: '$321,032',
        },
        {
            symbol: 'AMAT',
            name: 'Applied Materials Inc. Common Stock',
            change: [70],
            volume: '$4,836,032',
        },
        {
            symbol: 'AMC',
            name: 'AMC Entertainment Holdings Inc. Class A Common Stock',
            change: [15],
            volume: '$52,110,327',
        },
        {
            symbol: 'AMCR',
            name: 'Amcor plc Ordinary Shares',
            change: [70],
            volume: '$4,625,130',
        },
        {
            symbol: 'AMD',
            name: 'Advanced Micro Devices Inc. Common Stock',
            change: [15],
            volume: '$42,603,862',
        },
        {
            symbol: 'AME',
            name: 'AMETEK Inc.',
            change: [15],
            volume: '$697,025',
        },
        {
            symbol: 'AMGN',
            name: 'Amgen Inc. Common Stock',
            change: [20],
            volume: '$1,664,133',
        },
        {
            symbol: 'AMH',
            name: 'American Homes 4 Rent Common Shares of Beneficial Interest',
            change: [40],
            volume: '$2,269,744',
        },
        {
            symbol: 'AMOV',
            name: 'America Movil S.A.B. de C.V. Class A American Depositary Shares',
            change: [70],
            volume: '$2,242',
        },
        {
            symbol: 'AMP',
            name: 'Ameriprise Financial Inc. Common Stock',
            change: [30],
            volume: '$388,249',
        },
        {
            symbol: 'ABEV',
            name: 'Ambev S.A. American Depositary Shares (Each representing 1 Common Share)',
            change: [10],
            volume: '$27,226,664',
        },
        {
            symbol: 'AMT',
            name: 'American Tower Corporation (REIT) Common Stock',
            change: [10],
            volume: '$1,645,252',
        },
        {
            symbol: 'AMX',
            name: 'America Movil S.A.B. de C.V. American Depository Receipt Series L',
            change: [30],
            volume: '$1,825,806',
        },
        {
            symbol: 'ANET',
            name: 'Arista Networks Inc. Common Stock',
            change: [40],
            volume: '$454,166',
        },
        {
            symbol: 'ANSS',
            name: 'ANSYS Inc. Common Stock',
            change: [30],
            volume: '$292,992',
        },
        {
            symbol: 'ANTM',
            name: 'Anthem Inc. Common Stock',
            change: [70],
            volume: '$636,617',
        },
        {
            symbol: 'AON',
            name: 'Aon plc Class A Ordinary Shares (Ireland)',
            change: [80],
            volume: '$990,381',
        },
        {
            symbol: 'AOS',
            name: 'A.O. Smith Corporation Common Stock',
            change: [100],
            volume: '$433,746',
        },
        {
            symbol: 'APD',
            name: 'Air Products and Chemicals Inc. Common Stock',
            change: [60],
            volume: '$821,420',
        },
        {
            symbol: 'APH',
            name: 'Amphenol Corporation Common Stock',
            change: [40],
            volume: '$1,328,023',
        },
        {
            symbol: 'APO',
            name: 'Apollo Global Management Inc. Class A Common Stock',
            change: [70],
            volume: '$2,035,785',
        },
        {
            symbol: 'APP',
            name: 'Applovin Corporation Class A Common Stock',
            change: [40],
            volume: '$1,116,662',
        },
        {
            symbol: 'APTV',
            name: 'Aptiv PLC Ordinary Shares',
            change: [70],
            volume: '$1,260,348',
        },
        {
            symbol: 'ARE',
            name: 'Alexandria Real Estate Equities Inc. Common Stock',
            change: [60],
            volume: '$710,238',
        },
        {
            symbol: 'ARES',
            name: 'Ares Management Corporation Class A Common Stock',
            change: [20],
            volume: '$541,208',
        },
        {
            symbol: 'ARGX',
            name: 'argenx SE American Depositary Shares',
            change: [90],
            volume: '$85,463',
        },
        {
            symbol: 'ASAN',
            name: 'Asana Inc. Class A Common Stock',
            change: [90],
            volume: '$4,655,695',
        },
        {
            symbol: 'ASML',
            name: 'ASML Holding N.V. New York Registry Shares',
            change: [20],
            volume: '$698,114',
        },
        {
            symbol: 'ASX',
            name: 'ASE Technology Holding Co. Ltd. American Depositary Shares (each representing Two Common Shares) ',
            change: [50],
            volume: '$3,302,831',
        },
        {
            symbol: 'ATH',
            name: 'Athene Holding Ltd. Class A Common Shares',
            change: [40],
            volume: '$694,335',
        },
        {
            symbol: 'ATO',
            name: 'Atmos Energy Corporation Common Stock',
            change: [30],
            volume: '$598,542',
        },
        {
            symbol: 'ATUS',
            name: 'Altice USA Inc. Class A Common Stock',
            change: [50],
            volume: '$2,332,885',
        },
        {
            symbol: 'ATVI',
            name: 'Activision Blizzard Inc. Common Stock',
            change: [90],
            volume: '$5,605,410',
        },
        {
            symbol: 'AVB',
            name: 'AvalonBay Communities Inc. Common Stock',
            change: [60],
            volume: '$480,656',
        },
        {
            symbol: 'AVGO',
            name: 'Broadcom Inc. Common Stock',
            change: [15],
            volume: '$2,519,063',
        },
        {
            symbol: 'AVLR',
            name: 'Avalara Inc. Common Stock',
            change: [20],
            volume: '$439,804',
        },
        {
            symbol: 'AVTR',
            name: 'Avantor Inc. Common Stock',
            change: [90],
            volume: '$2,627,806',
        },
        {
            symbol: 'AVY',
            name: 'Avery Dennison Corporation Common Stock',
            change: [100],
            volume: '$296,562',
        },
        {
            symbol: 'AWK',
            name: 'American Water Works Company Inc. Common Stock',
            change: [80],
            volume: '$466,281',
        },
        {
            symbol: 'AXON',
            name: 'Axon Enterprise Inc. Common Stock',
            change: [90],
            volume: '$204,474',
        },
        {
            symbol: 'AXP',
            name: 'American Express Company Common Stock',
            change: [80],
            volume: '$4,206,446',
        },
        {
            symbol: 'AZN',
            name: 'AstraZeneca PLC American Depositary Shares',
            change: [90],
            volume: '$5,330,649',
        },
        {
            symbol: 'BA',
            name: 'Boeing Company (The) Common Stock',
            change: [50],
            volume: '$6,392,864',
        },
        {
            symbol: 'BABA',
            name: 'Alibaba Group Holding Limited American Depositary Shares each representing eight Ordinary share',
            change: [70],
            volume: '$16,420,945',
        },
        {
            symbol: 'BAC',
            name: 'Bank of America Corporation Common Stock',
            change: [90],
            volume: '$41,811,736',
        },
        {
            symbol: 'BAH',
            name: 'Booz Allen Hamilton Holding Corporation Common Stock',
            change: [30],
            volume: '$471,871',
        },
        {
            symbol: 'BAK',
            name: 'Braskem SA ADR',
            change: [50],
            volume: '$210,250',
        },
        {
            symbol: 'BAM',
            name: 'Brookfield Asset Management Inc. Common Stock',
            change: [30],
            volume: '$1,094,681',
        },
        {
            symbol: 'BAX',
            name: 'Baxter International Inc. Common Stock',
            change: [90],
            volume: '$5,100,113',
        },
        {
            symbol: 'BBD',
            name: 'Banco Bradesco Sa American Depositary Shares',
            change: [30],
            volume: '$31,442,617',
        },
        {
            symbol: 'BBDO',
            name: 'Banco Bradesco Sa American Depositary Shares (each representing one Common Share)',
            change: [50],
            volume: '$17,324',
        },
        {
            symbol: 'BBL',
            name: 'BHP Group PlcSponsored ADR',
            change: [50],
            volume: '$2,721,838',
        },
        {
            symbol: 'BBVA',
            name: 'Banco Bilbao Vizcaya Argentaria S.A. Common Stock',
            change: [40],
            volume: '$724,666',
        },
        {
            symbol: 'BBWI',
            name: 'Bath & Body Works Inc.',
            change: [90],
            volume: '$2,114,478',
        },
        {
            symbol: 'BBY',
            name: 'Best Buy Co. Inc. Common Stock',
            change: [15],
            volume: '$1,761,592',
        },
        {
            symbol: 'BCE',
            name: 'BCE Inc. Common Stock',
            change: [50],
            volume: '$596,448',
        },
        {
            symbol: 'BCS',
            name: 'Barclays PLC Common Stock',
            change: [50],
            volume: '$3,053,751',
        },
        {
            symbol: 'BDX',
            name: 'Becton Dickinson and Company Common Stock',
            change: [20],
            volume: '$1,381,799',
        },
        {
            symbol: 'BEKE',
            name: 'KE Holdings Inc American Depositary Shares (each representing three Class A Ordinary Shares)',
            change: [80],
            volume: '$8,117,044',
        },
        {
            symbol: 'BEN',
            name: 'Franklin Resources Inc. Common Stock',
            change: [60],
            volume: '$1,959,451',
        },
        {
            symbol: 'BEP',
            name: 'Brookfield Renewable Partners L.P. ',
            change: [80],
            volume: '$193,781',
        },
        {
            symbol: 'BG',
            name: 'Bunge Limited Bunge Limited',
            change: [90],
            volume: '$609,642',
        },
        {
            symbol: 'BGNE',
            name: 'BeiGene Ltd. American Depositary Shares',
            change: [30],
            volume: '$232,512',
        },
        {
            symbol: 'BHC',
            name: 'Bausch Health Companies Inc. Common Stock',
            change: [20],
            volume: '$1,314,658',
        },
        {
            symbol: 'BHP',
            name: 'BHP Group Limited American Depositary Shares (Each representing two Ordinary Shares)',
            change: [90],
            volume: '$3,366,756',
        },
        {
            symbol: 'BIDU',
            name: 'Baidu Inc. ADS',
            change: [40],
            volume: '$3,774,707',
        },
        {
            symbol: 'BIIB',
            name: 'Biogen Inc. Common Stock',
            change: [20],
            volume: '$549,244',
        },
        {
            symbol: 'BILI',
            name: 'Bilibili Inc. American Depositary Shares',
            change: [90],
            volume: '$3,024,850',
        },
        {
            symbol: 'BILL',
            name: 'Bill.com Holdings Inc. Common Stock',
            change: [40],
            volume: '$1,734,717',
        },
        {
            symbol: 'BIO',
            name: 'Bio-Rad Laboratories Inc. Class A Common Stock',
            change: [30],
            volume: '$86,641',
        },
        {
            symbol: 'BIP',
            name: 'Brookfield Infrastructure Partners LP Limited Partnership Units',
            change: [15],
            volume: '$121,108',
        },
        {
            symbol: 'BK',
            name: 'The Bank of New York Mellon Corporation Common Stock',
            change: [40],
            volume: '$3,049,926',
        },
        {
            symbol: 'BKI',
            name: 'Black Knight Inc. Common Stock ',
            change: [60],
            volume: '$509,158',
        },
        {
            symbol: 'BKR',
            name: 'Baker Hughes Company Class A Common Stock',
            change: [30],
            volume: '$3,041,104',
        },
        {
            symbol: 'BLDR',
            name: 'Builders FirstSource Inc. Common Stock',
            change: [70],
            volume: '$1,359,978',
        },
        {
            symbol: 'BLK',
            name: 'BlackRock Inc. Common Stock',
            change: [90],
            volume: '$418,708',
        },
        {
            symbol: 'BLL',
            name: 'Ball Corporation Common Stock',
            change: [90],
            volume: '$1,420,414',
        },
        {
            symbol: 'BMO',
            name: 'Bank Of Montreal Common Stock',
            change: [80],
            volume: '$580,315',
        },
        {
            symbol: 'BMRN',
            name: 'BioMarin Pharmaceutical Inc. Common Stock',
            change: [15],
            volume: '$1,046,654',
        },
        {
            symbol: 'BMY',
            name: 'Bristol-Myers Squibb Company Common Stock',
            change: [50],
            volume: '$7,770,767',
        },
        {
            symbol: 'BNS',
            name: 'Bank Nova Scotia Halifax Pfd 3 Ordinary Shares',
            change: [80],
            volume: '$643,132',
        },
        {
            symbol: 'BNTX',
            name: 'BioNTech SE American Depositary Share',
            change: [90],
            volume: '$2,238,610',
        },
        {
            symbol: 'BP',
            name: 'BP p.l.c. Common Stock',
            change: [15],
            volume: '$6,735,425',
        },
        {
            symbol: 'BR',
            name: 'Broadridge Financial Solutions Inc.Common Stock',
            change: [15],
            volume: '$329,793',
        },
        {
            symbol: 'BRKR',
            name: 'Bruker Corporation Common Stock',
            change: [90],
            volume: '$441,560',
        },
        {
            symbol: 'BRO',
            name: 'Brown & Brown Inc. Common Stock',
            change: [60],
            volume: '$777,428',
        },
        {
            symbol: 'BSBR',
            name: 'Banco Santander Brasil SA American Depositary Shares each representing one unit',
            change: [80],
            volume: '$1,306,698',
        },
        {
            symbol: 'BSX',
            name: 'Boston Scientific Corporation Common Stock',
            change: [15],
            volume: '$8,243,842',
        },
        {
            symbol: 'BSY',
            name: 'Bentley Systems Incorporated Class B Common Stock',
            change: [80],
            volume: '$807,365',
        },
        {
            symbol: 'BTI',
            name: 'British American Tobacco  Industries p.l.c. Common Stock ADR',
            change: [40],
            volume: '$1,385,777',
        },
        {
            symbol: 'BUD',
            name: 'Anheuser-Busch Inbev SA Sponsored ADR (Belgium)',
            change: [10],
            volume: '$1,271,577',
        },
        {
            symbol: 'BURL',
            name: 'Burlington Stores Inc. Common Stock',
            change: [90],
            volume: '$567,517',
        },
        {
            symbol: 'BWA',
            name: 'BorgWarner Inc. Common Stock',
            change: [30],
            volume: '$952,357',
        },
        {
            symbol: 'BX',
            name: 'Blackstone Inc. Common Stock',
            change: [30],
            volume: '$2,767,192',
        },
        {
            symbol: 'BXP',
            name: 'Boston Properties Inc. Common Stock',
            change: [40],
            volume: '$566,440',
        },
        {
            symbol: 'BZ',
            name: 'KANZHUN LIMITED American Depository Shares',
            change: [15],
            volume: '$434,349',
        },
        {
            symbol: 'C',
            name: 'Citigroup Inc. Common Stock',
            change: [20],
            volume: '$13,683,310',
        },
        {
            symbol: 'CACC',
            name: 'Credit Acceptance Corporation Common Stock',
            change: [100],
            volume: '$338,759',
        },
        {
            symbol: 'CAG',
            name: 'ConAgra Brands Inc. Common Stock',
            change: [10],
            volume: '$3,318,141',
        },
        {
            symbol: 'CAH',
            name: 'Cardinal Health Inc. Common Stock',
            change: [60],
            volume: '$1,629,576',
        },
        {
            symbol: 'CAJ',
            name: 'Canon Inc. American Depositary Shares',
            change: [90],
            volume: '$165,508',
        },
        {
            symbol: 'CARR',
            name: 'Carrier Global Corporation Common Stock ',
            change: [10],
            volume: '$3,048,661',
        },
        {
            symbol: 'CAT',
            name: 'Caterpillar Inc. Common Stock',
            change: [70],
            volume: '$2,512,008',
        },
        {
            symbol: 'CB',
            name: 'Chubb Limited  Common Stock',
            change: [70],
            volume: '$1,755,433',
        },
        {
            symbol: 'CBOE',
            name: 'Cboe Global Markets Inc. Common Stock',
            change: [50],
            volume: '$479,851',
        },
        {
            symbol: 'CBRE',
            name: 'CBRE Group Inc Common Stock Class A',
            change: [30],
            volume: '$1,157,685',
        },
        {
            symbol: 'CCEP',
            name: 'Coca-Cola Europacific Partners plc Ordinary Shares',
            change: [50],
            volume: '$931,291',
        },
        {
            symbol: 'CCI',
            name: 'Crown Castle International Corp. (REIT) Common Stock',
            change: [100],
            volume: '$1,320,700',
        },
        {
            symbol: 'CCK',
            name: 'Crown Holdings Inc.',
            change: [40],
            volume: '$445,526',
        },
        {
            symbol: 'CCL',
            name: 'Carnival Corporation Common Stock',
            change: [90],
            volume: '$44,190,090',
        },
        {
            symbol: 'CDAY',
            name: 'Ceridian HCM Holding Inc. Common Stock',
            change: [70],
            volume: '$595,378',
        },
        {
            symbol: 'CDNS',
            name: 'Cadence Design Systems Inc. Common Stock',
            change: [100],
            volume: '$899,339',
        },
        {
            symbol: 'CDW',
            name: 'CDW Corporation Common Stock',
            change: [15],
            volume: '$384,381',
        },
        {
            symbol: 'CE',
            name: 'Celanese Corporation Celanese Corporation Common Stock',
            change: [60],
            volume: '$559,213',
        },
        {
            symbol: 'CERN',
            name: 'Cerner Corporation Common Stock',
            change: [30],
            volume: '$1,818,693',
        },
        {
            symbol: 'CFG',
            name: 'Citizens Financial Group Inc. Common Stock',
            change: [20],
            volume: '$2,706,110',
        },
        {
            symbol: 'CFLT',
            name: 'Confluent Inc. Class A Common Stock',
            change: [30],
            volume: '$1,481,237',
        },
        {
            symbol: 'CG',
            name: 'The Carlyle Group Inc. Common Stock',
            change: [15],
            volume: '$817,886',
        },
        {
            symbol: 'CGNX',
            name: 'Cognex Corporation Common Stock',
            change: [80],
            volume: '$399,721',
        },
        {
            symbol: 'CHD',
            name: 'Church & Dwight Company Inc. Common Stock',
            change: [60],
            volume: '$625,767',
        },
        {
            symbol: 'CHGG',
            name: 'Chegg Inc. Common Stock',
            change: [15],
            volume: '$1,453,267',
        },
        {
            symbol: 'CHKP',
            name: 'Check Point Software Technologies Ltd. Ordinary Shares',
            change: [20],
            volume: '$603,928',
        },
        {
            symbol: 'CHRW',
            name: 'C.H. Robinson Worldwide Inc. Common Stock',
            change: [60],
            volume: '$759,669',
        },
        {
            symbol: 'CHT',
            name: 'Chunghwa Telecom Co. Ltd.',
            change: [90],
            volume: '$70,208',
        },
        {
            symbol: 'CHTR',
            name: 'Charter Communications Inc. Class A Common Stock New',
            change: [15],
            volume: '$817,427',
        },
        {
            symbol: 'CHWY',
            name: 'Chewy Inc. Class A Common Stock',
            change: [100],
            volume: '$6,559,474',
        },
        {
            symbol: 'CI',
            name: 'Cigna Corporation Common Stock',
            change: [50],
            volume: '$1,642,693',
        },
        {
            symbol: 'CINF',
            name: 'Cincinnati Financial Corporation Common Stock',
            change: [50],
            volume: '$369,961',
        },
        {
            symbol: 'CL',
            name: 'Colgate-Palmolive Company Common Stock',
            change: [70],
            volume: '$3,030,247',
        },
        {
            symbol: 'CLF',
            name: 'Cleveland-Cliffs Inc. Common Stock',
            change: [80],
            volume: '$13,163,749',
        },
        {
            symbol: 'CLR',
            name: 'Continental Resources Inc. Common Stock',
            change: [90],
            volume: '$1,015,642',
        },
        {
            symbol: 'CLVT',
            name: 'Clarivate Plc Ordinary Shares',
            change: [30],
            volume: '$1,790,139',
        },
        {
            symbol: 'CLX',
            name: 'Clorox Company (The) Common Stock',
            change: [15],
            volume: '$1,516,821',
        },
        {
            symbol: 'CM',
            name: 'Canadian Imperial Bank of Commerce Common Stock',
            change: [80],
            volume: '$200,244',
        },
        {
            symbol: 'CMCSA',
            name: 'Comcast Corporation Class A Common Stock',
            change: [30],
            volume: '$8,080,361',
        },
        {
            symbol: 'CME',
            name: 'CME Group Inc. Class A Common Stock',
            change: [70],
            volume: '$1,061,556',
        },
        {
            symbol: 'CMI',
            name: 'Cummins Inc. Common Stock',
            change: [60],
            volume: '$991,783',
        },
        {
            symbol: 'CMS',
            name: 'CMS Energy Corporation Common Stock',
            change: [30],
            volume: '$1,156,701',
        },
        {
            symbol: 'CNA',
            name: 'CNA Financial Corporation Common Stock',
            change: [100],
            volume: '$113,755',
        },
        {
            symbol: 'CNC',
            name: 'Centene Corporation Common Stock',
            change: [50],
            volume: '$1,905,717',
        },
        {
            symbol: 'CNHI',
            name: 'CNH Industrial N.V. Common Shares',
            change: [60],
            volume: '$1,298,968',
        },
        {
            symbol: 'CNI',
            name: 'Canadian National Railway Company Common Stock',
            change: [20],
            volume: '$6,148,781',
        },
        {
            symbol: 'CNP',
            name: 'CenterPoint Energy Inc (Holding Co) Common Stock',
            change: [60],
            volume: '$6,942,880',
        },
        {
            symbol: 'CNQ',
            name: 'Canadian Natural Resources Limited Common Stock',
            change: [50],
            volume: '$2,304,180',
        },
        {
            symbol: 'COF',
            name: 'Capital One Financial Corporation Common Stock',
            change: [50],
            volume: '$3,361,223',
        },
        {
            symbol: 'COHR',
            name: 'Coherent Inc. Common Stock',
            change: [60],
            volume: '$134,481',
        },
        {
            symbol: 'COIN',
            name: 'Coinbase Global Inc. Class A Common Stock',
            change: [20],
            volume: '$4,426,023',
        },
        {
            symbol: 'CONE',
            name: 'CyrusOne Inc Common Stock',
            change: [15],
            volume: '$892,851',
        },
        {
            symbol: 'COO',
            name: 'The Cooper Companies Inc. Common Stock',
            change: [100],
            volume: '$344,025',
        },
        {
            symbol: 'COP',
            name: 'ConocoPhillips Common Stock',
            change: [60],
            volume: '$7,954,191',
        },
        {
            symbol: 'COST',
            name: 'Costco Wholesale Corporation Common Stock',
            change: [90],
            volume: '$1,301,531',
        },
        {
            symbol: 'COUP',
            name: 'Coupa Software Incorporated Common Stock',
            change: [40],
            volume: '$1,648,233',
        },
        {
            symbol: 'CP',
            name: 'Canadian Pacific Railway Limited Common Stock',
            change: [90],
            volume: '$10,545,984',
        },
        {
            symbol: 'CPB',
            name: 'Campbell Soup Company Common Stock',
            change: [80],
            volume: '$2,893,419',
        },
        {
            symbol: 'CPNG',
            name: 'Coupang Inc. Class A Common Stock',
            change: [20],
            volume: '$11,333,543',
        },
        {
            symbol: 'CPRT',
            name: 'Copart Inc. (DE) Common Stock',
            change: [60],
            volume: '$660,917',
        },
        {
            symbol: 'CPT',
            name: 'Camden Property Trust Common Stock',
            change: [15],
            volume: '$608,613',
        },
        {
            symbol: 'CQP',
            name: 'Cheniere Energy Partners LP Cheniere Energy Partners LP Common Units',
            change: [20],
            volume: '$20,985',
        },
        {
            symbol: 'CRH',
            name: 'CRH PLC American Depositary Shares',
            change: [80],
            volume: '$308,771',
        },
        {
            symbol: 'CRL',
            name: 'Charles River Laboratories International Inc. Common Stock',
            change: [15],
            volume: '$223,663',
        },
        {
            symbol: 'CRM',
            name: 'Salesforce.com Inc Common Stock',
            change: [30],
            volume: '$7,356,656',
        },
        {
            symbol: 'CRWD',
            name: 'CrowdStrike Holdings Inc. Class A Common Stock',
            change: [90],
            volume: '$3,469,582',
        },
        {
            symbol: 'CS',
            name: 'Credit Suisse Group American Depositary Shares',
            change: [70],
            volume: '$2,157,689',
        },
        {
            symbol: 'CSCO',
            name: 'Cisco Systems Inc. Common Stock (DE)',
            change: [15],
            volume: '$9,732,173',
        },
        {
            symbol: 'CSGP',
            name: 'CoStar Group Inc. Common Stock',
            change: [15],
            volume: '$1,769,628',
        },
        {
            symbol: 'CSL',
            name: 'Carlisle Companies Incorporated Common Stock',
            change: [80],
            volume: '$133,027',
        },
        {
            symbol: 'CSX',
            name: 'CSX Corporation Common Stock',
            change: [60],
            volume: '$9,727,600',
        },
        {
            symbol: 'CTAS',
            name: 'Cintas Corporation Common Stock',
            change: [50],
            volume: '$334,630',
        },
        {
            symbol: 'CTLT',
            name: 'Catalent Inc. Common Stock',
            change: [30],
            volume: '$1,112,120',
        },
        {
            symbol: 'CTSH',
            name: 'Cognizant Technology Solutions Corporation Class A Common Stock',
            change: [100],
            volume: '$1,568,542',
        },
        {
            symbol: 'CTVA',
            name: 'Corteva Inc. Common Stock ',
            change: [15],
            volume: '$3,472,010',
        },
        {
            symbol: 'CTXS',
            name: 'Citrix Systems Inc. Common Stock',
            change: [40],
            volume: '$1,241,538',
        },
        {
            symbol: 'CUBE',
            name: 'CubeSmart Common Shares',
            change: [90],
            volume: '$905,717',
        },
        {
            symbol: 'CUK',
            name: 'Carnival Plc ADS ADS',
            change: [20],
            volume: '$1,496,820',
        },
        {
            symbol: 'CVAC',
            name: 'CureVac N.V. Ordinary Shares',
            change: [90],
            volume: '$299,276',
        },
        {
            symbol: 'CVE',
            name: 'Cenovus Energy Inc Common Stock',
            change: [15],
            volume: '$5,269,830',
        },
        {
            symbol: 'CVNA',
            name: 'Carvana Co. Class A Common Stock',
            change: [20],
            volume: '$649,329',
        },
        {
            symbol: 'CVS',
            name: 'CVS Health Corporation Common Stock',
            change: [80],
            volume: '$4,936,826',
        },
        {
            symbol: 'CVX',
            name: 'Chevron Corporation Common Stock',
            change: [80],
            volume: '$9,097,002',
        },
        {
            symbol: 'CX',
            name: 'Cemex S.A.B. de C.V. Sponsored ADR',
            change: [100],
            volume: '$3,658,277',
        },
        {
            symbol: 'CZR',
            name: 'Caesars Entertainment Inc. Common Stock',
            change: [60],
            volume: '$1,446,068',
        },
        {
            symbol: 'D',
            name: 'Dominion Energy Inc. Common Stock',
            change: [90],
            volume: '$2,134,337',
        },
        {
            symbol: 'DAL',
            name: 'Delta Air Lines Inc. Common Stock',
            change: [100],
            volume: '$6,644,194',
        },
        {
            symbol: 'DAR',
            name: 'Darling Ingredients Inc. Common Stock',
            change: [10],
            volume: '$740,629',
        },
        {
            symbol: 'DASH',
            name: 'DoorDash Inc. Class A Common Stock',
            change: [50],
            volume: '$1,255,331',
        },
        {
            symbol: 'DB',
            name: 'Deutsche Bank AG Common Stock',
            change: [10],
            volume: '$2,181,840',
        },
        {
            symbol: 'DBX',
            name: 'Dropbox Inc. Class A Common Stock',
            change: [15],
            volume: '$5,548,781',
        },
        {
            symbol: 'DD',
            name: 'DuPont de Nemours Inc. Common Stock',
            change: [20],
            volume: '$3,180,637',
        },
        {
            symbol: 'DDOG',
            name: 'Datadog Inc. Class A Common Stock',
            change: [90],
            volume: '$1,936,415',
        },
        {
            symbol: 'DE',
            name: 'Deere & Company Common Stock',
            change: [30],
            volume: '$1,901,966',
        },
        {
            symbol: 'DECK',
            name: 'Deckers Outdoor Corporation Common Stock',
            change: [50],
            volume: '$277,659',
        },
        {
            symbol: 'DELL',
            name: 'Dell Technologies Inc. Class C Common Stock ',
            change: [60],
            volume: '$2,549,379',
        },
        {
            symbol: 'DEO',
            name: 'Diageo plc Common Stock',
            change: [50],
            volume: '$318,865',
        },
        {
            symbol: 'DFS',
            name: 'Discover Financial Services Common Stock',
            change: [10],
            volume: '$1,447,309',
        },
        {
            symbol: 'DG',
            name: 'Dollar General Corporation Common Stock',
            change: [30],
            volume: '$1,107,839',
        },
        {
            symbol: 'DGX',
            name: 'Quest Diagnostics Incorporated Common Stock',
            change: [40],
            volume: '$844,149',
        },
        {
            symbol: 'DHI',
            name: 'D.R. Horton Inc. Common Stock',
            change: [15],
            volume: '$2,419,034',
        },
        {
            symbol: 'DHR',
            name: 'Danaher Corporation Common Stock',
            change: [15],
            volume: '$1,333,807',
        },
        {
            symbol: 'DIDI',
            name: 'DiDi Global Inc. American Depositary Shares (each four representing one Class A Ordinary Share)',
            change: [20],
            volume: '$44,804,453',
        },
        {
            symbol: 'DIS',
            name: 'Walt Disney Company (The) Common Stock',
            change: [15],
            volume: '$6,847,409',
        },
        {
            symbol: 'DISCA',
            name: 'Discovery Inc. Series A Common Stock',
            change: [20],
            volume: '$3,655,069',
        },
        {
            symbol: 'DISCB',
            name: 'Discovery Inc. Series B Common Stock',
            change: [20],
            volume: '$550',
        },
        {
            symbol: 'DISCK',
            name: 'Discovery Inc. Series C Common Stock',
            change: [40],
            volume: '$1,991,330',
        },
        {
            symbol: 'DISH',
            name: 'DISH Network Corporation Class A Common Stock',
            change: [70],
            volume: '$1,277,928',
        },
        {
            symbol: 'DKNG',
            name: 'DraftKings Inc. Class A Common Stock',
            change: [90],
            volume: '$6,936,293',
        },
        {
            symbol: 'DKS',
            name: "Dick's Sporting Goods Inc Common Stock",
            change: [20],
            volume: '$2,587,211',
        },
        {
            symbol: 'DLO',
            name: 'DLocal Limited Class A Common Shares',
            change: [80],
            volume: '$1,760,249',
        },
        {
            symbol: 'DLR',
            name: 'Digital Realty Trust Inc. Common Stock',
            change: [40],
            volume: '$1,296,246',
        },
        {
            symbol: 'DLTR',
            name: 'Dollar Tree Inc. Common Stock',
            change: [70],
            volume: '$3,939,223',
        },
        {
            symbol: 'DOCS',
            name: 'Doximity Inc. Class A Common Stock',
            change: [90],
            volume: '$2,779,581',
        },
        {
            symbol: 'DOCU',
            name: 'DocuSign Inc. Common Stock',
            change: [15],
            volume: '$9,918,436',
        },
        {
            symbol: 'DOV',
            name: 'Dover Corporation Common Stock',
            change: [80],
            volume: '$556,941',
        },
        {
            symbol: 'DOW',
            name: 'Dow Inc. Common Stock',
            change: [50],
            volume: '$3,690,360',
        },
        {
            symbol: 'DPZ',
            name: "Domino's Pizza Inc Common Stock",
            change: [70],
            volume: '$373,007',
        },
        {
            symbol: 'DRE',
            name: 'Duke Realty Corporation Common Stock',
            change: [80],
            volume: '$1,772,918',
        },
        {
            symbol: 'DRI',
            name: 'Darden Restaurants Inc. Common Stock',
            change: [80],
            volume: '$1,103,536',
        },
        {
            symbol: 'DT',
            name: 'Dynatrace Inc. Common Stock',
            change: [20],
            volume: '$1,416,598',
        },
        {
            symbol: 'DTE',
            name: 'DTE Energy Company Common Stock',
            change: [20],
            volume: '$630,638',
        },
        {
            symbol: 'DUK',
            name: 'Duke Energy Corporation (Holding Company) Common Stock',
            change: [60],
            volume: '$3,043,703',
        },
        {
            symbol: 'DVA',
            name: 'DaVita Inc. Common Stock',
            change: [15],
            volume: '$437,994',
        },
        {
            symbol: 'DVN',
            name: 'Devon Energy Corporation Common Stock',
            change: [90],
            volume: '$7,305,299',
        },
        {
            symbol: 'DXCM',
            name: 'DexCom Inc. Common Stock',
            change: [60],
            volume: '$393,319',
        },
        {
            symbol: 'E',
            name: 'ENI S.p.A. Common Stock',
            change: [50],
            volume: '$77,365',
        },
        {
            symbol: 'EA',
            name: 'Electronic Arts Inc. Common Stock',
            change: [40],
            volume: '$1,192,670',
        },
        {
            symbol: 'EBAY',
            name: 'eBay Inc. Common Stock',
            change: [40],
            volume: '$4,436,529',
        },
        {
            symbol: 'EBR',
            name: 'Centrais Electricas Brasileiras S A American Depositary Shares (Each representing one Common Share)',
            change: [70],
            volume: '$451,820',
        },
        {
            symbol: 'EC',
            name: 'Ecopetrol S.A. American Depositary Shares',
            change: [15],
            volume: '$594,418',
        },
        {
            symbol: 'ECL',
            name: 'Ecolab Inc. Common Stock',
            change: [90],
            volume: '$980,180',
        },
        {
            symbol: 'ED',
            name: 'Consolidated Edison Inc. Common Stock',
            change: [60],
            volume: '$1,948,003',
        },
        {
            symbol: 'EFX',
            name: 'Equifax Inc. Common Stock',
            change: [15],
            volume: '$301,252',
        },
        {
            symbol: 'EIX',
            name: 'Edison International Common Stock',
            change: [100],
            volume: '$924,503',
        },
        {
            symbol: 'EL',
            name: 'Estee Lauder Companies Inc. (The) Common Stock',
            change: [80],
            volume: '$739,056',
        },
        {
            symbol: 'ELAN',
            name: 'Elanco Animal Health Incorporated Common Stock',
            change: [80],
            volume: '$4,848,823',
        },
        {
            symbol: 'ELS',
            name: 'Equity Lifestyle Properties Inc. Common Stock',
            change: [80],
            volume: '$634,611',
        },
        {
            symbol: 'EMN',
            name: 'Eastman Chemical Company Common Stock',
            change: [30],
            volume: '$557,177',
        },
        {
            symbol: 'EMR',
            name: 'Emerson Electric Company Common Stock',
            change: [70],
            volume: '$2,008,573',
        },
        {
            symbol: 'ENB',
            name: 'Enbridge Inc Common Stock',
            change: [80],
            volume: '$3,838,087',
        },
        {
            symbol: 'ENIA',
            name: 'Enel Americas S.A. American Depositary Shares',
            change: [20],
            volume: '$915,289',
        },
        {
            symbol: 'ENPH',
            name: 'Enphase Energy Inc. Common Stock',
            change: [70],
            volume: '$1,180,724',
        },
        {
            symbol: 'ENTG',
            name: 'Entegris Inc. Common Stock',
            change: [10],
            volume: '$397,118',
        },
        {
            symbol: 'EOG',
            name: 'EOG Resources Inc. Common Stock',
            change: [60],
            volume: '$2,450,170',
        },
        {
            symbol: 'EPAM',
            name: 'EPAM Systems Inc. Common Stock',
            change: [15],
            volume: '$164,374',
        },
        {
            symbol: 'EPD',
            name: 'Enterprise Products Partners L.P. Common Stock',
            change: [80],
            volume: '$3,093,335',
        },
        {
            symbol: 'EQH',
            name: 'Equitable Holdings Inc. Common Stock',
            change: [60],
            volume: '$1,754,709',
        },
        {
            symbol: 'EQIX',
            name: 'Equinix Inc. Common Stock REIT',
            change: [20],
            volume: '$516,450',
        },
        {
            symbol: 'EQNR',
            name: 'Equinor ASA',
            change: [90],
            volume: '$1,698,747',
        },
        {
            symbol: 'EQR',
            name: 'Equity Residential Common Shares of Beneficial Interest',
            change: [30],
            volume: '$1,227,900',
        },
        {
            symbol: 'ERIC',
            name: 'Ericsson American Depositary Shares',
            change: [100],
            volume: '$3,433,921',
        },
        {
            symbol: 'ES',
            name: 'Eversource Energy (D/B/A) Common Stock',
            change: [30],
            volume: '$926,750',
        },
        {
            symbol: 'ESS',
            name: 'Essex Property Trust Inc. Common Stock',
            change: [80],
            volume: '$294,099',
        },
        {
            symbol: 'ESTC',
            name: 'Elastic N.V. Ordinary Shares',
            change: [80],
            volume: '$1,461,961',
        },
        {
            symbol: 'ET',
            name: 'Energy Transfer LP Common Units ',
            change: [50],
            volume: '$8,358,525',
        },
        {
            symbol: 'ETN',
            name: 'Eaton Corporation PLC Ordinary Shares',
            change: [20],
            volume: '$1,255,394',
        },
        {
            symbol: 'ETR',
            name: 'Entergy Corporation Common Stock',
            change: [40],
            volume: '$1,586,656',
        },
        {
            symbol: 'ETSY',
            name: 'Etsy Inc. Common Stock',
            change: [60],
            volume: '$1,908,906',
        },
        {
            symbol: 'EVRG',
            name: 'Evergy Inc. Common Stock',
            change: [90],
            volume: '$903,768',
        },
        {
            symbol: 'EW',
            name: 'Edwards Lifesciences Corporation Common Stock',
            change: [10],
            volume: '$1,280,846',
        },
        {
            symbol: 'EWBC',
            name: 'East West Bancorp Inc. Common Stock',
            change: [30],
            volume: '$282,941',
        },
        {
            symbol: 'EXAS',
            name: 'Exact Sciences Corporation Common Stock',
            change: [30],
            volume: '$835,203',
        },
        {
            symbol: 'EXC',
            name: 'Exelon Corporation Common Stock',
            change: [20],
            volume: '$3,535,297',
        },
        {
            symbol: 'EXPD',
            name: 'Expeditors International of Washington Inc. Common Stock',
            change: [15],
            volume: '$750,311',
        },
        {
            symbol: 'EXPE',
            name: 'Expedia Group Inc. Common Stock',
            change: [20],
            volume: '$1,420,130',
        },
        {
            symbol: 'EXR',
            name: 'Extra Space Storage Inc Common Stock',
            change: [30],
            volume: '$896,840',
        },
        {
            symbol: 'F',
            name: 'Ford Motor Company Common Stock',
            change: [15],
            volume: '$41,614,222',
        },
        {
            symbol: 'FANG',
            name: 'Diamondback Energy Inc. Commmon Stock',
            change: [80],
            volume: '$1,671,650',
        },
        {
            symbol: 'FAST',
            name: 'Fastenal Company Common Stock',
            change: [60],
            volume: '$1,671,184',
        },
        {
            symbol: 'FB',
            name: 'Facebook Inc. Class A Common Stock',
            change: [15],
            volume: '$7,509,555',
        },
        {
            symbol: 'FBHS',
            name: 'Fortune Brands Home & Security Inc. Common Stock',
            change: [60],
            volume: '$572,542',
        },
        {
            symbol: 'FCX',
            name: 'Freeport-McMoRan Inc. Common Stock',
            change: [90],
            volume: '$12,687,089',
        },
        {
            symbol: 'FDS',
            name: 'FactSet Research Systems Inc. Common Stock',
            change: [20],
            volume: '$95,151',
        },
        {
            symbol: 'FDX',
            name: 'FedEx Corporation Common Stock',
            change: [50],
            volume: '$1,524,734',
        },
        {
            symbol: 'FE',
            name: 'FirstEnergy Corp. Common Stock',
            change: [60],
            volume: '$2,979,435',
        },
        {
            symbol: 'FERG',
            name: 'Ferguson plc Ordinary Shares',
            change: [70],
            volume: '$12,876',
        },
        {
            symbol: 'FFIV',
            name: 'F5 Networks Inc. Common Stock',
            change: [60],
            volume: '$454,333',
        },
        {
            symbol: 'FICO',
            name: 'Fair Isaac Corproation Common Stock',
            change: [60],
            volume: '$143,937',
        },
        {
            symbol: 'FIS',
            name: 'Fidelity National Information Services Inc. Common Stock',
            change: [90],
            volume: '$4,771,732',
        },
        {
            symbol: 'FISV',
            name: 'Fiserv Inc. Common Stock',
            change: [90],
            volume: '$2,429,396',
        },
        {
            symbol: 'FITB',
            name: 'Fifth Third Bancorp Common Stock',
            change: [40],
            volume: '$4,129,959',
        },
        {
            symbol: 'FIVE',
            name: 'Five Below Inc. Common Stock',
            change: [60],
            volume: '$1,734,207',
        },
        {
            symbol: 'FIVN',
            name: 'Five9 Inc. Common Stock',
            change: [50],
            volume: '$2,648,070',
        },
        {
            symbol: 'FLT',
            name: 'FleetCor Technologies Inc. Common Stock',
            change: [40],
            volume: '$339,719',
        },
        {
            symbol: 'FMC',
            name: 'FMC Corporation Common Stock',
            change: [90],
            volume: '$937,157',
        },
        {
            symbol: 'FMS',
            name: 'Fresenius Medical Care AG Common Stock',
            change: [90],
            volume: '$368,534',
        },
        {
            symbol: 'FMX',
            name: 'Fomento Economico Mexicano S.A.B. de C.V. Common Stock',
            change: [50],
            volume: '$202,386',
        },
        {
            symbol: 'FND',
            name: 'Floor & Decor Holdings Inc. Common Stock',
            change: [100],
            volume: '$355,132',
        },
        {
            symbol: 'FNF',
            name: 'FNF Group of Fidelity National Financial Inc. Common Stock',
            change: [10],
            volume: '$941,890',
        },
        {
            symbol: 'FNV',
            name: 'Franco-Nevada Corporation',
            change: [20],
            volume: '$373,467',
        },
        {
            symbol: 'FOX',
            name: 'Fox Corporation Class B Common Stock',
            change: [70],
            volume: '$752,659',
        },
        {
            symbol: 'FOXA',
            name: 'Fox Corporation Class A Common Stock',
            change: [60],
            volume: '$1,529,648',
        },
        {
            symbol: 'FRC',
            name: 'FIRST REPUBLIC BANK Common Stock',
            change: [15],
            volume: '$404,708',
        },
        {
            symbol: 'FSLR',
            name: 'First Solar Inc. Common Stock',
            change: [15],
            volume: '$567,393',
        },
        {
            symbol: 'FTCH',
            name: 'Farfetch Limited Class A Ordinary Shares',
            change: [80],
            volume: '$2,438,759',
        },
        {
            symbol: 'FTNT',
            name: 'Fortinet Inc. Common Stock',
            change: [50],
            volume: '$706,854',
        },
        {
            symbol: 'FTS',
            name: 'Fortis Inc. Common Shares',
            change: [15],
            volume: '$171,218',
        },
        {
            symbol: 'FTV',
            name: 'Fortive Corporation Common Stock ',
            change: [100],
            volume: '$2,179,925',
        },
        {
            symbol: 'FUTU',
            name: 'Futu Holdings Limited American Depositary Shares',
            change: [50],
            volume: '$4,316,600',
        },
        {
            symbol: 'FWONA',
            name: 'Liberty Media Corporation Series A Liberty Formula One Common Stock',
            change: [50],
            volume: '$139,730',
        },
        {
            symbol: 'FWONK',
            name: 'Liberty Media Corporation Series C Liberty Formula One Common Stock',
            change: [70],
            volume: '$499,069',
        },
        {
            symbol: 'GD',
            name: 'General Dynamics Corporation Common Stock',
            change: [90],
            volume: '$881,260',
        },
        {
            symbol: 'GDDY',
            name: 'GoDaddy Inc. Class A Common Stock',
            change: [60],
            volume: '$832,150',
        },
        {
            symbol: 'GDRX',
            name: 'GoodRx Holdings Inc. Class A Common Stock',
            change: [70],
            volume: '$3,086,837',
        },
        {
            symbol: 'GDS',
            name: 'GDS Holdings Limited ADS',
            change: [100],
            volume: '$797,338',
        },
        {
            symbol: 'GE',
            name: 'General Electric Company Common Stock',
            change: [10],
            volume: '$7,616,843',
        },
        {
            symbol: 'GFL',
            name: 'GFL Environmental Inc. Subordinate voting shares no par value',
            change: [30],
            volume: '$684,565',
        },
        {
            symbol: 'GGG',
            name: 'Graco Inc. Common Stock',
            change: [70],
            volume: '$294,949',
        },
        {
            symbol: 'GH',
            name: 'Guardant Health Inc. Common Stock',
            change: [50],
            volume: '$659,453',
        },
        {
            symbol: 'GIB',
            name: 'CGI Inc. Common Stock',
            change: [40],
            volume: '$147,694',
        },
        {
            symbol: 'GILD',
            name: 'Gilead Sciences Inc. Common Stock',
            change: [40],
            volume: '$4,174,370',
        },
        {
            symbol: 'GIS',
            name: 'General Mills Inc. Common Stock',
            change: [15],
            volume: '$2,270,909',
        },
        {
            symbol: 'GLBE',
            name: 'Global-E Online Ltd. Ordinary Shares',
            change: [40],
            volume: '$410,617',
        },
        {
            symbol: 'GLOB',
            name: 'Globant S.A. Common Shares',
            change: [70],
            volume: '$224,965',
        },
        {
            symbol: 'GLPI',
            name: 'Gaming and Leisure Properties Inc. Common Stock',
            change: [90],
            volume: '$1,381,316',
        },
        {
            symbol: 'GLW',
            name: 'Corning Incorporated Common Stock',
            change: [20],
            volume: '$2,787,474',
        },
        {
            symbol: 'GM',
            name: 'General Motors Company Common Stock',
            change: [30],
            volume: '$9,932,254',
        },
        {
            symbol: 'GMAB',
            name: 'Genmab A/S ADS',
            change: [90],
            volume: '$161,204',
        },
        {
            symbol: 'GME',
            name: 'GameStop Corporation Common Stock',
            change: [20],
            volume: '$2,658,357',
        },
        {
            symbol: 'GNRC',
            name: 'Generac Holdlings Inc. Common Stock',
            change: [50],
            volume: '$538,911',
        },
        {
            symbol: 'GOLD',
            name: 'Barrick Gold Corporation Common Stock (BC)',
            change: [40],
            volume: '$20,232,506',
        },
        {
            symbol: 'GPC',
            name: 'Genuine Parts Company Common Stock',
            change: [50],
            volume: '$432,062',
        },
        {
            symbol: 'GPN',
            name: 'Global Payments Inc. Common Stock',
            change: [30],
            volume: '$2,691,584',
        },
        {
            symbol: 'GRFS',
            name: 'Grifols S.A. American Depositary Shares',
            change: [10],
            volume: '$295,296',
        },
        {
            symbol: 'GRMN',
            name: 'Garmin Ltd. Common Stock (Switzerland)',
            change: [20],
            volume: '$652,984',
        },
        {
            symbol: 'GRUB',
            name: 'Just Eat Takeaway.com N.V. American Depositary Shares',
            change: [15],
            volume: '$2,013,431',
        },
        {
            symbol: 'GS',
            name: 'Goldman Sachs Group Inc. (The) Common Stock',
            change: [10],
            volume: '$1,373,484',
        },
        {
            symbol: 'GSK',
            name: 'GlaxoSmithKline PLC Common Stock',
            change: [20],
            volume: '$3,020,606',
        },
        {
            symbol: 'GWRE',
            name: 'Guidewire Software Inc. Common Stock',
            change: [70],
            volume: '$1,927,590',
        },
        {
            symbol: 'GWW',
            name: 'W.W. Grainger Inc. Common Stock',
            change: [40],
            volume: '$226,896',
        },
        {
            symbol: 'HAL',
            name: 'Halliburton Company Common Stock',
            change: [10],
            volume: '$4,740,472',
        },
        {
            symbol: 'HAS',
            name: 'Hasbro Inc. Common Stock',
            change: [80],
            volume: '$249,342',
        },
        {
            symbol: 'HBAN',
            name: 'Huntington Bancshares Incorporated Common Stock',
            change: [70],
            volume: '$10,258,375',
        },
        {
            symbol: 'HCA',
            name: 'HCA Healthcare Inc. Common Stock',
            change: [30],
            volume: '$605,665',
        },
        {
            symbol: 'HD',
            name: 'Home Depot Inc. (The) Common Stock',
            change: [50],
            volume: '$2,774,837',
        },
        {
            symbol: 'HDB',
            name: 'HDFC Bank Limited Common Stock',
            change: [60],
            volume: '$1,167,551',
        },
        {
            symbol: 'HEI',
            name: 'Heico Corporation Common Stock',
            change: [15],
            volume: '$186,961',
        },
        {
            symbol: 'HES',
            name: 'Hess Corporation Common Stock',
            change: [15],
            volume: '$1,389,114',
        },
        {
            symbol: 'HIG',
            name: 'Hartford Financial Services Group Inc. (The) Common Stock',
            change: [60],
            volume: '$2,183,728',
        },
        {
            symbol: 'HLT',
            name: 'Hilton Worldwide Holdings Inc. Common Stock ',
            change: [60],
            volume: '$1,697,303',
        },
        {
            symbol: 'HMC',
            name: 'Honda Motor Company Ltd. Common Stock',
            change: [40],
            volume: '$876,737',
        },
        {
            symbol: 'HOLX',
            name: 'Hologic Inc. Common Stock',
            change: [50],
            volume: '$707,841',
        },
        {
            symbol: 'HON',
            name: 'Honeywell International Inc. Common Stock',
            change: [70],
            volume: '$1,622,388',
        },
        {
            symbol: 'HOOD',
            name: 'Robinhood Markets Inc. Class A Common Stock',
            change: [60],
            volume: '$4,654,130',
        },
        {
            symbol: 'HPE',
            name: 'Hewlett Packard Enterprise Company Common Stock',
            change: [15],
            volume: '$14,355,157',
        },
        {
            symbol: 'HPQ',
            name: 'HP Inc. Common Stock',
            change: [10],
            volume: '$8,119,602',
        },
        {
            symbol: 'HRL',
            name: 'Hormel Foods Corporation Common Stock',
            change: [80],
            volume: '$5,048,292',
        },
        {
            symbol: 'HSBC',
            name: 'HSBC Holdings plc. Common Stock',
            change: [40],
            volume: '$1,667,372',
        },
        {
            symbol: 'HSIC',
            name: 'Henry Schein Inc. Common Stock',
            change: [50],
            volume: '$585,536',
        },
        {
            symbol: 'HST',
            name: 'Host Hotels & Resorts Inc. Common Stock',
            change: [60],
            volume: '$5,977,414',
        },
        {
            symbol: 'HSY',
            name: 'The Hershey Company Common Stock',
            change: [50],
            volume: '$462,907',
        },
        {
            symbol: 'HTHT',
            name: 'Huazhu Group Limited American Depositary Shares',
            change: [15],
            volume: '$2,145,683',
        },
        {
            symbol: 'HUBB',
            name: 'Hubbell Inc Common Stock',
            change: [60],
            volume: '$97,715',
        },
        {
            symbol: 'HUBS',
            name: 'HubSpot Inc. Common Stock',
            change: [20],
            volume: '$244,262',
        },
        {
            symbol: 'HUM',
            name: 'Humana Inc. Common Stock',
            change: [50],
            volume: '$566,834',
        },
        {
            symbol: 'HWM',
            name: 'Howmet Aerospace Inc. Common Stock',
            change: [60],
            volume: '$1,411,568',
        },
        {
            symbol: 'HZNP',
            name: 'Horizon Therapeutics Public Limited Company Ordinary Shares',
            change: [60],
            volume: '$599,725',
        },
        {
            symbol: 'IAC',
            name: 'IAC/InterActiveCorp Common Stock',
            change: [100],
            volume: '$343,665',
        },
        {
            symbol: 'IBM',
            name: 'International Business Machines Corporation Common Stock',
            change: [50],
            volume: '$1,921,160',
        },
        {
            symbol: 'IBN',
            name: 'ICICI Bank Limited Common Stock',
            change: [60],
            volume: '$3,150,622',
        },
        {
            symbol: 'ICE',
            name: 'Intercontinental Exchange Inc. Common Stock',
            change: [20],
            volume: '$1,874,689',
        },
        {
            symbol: 'ICLR',
            name: 'ICON plc Ordinary Shares',
            change: [100],
            volume: '$389,960',
        },
        {
            symbol: 'IDXX',
            name: 'IDEXX Laboratories Inc. Common Stock',
            change: [80],
            volume: '$294,330',
        },
        {
            symbol: 'IEP',
            name: 'Icahn Enterprises L.P. Common Stock',
            change: [30],
            volume: '$309,506',
        },
        {
            symbol: 'IEX',
            name: 'IDEX Corporation Common Stock',
            change: [80],
            volume: '$263,937',
        },
        {
            symbol: 'IFF',
            name: 'Internationa Flavors & Fragrances Inc. Common Stock',
            change: [20],
            volume: '$1,209,973',
        },
        {
            symbol: 'IHG',
            name: 'Intercontinental Hotels Group American Depositary Shares (Each representing one Ordinary Share)',
            change: [80],
            volume: '$98,507',
        },
        {
            symbol: 'ILMN',
            name: 'Illumina Inc. Common Stock',
            change: [40],
            volume: '$517,904',
        },
        {
            symbol: 'IMO',
            name: 'Imperial Oil Limited Common Stock',
            change: [90],
            volume: '$273,886',
        },
        {
            symbol: 'INCY',
            name: 'Incyte Corp. Common Stock',
            change: [40],
            volume: '$1,042,908',
        },
        {
            symbol: 'INFO',
            name: 'IHS Markit Ltd. Common Shares',
            change: [70],
            volume: '$1,431,371',
        },
        {
            symbol: 'INFY',
            name: 'Infosys Limited American Depositary Shares',
            change: [20],
            volume: '$3,781,246',
        },
        {
            symbol: 'ING',
            name: 'ING Group N.V. Common Stock',
            change: [60],
            volume: '$1,748,276',
        },
        {
            symbol: 'INTC',
            name: 'Intel Corporation Common Stock',
            change: [80],
            volume: '$13,456,224',
        },
        {
            symbol: 'INTU',
            name: 'Intuit Inc. Common Stock',
            change: [30],
            volume: '$762,588',
        },
        {
            symbol: 'INVH',
            name: 'Invitation Homes Inc. Common Stock',
            change: [15],
            volume: '$4,317,321',
        },
        {
            symbol: 'IP',
            name: 'International Paper Company Common Stock',
            change: [10],
            volume: '$1,657,170',
        },
        {
            symbol: 'IPG',
            name: 'Interpublic Group of Companies Inc. (The) Common Stock',
            change: [20],
            volume: '$2,267,141',
        },
        {
            symbol: 'IQV',
            name: 'IQVIA Holdings Inc. Common Stock',
            change: [80],
            volume: '$509,685',
        },
        {
            symbol: 'IR',
            name: 'Ingersoll Rand Inc. Common Stock',
            change: [70],
            volume: '$3,760,328',
        },
        {
            symbol: 'IRM',
            name: 'Iron Mountain Incorporated (Delaware)Common Stock REIT',
            change: [40],
            volume: '$1,488,840',
        },
        {
            symbol: 'IS',
            name: 'ironSource Ltd. Class A Ordinary Shares',
            change: [90],
            volume: '$1,253,121',
        },
        {
            symbol: 'IT',
            name: 'Gartner Inc. Common Stock',
            change: [50],
            volume: '$368,836',
        },
        {
            symbol: 'ITUB',
            name: 'Itau Unibanco Banco Holding SA American Depositary Shares (Each repstg 500 Preferred shares)',
            change: [90],
            volume: '$27,738,938',
        },
        {
            symbol: 'ITW',
            name: 'Illinois Tool Works Inc. Common Stock',
            change: [50],
            volume: '$695,130',
        },
        {
            symbol: 'IVZ',
            name: 'Invesco Ltd Common Stock',
            change: [40],
            volume: '$3,477,160',
        },
        {
            symbol: 'IX',
            name: 'Orix Corp Ads Common Stock',
            change: [10],
            volume: '$18,848',
        },
        {
            symbol: 'J',
            name: 'Jacobs Engineering Group Inc. Common Stock',
            change: [90],
            volume: '$342,958',
        },
        {
            symbol: 'JBHT',
            name: 'J.B. Hunt Transport Services Inc. Common Stock',
            change: [15],
            volume: '$478,525',
        },
        {
            symbol: 'JCI',
            name: 'Johnson Controls International plc Ordinary Share',
            change: [20],
            volume: '$3,329,269',
        },
        {
            symbol: 'JD',
            name: 'JD.com Inc. American Depositary Shares',
            change: [50],
            volume: '$8,502,237',
        },
        {
            symbol: 'JHX',
            name: 'James Hardie Industries plc American Depositary Shares (Ireland)',
            change: [20],
            volume: '$29,614',
        },
        {
            symbol: 'JKHY',
            name: 'Jack Henry & Associates Inc. Common Stock',
            change: [30],
            volume: '$316,152',
        },
        {
            symbol: 'JLL',
            name: 'Jones Lang LaSalle Incorporated Common Stock',
            change: [40],
            volume: '$242,884',
        },
        {
            symbol: 'JNJ',
            name: 'Johnson & Johnson Common Stock',
            change: [10],
            volume: '$4,096,451',
        },
        {
            symbol: 'JPM',
            name: 'JP Morgan Chase & Co. Common Stock',
            change: [70],
            volume: '$7,959,728',
        },
        {
            symbol: 'K',
            name: 'Kellogg Company Common Stock',
            change: [40],
            volume: '$1,763,135',
        },
        {
            symbol: 'KB',
            name: 'KB Financial Group Inc',
            change: [70],
            volume: '$94,270',
        },
        {
            symbol: 'KDP',
            name: 'Keurig Dr Pepper Inc. Common Stock',
            change: [80],
            volume: '$5,148,138',
        },
        {
            symbol: 'KEP',
            name: 'Korea Electric Power Corporation Common Stock',
            change: [50],
            volume: '$111,632',
        },
        {
            symbol: 'KEY',
            name: 'KeyCorp Common Stock',
            change: [30],
            volume: '$6,050,092',
        },
        {
            symbol: 'KEYS',
            name: 'Keysight Technologies Inc. Common Stock',
            change: [20],
            volume: '$715,508',
        },
        {
            symbol: 'KHC',
            name: 'The Kraft Heinz Company Common Stock',
            change: [10],
            volume: '$5,550,251',
        },
        {
            symbol: 'KIM',
            name: 'Kimco Realty Corporation Common Stock',
            change: [100],
            volume: '$4,905,283',
        },
        {
            symbol: 'KKR',
            name: 'KKR & Co. Inc. Common Stock',
            change: [70],
            volume: '$2,721,949',
        },
        {
            symbol: 'KL',
            name: 'Kirkland Lake Gold Ltd. Common Shares',
            change: [20],
            volume: '$1,662,845',
        },
        {
            symbol: 'KLAC',
            name: 'KLA Corporation Common Stock',
            change: [60],
            volume: '$481,752',
        },
        {
            symbol: 'KMB',
            name: 'Kimberly-Clark Corporation Common Stock',
            change: [15],
            volume: '$1,426,817',
        },
        {
            symbol: 'KMI',
            name: 'Kinder Morgan Inc. Common Stock',
            change: [90],
            volume: '$6,399,205',
        },
        {
            symbol: 'KMX',
            name: 'CarMax Inc',
            change: [20],
            volume: '$607,376',
        },
        {
            symbol: 'KO',
            name: 'Coca-Cola Company (The) Common Stock',
            change: [10],
            volume: '$13,220,412',
        },
        {
            symbol: 'KR',
            name: 'Kroger Company (The) Common Stock',
            change: [60],
            volume: '$5,460,025',
        },
        {
            symbol: 'KSU',
            name: 'Kansas City Southern Common Stock',
            change: [20],
            volume: '$1,202,474',
        },
        {
            symbol: 'L',
            name: 'Loews Corporation Common Stock',
            change: [80],
            volume: '$796,690',
        },
        {
            symbol: 'LAMR',
            name: 'Lamar Advertising Company Class A Common Stock',
            change: [80],
            volume: '$307,915',
        },
        {
            symbol: 'LBRDA',
            name: 'Liberty Broadband Corporation Class A Common Stock',
            change: [60],
            volume: '$84,647',
        },
        {
            symbol: 'LBRDK',
            name: 'Liberty Broadband Corporation Class C Common Stock',
            change: [15],
            volume: '$582,281',
        },
        {
            symbol: 'LBTYA',
            name: 'Liberty Global plc Class A Ordinary Shares',
            change: [80],
            volume: '$903,180',
        },
        {
            symbol: 'LBTYB',
            name: 'Liberty Global plc Class B Ordinary Shares',
            change: [20],
            volume: '$58',
        },
        {
            symbol: 'LBTYK',
            name: 'Liberty Global plc Class C Ordinary Shares',
            change: [10],
            volume: '$2,018,077',
        },
        {
            symbol: 'LCID',
            name: 'Lucid Group Inc. Common Stock',
            change: [60],
            volume: '$25,239,286',
        },
        {
            symbol: 'LDOS',
            name: 'Leidos Holdings Inc. Common Stock',
            change: [100],
            volume: '$599,748',
        },
        {
            symbol: 'LEN',
            name: 'Lennar Corporation Class A Common Stock',
            change: [30],
            volume: '$1,228,593',
        },
        {
            symbol: 'LEVI',
            name: 'Levi Strauss & Co Class A Common Stock',
            change: [70],
            volume: '$1,015,792',
        },
        {
            symbol: 'LFC',
            name: 'China Life Insurance Company Limited American Depositary Shares',
            change: [60],
            volume: '$479,562',
        },
        {
            symbol: 'LH',
            name: 'Laboratory Corporation of America Holdings Common Stock',
            change: [40],
            volume: '$605,203',
        },
        {
            symbol: 'LHX',
            name: 'L3Harris Technologies Inc. Common Stock',
            change: [15],
            volume: '$1,119,858',
        },
        {
            symbol: 'LI',
            name: 'Li Auto Inc. American Depositary Shares',
            change: [40],
            volume: '$8,325,732',
        },
        {
            symbol: 'LII',
            name: 'Lennox International Inc. Common Stock',
            change: [50],
            volume: '$121,322',
        },
        {
            symbol: 'LIN',
            name: 'Linde plc Ordinary Share',
            change: [30],
            volume: '$1,150,808',
        },
        {
            symbol: 'LKQ',
            name: 'LKQ Corporation Common Stock',
            change: [50],
            volume: '$1,015,702',
        },
        {
            symbol: 'LLY',
            name: 'Eli Lilly and Company Common Stock',
            change: [70],
            volume: '$1,124,525',
        },
        {
            symbol: 'LMT',
            name: 'Lockheed Martin Corporation Common Stock',
            change: [70],
            volume: '$893,141',
        },
        {
            symbol: 'LNC',
            name: 'Lincoln National Corporation Common Stock',
            change: [20],
            volume: '$678,463',
        },
        {
            symbol: 'LNG',
            name: 'Cheniere Energy Inc. Common Stock',
            change: [40],
            volume: '$747,319',
        },
        {
            symbol: 'LNT',
            name: 'Alliant Energy Corporation Common Stock',
            change: [20],
            volume: '$681,640',
        },
        {
            symbol: 'LOGI',
            name: 'Logitech International S.A. Ordinary Shares',
            change: [40],
            volume: '$468,046',
        },
        {
            symbol: 'LOW',
            name: "Lowe's Companies Inc. Common Stock",
            change: [30],
            volume: '$2,260,871',
        },
        {
            symbol: 'LPLA',
            name: 'LPL Financial Holdings Inc. Common Stock',
            change: [15],
            volume: '$241,629',
        },
        {
            symbol: 'LRCX',
            name: 'Lam Research Corporation Common Stock',
            change: [50],
            volume: '$1,029,359',
        },
        {
            symbol: 'LSI',
            name: 'Life Storage Inc. Common Stock',
            change: [90],
            volume: '$412,457',
        },
        {
            symbol: 'LSPD',
            name: 'Lightspeed Commerce Inc. Subordinate Voting Shares',
            change: [60],
            volume: '$1,146,400',
        },
        {
            symbol: 'LSXMA',
            name: 'Liberty Media Corporation Series A Liberty SiriusXM Common Stock',
            change: [70],
            volume: '$463,628',
        },
        {
            symbol: 'LSXMB',
            name: 'Liberty Media Corporation Series B Liberty SiriusXM Common Stock',
            change: [50],
            volume: '$104',
        },
        {
            symbol: 'LSXMK',
            name: 'Liberty Media Corporation Series C Liberty SiriusXM Common Stock',
            change: [60],
            volume: '$536,190',
        },
        {
            symbol: 'LU',
            name: 'Lufax Holding Ltd American Depositary Shares two of which representing one Ordinary Share',
            change: [20],
            volume: '$4,100,084',
        },
        {
            symbol: 'LULU',
            name: 'lululemon athletica inc. Common Stock',
            change: [50],
            volume: '$712,315',
        },
        {
            symbol: 'LUMN',
            name: 'Lumen Technologies Inc. Common Stock',
            change: [20],
            volume: '$5,861,765',
        },
        {
            symbol: 'LUV',
            name: 'Southwest Airlines Company Common Stock',
            change: [10],
            volume: '$5,201,820',
        },
        {
            symbol: 'LVS',
            name: 'Las Vegas Sands Corp. Common Stock',
            change: [50],
            volume: '$5,753,963',
        },
        {
            symbol: 'LYB',
            name: 'LyondellBasell Industries NV Ordinary Shares Class A (Netherlands)',
            change: [100],
            volume: '$2,905,806',
        },
        {
            symbol: 'LYFT',
            name: 'Lyft Inc. Class A Common Stock',
            change: [50],
            volume: '$3,746,738',
        },
        {
            symbol: 'LYG',
            name: 'Lloyds Banking Group Plc American Depositary Shares',
            change: [20],
            volume: '$6,615,944',
        },
        {
            symbol: 'LYV',
            name: 'Live Nation Entertainment Inc. Common Stock',
            change: [70],
            volume: '$744,395',
        },
        {
            symbol: 'MA',
            name: 'Mastercard Incorporated Common Stock',
            change: [70],
            volume: '$5,170,513',
        },
        {
            symbol: 'MAA',
            name: 'Mid-America Apartment Communities Inc. Common Stock',
            change: [50],
            volume: '$526,962',
        },
        {
            symbol: 'MANH',
            name: 'Manhattan Associates Inc. Common Stock',
            change: [30],
            volume: '$296,149',
        },
        {
            symbol: 'MAR',
            name: 'Marriott International Class A Common Stock',
            change: [30],
            volume: '$1,354,782',
        },
        {
            symbol: 'MAS',
            name: 'Masco Corporation Common Stock',
            change: [60],
            volume: '$1,110,051',
        },
        {
            symbol: 'MASI',
            name: 'Masimo Corporation Common Stock',
            change: [100],
            volume: '$108,534',
        },
        {
            symbol: 'MCD',
            name: "McDonald's Corporation Common Stock",
            change: [40],
            volume: '$1,339,267',
        },
        {
            symbol: 'MCFE',
            name: 'McAfee Corp. Class A Common Stock',
            change: [90],
            volume: '$459,965',
        },
        {
            symbol: 'MCHP',
            name: 'Microchip Technology Incorporated Common Stock',
            change: [100],
            volume: '$1,038,651',
        },
        {
            symbol: 'MCK',
            name: 'McKesson Corporation Common Stock',
            change: [30],
            volume: '$508,270',
        },
    ];
}
