export enum ModuleNames {
    ChartsModule = "chartsModule",
    ViewportRowModelModule = "viewportRowModelModule",
    InfiniteRowModelModule = "infiniteRowModelModule",
    ClientSideRowModelModule = "clientSideRowModelModule",
    ServerSideRowModelModule = "serverSideRowModelModule",
    RowGroupingModule = "rowGroupingModule",
    CsvExportModule = "csvExportModule",
    ExcelExportModule = "excelExportModule",
    ClipboardModule = "clipboardModule",
    ColumnToolPanelModule = "columnToolPanelModule",
    FiltersToolPanelModule = "filtersToolPanelModule",
    MenuModule = "menuModule",
    SetFilterModule = "setFilterModule",
    StatusBarModule = "statusBarModule",
    SideBarModule = "sideBarModule",
}
