export const COUNTRY_CODES: Record<string, string> = {
    Afghanistan: 'af',
    Algeria: 'dz',
    Argentina: 'ar',
    Armenia: 'am',
    Australia: 'au',
    Austria: 'at',
    Azerbaijan: 'az',
    Bahamas: 'bs',
    Bahrain: 'bh',
    Barbados: 'bb',
    Belarus: 'by',
    Belgium: 'be',
    Botswana: 'bw',
    Brazil: 'br',
    Bulgaria: 'bg',
    Cameroon: 'cm',
    Canada: 'ca',
    Chile: 'cl',
    China: 'cn',
    'Chinese Taipei': 'tw',
    Colombia: 'co',
    'Costa Rica': 'cr',
    Croatia: 'hr',
    Cuba: 'cu',
    Cyprus: 'cy',
    'Czech Republic': 'cz',
    Denmark: 'dk',
    'Dominican Republic': 'do',
    Ecuador: 'ec',
    Egypt: 'eg',
    Eritrea: 'er',
    Estonia: 'ee',
    Ethiopia: 'et',
    Finland: 'fi',
    France: 'fr',
    Gabon: 'ga',
    Georgia: 'ge',
    Germany: 'de',
    'Great Britain': 'gb',
    Greece: 'gr',
    Grenada: 'gd',
    Guatemala: 'gt',
    'Hong Kong': 'hk',
    Hungary: 'hu',
    Iceland: 'is',
    India: 'in',
    Indonesia: 'id',
    Iran: 'ir',
    Ireland: 'ie',
    Israel: 'il',
    Italy: 'it',
    Jamaica: 'jm',
    Japan: 'jp',
    Kazakhstan: 'kz',
    Kenya: 'ke',
    Kuwait: 'kw',
    Kyrgyzstan: 'kg',
    Latvia: 'lv',
    Lithuania: 'lt',
    Macedonia: 'mk',
    Malaysia: 'my',
    Mauritius: 'mu',
    Mexico: 'mx',
    Moldova: 'md',
    Mongolia: 'mn',
    Montenegro: 'me',
    Morocco: 'ma',
    Mozambique: 'mz',
    Netherlands: 'nl',
    'New Zealand': 'nz',
    Nigeria: 'ng',
    'North Korea': 'kp',
    Norway: 'no',
    Panama: 'pa',
    Paraguay: 'py',
    Poland: 'pl',
    Portugal: 'pt',
    'Puerto Rico': 'pr',
    Qatar: 'qa',
    Romania: 'ro',
    Russia: 'ru',
    'Saudi Arabia': 'sa',
    Serbia: 'rs',
    'Serbia and Montenegro': 'rs',
    Singapore: 'sg',
    Slovakia: 'sk',
    Slovenia: 'si',
    'South Africa': 'za',
    'South Korea': 'kr',
    Spain: 'es',
    'Sri Lanka': 'lk',
    Sudan: 'sd',
    Sweden: 'se',
    Switzerland: 'ch',
    Syria: 'sy',
    Tajikistan: 'tj',
    Thailand: 'th',
    Togo: 'tg',
    'Trinidad and Tobago': 'tt',
    Tunisia: 'tn',
    Turkey: 'tr',
    Uganda: 'ug',
    Ukraine: 'ua',
    'United Arab Emirates': 'ae',
    'United States': 'us',
    Uruguay: 'uy',
    Uzbekistan: 'uz',
    Venezuela: 've',
    Vietnam: 'vn',
    Zimbabwe: 'zw',
};
