//
// NOTE: THIS FILE IS GENERATED DO NOT EDIT IT DIRECTLY!
// It can be regenerated by running `npm run codegen` or
// `npm run codegen:watch` to regenerate on changes.
//

import { definePart } from './theme-utils';
import * as helpers from './css-helpers';

export type BorderStyle = 'solid' | 'dotted' | 'dashed' | 'none';

export type CoreParam =
  | 'backgroundColor'
  | 'foregroundColor'
  | 'accentColor'
  | 'borderColor'
  | 'wrapperBorder'
  | 'headerBorder'
  | 'rowBorder'
  | 'footerBorder'
  | 'columnBorder'
  | 'pinnedColumnBorder'
  | 'pinnedRowBorder'
  | 'sidePanelBorder'
  | 'sideButtonSelectedBorder'
  | 'sideButtonSelectedBackgroundColor'
  | 'sideBarBackgroundColor'
  | 'fontFamily'
  | 'chromeBackgroundColor'
  | 'headerBackgroundColor'
  | 'headerFontWeight'
  | 'headerForegroundColor'
  | 'dataColor'
  | 'rangeSelectionBorderStyle'
  | 'rangeSelectionBorderColor'
  | 'rangeSelectionBackgroundColor'
  | 'rangeSelectionChartBackgroundColor'
  | 'rangeSelectionChartCategoryBackgroundColor'
  | 'rangeSelectionHighlightColor'
  | 'rowHoverColor'
  | 'columnHoverColor'
  | 'selectedRowBackgroundColor'
  | 'modalOverlayBackgroundColor'
  | 'oddRowBackgroundColor'
  | 'borderRadius'
  | 'wrapperBorderRadius'
  | 'cellWidgetSpacing'
  | 'labelWidgetSpacing'
  | 'rowGroupIndentSize'
  | 'valueChangeDeltaUpColor'
  | 'valueChangeDeltaDownColor'
  | 'valueChangeValueHighlightBackgroundColor'
  | 'gridSize'
  | 'cellHorizontalPadding'
  | 'fontSize'
  | 'rowHeight'
  | 'headerHeight'
  | 'popupShadow'
  | 'dropdownShadow'
  | 'dragGhostBackgroundColor'
  | 'dragGhostBorder'
  | 'insetFocusShadow'
  | 'sideBarPanelWidth'
  | 'headerColumnResizeHandleDisplay'
  | 'headerColumnResizeHandleHeight'
  | 'headerColumnResizeHandleWidth'
  | 'headerColumnResizeHandleColor'
  | 'widgetContainerHorizontalPadding'
  | 'widgetContainerVerticalPadding';

export type ColorsPreset = 'light' | 'dark';

export type ColorsParam = 'colorsPreset';

export type BordersPreset = 'horizontal' | 'default' | 'full';

export type BordersParam = 'bordersPreset';

export type QuartzIconsPreset = 'light' | 'regular' | 'bold';

export type QuartzIconsParam = 'quartzIconsPreset' | 'iconSize' | 'iconStrokeWidth';

import sidebarCssImport from './css/core/sidebar.css?inline';
import rootCssImport from './css/core/root.css?inline';
import resetCssImport from './css/core/reset.css?inline';
import pinnedColumnsCssImport from './css/core/pinned-columns.css?inline';
import headerCssImport from './css/core/header.css?inline';
import gridLayoutCssImport from './css/core/grid-layout.css?inline';
import gridBordersCssImport from './css/core/grid-borders.css?inline';
import dragAndDropCssImport from './css/core/drag-and-drop.css?inline';
import columnFiltersCssImport from './css/core/column-filters.css?inline';
import columnDropCssImport from './css/core/column-drop.css?inline';
import bordersTodoMoveIntoComponentFilesCssImport from './css/core/borders-todo-move-into-component-files.css?inline';
import advancedFilterCssImport from './css/core/advanced-filter.css?inline';

export const core = definePart<CoreParam>({
  partId: 'core',
  defaults: {
    backgroundColor: '#FFF',
    foregroundColor: '#181d1f',
    accentColor: '#2196f3',
    borderColor: helpers.transparentForeground(0.15),
    wrapperBorder: true,
    headerBorder: true,
    rowBorder: true,
    footerBorder: true,
    columnBorder: false,
    pinnedColumnBorder: true,
    pinnedRowBorder: true,
    sidePanelBorder: true,
    sideButtonSelectedBorder: true,
    sideButtonSelectedBackgroundColor: helpers.ref('backgroundColor'),
    sideBarBackgroundColor: helpers.ref('chromeBackgroundColor'),
    fontFamily:
      "'IBM Plex Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen-Sans, Ubuntu, Cantarell, 'Helvetica Neue', sans-serif",
    chromeBackgroundColor: helpers.transparentForeground(0.02),
    headerBackgroundColor: helpers.ref('chromeBackgroundColor'),
    headerFontWeight: '500',
    headerForegroundColor: helpers.ref('foregroundColor'),
    dataColor: helpers.ref('foregroundColor'),
    rangeSelectionBorderStyle: 'solid',
    rangeSelectionBorderColor: helpers.ref('accentColor'),
    rangeSelectionBackgroundColor: helpers.transparentAccent(0.2),
    rangeSelectionChartBackgroundColor: '#0058FF1A',
    rangeSelectionChartCategoryBackgroundColor: '#00FF841A',
    rangeSelectionHighlightColor: helpers.transparentAccent(0.5),
    rowHoverColor: helpers.transparentAccent(0.12),
    columnHoverColor: helpers.transparentAccent(0.05),
    selectedRowBackgroundColor: helpers.transparentAccent(0.08),
    modalOverlayBackgroundColor: helpers.transparentBackground(0.08),
    oddRowBackgroundColor: helpers.ref('backgroundColor'),
    borderRadius: '4px',
    wrapperBorderRadius: '8px',
    cellWidgetSpacing: helpers.calc('gridSize * 1.5'),
    labelWidgetSpacing: helpers.ref('gridSize'),
    rowGroupIndentSize: helpers.calc('cellWidgetSpacing + iconSize'),
    valueChangeDeltaUpColor: '#43a047',
    valueChangeDeltaDownColor: '#e53935',
    valueChangeValueHighlightBackgroundColor: '#16a08580',
    gridSize: '8px',
    cellHorizontalPadding: helpers.calc('gridSize * 2'),
    fontSize: '14px',
    rowHeight: helpers.calc('fontSize + gridSize * 3.5'),
    headerHeight: helpers.calc('fontSize + gridSize * 4.25'),
    popupShadow: '0 0 16px 0 #00000026',
    dropdownShadow: '0 1px 4px 1px #babfc766',
    dragGhostBackgroundColor: helpers.ref('backgroundColor'),
    dragGhostBorder: true,
    insetFocusShadow: 'inset 0 0 5px var(--ag-accent-color)',
    sideBarPanelWidth: '250px',
    headerColumnResizeHandleDisplay: 'block',
    headerColumnResizeHandleHeight: '30%',
    headerColumnResizeHandleWidth: '2px',
    headerColumnResizeHandleColor: helpers.ref('borderColor'),
    widgetContainerHorizontalPadding: helpers.calc('gridSize * 1.5'),
    widgetContainerVerticalPadding: helpers.calc('gridSize * 1.5'),
  },
  css: [
    sidebarCssImport,
    rootCssImport,
    resetCssImport,
    pinnedColumnsCssImport,
    headerCssImport,
    gridLayoutCssImport,
    gridBordersCssImport,
    dragAndDropCssImport,
    columnFiltersCssImport,
    columnDropCssImport,
    bordersTodoMoveIntoComponentFilesCssImport,
    advancedFilterCssImport,
  ],
});

export const colors = definePart<ColorsParam>({
  partId: 'colors',
  presets: {
    light: {},
    dark: {
      backgroundColor: '#1f2836',
      foregroundColor: '#FFF',
    },
  },
  defaults: {
    colorsPreset: null,
  },
});

export const borders = definePart<BordersParam>({
  partId: 'borders',
  presets: {
    horizontal: {
      wrapperBorder: false,
      sidePanelBorder: false,
    },
    default: {},
    full: {
      columnBorder: true,
    },
  },
  defaults: {
    bordersPreset: null,
  },
});

import quartzIconsCssImport from './css/quartz-icons/quartz-icons.css?inline';
import quartzIconsEmbeddedTsImport from './css/quartz-icons/quartz-icons-embedded';

export const quartzIcons = definePart<QuartzIconsParam>({
  partId: 'quartz-icons',
  presets: {
    light: {
      iconStrokeWidth: '1px',
    },
    regular: {},
    bold: {
      iconStrokeWidth: '2px',
    },
  },
  defaults: {
    quartzIconsPreset: null,
    iconSize: '16px',
    iconStrokeWidth: '1.5px',
  },
  css: [quartzIconsCssImport, quartzIconsEmbeddedTsImport],
});

export type ParamTypes = {
  /**
   * Background colour of the grid. The default is white - if you override this, ensure that there is enough contrast between the foreground and background.
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default "#FFF"
   */
  backgroundColor: string;

  /**
   * Foreground colour of the grid, and default text colour. The default is black - if you override this, ensure that there is enough contrast between the foreground and background.
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default "#181d1f"
   */
  foregroundColor: string;

  /**
   * The 'brand colour' for the grid, used wherever a non-neutral colour is required. Selections, focus outlines and checkboxes use the accent colour by default.
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default "#2196f3"
   */
  accentColor: string;

  /**
   * Default colour for borders.
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default transparentForeground(0.15)
   */
  borderColor: string;

  /**
   * Borders around the outside of the grid
   *
   * A CSS border value e.g. "solid 1px red". Passing true is equivalent to "solid 1px var(--ag-border-color)", and false to "none".
   *
   * @default true
   */
  wrapperBorder: string | boolean;

  /**
   * Borders between and below header rows.
   *
   * A CSS border value e.g. "solid 1px red". Passing true is equivalent to "solid 1px var(--ag-border-color)", and false to "none".
   *
   * @default true
   */
  headerBorder: string | boolean;

  /**
   * Borders between rows.
   *
   * A CSS border value e.g. "solid 1px red". Passing true is equivalent to "solid 1px var(--ag-border-color)", and false to "none".
   *
   * @default true
   */
  rowBorder: string | boolean;

  /**
   * Horizontal borders above footer components like the pagination and status bars
   *
   * A CSS border value e.g. "solid 1px red". Passing true is equivalent to "solid 1px var(--ag-border-color)", and false to "none".
   *
   * @default true
   */
  footerBorder: string | boolean;

  /**
   * Vertical borders separating columns.
   *
   * A CSS border value e.g. "solid 1px red". Passing true is equivalent to "solid 1px var(--ag-border-color)", and false to "none".
   *
   * @default false
   */
  columnBorder: string | boolean;

  /**
   * Borders between the grid and columns that are pinned to the left or right
   *
   * A CSS border value e.g. "solid 1px red". Passing true is equivalent to "solid 1px var(--ag-border-color)", and false to "none".
   *
   * @default true
   */
  pinnedColumnBorder: string | boolean;

  /**
   * Borders between the grid and rows that are pinned to the top or bottom
   *
   * A CSS border value e.g. "solid 1px red". Passing true is equivalent to "solid 1px var(--ag-border-color)", and false to "none".
   *
   * @default true
   */
  pinnedRowBorder: string | boolean;

  /**
   * Borders between the grid and side panels including the column and filter tool bars, and chart settings
   *
   * A CSS border value e.g. "solid 1px red". Passing true is equivalent to "solid 1px var(--ag-border-color)", and false to "none".
   *
   * @default true
   */
  sidePanelBorder: string | boolean;

  /**
   * Border around the selected sidebar button on the side panel
   *
   * A CSS border value e.g. "solid 1px red". Passing true is equivalent to "solid 1px var(--ag-border-color)", and false to "none".
   *
   * @default true
   */
  sideButtonSelectedBorder: string | boolean;

  /**
   * Border around the selected sidebar button on the side panel
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default ref("backgroundColor")
   */
  sideButtonSelectedBackgroundColor: string;

  /**
   * Background colour for non-data areas of the grid. Headers, tool panels and menus use this colour by default.
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default ref("chromeBackgroundColor")
   */
  sideBarBackgroundColor: string;

  /**
   * Font family used for all text.
   *
   * Any valid CSS expression is accepted.
   *
   * @default "'IBM Plex Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen-Sans, Ubuntu, Cantarell, 'Helvetica Neue', sans-serif"
   */
  fontFamily: string;

  /**
   * Background colour for non-data areas of the grid. Headers, tool panels and menus use this colour by default.
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default transparentForeground(0.02)
   */
  chromeBackgroundColor: string;

  /**
   * Background colour for header and header-like.
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default ref("chromeBackgroundColor")
   */
  headerBackgroundColor: string;

  /**
   * Weight of text in the header
   *
   * Any valid CSS expression is accepted.
   *
   * @default "500"
   */
  headerFontWeight: string;

  /**
   * Colour of text in the header
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default ref("foregroundColor")
   */
  headerForegroundColor: string;

  /**
   * Colour of text in grid cells.
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default ref("foregroundColor")
   */
  dataColor: string;

  /**
   * Style of the border around range selections.
   *
   * A CSS border-style value e.g. "solid" or "dashed".
   *
   * @default "solid"
   */
  rangeSelectionBorderStyle: BorderStyle;

  /**
   * The color used for borders around range selections. The selection background defaults to a semi-transparent version of this colour.
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default ref("accentColor")
   */
  rangeSelectionBorderColor: string;

  /**
   * Background colour of selected cell ranges. Choosing a semi-transparent colour ensure that multiple overlapping ranges look correct.
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default transparentAccent(0.2)
   */
  rangeSelectionBackgroundColor: string;

  /**
   * Background colour for cells that provide data to the current range chart
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default "#0058FF1A"
   */
  rangeSelectionChartBackgroundColor: string;

  /**
   * Background colour for cells that provide categories to the current range chart
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default "#00FF841A"
   */
  rangeSelectionChartCategoryBackgroundColor: string;

  /**
   * Background colour to briefly apply to a cell range when the user copies from or pastes into it.
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default transparentAccent(0.5)
   */
  rangeSelectionHighlightColor: string;

  /**
   * Background color when hovering over rows in the grid and in dropdown menus. Set to `transparent` to disable the hover effect. Note: if you want a rollover on one but not the other, use CSS selectors instead of this property.
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default transparentAccent(0.12)
   */
  rowHoverColor: string;

  /**
   * Background color when hovering over columns in the grid
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default transparentAccent(0.05)
   */
  columnHoverColor: string;

  /**
   * Background color of selected rows in the grid and in dropdown menus.
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default transparentAccent(0.08)
   */
  selectedRowBackgroundColor: string;

  /**
   * Background color of the overlay shown over the grid e.g. a data loading indicator.
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default transparentBackground(0.08)
   */
  modalOverlayBackgroundColor: string;

  /**
   * Background colour applied to every other row
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default ref("backgroundColor")
   */
  oddRowBackgroundColor: string;

  /**
   * Border radius applied to many elements such as menus, dialogs and form widgets.
   *
   * A CSS number value with length units, e.g. "1px" or "2em". If a JavaScript number is provided, its units are assumed to be 'px'.
   *
   * @default "4px"
   */
  borderRadius: string;

  /**
   * Border radius applied to the outermost container around the grid.
   *
   * A CSS number value with length units, e.g. "1px" or "2em". If a JavaScript number is provided, its units are assumed to be 'px'.
   *
   * @default "8px"
   */
  wrapperBorderRadius: string;

  /**
   * Horizontal spacing between widgets inside cells (e.g. row group expand buttons and row selection checkboxes).
   *
   * A CSS number value with length units, e.g. "1px" or "2em". If a JavaScript number is provided, its units are assumed to be 'px'.
   *
   * @default calc("gridSize * 1.5")
   */
  cellWidgetSpacing: string;

  /**
   * Horizontal spacing between icons and text inside labels, e.g. in the header and sidebar tabs
   *
   * A CSS number value with length units, e.g. "1px" or "2em". If a JavaScript number is provided, its units are assumed to be 'px'.
   *
   * @default ref("gridSize")
   */
  labelWidgetSpacing: string;

  /**
   * The indentation applied to each level of row grouping - deep rows are indented by a multiple of this value.
   *
   * A CSS number value with length units, e.g. "1px" or "2em". If a JavaScript number is provided, its units are assumed to be 'px'.
   *
   * @default calc("cellWidgetSpacing + iconSize")
   */
  rowGroupIndentSize: string;

  /**
   * Colour to temporarily apply to cell data when its value increases in an agAnimateShowChangeCellRenderer cell
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default "#43a047"
   */
  valueChangeDeltaUpColor: string;

  /**
   * Colour to temporarily apply to cell data when its value decreases in an agAnimateShowChangeCellRenderer cell
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default "#e53935"
   */
  valueChangeDeltaDownColor: string;

  /**
   * Colour to apply when a cell value changes and enableCellChangeFlash is enabled
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default "#16a08580"
   */
  valueChangeValueHighlightBackgroundColor: string;

  /**
   * Control how tightly data and UI elements are packed together. All padding and spacing in the grid is defined as a multiple of the grid size, so increasing it will make most components larger by increasing their internal white space while leaving the size of text and icons unchanged.
   *
   * A CSS number value with length units, e.g. "1px" or "2em". If a JavaScript number is provided, its units are assumed to be 'px'.
   *
   * @default "8px"
   */
  gridSize: string;

  /**
   * Colour to apply when a cell value changes and enableCellChangeFlash is enabled
   *
   * A CSS number value with length units, e.g. "1px" or "2em". If a JavaScript number is provided, its units are assumed to be 'px'.
   *
   * @default calc("gridSize * 2")
   */
  cellHorizontalPadding: string;

  /**
   * Height of grid rows
   *
   * A CSS number value with length units, e.g. "1px" or "2em". If a JavaScript number is provided, its units are assumed to be 'px'.
   *
   * @default "14px"
   */
  fontSize: string;

  /**
   * Height of grid rows
   *
   * A CSS number value with length units, e.g. "1px" or "2em". If a JavaScript number is provided, its units are assumed to be 'px'.
   *
   * @default calc("fontSize + gridSize * 3.5")
   */
  rowHeight: string;

  /**
   * Height of header rows
   *
   * A CSS number value with length units, e.g. "1px" or "2em". If a JavaScript number is provided, its units are assumed to be 'px'.
   *
   * @default calc("fontSize + gridSize * 4.25")
   */
  headerHeight: string;

  /**
   * Default shadow for elements that float above the grid e.g. dialogs and menus
   *
   * Any valid CSS expression is accepted.
   *
   * @default "0 0 16px 0 #00000026"
   */
  popupShadow: string;

  /**
   * Default shadow for dropdown menus
   *
   * Any valid CSS expression is accepted.
   *
   * @default "0 1px 4px 1px #babfc766"
   */
  dropdownShadow: string;

  /**
   * Background colour of the ghost element when dragging columns
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default ref("backgroundColor")
   */
  dragGhostBackgroundColor: string;

  /**
   * Border colour of the ghost element when dragging columns
   *
   * A CSS border value e.g. "solid 1px red". Passing true is equivalent to "solid 1px var(--ag-border-color)", and false to "none".
   *
   * @default true
   */
  dragGhostBorder: string | boolean;

  /**
   * Border colour of the ghost element when dragging columns
   *
   * Any valid CSS expression is accepted.
   *
   * @default "inset 0 0 5px var(--ag-accent-color)"
   */
  insetFocusShadow: string;

  /**
   * Default width of the sidebar that contains the columns and filters tool panels
   *
   * A CSS number value with length units, e.g. "1px" or "2em". If a JavaScript number is provided, its units are assumed to be 'px'.
   *
   * @default "250px"
   */
  sideBarPanelWidth: string;

  /**
   * Whether to show an indicator of the drag handle on resizable header columns. If hidden, the handle will still be active but invisible.
   *
   * Any valid CSS expression is accepted.
   *
   * @default "block"
   */
  headerColumnResizeHandleDisplay: string;

  /**
   * Height of the drag handle on resizable header columns. Percentage values are relative to the header height.
   *
   * A CSS number value with length units, e.g. "1px" or "2em". If a JavaScript number is provided, its units are assumed to be 'px'.
   *
   * @default "30%"
   */
  headerColumnResizeHandleHeight: string;

  /**
   * Width of the drag handle on resizable header columns.
   *
   * A CSS number value with length units, e.g. "1px" or "2em". If a JavaScript number is provided, its units are assumed to be 'px'.
   *
   * @default "2px"
   */
  headerColumnResizeHandleWidth: string;

  /**
   * Colour of the drag handle on resizable header columns
   *
   * Any valid CSS color expression is accepted. A JavaScript number between 0 and 1 is interpreted as a semi-transparent foreground color.
   *
   * @default ref("borderColor")
   */
  headerColumnResizeHandleColor: string;

  /**
   * The horizontal padding of containers that contain stacked widgets, such as menus and tool panels
   *
   * A CSS number value with length units, e.g. "1px" or "2em". If a JavaScript number is provided, its units are assumed to be 'px'.
   *
   * @default calc("gridSize * 1.5")
   */
  widgetContainerHorizontalPadding: string;

  /**
   * The vertical padding of containers that contain stacked widgets, such as menus and tool panels
   *
   * A CSS number value with length units, e.g. "1px" or "2em". If a JavaScript number is provided, its units are assumed to be 'px'.
   *
   * @default calc("gridSize * 1.5")
   */
  widgetContainerVerticalPadding: string;

  /**
   * Use one of the built-in sets of preset colors values. Available presets are: "light", "dark".
   *
   * Setting a preset provides default values for other properties that you can then override if required.
   *
   * @default null
   */
  colorsPreset: ColorsPreset | null;

  /**
   * Use one of the built-in sets of preset borders values. Available presets are: "horizontal", "default", "full".
   *
   * Setting a preset provides default values for other properties that you can then override if required.
   *
   * @default null
   */
  bordersPreset: BordersPreset | null;

  /**
   * Use one of the built-in sets of preset quartz-icons values. Available presets are: "light", "regular", "bold".
   *
   * Setting a preset provides default values for other properties that you can then override if required.
   *
   * @default null
   */
  quartzIconsPreset: QuartzIconsPreset | null;

  /**
   * Width & height of the icon image.
   *
   * A CSS number value with length units, e.g. "1px" or "2em". If a JavaScript number is provided, its units are assumed to be 'px'.
   *
   * @default "16px"
   */
  iconSize: string;

  /**
   * Width in pixels of lines making up the icon.
   *
   * A CSS number value with length units, e.g. "1px" or "2em". If a JavaScript number is provided, its units are assumed to be 'px'.
   *
   * @default "1.5px"
   */
  iconStrokeWidth: string;
};

export type Param = keyof ParamTypes;

export const allParts = [core, colors, borders, quartzIcons];
