<?php

$getRowNodeApi = [
    ['getRowNode(id)',
    'Returns the row node with the given ID. Works only with the InMemoryRowModel. The row node id is the one you provide with the callback <i>getRowNodeId(data)</i>, otherwise the id is a number auto generated by the grid when the row data is set.'
    ],
    ['forEachNode(callback)',
    'Iterates through each node (row) in the grid and calls the callback for each node. This works similar to the \'forEach\' method on a Javascript array. This is called for every node, ignoring any filtering or sorting applied within the grid. If pagination, then gets called for the currently loaded page. If using infinite row model, then gets called for each page loaded in the page cache.'
    ],
    ['forEachNodeAfterFilter(callback)',
    'Similar to forEachNode, except skips any filtered out data.'
    ],
    ['forEachNodeAfterFilterAndSort(callback)',
    'Similar to forEachNode, except skips any filtered out data and each the callback is called in the order the rows are displayed in the grid.'
    ],
    ['forEachLeafNode(callback)',
    'Similar to forEachNode, except lists all the leaf nodes. This effectively goes through all the data that you provided the grid before the grid did any grouping.'
    ],
    ['getDisplayedRowAtIndex(index)',
    'Returns the displayed rowNode at the riven index.'
    ],
    ['getDisplayedRowCount()',
    'Returns the total number of displayed rows.'
    ]
];

?>