export async function getData(delay: number = 100): Promise<any[]> {
    return new Promise(resolve => setTimeout(() => resolve(generateData()), delay));
}

function generateData(): any[] {
    return [
        { department: 'Other Spending', resource: 'General economic, commercial and labour', total: 18.8, change: -2.8 },
        { department: 'Other Spending', resource: 'Agriculture, forestry, fishing and hunt', total: 6.5, change: 0.3 },
        { department: 'Other Spending', resource: 'Fuel and energy', total: 8.8, change: -40 },
        { department: 'Other Spending', resource: 'Communication', total: 0.2, change: -0.1 },
        { department: 'Other Spending', resource: 'Other industries', total: 0.2, change: -0.1 },
        { department: 'Other Spending', resource: 'R&D Economic affairs', total: 12.6, change: 5.4 },
        { department: 'Other Spending', resource: 'Economic affairs n.e.c.', total: 1.1, change: 0.4 },
        { department: 'Other Spending', resource: 'Waste management', total: 3.4, change: 0.4 },
        { department: 'Other Spending', resource: 'Pollution abatement', total: 1, change: 0.6 },
        { department: 'Other Spending', resource: 'Protection of biodiversity and landscap', total: 0.5, change: 0 },
        { department: 'Other Spending', resource: 'R&D Environmental protection', total: 0.5, change: 0.2 },
        { department: 'Other Spending', resource: 'Environmental protection n.e.c.', total: 2.3, change: 0.6 },
        { department: 'Other Spending', resource: 'Housing development', total: 3.4, change: 0.7 },
        { department: 'Other Spending', resource: 'Community development', total: 0.6, change: 0.1 },
        { department: 'Other Spending', resource: 'Water supply', total: 0.4, change: -0.7 },
        { department: 'Other Spending', resource: 'Housing and community amenities n.e.c.', total: 0.3, change: 0.1 },
        { department: 'Other Spending', resource: 'Recreational and sporting services', total: 0.5, change: -0.5 },
        { department: 'Other Spending', resource: 'Cultural services', total: 2.3, change: -0.3 },
        { department: 'Other Spending', resource: 'Broadcasting and publishing services', total: 7.7, change: 2.6 },
        { department: 'Other Spending', resource: 'Religious and other community services', total: 0.1, change: -0.1 },
        { department: 'Other Spending', resource: 'R&D Recreation, culture and religion', total: 0.2, change: 0.1 },
        { department: 'Other Spending', resource: 'Recreation, culture and religion n.e.c.', total: 0.2, change: 0 },
        { department: 'Other Spending', resource: 'Other Spending', total: 59.4, change: 10.5 },
        { department: 'Education', resource: 'Pre-primary and primary education', total: 1.3, change: 0.2 },
        { department: 'Education', resource: 'Secondary education', total: 43.3, change: 0.4 },
        { department: 'Education', resource: 'Tertiary education', total: 5.1, change: 0.5 },
        { department: 'Education', resource: 'Education not definable by level', total: 1.9, change: 0.8 },
        { department: 'Education', resource: 'Subsidiary services to education', total: 0.8, change: 0 },
        { department: 'Education', resource: 'R&D Education', total: 2.7, change: -0.3 },
        { department: 'Education', resource: 'Education n.e.c.', total: 2.8, change: 0 },
        { department: 'Protection', resource: 'Police services', total: 5.5, change: -0.3 },
        { department: 'Protection', resource: 'Fire-protection services', total: 0.6, change: 0 },
        { department: 'Protection', resource: 'Law courts', total: 8.2, change: 0.3 },
        { department: 'Protection', resource: 'Prisons', total: 7.7, change: 1.6 },
        { department: 'Protection', resource: 'R&D Public order and safety', total: 1, change: -2.6 },
        { department: 'Protection', resource: 'Public order and safety n.e.c.', total: 1.2, change: 0 },
        { department: 'Defence', resource: 'Military defence', total: 50.4, change: 0 },
        { department: 'Defence', resource: 'Foreign military aid', total: 0.4, change: -2.2 },
        { department: 'Defence', resource: 'Foreign economic aid', total: 6.6, change: 1.5 },
        { department: 'Defence', resource: 'R&D Defence', total: 2.6, change: 0.3 },
        { department: 'Defence', resource: 'Defence n.e.c.', total: 0.2, change: 0 },
        { department: 'General Government', resource: 'Executive and legislative organs, finan', total: 19.8, change: -2.3 },
        { department: 'General Government', resource: 'General services', total: 1.5, change: 0 },
        { department: 'General Government', resource: 'R&D General public services', total: 0.5, change: 0.2 },
        { department: 'General Government', resource: 'General public services n.e.c.', total: 0.7, change: 0.3 },
        { department: 'Welfare', resource: 'Family and children', total: 16.8, change: 1.7 },
        { department: 'Welfare', resource: 'Housing', total: 6.2, change: -0.5 },
        { department: 'Welfare', resource: 'Social exclusion n.e.c.', total: 65.4, change: 9.4 },
        { department: 'Welfare', resource: 'Social protection n.e.c.', total: 15.1, change: 3.5 },
        { department: 'Pensions', resource: 'Sickness and disability', total: 61.2, change: 8.7 },
        { department: 'Pensions', resource: 'Old age', total: 141.8, change: 20 },
        { department: 'Health Care', resource: 'Medical service', total: 205.6, change: 9.4 },
        { department: 'Interest', resource: 'Public debt transactions', total: 76.9, change: -29.9 },
        { department: 'Transport', resource: 'Transport', total: 33.7, change: 1.6 },
    ];
}