export function getData(): any[] {
    return [
        {
            firstName: 'Bob',
            lastName: 'Harrison',
            gender: 'Male',
            address: '1197 Thunder Wagon Common, Cataract, RI, 02987-1016, US, (401) 747-0763',
            mood: 'Happy',
            country: 'Ireland',
        },
        {
            firstName: 'Jane',
            lastName: 'Wilson',
            gender: 'Female',
            age: 25,
            address: '3685 Rocky Glade, Showtucket, NU, X1E-9I0, CA, (867) 371-4215',
            mood: 'Sad',
            country: 'Ireland',
        },
        {
            firstName: 'Jane',
            lastName: 'Doe',
            gender: 'Female',
            age: 25,
            address: '3685 Rocky Glade, Showtucket, NU, X1E-9I0, CA, (867) 371-4215',
            mood: 'Sad',
            country: 'Ireland',
        },
        {
            firstName: 'Jane',
            lastName: 'Doe',
            gender: 'Female',
            age: 24,
            address: '3685 Rocky Glade, Showtucket, NU, X1E-9I0, CA, (867) 371-4215',
            mood: 'Sad',
            country: 'Ireland',
        },
        {
            firstName: 'Jane',
            lastName: 'Doe',
            gender: 'Female',
            age: 45,
            address: '3685 Rocky Glade, Showtucket, NU, X1E-9I0, CA, (867) 371-4215',
            mood: 'Sad',
            country: 'Ireland',
        },
        {
            firstName: 'Jane',
            lastName: 'Doe',
            gender: 'Female',
            age: 63,
            address: '3685 Rocky Glade, Showtucket, NU, X1E-9I0, CA, (867) 371-4215',
            mood: 'Sad',
            country: 'Ireland',
        },
        {
            firstName: 'Zahid',
            lastName: 'Khan',
            gender: 'Male',
            age: 56,
            address: '3235 High Forest, Glen Campbell, MS, 39035-6845, US, (601) 638-8186',
            mood: 'Happy',
            country: 'Ireland',
        },
        {
            firstName: 'Jerry',
            lastName: 'Mane',
            gender: 'Male',
            age: 22,
            address: '2234 Sleepy Pony Mall , Drain, DC, 20078-4243, US, (202) 948-3634',
            mood: 'Happy',
            country: 'Ireland',
        },
        {
            firstName: 'Bob',
            lastName: 'Harrison',
            gender: 'Male',
            address: '1197 Thunder Wagon Common, Cataract, RI, 02987-1016, US, (401) 747-0763',
            mood: 'Happy',
            country: 'Ireland',
        },
        {
            firstName: 'Mary',
            lastName: 'Wilson',
            gender: 'Female',
            age: 44,
            address: '3685 Rocky Glade, Showtucket, NU, X1E-9I0, CA, (867) 371-4215',
            mood: 'Sad',
            country: 'Ireland',
        },
        {
            firstName: 'Zahid',
            lastName: 'Khan',
            gender: 'Male',
            age: 12,
            address: '3235 High Forest, Glen Campbell, MS, 39035-6845, US, (601) 638-8186',
            mood: 'Happy',
            country: 'Ireland',
        },
        {
            firstName: 'Jerry',
            lastName: 'Mane',
            gender: 'Male',
            age: 12,
            address: '2234 Sleepy Pony Mall , Drain, DC, 20078-4243, US, (202) 948-3634',
            mood: 'Happy',
            country: 'Ireland',
        },
        {
            firstName: 'Bob',
            lastName: 'Harrison',
            gender: 'Male',
            address: '1197 Thunder Wagon Common, Cataract, RI, 02987-1016, US, (401) 747-0763',
            mood: 'Happy',
            country: 'Ireland',
        },
        {
            firstName: 'Mary',
            lastName: 'Wilson',
            gender: 'Female',
            age: 29,
            address: '3685 Rocky Glade, Showtucket, NU, X1E-9I0, CA, (867) 371-4215',
            mood: 'Sad',
            country: 'Ireland',
        },
        {
            firstName: 'Zahid',
            lastName: 'Khan',
            gender: 'Male',
            age: 87,
            address: '3235 High Forest, Glen Campbell, MS, 39035-6845, US, (601) 638-8186',
            mood: 'Happy',
            country: 'Ireland',
        },
        {
            firstName: 'Jerry',
            lastName: 'Mane',
            gender: 'Male',
            age: 49,
            address: '2234 Sleepy Pony Mall , Drain, DC, 20078-4243, US, (202) 948-3634',
            mood: 'Happy',
            country: 'Ireland',
        },
        {
            firstName: 'Bob',
            lastName: 'Harrison',
            gender: 'Male',
            address: '1197 Thunder Wagon Common, Cataract, RI, 02987-1016, US, (401) 747-0763',
            mood: 'Happy',
            country: 'Ireland',
        },
        {
            firstName: 'Mary',
            lastName: 'Wilson',
            gender: 'Female',
            age: 11,
            address: '3685 Rocky Glade, Showtucket, NU, X1E-9I0, CA, (867) 371-4215',
            mood: 'Sad',
            country: 'Ireland',
        },
        {
            firstName: 'Zahid',
            lastName: 'Khan',
            gender: 'Male',
            age: 12,
            address: '3235 High Forest, Glen Campbell, MS, 39035-6845, US, (601) 638-8186',
            mood: 'Happy',
            country: 'Ireland',
        },
        {
            firstName: 'Jerry',
            lastName: 'Mane',
            gender: 'Male',
            age: 34,
            address: '2234 Sleepy Pony Mall , Drain, DC, 20078-4243, US, (202) 948-3634',
            mood: 'Happy',
            country: 'Ireland',
        },
        {
            firstName: 'Bob',
            lastName: 'Harrison',
            gender: 'Male',
            address: '1197 Thunder Wagon Common, Cataract, RI, 02987-1016, US, (401) 747-0763',
            mood: 'Happy',
            country: 'Ireland',
        },
        {
            firstName: 'Mary',
            lastName: 'Wilson',
            gender: 'Female',
            age: 66,
            address: '3685 Rocky Glade, Showtucket, NU, X1E-9I0, CA, (867) 371-4215',
            mood: 'Sad',
            country: 'Ireland',
        },
        {
            firstName: 'Zahid',
            lastName: 'Khan',
            gender: 'Male',
            age: 77,
            address: '3235 High Forest, Glen Campbell, MS, 39035-6845, US, (601) 638-8186',
            mood: 'Happy',
            country: 'Ireland',
        },
        {
            firstName: 'Jerry',
            lastName: 'Mane',
            gender: 'Male',
            age: 21,
            address: '2234 Sleepy Pony Mall , Drain, DC, 20078-4243, US, (202) 948-3634',
            mood: 'Happy',
            country: 'Ireland',
        },
        {
            firstName: 'Bob',
            lastName: 'Harrison',
            gender: 'Male',
            address: '1197 Thunder Wagon Common, Cataract, RI, 02987-1016, US, (401) 747-0763',
            mood: 'Happy',
            country: 'Ireland',
        },
        {
            firstName: 'Mary',
            lastName: 'Wilson',
            gender: 'Female',
            age: 32,
            address: '3685 Rocky Glade, Showtucket, NU, X1E-9I0, CA, (867) 371-4215',
            mood: 'Sad',
            country: 'Ireland',
        },
        {
            firstName: 'Zahid',
            lastName: 'Khan',
            gender: 'Male',
            age: 43,
            address: '3235 High Forest, Glen Campbell, MS, 39035-6845, US, (601) 638-8186',
            mood: 'Happy',
            country: 'Ireland',
        },
        {
            firstName: 'John',
            lastName: 'Mane',
            gender: 'Male',
            age: 34,
            address: '2234 Sleepy Pony Mall , Drain, DC, 20078-4243, US, (202) 948-3634',
            mood: 'Happy',
            country: 'Ireland',
        },
        {
            firstName: 'Bob',
            lastName: 'Harrison',
            gender: 'Male',
            address: '1197 Thunder Wagon Common, Cataract, RI, 02987-1016, US, (401) 747-0763',
            mood: 'Happy',
            country: 'Ireland',
        },
        {
            firstName: 'Mary',
            lastName: 'Wilson',
            gender: 'Female',
            age: 23,
            address: '3685 Rocky Glade, Showtucket, NU, X1E-9I0, CA, (867) 371-4215',
            mood: 'Sad',
            country: 'Ireland',
        },
        {
            firstName: 'Zahid',
            lastName: 'Khan',
            gender: 'Male',
            age: 19,
            address: '3235 High Forest, Glen Campbell, MS, 39035-6845, US, (601) 638-8186',
            mood: 'Happy',
            country: 'Ireland',
        },
        {
            firstName: 'Jerry',
            lastName: 'Mane',
            gender: 'Male',
            age: 44,
            address: '2234 Sleepy Pony Mall , Drain, DC, 20078-4243, US, (202) 948-3634',
            mood: 'Happy',
            country: 'Ireland',
        },
        {
            firstName: 'Bob',
            lastName: 'Harrison',
            gender: 'Male',
            address: '1197 Thunder Wagon Common, Cataract, RI, 02987-1016, US, (401) 747-0763',
            mood: 'Happy',
            country: 'Ireland',
        },
        {
            firstName: 'Mary',
            lastName: 'Wilson',
            gender: 'Female',
            age: 33,
            address: '3685 Rocky Glade, Showtucket, NU, X1E-9I0, CA, (867) 371-4215',
            mood: 'Sad',
            country: 'Ireland',
        },
    ];
}
