// Type definitions for ag-grid v3.2.2
// Project: http://www.ag-grid.com/
// Definitions by: Niall Crosby <https://github.com/ceolter/>
// Definitions: https://github.com/borisyankov/DefinitelyTyped
import { GridOptions } from "../entities/gridOptions";
export default class AgGridNg2 {
    private elementDef;
    private _agGrid;
    private _initialised;
    private gridOptions;
    private api;
    private columnApi;
    modelUpdated: any;
    cellClicked: any;
    cellDoubleClicked: any;
    cellContextMenu: any;
    cellValueChanged: any;
    cellFocused: any;
    rowSelected: any;
    rowDeselected: any;
    selectionChanged: any;
    beforeFilterChanged: any;
    afterFilterChanged: any;
    filterModified: any;
    beforeSortChanged: any;
    afterSortChanged: any;
    virtualRowRemoved: any;
    rowClicked: any;
    rowDoubleClicked: any;
    ready: any;
    gridSizeChanged: any;
    rowGroupOpened: any;
    columnEverythingChanged: any;
    columnRowGroupChanged: any;
    columnValueChanged: any;
    columnMoved: any;
    columnVisible: any;
    columnGroupOpened: any;
    columnResized: any;
    columnPinnedCountChanged: any;
    virtualPaging: boolean;
    toolPanelSuppressGroups: boolean;
    toolPanelSuppressValues: boolean;
    rowsAlreadyGrouped: boolean;
    suppressRowClickSelection: boolean;
    suppressCellSelection: boolean;
    sortingOrder: string[];
    suppressMultiSort: boolean;
    suppressHorizontalScroll: boolean;
    unSortIcon: boolean;
    rowHeight: number;
    rowBuffer: number;
    enableColResize: boolean;
    enableCellExpressions: boolean;
    enableSorting: boolean;
    enableServerSideSorting: boolean;
    enableFilter: boolean;
    enableServerSideFilter: boolean;
    colWidth: number;
    suppressMenuHide: boolean;
    debug: boolean;
    icons: any;
    angularCompileRows: boolean;
    angularCompileFilters: boolean;
    angularCompileHeaders: boolean;
    localeText: any;
    localeTextFunc: Function;
    groupSuppressAutoColumn: boolean;
    groupSelectsChildren: boolean;
    groupHideGroupColumns: boolean;
    groupIncludeFooter: boolean;
    groupUseEntireRow: boolean;
    groupSuppressRow: boolean;
    groupSuppressBlankHeader: boolean;
    groupColumnDef: any;
    forPrint: boolean;
    context: any;
    rowStyle: any;
    rowClass: any;
    headerCellRenderer: any;
    groupDefaultExpanded: number;
    slaveGrids: GridOptions[];
    rowSelection: string;
    rowDeselection: boolean;
    headerCellTemplate: string;
    rowData: any[];
    floatingTopRowData: any[];
    floatingBottomRowData: any[];
    showToolPanel: boolean;
    groupAggFunction: (nodes: any[]) => void;
    columnDefs: any[];
    datasource: any;
    pinnedColumnCount: number;
    quickFilterText: string;
    headerHeight: number;
    constructor(elementDef: any);
    ngOnInit(): void;
    ngOnChanges(changes: any): void;
    ngOnDestroy(): void;
    private globalEventListener(eventType, event);
}
export declare function initialiseAgGridWithAngular2(ng: any): void;
