export const data = [
    {
        athlete: '',
        age: 0,
        country: 'Unknown',
        year: 2024,
        date: '01/01/2024',
        sport: 'N/A',
        gold: 0,
        silver: 0,
        bronze: 0,
        total: 0,
    },
    {
        athlete: 'Ava Reed',
        age: 24,
        country: 'USA',
        year: 2024,
        date: '07/08/2024',
        sport: 'Swimming',
        gold: 2,
        silver: 1,
        bronze: 2,
        total: 5,
    },
    {
        athlete: 'Ben Carter',
        age: 28,
        country: 'Canada',
        year: 2024,
        date: '08/08/2024',
        sport: 'Rowing',
        gold: 0,
        silver: 1,
        bronze: 1,
        total: 2,
    },
    {
        athlete: 'Chloe Kim',
        age: 22,
        country: 'Korea',
        year: 2024,
        date: '09/08/2024',
        sport: 'Archery',
        gold: 1,
        silver: 2,
        bronze: 1,
        total: 4,
    },
    {
        athlete: 'Diego Mora',
        age: 30,
        country: 'Spain',
        year: 2024,
        date: '10/08/2024',
        sport: 'Cycling',
        gold: 3,
        silver: 1,
        bronze: 1,
        total: 5,
    },
    {
        athlete: 'Ella Stone',
        age: 26,
        country: 'UK',
        year: 2024,
        date: '11/08/2024',
        sport: 'Athletics',
        gold: 0,
        silver: 1,
        bronze: 0,
        total: 1,
    },
    {
        athlete: 'Farah Khan',
        age: 27,
        country: 'India',
        year: 2024,
        date: '12/08/2024',
        sport: 'Shooting',
        gold: 2,
        silver: 2,
        bronze: 1,
        total: 5,
    },
    {
        athlete: 'Hugo Silva',
        age: 29,
        country: 'Brazil',
        year: 2024,
        date: '13/08/2024',
        sport: 'Judo',
        gold: 1,
        silver: 1,
        bronze: 1,
        total: 3,
    },
    {
        athlete: 'Iris Young',
        age: 23,
        country: 'Australia',
        year: 2024,
        date: '14/08/2024',
        sport: 'Surfing',
        gold: 4,
        silver: 1,
        bronze: 1,
        total: 6,
    },
    {
        athlete: 'Jon Park',
        age: 31,
        country: 'Japan',
        year: 2024,
        date: '15/08/2024',
        sport: 'Gymnastics',
        gold: 0,
        silver: 1,
        bronze: 0,
        total: 1,
    },
];
