// Source: https://www.gov.uk/government/statistics/renewable-sources-of-energy-chapter-6-digest-of-united-kingdom-energy-statistics-dukes
export function getData() {
  return [
    {
      year: new Date(1990, 0, 1),
      "Onshore wind": 1,
      "Offshore wind": 0,
      "Solar photovoltaics": 0,
      "Small scale Hydro": 11,
    },
    {
      year: new Date(1991, 0, 1),
      "Onshore wind": 1,
      "Offshore wind": 0,
      "Solar photovoltaics": 0,
      "Small scale Hydro": 12,
    },
    {
      year: new Date(1992, 0, 1),
      "Onshore wind": 3,
      "Offshore wind": 0,
      "Solar photovoltaics": 0,
      "Small scale Hydro": 13,
    },
    {
      year: new Date(1993, 0, 1),
      "Onshore wind": 19,
      "Offshore wind": 0,
      "Solar photovoltaics": 0,
      "Small scale Hydro": 14,
    },
    {
      year: new Date(1994, 0, 1),
      "Onshore wind": 30,
      "Offshore wind": 0,
      "Solar photovoltaics": 0,
      "Small scale Hydro": 14,
    },
    {
      year: new Date(1995, 0, 1),
      "Onshore wind": 34,
      "Offshore wind": 0,
      "Solar photovoltaics": 0,
      "Small scale Hydro": 14,
    },
    {
      year: new Date(1996, 0, 1),
      "Onshore wind": 42,
      "Offshore wind": 0,
      "Solar photovoltaics": 0,
      "Small scale Hydro": 10,
    },
    {
      year: new Date(1997, 0, 1),
      "Onshore wind": 57,
      "Offshore wind": 0,
      "Solar photovoltaics": 0,
      "Small scale Hydro": 14,
    },
    {
      year: new Date(1998, 0, 1),
      "Onshore wind": 75,
      "Offshore wind": 0,
      "Solar photovoltaics": 0,
      "Small scale Hydro": 18,
    },
    {
      year: new Date(1999, 0, 1),
      "Onshore wind": 73,
      "Offshore wind": 0,
      "Solar photovoltaics": 0,
      "Small scale Hydro": 18,
    },
    {
      year: new Date(2000, 0, 1),
      "Onshore wind": 81,
      "Offshore wind": 0,
      "Solar photovoltaics": 0,
      "Small scale Hydro": 18,
    },
    {
      year: new Date(2001, 0, 1),
      "Onshore wind": 83,
      "Offshore wind": 0,
      "Solar photovoltaics": 0,
      "Small scale Hydro": 18,
    },
    {
      year: new Date(2002, 0, 1),
      "Onshore wind": 108,
      "Offshore wind": 0,
      "Solar photovoltaics": 0,
      "Small scale Hydro": 18,
    },
    {
      year: new Date(2003, 0, 1),
      "Onshore wind": 110,
      "Offshore wind": 1,
      "Solar photovoltaics": 0,
      "Small scale Hydro": 13,
    },
    {
      year: new Date(2004, 0, 1),
      "Onshore wind": 149,
      "Offshore wind": 17,
      "Solar photovoltaics": 0,
      "Small scale Hydro": 24,
    },
    {
      year: new Date(2005, 0, 1),
      "Onshore wind": 215,
      "Offshore wind": 35,
      "Solar photovoltaics": 1,
      "Small scale Hydro": 38,
    },
    {
      year: new Date(2006, 0, 1),
      "Onshore wind": 307,
      "Offshore wind": 56,
      "Solar photovoltaics": 1,
      "Small scale Hydro": 41,
    },
    {
      year: new Date(2007, 0, 1),
      "Onshore wind": 386,
      "Offshore wind": 67,
      "Solar photovoltaics": 1,
      "Small scale Hydro": 45,
    },
    {
      year: new Date(2008, 0, 1),
      "Onshore wind": 498,
      "Offshore wind": 115,
      "Solar photovoltaics": 1,
      "Small scale Hydro": 47,
    },
    {
      year: new Date(2009, 0, 1),
      "Onshore wind": 647,
      "Offshore wind": 151,
      "Solar photovoltaics": 2,
      "Small scale Hydro": 49,
    },
    {
      year: new Date(2010, 0, 1),
      "Onshore wind": 621,
      "Offshore wind": 263,
      "Solar photovoltaics": 3,
      "Small scale Hydro": 43,
    },
    {
      year: new Date(2011, 0, 1),
      "Onshore wind": 930,
      "Offshore wind": 443,
      "Solar photovoltaics": 21,
      "Small scale Hydro": 61,
    },
    {
      year: new Date(2012, 0, 1),
      "Onshore wind": 1053,
      "Offshore wind": 654,
      "Solar photovoltaics": 116,
      "Small scale Hydro": 58,
    },
    {
      year: new Date(2013, 0, 1),
      "Onshore wind": 1455,
      "Offshore wind": 986,
      "Solar photovoltaics": 173,
      "Small scale Hydro": 58,
    },
    {
      year: new Date(2014, 0, 1),
      "Onshore wind": 1595,
      "Offshore wind": 1153,
      "Solar photovoltaics": 349,
      "Small scale Hydro": 72,
    },
    {
      year: new Date(2015, 0, 1),
      "Onshore wind": 1965,
      "Offshore wind": 1498,
      "Solar photovoltaics": 648,
      "Small scale Hydro": 85,
    },
    {
      year: new Date(2016, 0, 1),
      "Onshore wind": 1785,
      "Offshore wind": 1411,
      "Solar photovoltaics": 894,
      "Small scale Hydro": 87,
    },
    {
      year: new Date(2017, 0, 1),
      "Onshore wind": 2470,
      "Offshore wind": 1798,
      "Solar photovoltaics": 985,
      "Small scale Hydro": 112,
    },
    {
      year: new Date(2018, 0, 1),
      "Onshore wind": 2612,
      "Offshore wind": 2281,
      "Solar photovoltaics": 1089,
      "Small scale Hydro": 111,
    },
    {
      year: new Date(2019, 0, 1),
      "Onshore wind": 2739,
      "Offshore wind": 2749,
      "Solar photovoltaics": 1068,
      "Small scale Hydro": 120,
    },
    {
      year: new Date(2020, 0, 1),
      "Onshore wind": 3004,
      "Offshore wind": 3498,
      "Solar photovoltaics": 1109,
      "Small scale Hydro": 134,
    },
    {
      year: new Date(2021, 0, 1),
      "Onshore wind": 2507,
      "Offshore wind": 3053,
      "Solar photovoltaics": 1044,
      "Small scale Hydro": 119,
    },
  ]
}
