export const getData = () => [
    { productName: 'Laptop', salesRevenue: 15000, profitMargin: 0.25, status: 'Delivered' },
    { productName: 'Shirt', salesRevenue: 500, profitMargin: 0.03, status: 'Cancelled' },
    { productName: 'Smartphone', salesRevenue: 9500, profitMargin: 0.18, status: 'Cancelled' },
    { productName: 'Bananas', salesRevenue: 8000, profitMargin: 0.15, status: 'Delivered' },
    { productName: 'Tablet', salesRevenue: 14000, profitMargin: 0.22, status: 'Pending' },
    { productName: 'Jeans', salesRevenue: 250, profitMargin: 0.1, status: 'Cancelled' },
    { productName: 'TV', salesRevenue: 4500, profitMargin: 0.35, status: 'Delivered' },
    { productName: 'Headphones', salesRevenue: 9000, profitMargin: 0.2, status: 'Cancelled' },
    { productName: 'Coffee Maker', salesRevenue: 12000, profitMargin: 0.18, status: 'Delivered' },
    { productName: 'Microwave', salesRevenue: 11250, profitMargin: 0.12, status: 'Pending' },
    { productName: 'Washing Machine', salesRevenue: 21000, profitMargin: 0.3, status: 'Delivered' },
    { productName: 'Refrigerator', salesRevenue: 350, profitMargin: 0.32, status: 'Cancelled' },
    { productName: 'Sofa', salesRevenue: 15000, profitMargin: 0.28, status: 'Delivered' },
    { productName: 'Dining Table', salesRevenue: 18000, profitMargin: 0.3, status: 'Pending' },
    { productName: 'Bed', salesRevenue: 25000, profitMargin: 0.35, status: 'Delivered' },
    { productName: 'Wardrobe', salesRevenue: 125, profitMargin: 0.22, status: 'Cancelled' },
    { productName: 'Bookshelf', salesRevenue: 8000, profitMargin: 0.1, status: 'Delivered' },
    { productName: 'Pencil', salesRevenue: 1000, profitMargin: 0.05, status: 'Delivered' },
    { productName: 'Notebook', salesRevenue: 375, profitMargin: 0.08, status: 'Delivered' },
    { productName: 'Desk', salesRevenue: 50, profitMargin: 0.2, status: 'Cancelled' },
    { productName: 'Chair', salesRevenue: 10000, profitMargin: 0.25, status: 'Delivered' },
    { productName: 'Socks', salesRevenue: 1000, profitMargin: 0.05, status: 'Delivered' },
    { productName: 'T-Shirt', salesRevenue: 3000, profitMargin: 0.15, status: 'Delivered' },
    { productName: 'Jacket', salesRevenue: 12000, profitMargin: 0.18, status: 'Cancelled' },
    { productName: 'Hat', salesRevenue: 4500, profitMargin: 0.1, status: 'Delivered' },
    { productName: 'Scarf', salesRevenue: 2400, profitMargin: 0.12, status: 'Pending' },
    { productName: 'Sunglasses', salesRevenue: 7500, profitMargin: 0.25, status: 'Delivered' },
    { productName: 'Belt', salesRevenue: 4000, profitMargin: 0.12, status: 'Cancelled' },
    { productName: 'Watch', salesRevenue: 14000, profitMargin: 0.28, status: 'Delivered' },
    { productName: 'Wallet', salesRevenue: 13500, profitMargin: 0.22, status: 'Pending' },
    { productName: 'Necklace', salesRevenue: 9000, profitMargin: 0.3, status: 'Delivered' },
    { productName: 'Bracelet', salesRevenue: 13500, profitMargin: 0.25, status: 'Cancelled' },
    { productName: 'Ring', salesRevenue: 17500, profitMargin: 0.3, status: 'Delivered' },
    { productName: 'Blender', salesRevenue: 7500, profitMargin: 0.2, status: 'Pending' },
    { productName: 'Toaster', salesRevenue: 6000, profitMargin: 0.15, status: 'Delivered' },
    { productName: 'Mixer', salesRevenue: 13500, profitMargin: 0.18, status: 'Cancelled' },
    { productName: 'Iron', salesRevenue: 8000, profitMargin: 0.2, status: 'Delivered' },
    { productName: 'Vacuum Cleaner', salesRevenue: 18000, profitMargin: 0.3, status: 'Pending' },
    { productName: 'Fan', salesRevenue: 10500, profitMargin: 0.25, status: 'Delivered' },
    { productName: 'Air Conditioner', salesRevenue: 40000, profitMargin: 0.35, status: 'Cancelled' },
    { productName: 'Heater', salesRevenue: 15000, profitMargin: 0.28, status: 'Delivered' },
    { productName: 'Dishwasher', salesRevenue: 21000, profitMargin: 0.32, status: 'Pending' },
    { productName: 'Oven', salesRevenue: 25000, profitMargin: 0.3, status: 'Delivered' },
    { productName: 'Grill', salesRevenue: 20000, profitMargin: 0.3, status: 'Cancelled' },
    { productName: 'Blender', salesRevenue: 10000, profitMargin: 0.18, status: 'Delivered' },
    { productName: 'Jeans', salesRevenue: 6000, profitMargin: 0.2, status: 'Pending' },
    { productName: 'Shirt', salesRevenue: 7500, profitMargin: 0.18, status: 'Delivered' },
    { productName: 'Dress', salesRevenue: 13500, profitMargin: 0.22, status: 'Cancelled' },
    { productName: 'Skirt', salesRevenue: 8000, profitMargin: 0.2, status: 'Delivered' },
    { productName: 'Blouse', salesRevenue: 6000, profitMargin: 0.25, status: 'Pending' },
    { productName: 'Coat', salesRevenue: 14000, profitMargin: 0.28, status: 'Delivered' },
    { productName: 'Tie', salesRevenue: 4000, profitMargin: 0.1, status: 'Cancelled' },
    { productName: 'Socks', salesRevenue: 300, profitMargin: 0.15, status: 'Delivered' },
    { productName: 'Sweater', salesRevenue: 75, profitMargin: 0.2, status: 'Pending' },
    { productName: 'Boots', salesRevenue: 16000, profitMargin: 0.3, status: 'Delivered' },
    { productName: 'Sandals', salesRevenue: 10000, profitMargin: 0.2, status: 'Cancelled' },
    { productName: 'Sneakers', salesRevenue: 475, profitMargin: 0.22, status: 'Delivered' },
    { productName: 'Heels', salesRevenue: 14000, profitMargin: 0.25, status: 'Pending' },
    { productName: 'Flip Flops', salesRevenue: 4000, profitMargin: 0.15, status: 'Delivered' },
    { productName: 'Slippers', salesRevenue: 7500, profitMargin: 0.18, status: 'Cancelled' },
    { productName: 'Laptop Bag', salesRevenue: 6000, profitMargin: 0.2, status: 'Delivered' },
    { productName: 'Backpack', salesRevenue: 350, profitMargin: 0.25, status: 'Pending' },
    { productName: 'Briefcase', salesRevenue: 7500, profitMargin: 0.3, status: 'Delivered' },
    { productName: 'Messenger Bag', salesRevenue: 8000, profitMargin: 0.2, status: 'Cancelled' },
    { productName: 'Suitcase', salesRevenue: 8000, profitMargin: 0.18, status: 'Delivered' },
    { productName: 'Travel Mug', salesRevenue: 1000, profitMargin: 0.08, status: 'Delivered' },
    { productName: 'Umbrella', salesRevenue: 900, profitMargin: 0.07, status: 'Cancelled' },
    { productName: 'Sunglasses', salesRevenue: 8000, profitMargin: 0.2, status: 'Cancelled' },
    { productName: 'Gloves', salesRevenue: 7500, profitMargin: 0.15, status: 'Delivered' },
    { productName: 'Beanie', salesRevenue: 2400, profitMargin: 0.12, status: 'Pending' },
    { productName: 'Earmuffs', salesRevenue: 1200, profitMargin: 0.1, status: 'Delivered' },
    { productName: 'Laptop', salesRevenue: 450, profitMargin: 0.28, status: 'Cancelled' },
    { productName: 'Tablet', salesRevenue: 12000, profitMargin: 0.22, status: 'Delivered' },
    { productName: 'Smartphone', salesRevenue: 18000, profitMargin: 0.25, status: 'Pending' },
    { productName: 'Smartwatch', salesRevenue: 10000, profitMargin: 0.2, status: 'Delivered' },
    { productName: 'Headphones', salesRevenue: 12000, profitMargin: 0.18, status: 'Cancelled' },
    { productName: 'Speakers', salesRevenue: 8000, profitMargin: 0.2, status: 'Delivered' },
    { productName: 'Monitor', salesRevenue: 9000, profitMargin: 0.28, status: 'Pending' },
];
