import { _camelCaseToHumanText } from 'ag-stack';

import type { NamedBean } from '../context/bean';
import { BeanStub } from '../context/beanStub';
import type { ColDef, ColGroupDef } from '../entities/colDef';
import type { AutoGenerateColumnDefsOptions } from '../entities/gridOptions';

export class AutoGenerateColumnsService extends BeanStub implements NamedBean {
    beanName = 'autoGenColsSvc' as const;

    public postConstruct(): void {
        const generateColsFunc = () => this.generateColumns();
        generateColsFunc();
        this.addManagedPropertyListener('rowData', generateColsFunc);
        this.addManagedPropertyListener('autoGenerateColumnDefs', generateColsFunc);
    }

    private generateColumns(): void {
        const gos = this.gos;
        const optionValue = gos.get('autoGenerateColumnDefs');
        if (!optionValue) {
            return;
        }

        const rowData = gos.get('rowData');
        if (!rowData || rowData.length === 0) {
            return;
        }

        const config: AutoGenerateColumnDefsOptions = typeof optionValue === 'object' ? optionValue : {};
        const firstRow = rowData[0] as Record<string, unknown>;
        let columnDefs = _buildColumnDefs(firstRow, undefined, config);

        const processCallback = gos.getCallback('processAutoGeneratedColumnDefs');
        if (processCallback) {
            columnDefs = processCallback({ colDefs: columnDefs, rowData });
        }

        gos.updateGridOptions({ options: { columnDefs }, source: 'optionsUpdated' });
    }
}

function _buildColumnDefs(
    obj: Record<string, unknown>,
    prefix: string | undefined,
    config: AutoGenerateColumnDefsOptions
): (ColDef | ColGroupDef)[] {
    const objectValues = config.objectValues ?? 'recurse';
    const arrayValues = config.arrayValues ?? 'include';
    const nullishValues = config.nullishValues ?? 'include';

    const keys = Object.keys(obj);
    const defs: (ColDef | ColGroupDef)[] = [];
    for (let i = 0, len = keys.length; i < len; ++i) {
        const key = keys[i];
        const value = obj[key];
        const field = prefix ? `${prefix}.${key}` : key;

        if (_isPlainObject(value)) {
            if (objectValues === 'recurse') {
                const children = _buildColumnDefs(value as Record<string, unknown>, field, config);
                if (children.length > 0) {
                    defs.push({
                        headerName: _camelCaseToHumanText(key) ?? key,
                        children,
                    });
                }
            } else if (objectValues === 'flat') {
                defs.push(_makeLeafColDef(field, key, prefix));
            }
        } else if (Array.isArray(value)) {
            if (arrayValues === 'include') {
                defs.push(_makeLeafColDef(field, key, prefix));
            }
        } else if (value == null) {
            if (nullishValues === 'include') {
                defs.push(_makeLeafColDef(field, key, prefix));
            }
        } else if (typeof value !== 'function') {
            defs.push(_makeLeafColDef(field, key, prefix));
        }
    }
    return defs;
}

function _makeLeafColDef(field: string, key: string, prefix: string | undefined): ColDef {
    const colDef: ColDef = { field };
    if (prefix) {
        colDef.headerName = _camelCaseToHumanText(key) ?? key;
    }
    return colDef;
}

function _isPlainObject(value: unknown): value is Record<string, unknown> {
    return (
        value !== null &&
        typeof value === 'object' &&
        !Array.isArray(value) &&
        !(value instanceof Date) &&
        Object.getPrototypeOf(value) === Object.prototype
    );
}
