var data = [
    {
        product: 'Palm Oil',
        portfolio: 'Aggressive',
        book: 'GL-62472',
        current: 47219,
        tradeId: 0,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Aggressive',
        book: 'GL-62472',
        current: 84157,
        tradeId: 1,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Aggressive',
        book: 'GL-62472',
        current: 50829,
        tradeId: 2,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Aggressive',
        book: 'GL-62473',
        current: 23098,
        tradeId: 3,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Aggressive',
        book: 'GL-62473',
        current: 4678,
        tradeId: 4,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Aggressive',
        book: 'GL-62473',
        current: 51441,
        tradeId: 5,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Aggressive',
        book: 'GL-62474',
        current: 5966,
        tradeId: 6,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Aggressive',
        book: 'GL-62474',
        current: 11995,
        tradeId: 7,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Aggressive',
        book: 'GL-62474',
        current: 15026,
        tradeId: 8,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Aggressive',
        book: 'GL-62474',
        current: 84306,
        tradeId: 9,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Defensive',
        book: 'GL-62475',
        current: 50343,
        tradeId: 10,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Defensive',
        book: 'GL-62475',
        current: 56278,
        tradeId: 11,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Defensive',
        book: 'GL-62476',
        current: 68880,
        tradeId: 12,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Defensive',
        book: 'GL-62476',
        current: 90513,
        tradeId: 13,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Defensive',
        book: 'GL-62476',
        current: 49321,
        tradeId: 14,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Defensive',
        book: 'GL-62476',
        current: 60558,
        tradeId: 15,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Income',
        book: 'GL-62477',
        current: 88868,
        tradeId: 16,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Income',
        book: 'GL-62477',
        current: 19948,
        tradeId: 17,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Income',
        book: 'GL-62477',
        current: 58216,
        tradeId: 18,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Income',
        book: 'GL-62478',
        current: 82786,
        tradeId: 19,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Income',
        book: 'GL-62478',
        current: 88014,
        tradeId: 20,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Income',
        book: 'GL-62478',
        current: 92169,
        tradeId: 21,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Income',
        book: 'GL-62478',
        current: 90090,
        tradeId: 22,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Income',
        book: 'GL-62479',
        current: 72012,
        tradeId: 23,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Income',
        book: 'GL-62479',
        current: 18826,
        tradeId: 24,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Income',
        book: 'GL-62479',
        current: 2792,
        tradeId: 25,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Income',
        book: 'GL-62479',
        current: 12529,
        tradeId: 26,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Income',
        book: 'GL-62480',
        current: 47307,
        tradeId: 27,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Income',
        book: 'GL-62480',
        current: 62488,
        tradeId: 28,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Income',
        book: 'GL-62480',
        current: 97181,
        tradeId: 29,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Speculative',
        book: 'GL-62481',
        current: 96506,
        tradeId: 30,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Speculative',
        book: 'GL-62481',
        current: 87164,
        tradeId: 31,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Speculative',
        book: 'GL-62481',
        current: 87652,
        tradeId: 32,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Speculative',
        book: 'GL-62481',
        current: 65921,
        tradeId: 33,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Speculative',
        book: 'GL-62482',
        current: 74646,
        tradeId: 34,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Speculative',
        book: 'GL-62482',
        current: 72141,
        tradeId: 35,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Speculative',
        book: 'GL-62482',
        current: 27790,
        tradeId: 36,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Speculative',
        book: 'GL-62483',
        current: 16450,
        tradeId: 37,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Speculative',
        book: 'GL-62483',
        current: 73037,
        tradeId: 38,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Speculative',
        book: 'GL-62484',
        current: 86713,
        tradeId: 39,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Speculative',
        book: 'GL-62484',
        current: 84399,
        tradeId: 40,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Speculative',
        book: 'GL-62484',
        current: 31984,
        tradeId: 41,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Speculative',
        book: 'GL-62484',
        current: 96176,
        tradeId: 42,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Hybrid',
        book: 'GL-62485',
        current: 86310,
        tradeId: 43,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Hybrid',
        book: 'GL-62485',
        current: 20916,
        tradeId: 44,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Hybrid',
        book: 'GL-62485',
        current: 14266,
        tradeId: 45,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Hybrid',
        book: 'GL-62486',
        current: 8799,
        tradeId: 46,
    },
    {
        product: 'Palm Oil',
        portfolio: 'Hybrid',
        book: 'GL-62486',
        current: 11523,
        tradeId: 47,
    },
    {
        product: 'Rubber',
        portfolio: 'Aggressive',
        book: 'GL-62487',
        current: 31334,
        tradeId: 48,
    },
    {
        product: 'Rubber',
        portfolio: 'Aggressive',
        book: 'GL-62487',
        current: 96971,
        tradeId: 49,
    },
    {
        product: 'Rubber',
        portfolio: 'Aggressive',
        book: 'GL-62487',
        current: 62525,
        tradeId: 50,
    },
    {
        product: 'Rubber',
        portfolio: 'Aggressive',
        book: 'GL-62487',
        current: 4083,
        tradeId: 51,
    },
    {
        product: 'Rubber',
        portfolio: 'Aggressive',
        book: 'GL-62488',
        current: 94926,
        tradeId: 52,
    },
    {
        product: 'Rubber',
        portfolio: 'Aggressive',
        book: 'GL-62488',
        current: 27236,
        tradeId: 53,
    },
    {
        product: 'Rubber',
        portfolio: 'Aggressive',
        book: 'GL-62489',
        current: 86257,
        tradeId: 54,
    },
    {
        product: 'Rubber',
        portfolio: 'Aggressive',
        book: 'GL-62489',
        current: 98446,
        tradeId: 55,
    },
    {
        product: 'Rubber',
        portfolio: 'Aggressive',
        book: 'GL-62489',
        current: 40089,
        tradeId: 56,
    },
    {
        product: 'Rubber',
        portfolio: 'Aggressive',
        book: 'GL-62490',
        current: 11542,
        tradeId: 57,
    },
    {
        product: 'Rubber',
        portfolio: 'Aggressive',
        book: 'GL-62490',
        current: 7186,
        tradeId: 58,
    },
    {
        product: 'Rubber',
        portfolio: 'Aggressive',
        book: 'GL-62490',
        current: 11326,
        tradeId: 59,
    },
    {
        product: 'Rubber',
        portfolio: 'Aggressive',
        book: 'GL-62490',
        current: 10429,
        tradeId: 60,
    },
    {
        product: 'Rubber',
        portfolio: 'Defensive',
        book: 'GL-62491',
        current: 29595,
        tradeId: 61,
    },
    {
        product: 'Rubber',
        portfolio: 'Defensive',
        book: 'GL-62491',
        current: 33256,
        tradeId: 62,
    },
    {
        product: 'Rubber',
        portfolio: 'Defensive',
        book: 'GL-62491',
        current: 70631,
        tradeId: 63,
    },
    {
        product: 'Rubber',
        portfolio: 'Defensive',
        book: 'GL-62491',
        current: 74711,
        tradeId: 64,
    },
    {
        product: 'Rubber',
        portfolio: 'Defensive',
        book: 'GL-62492',
        current: 27317,
        tradeId: 65,
    },
    {
        product: 'Rubber',
        portfolio: 'Defensive',
        book: 'GL-62492',
        current: 62930,
        tradeId: 66,
    },
    {
        product: 'Rubber',
        portfolio: 'Defensive',
        book: 'GL-62492',
        current: 34468,
        tradeId: 67,
    },
    {
        product: 'Rubber',
        portfolio: 'Defensive',
        book: 'GL-62492',
        current: 18429,
        tradeId: 68,
    },
    {
        product: 'Rubber',
        portfolio: 'Defensive',
        book: 'GL-62493',
        current: 21450,
        tradeId: 69,
    },
    {
        product: 'Rubber',
        portfolio: 'Defensive',
        book: 'GL-62493',
        current: 42759,
        tradeId: 70,
    },
    {
        product: 'Rubber',
        portfolio: 'Defensive',
        book: 'GL-62493',
        current: 29336,
        tradeId: 71,
    },
    {
        product: 'Rubber',
        portfolio: 'Defensive',
        book: 'GL-62494',
        current: 58534,
        tradeId: 72,
    },
    {
        product: 'Rubber',
        portfolio: 'Defensive',
        book: 'GL-62494',
        current: 16575,
        tradeId: 73,
    },
    {
        product: 'Rubber',
        portfolio: 'Income',
        book: 'GL-62495',
        current: 26683,
        tradeId: 74,
    },
    {
        product: 'Rubber',
        portfolio: 'Income',
        book: 'GL-62495',
        current: 40622,
        tradeId: 75,
    },
    {
        product: 'Rubber',
        portfolio: 'Income',
        book: 'GL-62495',
        current: 63484,
        tradeId: 76,
    },
    {
        product: 'Rubber',
        portfolio: 'Income',
        book: 'GL-62496',
        current: 76283,
        tradeId: 77,
    },
    {
        product: 'Rubber',
        portfolio: 'Income',
        book: 'GL-62496',
        current: 10770,
        tradeId: 78,
    },
    {
        product: 'Rubber',
        portfolio: 'Income',
        book: 'GL-62496',
        current: 41974,
        tradeId: 79,
    },
    {
        product: 'Rubber',
        portfolio: 'Income',
        book: 'GL-62496',
        current: 25978,
        tradeId: 80,
    },
    {
        product: 'Rubber',
        portfolio: 'Income',
        book: 'GL-62497',
        current: 57085,
        tradeId: 81,
    },
    {
        product: 'Rubber',
        portfolio: 'Income',
        book: 'GL-62497',
        current: 80855,
        tradeId: 82,
    },
    {
        product: 'Rubber',
        portfolio: 'Income',
        book: 'GL-62498',
        current: 68127,
        tradeId: 83,
    },
    {
        product: 'Rubber',
        portfolio: 'Income',
        book: 'GL-62498',
        current: 34155,
        tradeId: 84,
    },
    {
        product: 'Rubber',
        portfolio: 'Speculative',
        book: 'GL-62499',
        current: 71129,
        tradeId: 85,
    },
    {
        product: 'Rubber',
        portfolio: 'Speculative',
        book: 'GL-62499',
        current: 12205,
        tradeId: 86,
    },
    {
        product: 'Rubber',
        portfolio: 'Speculative',
        book: 'GL-62500',
        current: 58232,
        tradeId: 87,
    },
    {
        product: 'Rubber',
        portfolio: 'Speculative',
        book: 'GL-62500',
        current: 89594,
        tradeId: 88,
    },
    {
        product: 'Rubber',
        portfolio: 'Speculative',
        book: 'GL-62501',
        current: 64759,
        tradeId: 89,
    },
    {
        product: 'Rubber',
        portfolio: 'Speculative',
        book: 'GL-62501',
        current: 23025,
        tradeId: 90,
    },
    {
        product: 'Rubber',
        portfolio: 'Speculative',
        book: 'GL-62501',
        current: 90050,
        tradeId: 91,
    },
    {
        product: 'Rubber',
        portfolio: 'Speculative',
        book: 'GL-62502',
        current: 57201,
        tradeId: 92,
    },
    {
        product: 'Rubber',
        portfolio: 'Speculative',
        book: 'GL-62502',
        current: 36692,
        tradeId: 93,
    },
    {
        product: 'Rubber',
        portfolio: 'Speculative',
        book: 'GL-62502',
        current: 79330,
        tradeId: 94,
    },
    {
        product: 'Rubber',
        portfolio: 'Hybrid',
        book: 'GL-62503',
        current: 55489,
        tradeId: 95,
    },
    {
        product: 'Rubber',
        portfolio: 'Hybrid',
        book: 'GL-62503',
        current: 12180,
        tradeId: 96,
    },
    {
        product: 'Rubber',
        portfolio: 'Hybrid',
        book: 'GL-62503',
        current: 95857,
        tradeId: 97,
    },
    {
        product: 'Rubber',
        portfolio: 'Hybrid',
        book: 'GL-62504',
        current: 96432,
        tradeId: 98,
    },
    {
        product: 'Rubber',
        portfolio: 'Hybrid',
        book: 'GL-62504',
        current: 68686,
        tradeId: 99,
    },
    {
        product: 'Wool',
        portfolio: 'Aggressive',
        book: 'GL-62505',
        current: 36600,
        tradeId: 100,
    },
    {
        product: 'Wool',
        portfolio: 'Aggressive',
        book: 'GL-62505',
        current: 70421,
        tradeId: 101,
    },
    {
        product: 'Wool',
        portfolio: 'Aggressive',
        book: 'GL-62506',
        current: 69999,
        tradeId: 102,
    },
    {
        product: 'Wool',
        portfolio: 'Aggressive',
        book: 'GL-62506',
        current: 89403,
        tradeId: 103,
    },
    {
        product: 'Wool',
        portfolio: 'Defensive',
        book: 'GL-62507',
        current: 90423,
        tradeId: 104,
    },
    {
        product: 'Wool',
        portfolio: 'Defensive',
        book: 'GL-62507',
        current: 96242,
        tradeId: 105,
    },
    {
        product: 'Wool',
        portfolio: 'Defensive',
        book: 'GL-62508',
        current: 85107,
        tradeId: 106,
    },
    {
        product: 'Wool',
        portfolio: 'Defensive',
        book: 'GL-62508',
        current: 89268,
        tradeId: 107,
    },
    {
        product: 'Wool',
        portfolio: 'Defensive',
        book: 'GL-62508',
        current: 35046,
        tradeId: 108,
    },
    {
        product: 'Wool',
        portfolio: 'Defensive',
        book: 'GL-62509',
        current: 6289,
        tradeId: 109,
    },
    {
        product: 'Wool',
        portfolio: 'Defensive',
        book: 'GL-62509',
        current: 8184,
        tradeId: 110,
    },
    {
        product: 'Wool',
        portfolio: 'Income',
        book: 'GL-62510',
        current: 23909,
        tradeId: 111,
    },
    {
        product: 'Wool',
        portfolio: 'Income',
        book: 'GL-62510',
        current: 21300,
        tradeId: 112,
    },
    {
        product: 'Wool',
        portfolio: 'Income',
        book: 'GL-62510',
        current: 1876,
        tradeId: 113,
    },
    {
        product: 'Wool',
        portfolio: 'Income',
        book: 'GL-62511',
        current: 13551,
        tradeId: 114,
    },
    {
        product: 'Wool',
        portfolio: 'Income',
        book: 'GL-62511',
        current: 96455,
        tradeId: 115,
    },
    {
        product: 'Wool',
        portfolio: 'Income',
        book: 'GL-62512',
        current: 6303,
        tradeId: 116,
    },
    {
        product: 'Wool',
        portfolio: 'Income',
        book: 'GL-62512',
        current: 34072,
        tradeId: 117,
    },
    {
        product: 'Wool',
        portfolio: 'Income',
        book: 'GL-62512',
        current: 95427,
        tradeId: 118,
    },
    {
        product: 'Wool',
        portfolio: 'Speculative',
        book: 'GL-62513',
        current: 70487,
        tradeId: 119,
    },
    {
        product: 'Wool',
        portfolio: 'Speculative',
        book: 'GL-62513',
        current: 59171,
        tradeId: 120,
    },
    {
        product: 'Wool',
        portfolio: 'Speculative',
        book: 'GL-62513',
        current: 61667,
        tradeId: 121,
    },
    {
        product: 'Wool',
        portfolio: 'Speculative',
        book: 'GL-62513',
        current: 16014,
        tradeId: 122,
    },
    {
        product: 'Wool',
        portfolio: 'Speculative',
        book: 'GL-62514',
        current: 6961,
        tradeId: 123,
    },
    {
        product: 'Wool',
        portfolio: 'Speculative',
        book: 'GL-62514',
        current: 17369,
        tradeId: 124,
    },
    {
        product: 'Wool',
        portfolio: 'Hybrid',
        book: 'GL-62515',
        current: 69849,
        tradeId: 125,
    },
    {
        product: 'Wool',
        portfolio: 'Hybrid',
        book: 'GL-62515',
        current: 88171,
        tradeId: 126,
    },
    {
        product: 'Wool',
        portfolio: 'Hybrid',
        book: 'GL-62515',
        current: 956,
        tradeId: 127,
    },
    {
        product: 'Wool',
        portfolio: 'Hybrid',
        book: 'GL-62516',
        current: 66088,
        tradeId: 128,
    },
    {
        product: 'Wool',
        portfolio: 'Hybrid',
        book: 'GL-62516',
        current: 69737,
        tradeId: 129,
    },
    {
        product: 'Wool',
        portfolio: 'Hybrid',
        book: 'GL-62516',
        current: 14140,
        tradeId: 130,
    },
    {
        product: 'Wool',
        portfolio: 'Hybrid',
        book: 'GL-62516',
        current: 61347,
        tradeId: 131,
    },
    {
        product: 'Wool',
        portfolio: 'Hybrid',
        book: 'GL-62517',
        current: 29209,
        tradeId: 132,
    },
    {
        product: 'Wool',
        portfolio: 'Hybrid',
        book: 'GL-62517',
        current: 98225,
        tradeId: 133,
    },
    {
        product: 'Wool',
        portfolio: 'Hybrid',
        book: 'GL-62517',
        current: 79080,
        tradeId: 134,
    },
    {
        product: 'Wool',
        portfolio: 'Hybrid',
        book: 'GL-62518',
        current: 28606,
        tradeId: 135,
    },
    {
        product: 'Wool',
        portfolio: 'Hybrid',
        book: 'GL-62518',
        current: 1865,
        tradeId: 136,
    },
    {
        product: 'Wool',
        portfolio: 'Hybrid',
        book: 'GL-62518',
        current: 9102,
        tradeId: 137,
    },
    {
        product: 'Wool',
        portfolio: 'Hybrid',
        book: 'GL-62518',
        current: 91174,
        tradeId: 138,
    },
    {
        product: 'Amber',
        portfolio: 'Aggressive',
        book: 'GL-62519',
        current: 31399,
        tradeId: 139,
    },
    {
        product: 'Amber',
        portfolio: 'Aggressive',
        book: 'GL-62519',
        current: 38112,
        tradeId: 140,
    },
    {
        product: 'Amber',
        portfolio: 'Aggressive',
        book: 'GL-62519',
        current: 50578,
        tradeId: 141,
    },
    {
        product: 'Amber',
        portfolio: 'Aggressive',
        book: 'GL-62519',
        current: 51407,
        tradeId: 142,
    },
    {
        product: 'Amber',
        portfolio: 'Aggressive',
        book: 'GL-62520',
        current: 59701,
        tradeId: 143,
    },
    {
        product: 'Amber',
        portfolio: 'Aggressive',
        book: 'GL-62520',
        current: 84948,
        tradeId: 144,
    },
    {
        product: 'Amber',
        portfolio: 'Aggressive',
        book: 'GL-62521',
        current: 27681,
        tradeId: 145,
    },
    {
        product: 'Amber',
        portfolio: 'Aggressive',
        book: 'GL-62521',
        current: 83581,
        tradeId: 146,
    },
    {
        product: 'Amber',
        portfolio: 'Aggressive',
        book: 'GL-62521',
        current: 48936,
        tradeId: 147,
    },
    {
        product: 'Amber',
        portfolio: 'Aggressive',
        book: 'GL-62522',
        current: 92374,
        tradeId: 148,
    },
    {
        product: 'Amber',
        portfolio: 'Aggressive',
        book: 'GL-62522',
        current: 28837,
        tradeId: 149,
    },
    {
        product: 'Amber',
        portfolio: 'Aggressive',
        book: 'GL-62522',
        current: 8181,
        tradeId: 150,
    },
    {
        product: 'Amber',
        portfolio: 'Defensive',
        book: 'GL-62523',
        current: 1393,
        tradeId: 151,
    },
    {
        product: 'Amber',
        portfolio: 'Defensive',
        book: 'GL-62523',
        current: 15208,
        tradeId: 152,
    },
    {
        product: 'Amber',
        portfolio: 'Defensive',
        book: 'GL-62524',
        current: 40942,
        tradeId: 153,
    },
    {
        product: 'Amber',
        portfolio: 'Defensive',
        book: 'GL-62524',
        current: 66463,
        tradeId: 154,
    },
    {
        product: 'Amber',
        portfolio: 'Defensive',
        book: 'GL-62524',
        current: 42318,
        tradeId: 155,
    },
    {
        product: 'Amber',
        portfolio: 'Defensive',
        book: 'GL-62524',
        current: 78499,
        tradeId: 156,
    },
    {
        product: 'Amber',
        portfolio: 'Income',
        book: 'GL-62525',
        current: 15803,
        tradeId: 157,
    },
    {
        product: 'Amber',
        portfolio: 'Income',
        book: 'GL-62525',
        current: 90189,
        tradeId: 158,
    },
    {
        product: 'Amber',
        portfolio: 'Income',
        book: 'GL-62526',
        current: 11151,
        tradeId: 159,
    },
    {
        product: 'Amber',
        portfolio: 'Income',
        book: 'GL-62526',
        current: 44348,
        tradeId: 160,
    },
    {
        product: 'Amber',
        portfolio: 'Income',
        book: 'GL-62526',
        current: 69034,
        tradeId: 161,
    },
    {
        product: 'Amber',
        portfolio: 'Income',
        book: 'GL-62526',
        current: 29013,
        tradeId: 162,
    },
    {
        product: 'Amber',
        portfolio: 'Income',
        book: 'GL-62527',
        current: 51021,
        tradeId: 163,
    },
    {
        product: 'Amber',
        portfolio: 'Income',
        book: 'GL-62527',
        current: 5218,
        tradeId: 164,
    },
    {
        product: 'Amber',
        portfolio: 'Income',
        book: 'GL-62527',
        current: 92277,
        tradeId: 165,
    },
    {
        product: 'Amber',
        portfolio: 'Income',
        book: 'GL-62527',
        current: 67888,
        tradeId: 166,
    },
    {
        product: 'Amber',
        portfolio: 'Speculative',
        book: 'GL-62528',
        current: 15627,
        tradeId: 167,
    },
    {
        product: 'Amber',
        portfolio: 'Speculative',
        book: 'GL-62528',
        current: 40676,
        tradeId: 168,
    },
    {
        product: 'Amber',
        portfolio: 'Speculative',
        book: 'GL-62528',
        current: 90009,
        tradeId: 169,
    },
    {
        product: 'Amber',
        portfolio: 'Speculative',
        book: 'GL-62528',
        current: 43977,
        tradeId: 170,
    },
    {
        product: 'Amber',
        portfolio: 'Speculative',
        book: 'GL-62529',
        current: 71031,
        tradeId: 171,
    },
    {
        product: 'Amber',
        portfolio: 'Speculative',
        book: 'GL-62529',
        current: 5553,
        tradeId: 172,
    },
    {
        product: 'Amber',
        portfolio: 'Speculative',
        book: 'GL-62529',
        current: 74742,
        tradeId: 173,
    },
    {
        product: 'Amber',
        portfolio: 'Speculative',
        book: 'GL-62530',
        current: 98007,
        tradeId: 174,
    },
    {
        product: 'Amber',
        portfolio: 'Speculative',
        book: 'GL-62530',
        current: 95909,
        tradeId: 175,
    },
    {
        product: 'Amber',
        portfolio: 'Speculative',
        book: 'GL-62531',
        current: 65144,
        tradeId: 176,
    },
    {
        product: 'Amber',
        portfolio: 'Speculative',
        book: 'GL-62531',
        current: 89147,
        tradeId: 177,
    },
    {
        product: 'Amber',
        portfolio: 'Hybrid',
        book: 'GL-62532',
        current: 44434,
        tradeId: 178,
    },
    {
        product: 'Amber',
        portfolio: 'Hybrid',
        book: 'GL-62532',
        current: 88236,
        tradeId: 179,
    },
    {
        product: 'Amber',
        portfolio: 'Hybrid',
        book: 'GL-62532',
        current: 41887,
        tradeId: 180,
    },
    {
        product: 'Amber',
        portfolio: 'Hybrid',
        book: 'GL-62532',
        current: 13171,
        tradeId: 181,
    },
    {
        product: 'Amber',
        portfolio: 'Hybrid',
        book: 'GL-62533',
        current: 99986,
        tradeId: 182,
    },
    {
        product: 'Amber',
        portfolio: 'Hybrid',
        book: 'GL-62533',
        current: 19674,
        tradeId: 183,
    },
    {
        product: 'Amber',
        portfolio: 'Hybrid',
        book: 'GL-62533',
        current: 4643,
        tradeId: 184,
    },
    {
        product: 'Amber',
        portfolio: 'Hybrid',
        book: 'GL-62533',
        current: 22252,
        tradeId: 185,
    },
    {
        product: 'Amber',
        portfolio: 'Hybrid',
        book: 'GL-62534',
        current: 49758,
        tradeId: 186,
    },
    {
        product: 'Amber',
        portfolio: 'Hybrid',
        book: 'GL-62534',
        current: 18079,
        tradeId: 187,
    },
    {
        product: 'Amber',
        portfolio: 'Hybrid',
        book: 'GL-62534',
        current: 80386,
        tradeId: 188,
    },
    {
        product: 'Amber',
        portfolio: 'Hybrid',
        book: 'GL-62535',
        current: 87401,
        tradeId: 189,
    },
    {
        product: 'Amber',
        portfolio: 'Hybrid',
        book: 'GL-62535',
        current: 47481,
        tradeId: 190,
    },
    {
        product: 'Copper',
        portfolio: 'Aggressive',
        book: 'GL-62536',
        current: 51641,
        tradeId: 191,
    },
    {
        product: 'Copper',
        portfolio: 'Aggressive',
        book: 'GL-62536',
        current: 91643,
        tradeId: 192,
    },
    {
        product: 'Copper',
        portfolio: 'Aggressive',
        book: 'GL-62536',
        current: 62642,
        tradeId: 193,
    },
    {
        product: 'Copper',
        portfolio: 'Aggressive',
        book: 'GL-62536',
        current: 29963,
        tradeId: 194,
    },
    {
        product: 'Copper',
        portfolio: 'Aggressive',
        book: 'GL-62537',
        current: 33693,
        tradeId: 195,
    },
    {
        product: 'Copper',
        portfolio: 'Aggressive',
        book: 'GL-62537',
        current: 37410,
        tradeId: 196,
    },
    {
        product: 'Copper',
        portfolio: 'Aggressive',
        book: 'GL-62537',
        current: 51435,
        tradeId: 197,
    },
    {
        product: 'Copper',
        portfolio: 'Aggressive',
        book: 'GL-62537',
        current: 83191,
        tradeId: 198,
    },
    {
        product: 'Copper',
        portfolio: 'Aggressive',
        book: 'GL-62538',
        current: 31159,
        tradeId: 199,
    },
    {
        product: 'Copper',
        portfolio: 'Aggressive',
        book: 'GL-62538',
        current: 99437,
        tradeId: 200,
    },
    {
        product: 'Copper',
        portfolio: 'Aggressive',
        book: 'GL-62538',
        current: 64024,
        tradeId: 201,
    },
    {
        product: 'Copper',
        portfolio: 'Aggressive',
        book: 'GL-62538',
        current: 38069,
        tradeId: 202,
    },
    {
        product: 'Copper',
        portfolio: 'Defensive',
        book: 'GL-62539',
        current: 33796,
        tradeId: 203,
    },
    {
        product: 'Copper',
        portfolio: 'Defensive',
        book: 'GL-62539',
        current: 87465,
        tradeId: 204,
    },
    {
        product: 'Copper',
        portfolio: 'Defensive',
        book: 'GL-62540',
        current: 33352,
        tradeId: 205,
    },
    {
        product: 'Copper',
        portfolio: 'Defensive',
        book: 'GL-62540',
        current: 21622,
        tradeId: 206,
    },
    {
        product: 'Copper',
        portfolio: 'Defensive',
        book: 'GL-62541',
        current: 4681,
        tradeId: 207,
    },
    {
        product: 'Copper',
        portfolio: 'Defensive',
        book: 'GL-62541',
        current: 93152,
        tradeId: 208,
    },
    {
        product: 'Copper',
        portfolio: 'Defensive',
        book: 'GL-62542',
        current: 77770,
        tradeId: 209,
    },
    {
        product: 'Copper',
        portfolio: 'Defensive',
        book: 'GL-62542',
        current: 9211,
        tradeId: 210,
    },
    {
        product: 'Copper',
        portfolio: 'Defensive',
        book: 'GL-62542',
        current: 55437,
        tradeId: 211,
    },
    {
        product: 'Copper',
        portfolio: 'Defensive',
        book: 'GL-62542',
        current: 43841,
        tradeId: 212,
    },
    {
        product: 'Copper',
        portfolio: 'Income',
        book: 'GL-62543',
        current: 62154,
        tradeId: 213,
    },
    {
        product: 'Copper',
        portfolio: 'Income',
        book: 'GL-62543',
        current: 54932,
        tradeId: 214,
    },
    {
        product: 'Copper',
        portfolio: 'Income',
        book: 'GL-62544',
        current: 78198,
        tradeId: 215,
    },
    {
        product: 'Copper',
        portfolio: 'Income',
        book: 'GL-62544',
        current: 67060,
        tradeId: 216,
    },
    {
        product: 'Copper',
        portfolio: 'Income',
        book: 'GL-62544',
        current: 94615,
        tradeId: 217,
    },
];
