export function getData() {
    const data = [
        {
            product: 'Dreams of You',
            artist: 'David Nearing',
            category: 'Soft Rock',
            year: '1978',
            status: 'active',
            available: 8,
            incoming: 20,
            image: 'dreamsofyou.webp',
            price: 32,
            sold: 18,
            priceIncrease: 5, // in percentage
            variants: 2,
            variantDetails: [
                {
                    title: 'Dreams of You',
                    available: 5,
                    format: 'LP, Album, Reissue',
                    label: 'Amberline Records',
                    cat: 'ARL1978-01',
                    country: 'Worldwide',
                    year: '2024',
                },
                {
                    title: 'Dreams of You',
                    available: 3,
                    format: 'CD, Album, Remastered',
                    label: 'Amberline Records',
                    cat: 'ARCD-78X',
                    country: 'Europe',
                    year: '2024',
                },
            ],
        },
        {
            product: 'Blue Skies',
            artist: 'Maya Allen',
            category: 'Pop',
            year: '2022',
            status: 'outOfStock',
            available: 0,
            incoming: 0,
            image: 'blueskies.webp',
            price: 25,
            sold: 12,
            priceIncrease: 10, // in percentage
            variants: 1,
            variantDetails: [
                {
                    title: 'Blue Skies',
                    available: 0,
                    format: 'LP, Album, Limited Edition, Pink',
                    label: 'Celestia Records',
                    cat: 'CR5050-P',
                    country: 'US',
                    year: '2023',
                },
            ],
        },
        {
            product: 'Heaven',
            artist: 'Velvet Wave',
            category: 'Synth-pop',
            year: '1989',
            status: 'active',
            available: 10,
            incoming: 5,
            image: 'heaven.webp',
            price: 20,
            sold: 5,
            priceIncrease: 10, // in percentage
            variants: 2,
            variantDetails: [
                {
                    title: 'Heaven',
                    available: 4,
                    format: 'CD, Album, Stereo',
                    label: 'NovaCore',
                    cat: 'NC-1989-CD',
                    country: 'USA',
                    year: '2023',
                },
                {
                    title: 'Heaven',
                    available: 6,
                    format: 'LP, Album, Reissue, 180 Gram',
                    label: 'NovaCore',
                    cat: 'NC-1989-LP',
                    country: 'Europe',
                    year: '2024',
                },
            ],
        },
        {
            product: 'Life Matters',
            artist: 'Danielle James',
            category: 'Rhythm & Blues',
            year: '2007',
            status: 'paused',
            available: 4,
            incoming: 15,
            image: 'lifematters.webp',
            price: 28,
            sold: 9,
            priceIncrease: 5, // in percentage
            variants: 2,
            variantDetails: [
                {
                    title: 'Life Matters',
                    available: 2,
                    format: 'LP, Album, Deluxe Edition',
                    label: 'Harmony Soul',
                    cat: 'HSR2007DLX',
                    country: 'Worldwide',
                    year: '2023',
                },
                {
                    title: 'Life Matters',
                    available: 2,
                    format: 'CD, Album',
                    label: 'Harmony Soul',
                    cat: 'HSR2007CD',
                    country: 'Europe',
                    year: '2023',
                },
            ],
        },
        {
            product: 'Lonely Hearts',
            artist: 'Emma Stone',
            category: 'Alt-pop',
            year: '2023',
            status: 'active',
            available: 14,
            incoming: 24,
            image: 'lonelyhearts.webp',
            price: 34,
            sold: 17,
            priceIncrease: 12, // in percentage
            variants: 1,
            variantDetails: [
                {
                    title: 'Lonely Hearts',
                    available: 5,
                    format: '2×LP, Album, Limited Edition',
                    label: 'Veridian Sounds',
                    cat: 'VS-2023-HEART',
                    country: 'Worldwide',
                    year: '2023',
                },
            ],
        },
        {
            product: 'Imaginary Groove',
            artist: 'Leo Collins',
            category: 'Jazz',
            year: '1972',
            status: 'active',
            available: 6,
            incoming: 10,
            image: 'imaginarygroove.webp',
            price: 30,
            sold: 8,
            priceIncrease: 8, // in percentage
            variants: 2,
            variantDetails: [
                {
                    title: 'Imaginary Groove',
                    available: 3,
                    format: 'LP, Album, Stereo',
                    label: 'Kindred Audio',
                    cat: 'KA-72-IG-LP',
                    country: 'Europe',
                    year: '2023',
                },
                {
                    title: 'Imaginary Groove',
                    available: 3,
                    format: 'CD, Album',
                    label: 'Kindred Audio',
                    cat: 'KA-72-IG-CD',
                    country: 'US',
                    year: '2023',
                },
            ],
        },
        {
            product: 'Desert Bloom',
            artist: 'Indigo Ray',
            category: 'Electronic',
            year: '2021',
            status: 'paused',
            available: 3,
            incoming: 7,
            image: 'desertbloom.webp',
            price: 27,
            sold: 11,
            priceIncrease: 6, // in percentage
            variants: 1,
            variantDetails: [
                {
                    title: 'Desert Bloom',
                    available: 3,
                    format: 'LP, Album',
                    label: 'Neon Pulse',
                    cat: 'NP-DB-21',
                    country: 'Worldwide',
                    year: '2023',
                },
            ],
        },
        {
            product: 'Golden Daze',
            artist: 'The Marlowe Sound',
            category: 'Rock',
            year: '1985',
            status: 'active',
            available: 10,
            incoming: 12,
            image: 'goldendaze.webp',
            price: 31,
            sold: 15,
            priceIncrease: 7, // in percentage
            variants: 2,
            variantDetails: [
                {
                    title: 'Golden Daze',
                    available: 6,
                    format: 'LP, Album, Reissue',
                    label: 'Copperline Records',
                    cat: 'CRD-GL85',
                    country: 'USA',
                    year: '2024',
                },
                {
                    title: 'Golden Daze',
                    available: 4,
                    format: 'CD, Album, Remastered',
                    label: 'Copperline Records',
                    cat: 'CRD-GL85-CD',
                    country: 'Europe',
                    year: '2024',
                },
            ],
        },
        {
            product: 'Fragments',
            artist: 'Nova Elle',
            category: 'Trance',
            year: '2020',
            status: 'active',
            available: 5,
            incoming: 9,
            image: 'fragments.webp',
            price: 29,
            sold: 6,
            priceIncrease: 4, // in percentage
            variants: 1,
            variantDetails: [
                {
                    title: 'Fragments',
                    available: 5,
                    format: 'LP, Album, Limited Edition, Glow',
                    label: 'Hyperstream',
                    cat: 'HS-FRAG2020',
                    country: 'Worldwide',
                    year: '2023',
                },
            ],
        },
        {
            product: 'Solstice City',
            artist: 'Aurora Lines',
            category: 'Ambient',
            year: '2022',
            status: 'outOfStock',
            available: 0,
            incoming: 0,
            image: 'solsticecity.webp',
            price: 26,
            sold: 9,
            priceIncrease: 0, // in percentage
            variants: 1,
            variantDetails: [
                {
                    title: 'Solstice City',
                    available: 0,
                    format: 'LP, Album, Transparent Blue',
                    label: 'Lunar Echo',
                    cat: 'LE-SOL22',
                    country: 'Europe',
                    year: '2023',
                },
            ],
        },
    ];
    return data;
}
