import type { IAthlete } from './types';

export const getAthletesData = (): IAthlete[] => {
    return [
        {
            id: '1',
            athlete: 'Natalie Coughlin',
            age: 25,
            country: 'United States',
            year: 2008,
            date: '24/08/2008',
            sport: 'Swimming',
            gold: 1,
            silver: 2,
            bronze: 3,
            total: 6,
        },
        {
            id: '2',
            athlete: 'Aleksey Nemov',
            age: 24,
            country: null,
            year: 2000,
            date: null,
            sport: 'Gymnastics',
            gold: 2,
            silver: 1,
            bronze: 3,
            total: 6,
        },
        {
            id: '3',
            athlete: 'Alicia Coutts',
            age: 24,
            country: 'Australia',
            year: 2012,
            date: '12/08/2012',
            sport: 'Swimming',
            gold: 1,
            silver: 3,
            bronze: 1,
            total: 5,
        },
        {
            id: '4',
            athlete: 'Missy Franklin',
            age: 17,
            country: null,
            year: 2012,
            date: '12/08/2012',
            sport: 'Swimming',
            gold: 4,
            silver: 0,
            bronze: 1,
            total: 5,
        },
        {
            id: '5',
            athlete: 'Ryan Lochte',
            age: null,
            country: 'United States',
            year: 2012,
            date: null,
            sport: 'Swimming',
            gold: 2,
            silver: 2,
            bronze: 1,
            total: 5,
        },
        {
            id: '6',
            athlete: 'Allison Schmitt',
            age: 22,
            country: 'United States',
            year: 2012,
            date: '12/08/2012',
            sport: 'Swimming',
            gold: 3,
            silver: 1,
            bronze: 1,
            total: 5,
        },
        {
            id: '7',
            athlete: 'Natalie Coughlin',
            age: 21,
            country: 'United States',
            year: 2004,
            date: '29/08/2004',
            sport: 'Swimming',
            gold: 2,
            silver: 2,
            bronze: 1,
            total: 5,
        },
        {
            id: '8',
            athlete: 'Dara Torres',
            age: 33,
            country: 'United States',
            year: 2000,
            date: '01/10/2000',
            sport: 'Swimming',
            gold: 2,
            silver: 0,
            bronze: 3,
            total: 5,
        },
        {
            id: '9',
            athlete: 'Cindy Klassen',
            age: null,
            country: 'Canada',
            year: 2006,
            date: '26/02/2006',
            sport: 'Speed Skating',
            gold: 1,
            silver: 2,
            bronze: 2,
            total: 5,
        },
        {
            id: '10',
            athlete: 'Nastia Liukin',
            age: 18,
            country: null,
            year: 2008,
            date: '24/08/2008',
            sport: 'Gymnastics',
            gold: 1,
            silver: 3,
            bronze: 1,
            total: 5,
        },
        {
            id: '11',
            athlete: 'Marit Bjørgen',
            age: 29,
            country: 'Norway',
            year: 2010,
            date: null,
            sport: 'Cross Country Skiing',
            gold: 3,
            silver: 1,
            bronze: 1,
            total: 5,
        },
        {
            id: '12',
            athlete: 'Sun Yang',
            age: null,
            country: 'China',
            year: 2012,
            date: '12/08/2012',
            sport: 'Swimming',
            gold: 2,
            silver: 1,
            bronze: 1,
            total: 4,
        },
        {
            id: '13',
            athlete: 'Kirsty Coventry',
            age: 24,
            country: 'Zimbabwe',
            year: 2008,
            date: '24/08/2008',
            sport: 'Swimming',
            gold: 1,
            silver: 3,
            bronze: 0,
            total: 4,
        },
        {
            id: '14',
            athlete: 'Libby Lenton-Trickett',
            age: 23,
            country: 'Australia',
            year: 2008,
            date: '24/08/2008',
            sport: 'Swimming',
            gold: 2,
            silver: 1,
            bronze: 1,
            total: 4,
        },
        {
            id: '15',
            athlete: 'Ryan Lochte',
            age: 24,
            country: null,
            year: 2008,
            date: null,
            sport: 'Swimming',
            gold: 2,
            silver: 0,
            bronze: 2,
            total: 4,
        },
        {
            id: '16',
            athlete: 'Inge de Bruijn',
            age: null,
            country: 'Netherlands',
            year: 2004,
            date: '29/08/2004',
            sport: 'Swimming',
            gold: 1,
            silver: 1,
            bronze: 2,
            total: 4,
        },
        {
            id: '17',
            athlete: 'Petria Thomas',
            age: 28,
            country: 'Australia',
            year: 2004,
            date: '29/08/2004',
            sport: 'Swimming',
            gold: 3,
            silver: 1,
            bronze: 0,
            total: 4,
        },
        {
            id: '18',
            athlete: 'Ian Thorpe',
            age: 21,
            country: 'Australia',
            year: 2004,
            date: '29/08/2004',
            sport: 'Swimming',
            gold: 2,
            silver: 1,
            bronze: 1,
            total: 4,
        },
        {
            id: '19',
            athlete: 'Inge de Bruijn',
            age: 27,
            country: 'Netherlands',
            year: 2000,
            date: '01/10/2000',
            sport: 'Swimming',
            gold: 3,
            silver: 1,
            bronze: 0,
            total: 4,
        },
        {
            id: '20',
            athlete: 'Gary Hall Jr.',
            age: 25,
            country: 'United States',
            year: 2000,
            date: null,
            sport: 'Swimming',
            gold: 2,
            silver: 1,
            bronze: 1,
            total: 4,
        },
        {
            id: '21',
            athlete: 'Michael Klim',
            age: 23,
            country: 'Australia',
            year: 2000,
            date: '01/10/2000',
            sport: 'Swimming',
            gold: 2,
            silver: 2,
            bronze: 0,
            total: 4,
        },
        {
            id: '22',
            athlete: "Susie O'Neill",
            age: 27,
            country: 'Australia',
            year: 2000,
            date: '01/10/2000',
            sport: 'Swimming',
            gold: 1,
            silver: 3,
            bronze: 0,
            total: 4,
        },
        {
            id: '23',
            athlete: 'Jenny Thompson',
            age: 27,
            country: 'United States',
            year: 2000,
            date: '01/10/2000',
            sport: 'Swimming',
            gold: 3,
            silver: 0,
            bronze: 1,
            total: 4,
        },
        {
            id: '24',
            athlete: 'Pieter van den Hoogenband',
            age: 22,
            country: 'Netherlands',
            year: 2000,
            date: '01/10/2000',
            sport: 'Swimming',
            gold: 2,
            silver: 0,
            bronze: 2,
            total: 4,
        },
        {
            id: '25',
            athlete: 'An Hyeon-Su',
            age: 20,
            country: 'South Korea',
            year: 2006,
            date: '26/02/2006',
            sport: 'Short-Track Speed Skating',
            gold: 3,
            silver: 0,
            bronze: 1,
            total: 4,
        },
        {
            id: '26',
            athlete: 'Aliya Mustafina',
            age: 17,
            country: 'Russia',
            year: 2012,
            date: '12/08/2012',
            sport: 'Gymnastics',
            gold: 1,
            silver: 1,
            bronze: 2,
            total: 4,
        },
        {
            id: '27',
            athlete: 'Shawn Johnson',
            age: 16,
            country: 'United States',
            year: 2008,
            date: '24/08/2008',
            sport: 'Gymnastics',
            gold: 1,
            silver: 3,
            bronze: 0,
            total: 4,
        },
        {
            id: '28',
            athlete: 'Dmitry Sautin',
            age: 26,
            country: 'Russia',
            year: 2000,
            date: '01/10/2000',
            sport: 'Diving',
            gold: 1,
            silver: 1,
            bronze: 2,
            total: 4,
        },
        {
            id: '29',
            athlete: 'Leontien Zijlaard-van Moorsel',
            age: 30,
            country: 'Netherlands',
            year: 2000,
            date: '01/10/2000',
            sport: 'Cycling',
            gold: 3,
            silver: 1,
            bronze: 0,
            total: 4,
        },
        {
            id: '30',
            athlete: 'Petter Northug Jr.',
            age: 24,
            country: 'Norway',
            year: 2010,
            date: '28/02/2010',
            sport: 'Cross Country Skiing',
            gold: 2,
            silver: 1,
            bronze: 1,
            total: 4,
        },
        {
            id: '31',
            athlete: 'Ole Einar Bjørndalen',
            age: 28,
            country: 'Norway',
            year: 2002,
            date: '24/02/2002',
            sport: 'Biathlon',
            gold: 4,
            silver: 0,
            bronze: 0,
            total: 4,
        },
    ];
};
