export const CROSS_FILTER_MARKER_FILL_OPACITY_FACTOR = 0.25;
export const CROSS_FILTER_MARKER_STROKE_OPACITY_FACTOR = 0.125;

export const FULLY_OPAQUE = 1;
export const FULLY_TRANSPARENT = 0;
export const ITEM_HIGHLIGHT_SIZE = 14;
