import { createApp, defineComponent, ref } from 'vue';

import type { ColDef } from 'ag-grid-community';
import {
    ClientSideRowModelModule,
    ModuleRegistry,
    NumberFilterModule,
    TextFilterModule,
    ValidationModule,
} from 'ag-grid-community';
import { AutoGenerateColumnsModule } from 'ag-grid-enterprise';
import { AgGridVue } from 'ag-grid-vue3';

import { FileDropOverlay } from './fileDropOverlay';
import './styles.css';

ModuleRegistry.registerModules([
    ClientSideRowModelModule,
    TextFilterModule,
    NumberFilterModule,
    AutoGenerateColumnsModule,
    ...(process.env.NODE_ENV !== 'production' ? [ValidationModule] : []),
]);

const sampleCsv = `Name,Age,Country,Sport,Gold,Silver,Bronze
Michael Phelps,23,United States,Swimming,8,0,0
Usain Bolt,21,Jamaica,Athletics,3,0,0
Natalie Coughlin,25,United States,Swimming,1,2,3
Stephanie Rice,20,Australia,Swimming,3,0,0
Chris Hoy,32,Great Britain,Cycling,3,0,0
Rebecca Adlington,19,Great Britain,Swimming,2,0,0
Kobe Bryant,29,United States,Basketball,1,0,0
Elena Isinbaeva,26,Russia,Athletics,1,0,0
Shelly-Ann Fraser,21,Jamaica,Athletics,1,0,0
Alain Bernard,25,France,Swimming,1,1,0`;

function unquote(value: string): string {
    const trimmed = value.trim();
    if (trimmed.length >= 2 && trimmed[0] === '"' && trimmed[trimmed.length - 1] === '"') {
        return trimmed.slice(1, -1).replace(/""/g, '"');
    }
    return trimmed;
}

function parseCsv(csvText: string): Record<string, string | number>[] {
    const lines = csvText.trim().split('\n');
    const headers = lines[0].split(',').map(unquote);
    return lines.slice(1).map((line) => {
        const values = line.split(',').map(unquote);
        const row: Record<string, string | number> = {};
        headers.forEach((header, j) => {
            const val = values[j];
            row[header] = isNaN(Number(val)) ? val : Number(val);
        });
        return row;
    });
}

const VueExample = defineComponent({
    components: {
        'ag-grid-vue': AgGridVue,
    },
    template: `
        <div class="example-wrapper">
            <div class="button-row">
                <button type="button" @click="onLoadSampleData">Load Sample CSV</button>
                <button type="button" @click="onClearData">Clear Data</button>
            </div>
            <div class="grid-wrapper" @drop.prevent="onDrop" @dragover.prevent>
                <ag-grid-vue
                    style="width: 100%; height: 100%;"
                    :autoGenerateColumnDefs="true"
                    :rowData="rowData"
                    :columnDefs="columnDefs"
                    :activeOverlay="activeOverlay"
                    :processAutoGeneratedColumnDefs="processAutoGeneratedColumnDefs"
                />
            </div>
        </div>
    `,
    setup() {
        const rowData = ref<Record<string, string | number>[] | null>(null);
        const columnDefs = ref<ColDef[]>([]);
        const activeOverlay = ref<any>(FileDropOverlay);

        const processAutoGeneratedColumnDefs = (params: { colDefs: ColDef[]; rowData: any[] }) => {
            return params.colDefs.map((colDef) => {
                const sampleValue = params.rowData[0]?.[colDef.field!];
                if (!isNaN(Number(sampleValue))) {
                    return { ...colDef, filter: 'agNumberColumnFilter' };
                }
                return { ...colDef, filter: 'agTextColumnFilter' };
            });
        };

        const loadData = (csvText: string) => {
            rowData.value = parseCsv(csvText);
            activeOverlay.value = undefined;
        };

        const onLoadSampleData = () => {
            loadData(sampleCsv);
        };

        const onClearData = () => {
            rowData.value = null;
            columnDefs.value = [];
            activeOverlay.value = FileDropOverlay;
        };

        const onDrop = (event: DragEvent) => {
            const file = event.dataTransfer?.files[0];
            if (!file) return;
            const reader = new FileReader();
            reader.onload = (e) => {
                const text = (e.target as FileReader).result as string;
                loadData(text);
            };
            reader.readAsText(file);
        };

        return {
            rowData,
            columnDefs,
            activeOverlay,
            processAutoGeneratedColumnDefs,
            onLoadSampleData,
            onClearData,
            onDrop,
        };
    },
});

createApp(VueExample).mount('#app');
