name: Bump Beta Version

on:
    workflow_dispatch: {}
    schedule:
        - cron: '0 20 * * 0'

env:
    NX_NO_CLOUD: true
    NX_BRANCH: ${{ github.ref }}
    DEPLOYMENT_APP_ID: 957224

jobs:
    bump_version_and_tag:
        runs-on: ubuntu-24.04
        permissions:
            contents: write
        steps:
            - name: Authenticate with GitHub App
              uses: actions/create-github-app-token@v1
              id: app-token
              with:
                  app-id: ${{ env.DEPLOYMENT_APP_ID }}
                  private-key: ${{ secrets.DEPLOYMENT_APP_PRIVATE_KEY }}

            - name: Checkout
              id: checkout
              uses: actions/checkout@v4
              with:
                  token: ${{ steps.app-token.outputs.token }}
                  fetch-depth: 1 # shallow copy

            - name: Fetch Refs
              run: git fetch origin --depth 1 latest-success latest

            - name: Setup Node.js
              id: setup_node
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'yarn'

            - name: Calculate Next Beta Version
              id: next_version
              run: |
                  NEW_VERSION=$(node ./scripts/calculate-next-version.js)
                  CHARTS_NEW_VERSION=$(node -e "console.log(require('./packages/ag-grid-enterprise/package.json').optionalDependencies['ag-charts-community'])")
                  echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
                  echo "CHARTS_NEW_VERSION=${CHARTS_NEW_VERSION}" >> $GITHUB_ENV
                  echo "version=${NEW_VERSION}" >> $GITHUB_OUTPUT
                  echo "tag=b${NEW_VERSION}" >> $GITHUB_OUTPUT

            - name: Bump Beta Package Version
              run: node scripts/deployments/versionModules.js ${NEW_VERSION} ${CHARTS_NEW_VERSION} local

            - name: Commit Changes
              uses: EndBug/add-and-commit@v9
              if: success()
              with:
                  default_author: github_actions
                  message: Automated package version bump to ${{ steps.next_version.outputs.version }}.

            - name: Tag Latest Successful Commit
              uses: EndBug/latest-tag@latest
              if: success()
              with:
                  ref: ${{ steps.next_version.outputs.tag }}
                  description: Latest commit to pass GitHub Actions workflow on latest branch.

            - name: Tag Latest Successful Commit
              uses: EndBug/latest-tag@latest
              if: success()
              with:
                  ref: latest-beta-version
                  description: Latest commit to pass GitHub Actions workflow on latest branch.
