name: Bump Beta Version

on:
    workflow_dispatch: {}
    schedule:
        - cron: '0 20 * * 0'

env:
    NX_NO_CLOUD: true
    NX_BRANCH: ${{ github.ref }}
    DEPLOYMENT_APP_ID: 957224

jobs:
    bump_version_and_tag:
        runs-on: ubuntu-24.04
        permissions:
            contents: write
        steps:
            - name: Authenticate with GitHub App
              uses: actions/create-github-app-token@v1
              id: app-token
              with:
                  app-id: ${{ env.DEPLOYMENT_APP_ID }}
                  private-key: ${{ secrets.DEPLOYMENT_APP_PRIVATE_KEY }}

            - name: Checkout
              id: checkout
              uses: actions/checkout@v4
              with:
                  token: ${{ steps.app-token.outputs.token }}
                  fetch-depth: 1 # shallow copy

            - name: Fetch Refs
              run: git fetch origin --depth 1 latest-success latest

            - name: Setup
              id: setup
              uses: ./.github/actions/setup-nx
              with:
                cache_mode: ro

            - name: nx pack:verify
              id: pack-verify
              run: |
                NODE_ENV=production yarn nx pack:verify -c staging

            - name: Tag Latest Successful Commit
              uses: EndBug/latest-tag@latest
              if: success()
              with:
                  ref: latest-beta-version
                  description: Latest commit to pass GitHub Actions workflow on latest branch.
