name: CI

on:
  push:
    branches:
      - 'latest'
      - 'b[0-9][0-9]?.[0-9][0-9]?.[0-9][0-9]?'
      - 'seanlandsman-patch-9'
  pull_request:
    branches:
      - 'latest'
      - 'next'
      - 'b[0-9][0-9]?.[0-9][0-9]?.[0-9][0-9]?'
      - 'seanlandsman-patch-9'
  workflow_dispatch:
    inputs:
      run_docs:
        description: 'Skip docs build & link checker'
        type: 'choice'
        required: true
        default: 'true'
        options:
          - 'true'
          - 'false'
      run_bundle_size:
        description: 'Skip bundle size tests'
        type: 'choice'
        required: true
        default: 'true'
        options:
          - 'true'
          - 'false'
      clean_checkout:
        description: 'Disable all caching'
        type: 'choice'
        required: true
        default: 'false'
        options:
          - 'true'
          - 'false'
      nx_command:
        type: 'choice'
        required: true
        default: 'affected'
        options:
          - 'affected'
          - 'run-many'
env:
  NX_NO_CLOUD: true
  NX_BRANCH: ${{ github.ref }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  SHARP_IGNORE_GLOBAL_LIBVIPS: true
  YARN_REGISTRY: "http://52.50.158.57:4873"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/latest' }}

jobs:
  build_lint:
    name: Build & Lint
    outputs:
      nx_base: ${{ steps.setup.outputs.base }}
      build: ${{ steps.build.outcome || '' }}
      lint: ${{ steps.lint.outcome || '' }}
      format: ${{ steps.format.outcome || '' }}
      test_count: ${{ steps.matrix.outputs.test_count }}
      test_matrix: ${{ steps.matrix.outputs.test_matrix }}
      e2e_test_count: ${{ steps.matrix.outputs.e2e_test_count }}
      e2e_test_matrix: ${{ steps.matrix.outputs.e2e_test_matrix }}
      bundle_test_count: ${{ steps.matrix.outputs.bundle_test_count }}
      bundle_test_matrix: ${{ steps.matrix.outputs.bundle_test_matrix }}
      build_type: ${{ steps.setup.outputs.type }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # shallow copy

      - name: Fetch Refs
        run: |
          git fetch origin --depth 1 latest
          git fetch origin --depth 1 tag latest-success

      - name: Find matching workflow
        id: find_latest_sha
        uses: SamhammerAG/last-successful-build-action@v4
        with:
          branch: "latest"
          workflow: "ci"
          verify: false

      - name: Test Outputs
        run: |
          echo "Current SHA: ${{ github.sha }}"
          echo "Latest Success SHA: ${{ steps.find_latest_sha.outputs.sha }}"
          echo "Current Branch: ${{ env.BRANCH_NAME }}"
          echo "Current Workflow: ${{ github.workflow }}"
