name: Documentation Tests
# Testing of AG Grid Examples

env:
    NX_NO_CLOUD: true
    CI: true
    DEFAULT_RETENTION_DAYS: 30
    PREV_COMMIT_SHA_FILE: ./commit-sha.txt
    CTRF_FILE: ./ctrf-report.json
    SLACK_CHANNEL: '#ci-grid-gate'
    AG_LIBRARY: grid
on:
    workflow_dispatch:
        inputs:
            skip_vanilla:
                description: 'Skip Vanilla tests'
                type: boolean
                required: true
                default: true
            skip_typescript:
                description: 'Skip Typescript tests'
                type: boolean
                required: true
                default: true
            skip_reactFunctional:
                description: 'Skip React Functional tests'
                type: boolean
                required: true
                default: true
            skip_reactFunctionalTs:
                description: 'Skip React Functional TS tests'
                type: boolean
                required: true
                default: true
            skip_angular:
                description: 'Skip Angular tests'
                type: boolean
                required: true
                default: true
            skip_vue3:
                description: 'Skip Vue3 tests'
                type: boolean
                required: true
                default: true
            skip_demo_smoke:
                description: 'Skip Demo / Smoke tests'
                type: boolean
                required: true
                default: true
            skip_recipes:
                description: 'Skip Public Recipes tests'
                type: boolean
                required: true
                default: true
            notify:
                description: 'Notify Slack channel'
                type: boolean
                default: true
                required: true
            force_jira_ticket:
                description: 'Force create a Jira ticket even if the run is not scheduled'
                type: boolean
                default: false
                required: true
    #schedule:
    #    - cron: '30 2 * * *' # Run daily at 2:30am UTC

jobs:
    # Run all framework tasks in parallel
    

    download-examples:
      name: Download all-examples.json
      runs-on: ubuntu-latest
      outputs:
        cache-key: ${{ steps.cache-key.outputs.key }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 1

        - name: Download all-examples-cached.json
          run: |
            mkdir -p ./testing/ag-grid-docs/e2e/.cache
            curl https://grid-staging.ag-grid.com/debug/all-examples.json > ./testing/ag-grid-docs/e2e/.cache/all-examples-cached.json

        - name: Generate cache key
          id: cache-key
          run: |
            CACHE_KEY="all-examples-$(sha256sum ./testing/ag-grid-docs/e2e/.cache/all-examples-cached.json | cut -d' ' -f1)"
            echo "key=${CACHE_KEY}" >> $GITHUB_OUTPUT
            echo "Generated cache key: ${CACHE_KEY}"

        - name: Cache all-examples-cached.json
          uses: actions/cache@v4
          with:
            path: ./testing/ag-grid-docs/e2e/.cache/all-examples-cached.json
            key: ${{ steps.cache-key.outputs.key }}

    
    test-demos-smoke:
        if: ${{ github.event.inputs.skip_demo_smoke != 'true' }}
        name: Smoke Test Demos / Examples
        needs: download-examples
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 1

            - name: Restore all-examples-cached.json
              uses: actions/cache@v4
              with:
                path: ./testing/ag-grid-docs/e2e/.cache/all-examples-cached.json
                key: ${{ needs.download-examples.outputs.cache-key }}

            - name: Install Playwright Browsers
              working-directory: testing/ag-grid-docs
              run: npm i && npx playwright install chromium firefox webkit --with-deps --only-shell

            - name: Demo Pages
              working-directory: testing/ag-grid-docs
              env:
                BASE_URL: https://grid-staging.ag-grid.com/
              run: npx playwright test ag-grid-demos.spec.ts
            
            - name: Smoke Test Examples (ag-grid.com)
              if: always()
              working-directory: testing/ag-grid-docs
              env:
                BASE_URL: https://ag-grid.com
                AG_GRID_PERCENTAGE_TO_RUN: 0.01
              run: npx playwright test smoke-test-examples.spec.ts

            - name: Upload Test Report
              id: upload-report
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                name: playwright-report-demos
                path: reports/
                retention-days: ${{env.DEFAULT_RETENTION_DAYS}}            

    test-vanilla:
        if: ${{ github.event.inputs.skip_vanilla != 'true' }}
        name: Test Vanilla Examples
        needs: download-examples
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            shardIndex: [1, 2]
            shardTotal: [2]
        steps:
          - uses: actions/checkout@v4
          - uses: ./.github/actions/test-framework-examples
            with:
              framework: vanilla
              cache-key: ${{ needs.download-examples.outputs.cache-key }}

    test-typescript:
        if: ${{ github.event.inputs.skip_typescript != 'true' }}
        name: Test Typescript Examples
        needs: download-examples
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            shardIndex: [1]
            shardTotal: [1]
        steps:
          - uses: actions/checkout@v4
          - uses: ./.github/actions/test-framework-examples
            with:
              framework: typescript
              cache-key: ${{ needs.download-examples.outputs.cache-key }}

    test-react-functional:
        if: ${{ github.event.inputs.skip_reactFunctional != 'true' }}
        name: Test React Examples
        needs: download-examples
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            shardIndex: [1]
            shardTotal: [1]
        steps:
          - uses: actions/checkout@v4
          - uses: ./.github/actions/test-framework-examples
            with:
              framework: reactFunctional
              cache-key: ${{ needs.download-examples.outputs.cache-key }}

    test-react-functional-ts:
        if: ${{ github.event.inputs.skip_reactFunctionalTs != 'true' }}
        name: Test React TS Examples
        needs: download-examples
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            shardIndex: [1, 2]
            shardTotal: [2]
        steps:
          - uses: actions/checkout@v4
          - uses: ./.github/actions/test-framework-examples
            with:
              framework: reactFunctionalTs
              cache-key: ${{ needs.download-examples.outputs.cache-key }}

    test-vue3:
        if: ${{ github.event.inputs.skip_vue3 != 'true' }}
        name: Test Vue Examples
        needs: download-examples
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            shardIndex: [1]
            shardTotal: [1]
        steps:
          - uses: actions/checkout@v4
          - uses: ./.github/actions/test-framework-examples
            with:
              framework: vue3
              cache-key: ${{ needs.download-examples.outputs.cache-key }}

    test-angular:
        if: ${{ github.event.inputs.skip_angular != 'true' }}
        name: Test Angular Examples
        needs: download-examples
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            shardIndex: [1, 2]
            shardTotal: [2]
        steps:
          - uses: actions/checkout@v4
          - uses: ./.github/actions/test-framework-examples
            with:
              framework: angular
              cache-key: ${{ needs.download-examples.outputs.cache-key }}

    test-recipes:
      if: ${{ github.event.inputs.skip_recipes != 'true' }}
      name: Test Public Testing Recipes
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
      steps:
        - uses: actions/checkout@v4
        - name: Bootstrap
          run: npm run bootstrap
        - name: Run Public Testing Recipes
          run: yarn nx run ag-grid-public-e2e-testing-recipes:test:recipes -c staging
        - name: Upload Test Report
          id: upload-recipes-report
          uses: actions/upload-artifact@v4
          if: ${{ !cancelled() }}
          with:
            name: playwright-report-recipes
            path: reports/
            retention-days: ${{env.DEFAULT_RETENTION_DAYS}}  

    publish-reports:
      if: always()
      needs:
        - test-demos-smoke
        - test-react-functional
        - test-react-functional-ts
        - test-angular
        - test-typescript
        - test-vanilla
        - test-vue3
        - test-recipes
      env:
        IS_SUCCESS: ${{ needs.test-angular.result != 'failure' && needs.test-react-functional.result != 'failure' && needs.test-react-functional-ts.result != 'failure' && needs.test-typescript.result != 'failure' && needs.test-vanilla.result != 'failure' && needs.test-vue3.result != 'failure' && needs.test-demos-smoke.result != 'failure' && needs.test-recipes.result != 'failure' }}
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 1

        - name: Download all test reports
          uses: actions/download-artifact@v4
          with:
            path: combined-reports

        - name: Publish Combined Test Report
          id: ctrf
          uses: ctrf-io/github-test-reporter@v1.0.17
          with:
            report-path: 'combined-reports/**/*.json'
            summary-report: true
            failed-report: true
            flaky-report: true
            skipped-report: true
            write-ctrf-to-file: ${{ env.CTRF_FILE }}

        - name: Get previous run commit SHA
          id: prev-commit-sha
          uses: actions/cache/restore@v4
          with:
            restore-keys: |
              doc-tests-prev-commit-
              doc-tests-prev-commit-${{ github.ref }}
            path: ${{ env.PREV_COMMIT_SHA_FILE }}
            key: doc-tests-prev-commit-${{ github.ref }}-${{ github.sha }}

        - name: Load files into environment
          continue-on-error: true
          run: |
            if [ -f ${{ env.PREV_COMMIT_SHA_FILE }} ]; then
            {
               echo 'PREV_COMMIT_SHA<<EOF'
               cat ${{ env.PREV_COMMIT_SHA_FILE }}
               echo 'EOF'
            } >> $GITHUB_ENV
            else
              echo 'PREV_COMMIT_SHA_FILE not found'
            fi

        - name: Slack Notification
          if: ${{ github.event_name == 'schedule' || inputs.notify }}
          continue-on-error: true
          uses: ./external/ag-shared/github/actions/slack-integration
          with:
            AG_LIBRARY: ${{ env.AG_LIBRARY }}
            CTRF_REPORT_FILE: ${{ env.CTRF_FILE }}
            SLACK_BOT_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_OAUTH_TOKEN }}
            SLACK_CHANNEL: ${{ env.SLACK_CHANNEL }}
            PREV_COMMIT_SHA: ${{ env.PREV_COMMIT_SHA }}
            CURRENT_COMMIT_SHA: ${{ github.sha }}
            IS_SUCCESS: ${{ env.IS_SUCCESS }}

        - name: Create Jira Ticket
          uses: ./.github/actions/jira-integration
          continue-on-error: true
          if: ${{ github.event_name == 'schedule' || inputs.force_jira_ticket }}
          with:
              JIRA_API_AUTH: ${{ secrets.JIRA_API_AUTH }}
              JIRA_SUMMARY: "[NR] CI/CD workflow '${{ github.workflow }}' is failing."
              CTRF_REPORT_FILE: ${{ env.CTRF_FILE }}
              PREV_COMMIT_SHA: ${{ env.PREV_COMMIT_SHA }}
              CURRENT_COMMIT_SHA: ${{ github.sha }}
              IS_SUCCESS: ${{ env.IS_SUCCESS }}

        - name: Set commit SHA
          id: set-commit-sha
          run: |
            echo ${{ github.sha }} > ${{ env.PREV_COMMIT_SHA_FILE }}

        - name: Save Current Commit Hash
          uses: actions/cache/save@v4
          with:
            path: ${{ env.PREV_COMMIT_SHA_FILE }}
            key: ${{ steps.prev-commit-sha.outputs.cache-primary-key }}
