name: Doc Tests 
description: Testing of AG Grid Examples

env:
    NX_NO_CLOUD: true
    CI: true
    DEFAULT_RETENTION_DAYS: 30

on:
    push:
        branches: ['AG-15304-doc-tests']
    pull_request:
        branches: ['AG-15304-doc-tests']
    workflow_dispatch:
        inputs:
            clean_checkout:
                description: 'Disable all caching'
                type: 'choice'
                required: true
                default: 'false'
                options:
                    - 'true'
                    - 'false'
    schedule:
        - cron: '30 2 * * *' # Run daily at 2:30am UTC

jobs:
    # Run all framework tasks in parallel
    test-demos:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 1

            - name: Setup
              uses: ./.github/actions/setup-nx
              with:
                cache_mode: ${{ github.event.inputs.clean_checkout == 'true' && 'off' || 'rw' }}

            - name: Demo Pages
              run: yarn nx run ag-grid-docs-testing:test:e2e:demos

            - name: Upload Test Report
              id: upload-report
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                name: playwright-report-demos
                path: reports/
                retention-days: ${{env.DEFAULT_RETENTION_DAYS}}

    download-examples:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 1

        - name: Download all-examples.json
          run: |
            mkdir -p ./e2e/config
            curl https://grid-staging.ag-grid.com/debug/all-examples.json > ./e2e/config/all-examples.json

        - name: Cache all-examples.json
          uses: actions/cache@v4
          with:
            path: ./e2e/config/all-examples.json
            key: all-examples-${{ hashFiles('./e2e/config/all-examples.json') }}

    test-react-functional:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 1

            - name: Restore all-examples.json
              uses: actions/cache@v4
              with:
                path: ./e2e/config/all-examples.json
                key: all-examples-${{ hashFiles('./e2e/config/all-examples.json') }}

            - name: Setup
              uses: ./.github/actions/setup-nx
              with:
                cache_mode: ${{ github.event.inputs.clean_checkout == 'true' && 'off' || 'rw' }}

            - name: React Functional
              run: yarn nx run ag-grid-docs-testing:test:e2e:reactFunctional

            - name: Upload Test Report
              id: upload-report
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                name: playwright-report-react-functional
                path: reports/
                retention-days: ${{env.DEFAULT_RETENTION_DAYS}}

    test-react-functional-ts:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 1

            - name: Restore all-examples.json
              uses: actions/cache@v4
              with:
                path: ./e2e/config/all-examples.json
                key: all-examples-${{ hashFiles('./e2e/config/all-examples.json') }}                

            - name: Setup
              uses: ./.github/actions/setup-nx
              with:
                cache_mode: ${{ github.event.inputs.clean_checkout == 'true' && 'off' || 'rw' }}

            - name: React Functional TS
              run: yarn nx run ag-grid-docs-testing:test:e2e:reactFunctionalTs

            - name: Upload Test Report
              id: upload-report
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                name: playwright-report-react-functional-ts
                path: reports/
                retention-days: ${{env.DEFAULT_RETENTION_DAYS}}

    test-angular:
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            shardIndex: [1, 2, 3, 4]
            shardTotal: [4]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 1

            - name: Restore all-examples.json
              uses: actions/cache@v4
              with:
                path: ./e2e/config/all-examples.json
                key: all-examples-${{ hashFiles('./e2e/config/all-examples.json') }}

            - name: Setup
              uses: ./.github/actions/setup-nx
              with:
                cache_mode: ${{ github.event.inputs.clean_checkout == 'true' && 'off' || 'rw' }}

            - name: Angular
              run: yarn nx run ag-grid-docs-testing:test:e2e:angular --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

            - name: Upload Test Report
              id: upload-report
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                name: playwright-report-angular-${{ matrix.shardIndex }}-of-${{ matrix.shardTotal }}
                path: reports/
                retention-days: ${{env.DEFAULT_RETENTION_DAYS}}

    test-typescript:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 1

            - name: Restore all-examples.json
              uses: actions/cache@v4
              with:
                path: ./e2e/config/all-examples.json
                key: all-examples-${{ hashFiles('./e2e/config/all-examples.json') }}

            - name: Setup
              uses: ./.github/actions/setup-nx
              with:
                cache_mode: ${{ github.event.inputs.clean_checkout == 'true' && 'off' || 'rw' }}

            - name: Typescript
              run: yarn nx run ag-grid-docs-testing:test:e2e:typescript

            - name: Upload Test Report
              id: upload-report
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                name: playwright-report-typescript
                path: reports/
                retention-days: ${{env.DEFAULT_RETENTION_DAYS}}

    test-vanilla:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 1

            - name: Restore all-examples.json
              uses: actions/cache@v4
              with:
                path: ./e2e/config/all-examples.json
                key: all-examples-${{ hashFiles('./e2e/config/all-examples.json') }}

            - name: Setup
              uses: ./.github/actions/setup-nx
              with:
                cache_mode: ${{ github.event.inputs.clean_checkout == 'true' && 'off' || 'rw' }}

            - name: Vanilla
              run: yarn nx run ag-grid-docs-testing:test:e2e:vanilla

            - name: Upload Test Report
              id: upload-report
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                name: playwright-report-vanilla
                path: reports/
                retention-days: ${{env.DEFAULT_RETENTION_DAYS}}

    test-vue3:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 1

            - name: Restore all-examples.json
              uses: actions/cache@v4
              with:
                path: ./e2e/config/all-examples.json
                key: all-examples-${{ hashFiles('./e2e/config/all-examples.json') }}

            - name: Setup
              uses: ./.github/actions/setup-nx
              with:
                cache_mode: ${{ github.event.inputs.clean_checkout == 'true' && 'off' || 'rw' }}

            - name: Vue3
              run: yarn nx run ag-grid-docs-testing:test:e2e:vue3

            - name: Upload Test Report
              id: upload-report
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                name: playwright-report-vue3
                path: reports/
                retention-days: ${{env.DEFAULT_RETENTION_DAYS}}
    publish-reports:
      if: always()
      needs:
        - test-demos
        - test-react-functional
        - test-react-functional-ts
        - test-angular
        - test-typescript
        - test-vanilla
        - test-vue3
      runs-on: ubuntu-latest
      steps:
        - name: Download all test reports
          uses: actions/download-artifact@v4
          with:
            path: combined-reports

        - name: Publish Combined Test Report
          uses: ctrf-io/github-test-reporter@v1
          with:
            report-path: 'combined-reports/**/*.json'
            summary-report: true
            failed-report: true
            flaky-report: true
            skipped-report: true