name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:  
  Build-Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # shallow copy
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: yarn.lock
         
      - name: Bootstrap
        run: |
          npm run bootstrap
        
      # - name: nx format:check
      #   run: |
      #     yarn nx format:check --all

      # - name: nx lint
      #   run: |
      #     yarn nx lint 

      # - name: nx pack:verify --prod
      #   run: |
      #     yarn nx pack:verify --prod

      # - name: nx test:modules
      #   run: |
      #     yarn nx test:modules
            
      # - name: nx run ag-grid-docs:test
      #   run: |
      #     yarn nx run ag-grid-docs:test
 
