name: Performance Tests

on:
  issue_comment:
    types: [ created ]
  workflow_dispatch:
    inputs:
      notify:
        description: 'Notify Slack channel'
        type: boolean
        default: false
        required: true
      force_scheduled:
        description: 'Run the scheduled set of benchmarks'
        type: boolean
        default: false
      force_pr_id:
        description: 'PR ID to update (used for debugging this workflow)'
        type: number
        required: false
      force_jira_ticket:
        description: 'Force create a Jira ticket even if the run is not scheduled'
        type: boolean
        default: false
        required: true
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC

env:
  NX_NO_CLOUD: true
  NX_BRANCH: ${{ github.ref }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  SHARP_IGNORE_GLOBAL_LIBVIPS: true
  YARN_REGISTRY: "http://52.50.158.57:4873"
  CI: true
  PR_ID: ${{ inputs.force_pr_id || github.event.issue.number }}
  COMMENT_FILE: ./comment.md
  PW_REPORT_PATH: ./reports/playwright.json
  CTRF_FILE: ./reports/performance.json
  SLACK_CHANNEL: '#ci-grid-gate'
  AG_LIBRARY: grid

permissions:
  contents: read

jobs:
  # Check permissions for issue_comment events
  check-permissions:
    runs-on: ubuntu-latest
    outputs:
      allowed: ${{ steps.check.outputs.allowed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check user permissions
        id: check
        uses: ./external/ag-shared/github/actions/check-issue-comment-permissions
        with:
          command: '/benchmarks'

