name: OSS Scorecard Results Check
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ 'OSS Scorecard' ]
    types:
      - completed

env:
  CTRF_FILE: ./ctrf-report.json
  SLACK_CHANNEL: '#ci-grid-gate'
  AG_LIBRARY: grid
  THRESHOLD: 7.1

permissions: read-all

jobs:
  check_results:
    name: Scorecard Results Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # shallow copy

      - name: "Check Results"
        id: check_results
        run: |
          node external/ag-shared/scripts/ossf-scorecard/getAndCheckResults.mjs ${{ env.AG_LIBRARY }} ${{ env.THRESHOLD }}

      - name: Slack Notification
        uses: ./external/ag-shared/github/actions/slack-integration
        with:
          AG_LIBRARY: ${{ env.AG_LIBRARY }}
          CTRF_REPORT_FILE: ${{ env.CTRF_FILE }}
          SLACK_BOT_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_OAUTH_TOKEN }}
          SLACK_CHANNEL: ${{ env.SLACK_CHANNEL }}
          IS_SUCCESS: ${{ steps.check_results.result != '0' }}
